/* DECODE — Biology: plain-English explanations keyed by textlines block index */
window.DECODE = window.DECODE || {};

window.DECODE['bio1'] = {
  0: 'What makes something alive? Not movement alone — clouds move but aren\u2019t alive; plants don\u2019t run but are. The real test happens at the <b>molecular scale</b>: living things continuously repair, rebuild and organise themselves.',
  3: 'The core problem of being alive: the environment constantly breaks down your ordered structure. Staying alive means continuously <b>repairing the damage</b> — and that needs energy and molecules, non-stop.',
  5: 'The maintenance jobs get a name: <b>life processes</b> — nutrition, respiration, transportation and excretion. Together they keep the body\u2019s machinery running despite the environment\u2019s wear and tear.',
  8: 'Molecular repair needs energy from outside sources; the processes that make that energy usable, and the exchange of gases they require, are nutrition and respiration — the first two life processes.',
  9: 'Single-celled life is easy to service: the whole cell surface touches the environment, so <b>diffusion alone</b> delivers food and oxygen and removes waste. No organs needed.',
  10: 'Multicellular bodies face a logistics problem — most cells sit deep inside, far from air and food. The solution: specialised <b>tissues and organs</b> (gut, lungs, blood) that move materials to every cell.',
  14: 'Nutrition splits into two strategies: <b>autotrophic</b> (self-feeding — plants make food from CO\u2082 + water + sunlight) and <b>heterotrophic</b> (other-feeding — animals and fungi take ready-made food).',
  15: 'Photosynthesis in one line: <b>6CO\u2082 + 12H\u2082O \u2192 C\u2086H\u2081\u2082O\u2086 + 6O\u2082 + 6H\u2082O</b> (light + chlorophyll). The glucose not used immediately is stored as starch.',
  17: 'The two steps: (1) <b>light reaction</b> — chlorophyll traps sunlight \u2192 chemical energy, water splits, O\u2082 released; (2) <b>dark reaction</b> — CO\u2082 is converted to carbohydrate using that stored energy, no light needed.',
  18: 'Leaf anatomy for photosynthesis: chloroplasts pack the mesophyll cells; CO\u2082 enters through <b>stomata</b> — pores whose guard cells open and close them; water arrives through veins (xylem).',
  21: 'Beyond photosynthesis, plants need minerals: nitrogen (as nitrates), phosphorus, iron, magnesium — dissolved in soil water, absorbed by roots. Nitrogen builds proteins; magnesium sits inside chlorophyll itself.',
  26: 'Heterotrophs come in three temperaments: <b>saprophytes</b> (fungi digest food outside the body and absorb it), <b>parasites</b> (cuscuta, ticks, leech — steal from a living host) and <b>holozoic</b> (animals that ingest, digest and egest).',
  29: 'Single-cell eating styles: amoeba extends <b>pseudopodia</b> around food and digests it in a food vacuole; paramoecium\u2019s cilia sweep food to a fixed spot. Same goal — different traffic systems.',
  30: 'The human alimentary canal: mouth \u2192 oesophagus \u2192 stomach \u2192 small intestine \u2192 large intestine \u2192 rectum \u2192 anus, plus the liver and pancreas emptying in. One tube, many specialised stations.',
  31: 'Different foods, one pipeline: the trick is <b>enzymes</b> — biological catalysts, each tuned to one food type, each needing its own pH. That\u2019s why the canal keeps changing its chemistry station to station.',
  32: 'Digestion begins in the mouth: <b>salivary amylase</b> starts breaking starch into sugar — that\u2019s why chewed bread turns faintly sweet.',
  33: '<b>Peristalsis</b> — wave-like muscle contractions — pushes food along the canal in a regulated rhythm. The canal is muscular for exactly this reason.',
  34: 'The stomach\u2019s three secretions: <b>HCl</b> (acidic medium, kills germs), <b>mucus</b> (protects the stomach wall from its own acid) and <b>pepsin</b> (protein-digesting enzyme). Acid + armour + enzyme.',
  36: 'The <b>small intestine</b> finishes everything: bile emulsifies fats, pancreatic juice brings trypsin/amylase/lipase, and intestinal juice completes the job. It\u2019s the longest station — absorption happens here.',
  37: 'Bile\u2019s trick is the same as soap\u2019s: <b>emulsification</b> — big fat globules are broken into tiny droplets, multiplying the surface area lipase can attack. (Note the cross-reference back to che4\u2019s soap chemistry.)',
  38: 'Absorption hardware: <b>villi</b> — millions of finger-like folds, each with a blood vessel net. Folded surface = huge absorption area in a compact gut.',
  42: 'Respiration\u2019s purpose: break down food to release energy, and trap it as <b>ATP</b> — the cell\u2019s energy currency that powers everything else.',
  43: 'Yeast\u2019s anaerobic route: glucose \u2192 ethanol + CO\u2082 + little energy (<b>fermentation</b> — the chemistry of bread and beer).',
  44: 'Your muscles\u2019 emergency route when oxygen runs short: glucose \u2192 <b>lactic acid</b> + little energy. Lactic acid build-up is the cramp after a sprint.',
  45: 'ATP detail worth remembering: the energy released in respiration is immediately stored as ATP, whose terminal phosphate bond is broken to release energy exactly where and when the cell needs it.',
  47: 'The two pathways diverge after the first step: glucose \u2192 pyruvate in the <b>cytoplasm</b>; then with oxygen \u2192 CO\u2082 + H\u2082O + much ATP in the <b>mitochondria</b>; without oxygen \u2192 ethanol or lactic acid.',
  48: 'Plant twist: by day, the CO\u2082 from respiration is reused for photosynthesis — so leaves give out oxygen. At night, only respiration runs — plants "breathe out" CO\u2082.',
  51: 'Fish breathe water: gills extract <b>dissolved</b> oxygen as water flows past — efficient because blood flows the opposite way to the water (counter-current exchange).',
  52: 'The human airway: nostrils \u2192 pharynx \u2192 larynx \u2192 trachea (cartilage-ringed) \u2192 bronchi \u2192 bronchioles \u2192 alveoli. Warm, filter, humidify, deliver.',
  55: 'The alveoli: balloon-like sacs, one cell thick, wrapped in capillaries. This is the actual lung surface — all the tubes are just delivery plumbing. Total alveolar surface \u2248 80 m\u00b2.',
  56: 'Breathing mechanics: diaphragm flattens + ribs lift \u2192 chest volume rises \u2192 pressure drops \u2192 air rushes IN. Relaxation reverses everything \u2192 air flows OUT. Residual air keeps alveoli from collapsing.',
  57: 'Why blood, not just diffusion: in a large body, diffusion is far too slow to deliver oxygen to deep cells. The <b>respiratory pigment haemoglobin</b> (inside RBCs) carries oxygen, and the blood stream delivers it — a pump plus a network.',
  61: 'The heart\u2019s floor plan: four chambers — two atria (receiving) above, two ventricles (pumping) below. The right side handles deoxygenated blood to the lungs; the left side pushes oxygenated blood to the body.',
  62: 'The double circuit traced: lungs \u2192 left atrium \u2192 left ventricle \u2192 body \u2192 right atrium \u2192 right ventricle \u2192 lungs. Blood passes through the heart <b>twice</b> per lap — "double circulation".',
  64: 'Why separation matters: keeping oxygenated and deoxygenated blood apart delivers the highest oxygen supply — exactly what warm-blooded birds and mammals (who burn energy to hold body temperature) need.',
  66: '<b>Blood pressure</b>: the force on vessel walls — systolic (ventricle contracts, ~120 mm Hg) over diastolic (relaxes, ~80). The instrument: <b>sphygmomanometer</b>.',
  68: 'Vessel architecture: <b>arteries</b> thick-walled and elastic (high pressure, no valves); <b>veins</b> thin-walled with valves (low pressure, one-way return); <b>capillaries</b> one-cell thick for exchange.',
  70: '<b>Platelets</b> — the leak-repair crew: they cluster at a cut and trigger clotting, plugging the leak in minutes. Deficiency = excessive bleeding from small wounds.',
  71: '<b>Lymph</b>: the colourless drainage fluid — it leaks out of capillaries, bathes the tissues, and carries it back plus absorbed fats from the intestine. Circulation\u2019s shadow system.',
  74: 'Plant transport is different: plants don\u2019t wander, so energy demands are low — they can run on slow, cheap transport (no pump, no haemoglobin) but still need two highways: <b>xylem</b> (water up) and <b>phloem</b> (food around).',
  76: 'Xylem: interconnected vessel cells forming continuous water columns from root to leaf — dead, hollow tubes perfect for plumbing.',
  77: 'The push: <b>root pressure</b> — root cells actively pump minerals, water follows by osmosis, pressure rises at night (guttation droplets). But push alone can\u2019t lift water to a treetop.',
  78: 'The pull: <b>transpiration</b> — evaporation from leaf surfaces sucks the whole water column upward (cohesion of water keeps the column unbroken). Transpiration also cools the plant and hauls minerals up with the stream.',
  79: 'Phloem runs both ways: sucrose loaded at source (leaf) using ATP, unloaded at sink (root/fruit) — this active transport is <b>translocation</b>. Unlike xylem, phloem cells stay alive and spend energy.',
  82: 'Excretion: the removal of harmful nitrogenous wastes (urea in humans) built up by metabolism. Not to be confused with egestion (undigested food out of the gut).',
  84: 'The nephron\u2019s three-step algorithm: (1) <b>glomerular filtration</b> — blood pressure squeezes water/glucose/salts/urea into the capsule; (2) <b>selective reabsorption</b> — useful things reclaimed in the tubule; (3) remaining fluid = urine.',
  85: 'How concentrated is your urine? The tubule fine-tunes water reabsorption to how much you drank and sweated — drink more, dilute urine; dehydrated, concentrated urine.',
  87: 'The <b>artificial kidney</b> (dialysis): blood flows through semi-permeable tubes bathed in dialysis fluid — wastes diffuse out, blood cells and proteins stay in. No reabsorption step, so it\u2019s an imperfect but life-saving substitute.',
  89: 'Plant excretion, plant-style: O\u2082 and CO\u2082 simply escape through stomata, water leaves by transpiration, and nitrogenous wastes/resins/gums are parked in falling leaves, bark and old xylem — waste <b>isolated</b>, not eliminated.'
};

window.DECODE['bio2'] = {
  2: 'The pattern behind every response: a <b>stimulus</b> (bright light, heat) is detected by receptors, the information travels, and a response follows — movement, secretion, or both. Control and coordination = detection \u2192 transmission \u2192 action.',
  5: 'Animals get two control systems: <b>nervous</b> (electrical impulses via neurons — fast, targeted, short-lived) and <b>endocrine</b> (hormones in blood — slower, body-wide, longer-lasting). They work as a team.',
  6: 'The neuron\u2019s wiring: information enters at the <b>dendritic tip</b>, travels as an electro-chemical impulse along the axon, and exits at the nerve endings — where it releases a chemical across the <b>synapse</b> to the next cell.',
  7: 'The synapse\u2019s chemical hop: at the gap\u2019s edge, the impulse releases neurotransmitter molecules, which cross and fire the next neuron. That is also where nerves talk to muscles.',
  9: '<b>Reflex actions</b>: sudden, automatic protective responses — touching a flame, a knee jerk, blinking. The body acts first; the thinking brain gets informed later. Speed saves skin.',
  10: 'Why bypass the brain? Thinking is slow — nerves to the brain and back take time the burning finger doesn\u2019t have. The <b>spinal cord</b> can compute "withdraw!" itself.',
  14: 'The <b>reflex arc</b> traced: receptors in skin \u2192 sensory neuron \u2192 relay neuron in spinal cord \u2192 motor neuron \u2192 muscle (effector). Draw this arrow-chain — a guaranteed diagram question.',
  15: 'The brain\u2019s job description: receive information from all over the body, integrate it, and decide. Thinking + memory + voluntary action all live here.',
  17: 'Brain geography: <b>fore-brain</b> (cerebrum — thinking, memory), <b>mid-brain</b> (involuntary like pupil/eye movements), <b>hind-brain</b> (cerebellum — balance; medulla — heartbeat, breathing, BP, vomiting).',
  21: 'The cerebellum\u2019s portfolio: walking a straight line, riding a bicycle, precise hand movements — posture, balance, and the fine tuning of voluntary actions.',
  22: 'Brain protection: the bony skull, three membranes (meninges), and <b>cerebrospinal fluid</b> absorbing shocks — the softest organ gets the hardest armour.',
  24: 'How nerve becomes movement: muscle cells hold <b>proteins</b> that change shape and slide past each other when the nerve\u2019s chemical signal arrives — cells shorten = movement.',
  25: 'Plant movement, first look: a germinating seed sends the root <b>down</b> and shoot <b>up</b> regardless of how it was planted — directional, growth-driven movement.',
  27: 'The sensitive plant (Mimosa) folds instantly on touch — <b>no growth involved</b>, cells change shape by losing water. Compare: slow tropic growth movements vs this fast "nastic" fold.',
  29: 'The tendril\u2019s trick: touched side grows <b>slower</b> (auxin moves away), far side grows faster — the tendril bends around the support. Movement by unequal growth.',
  31: '<b>Tropisms</b> — directional growth towards (+) or away (\u2013) from the stimulus: phototropism (light), geotropism (gravity), hydrotropism (water), chemotropism (chemicals — pollen tube to ovule).',
  34: 'Plants face a limitation: electrical impulses need specialised tissue, and a plant has no nervous system. So plants signal by <b>chemicals</b> — hormones.',
  36: 'The chemical advantage: a molecule released by one cell reaches many cells via the transport stream — so one signal can affect the <b>whole plant</b> gradually, not just a single wire.',
  37: 'The plant hormone cast: <b>auxin</b> (cell elongation), <b>gibberellin</b> (stem growth, germination), <b>cytokinin</b> (cell division), <b>abscisic acid</b> (growth inhibitor, closes stomata), ethylene (ripening). Promoters vs inhibitors — the balance rules.',
  38: 'Phototropism decoded: light scatters auxin to the shaded side \u2192 those cells elongate more \u2192 the shoot bends <b>towards</b> the light. The hormone doesn\u2019t vanish — it relocates.',
  41: 'The adrenal story: seeing danger \u2192 adrenaline \u2192 faster heartbeat, faster breathing, more blood and oxygen to muscles — the "fight or flight" readiness. Chemical coordination\u2019s star demo.',
  45: '<b>Thyroxin</b> needs <b>iodine</b>. Shortage = swollen thyroid (<b>goitre</b>) — the reason salt is iodised. Thyroxin regulates carbohydrate, protein and fat metabolism.',
  46: 'Puberty\u2019s master switch: the pituitary signals the <b>testes</b> (testosterone) and <b>ovaries</b> (oestrogen) — the hormones that drive the changes in boys\u2019 and girls\u2019 bodies at adolescence.',
  47: '<b>Insulin</b>, from the pancreas, regulates blood sugar. Its shortage or failure = <b>diabetes</b> — sugar accumulates in blood and spills into urine.',
  48: 'Feedback in action: sugar rises after a meal \u2192 pancreatic cells detect it \u2192 insulin released \u2192 cells absorb sugar \u2192 level falls. Hormones are self-regulating thermostats, not one-way switches.',
  50: 'The comparison the exam loves: <b>nervous</b> = wire + electricity, fast and point-to-point; <b>hormonal</b> = bloodstream + molecules, slow and body-wide. Together they run the animal.'
};

window.DECODE['bio3'] = {
  2: 'Why offspring resemble parents: the body\u2019s blueprints are copied. The <b>basic event of reproduction = making a DNA copy</b> — the instruction manual for building another individual.',
  3: 'The copying is excellent but not perfect: slight <b>variations</b> creep into every copy. Two daughter cells are similar, never identical — the engine of diversity.',
  5: 'Those copying errors are not flaws — they are the raw material that lets populations adapt. This section is the bridge to Heredity and Evolution chapters.',
  6: 'Why variation matters: a niche (an organism\u2019s slot in the ecosystem) can change — temperature, water, food, predators. Variation is the population\u2019s insurance policy.',
  7: 'The bacteria-in-temperate-waters thought experiment: if the water warms and every individual is identical, all die together; if variation exists, some survive and multiply. Survival of the varied.',
  10: '<b>Fission</b>: single-celled division. <b>Binary</b> = two equal halves (amoeba any plane, paramoecium transversely); <b>multiple</b> = many daughter cells at once (Plasmodium inside a host).',
  12: '<b>Budding</b> in yeast: a small outgrowth swells, nucleus divides, one copy enters — the bud pinches off. Same genome, new individual.',
  13: 'Why multicellular organisms can\u2019t just split in two: their cells are <b>specialised</b> (liver cells aren\u2019t muscle cells). A random half cannot rebuild a whole — unlike planaria\u2019s specialised regeneration cells.',
  15: '<b>Regeneration</b>: planaria and sponces regrow a complete organism from a fragment. The trick belongs to <b>specialised cells</b> that proliferate and re-differentiate at the cut.',
  17: 'Hydra\u2019s budding uses regenerative cells for reproduction — a bud with tentacles forms on the parent\u2019s flank, detaches, and lives alone.',
  18: '<b>Vegetative propagation</b>: new plants from vegetative parts — rose and banana by cuttings/layering (neither sets viable seed easily), sugarcane by stem pieces.',
  20: '<b>Bryophyllum</b>: buds along the leaf margin sprout into plantlets that drop and root — leaves that reproduce. Potato\u2019s "eyes" are buds on a swollen stem (tuber) — cut a piece with an eye, grow a plant.',
  22: '<b>Spore formation</b> in Rhizopus: blob-like <b>sporangia</b> on hyphae release thick-walled <b>spores</b> that survive heat and drought, then germinate on moist bread — reproduction plus a lifeboat.',
  24: 'The sexual idea: instead of one genome copied, <b>two individuals combine their DNA</b> — the next generation is a fresh mix, not a clone. That mixing is the whole point.',
  26: 'Two sources of variation stack: DNA-copying errors <b>plus</b> combination of two parents\u2019 variants — sexual reproduction multiplies diversity.',
  30: 'The flower\u2019s parts mapped: <b>stamen</b> (anther + filament) makes pollen; <b>pistil</b> (stigma + style + ovary) holds the ovules. Petals/sepals are advertising and packaging.',
  32: '<b>Pollination</b> = pollen travel from anther to stigma. <b>Self-pollination</b>: same flower. <b>Cross-pollination</b>: different flower/plant — more variation, which is why many flowers bribe insects.',
  33: 'After pollination, a <b>pollen tube</b> grows down the style to the ovule — the male gamete fuses with the egg: <b>fertilisation</b>. Zygote \u2192 embryo; ovule \u2192 seed; ovary \u2192 fruit.',
  35: 'Puberty\u2019s visible script: height spurt, body hair, skin changes, plus <b>common</b> changes (growth, new feelings) and <b>sex-specific</b> ones (breast development and menstruation in girls; facial hair, voice change in boys).',
  39: 'Why sexual maturity arrives on a schedule: the body becomes able to <b>protect and nurture</b> offspring — resources, size, and behaviours must be ready first.',
  42: 'Reproduction needs two systems: one that <b>makes</b> germ cells, and one that <b>delivers</b> them to meet — hence the whole reproductive anatomy of the next sections.',
  43: 'Male system: <b>testes</b> (make sperm + testosterone; held in the <b>scrotum</b> outside the body — sperm need a temperature ~3 K lower) \u2192 epididymis \u2192 vas deferens \u2192 urethra; seminal vesicles + prostate add semen fluid.',
  45: 'Female system: <b>ovaries</b> (one egg per cycle) \u2192 <b>fallopian tube</b> (fertilisation site) \u2192 <b>uterus</b> (implantation, gestation) \u2192 cervix \u2192 vagina (birth canal).',
  46: 'Conception: sperm deposited in the vagina swim to the fallopian tube; the fertilised egg (zygote) travels down and <b>implants</b> in the thickened uterine lining.',
  47: 'The <b>placenta</b>: villi-rich tissue exchanging food, oxygen and waste between foetal and maternal blood — with viruses, alcohol and drugs able to cross too. The umbilical cord is the fetus\u2019s supply line.',
  48: 'If the egg isn\u2019t fertilised, the prepared lining isn\u2019t needed: it sheds with blood — <b>menstruation</b>, roughly every 28 days.',
  49: 'Reproductive health\u2019s frame: sex can mean pregnancy and disease — so health = knowledge, contraception access, and protection from STIs. Reproduction should be a choice.',
  51: 'Contraception\u2019s three tracks: <b>barrier</b> (condom, diaphragm — condoms also block STIs), <b>hormonal/IUCD</b> (pills change hormones; copper-T in the uterus) and <b>surgical</b> (vasectomy/tubectomy — permanent).',
  53: 'Surgical methods are the most reliable but irreversible — best for couples who want no more children. Pills carry side effects; condoms are the only dual-purpose method.',
  54: 'Female foeticide: illegal and destructive — it skews the child sex ratio. The chapter\u2019s ethics page; one-mark questions come from here.',
  58: 'Summary skeleton: DNA copying \u2192 variation \u2192 asexual modes (fission, budding, fragmentation, regeneration, vegetative propagation, spores) vs sexual (gamete fusion, more variation); flower = plant\u2019s sexual organ; human systems; contraception for health.'
};

window.DECODE['bio4'] = {
  0: 'The chapter\u2019s question: reproduction makes new individuals "similar, but subtly different." Where does the similarity come from, and what rules govern the differences? Answer: <b>heredity</b> — Mendel\u2019s rules.',
  1: 'Variation accumulates down generations: a bacterium divides, its copies divide — each round adds new small differences to inherited ones. Even asexual reproduction generates diversity.',
  2: 'Two inheritances arrive together: a <b>common basic body design</b> (the family resemblance) plus <b>subtle changes</b> to it (the individuality). Every offspring is a remix, not a photocopy.',
  4: 'Do all variations survive equally? No — the environment selects. A variation that helps in a hot year may be useless in a cold one. Survival depends on the <b>niche</b>, and niches change.',
  6: '<b>Inherited traits</b> = those passed via DNA from parents. The NCERT ear-lobe activity (attached vs free) shows a human either/or trait, Mendel-style — your family\u2019s own genetics lab.',
  8: '<b>Gregor Mendel</b>, monk in Brno, ~1856-63: chose the garden pea — fast generations, self-pollinating (so pure lines), and seven either/or traits. His tool: counting. Statistics exposed the hidden rules.',
  9: 'Why peas beat other organisms: a single trait can be tracked cleanly, pure parents are available, and generations turn over fast. The experimental design was as brilliant as the results.',
  11: 'The F\u2081 shock: pure tall \u00d7 pure dwarf gives <b>all tall</b> — no blending, no "halfway" plants. The dwarf factor hides but doesn\u2019t vanish (F\u2082 proves it). Traits are particles, not paint.',
  12: 'F\u2082: about <b>3 tall : 1 dwarf</b>. One quarter short again — so both tallness and dwarfness factors survived inside the F\u2081 plants. Something segregated cleanly when F\u2081 made gametes.',
  13: 'The modern reading: TT and Tt are tall; only tt is short. Genotype vs phenotype — a 1:2:1 genotype ratio hiding beneath a 3:1 phenotype ratio. The 2-in-3 Tt plants are "carriers" of dwarfness.',
  14: 'The <b>dihybrid</b> twist: two traits at once — round/wrinkled seed \u00d7 tall/short plants. F\u2082 throws up <b>new combinations</b>: tall-wrinkled, short-round — impossible if traits travelled glued together.',
  18: 'F\u2082 of the dihybrid: 9 round-yellow : 3 round-green : 3 wrinkled-yellow : 1 wrinkled-green — each <b>trait pair segregates independently</b>. Mendel\u2019s second law: independent assortment.',
  20: 'Genes sit on <b>chromosomes</b> — each cell carries two sets (one from each parent); gametes carry one. The physical machinery behind Mendel\u2019s abstract "factors".',
  21: '<b>Sex determination</b>: the 23rd human chromosome pair — XX female, XY male. Every egg carries X; sperm are 50/50 X and Y — so the <b>father\u2019s sperm decides</b> the child\u2019s sex.',
  22: 'Not every species works this way: in snails an individual can <b>change sex</b>; in some turtles the <b>temperature</b> of the nest decides. Nature has multiple blueprints.',
  24: 'The Punnett square for X\u00d7Y sperm: half XX (girls), half XY (boys) — 50:50 every time. A society that blames mothers for a daughter\u2019s birth is biologically wrong, full stop.'
};

window.DECODE['bio5'] = {
  0: 'FORMATIVE-ONLY for 2026-27: the Evolution half of the old chapter, re-issued via the CBSE <b>Reading Material</b>. Not in the year-end exam — study it for your Portfolio write-up. It begins from where Heredity ended: variation + the environment.',
  1: 'Beetle story, situation 1: a <b>colour variation</b> (blue beetles) arises in a red population. Crows eat the visible red ones — the blues survive. A plant then spreads through the bushes making green the camouflage colour. Nobody "chose" anything — the environment filtered.',
  2: 'The green beetle variant takes over without any beetle "trying". Natural selection is a sieve, not a sculptor with a plan.',
  3: 'Situation 2, the random disaster: an elephant tramples the bushes — most beetles die, and by pure chance the survivors are mostly <b>blue</b>. The next generation is blue not because blue is better, but because blue got lucky. This is <b>genetic drift</b>.',
  4: 'Contrast to memorise: <b>natural selection</b> gives the trait a survival advantage; <b>genetic drift</b> is accidental frequency change — both can make a rare variant common.',
  6: 'The second beetle situation shows drift\u2019s signature: the colour gave <b>no survival advantage</b> — the change spread by accident alone.',
  8: '<b>Acquired vs inherited</b>: the germ cells alone carry DNA to the next generation. Changes to body cells in one\u2019s lifetime (muscles, skills, injuries) never enter the germ line.',
  9: 'The mouse-tail test: cutting tails for generations — every baby still has a tail. Acquired traits <b>cannot direct evolution</b>. This kills "giraffes stretched their necks" folklore.',
  14: 'When is it a new species? When the beetle group can <b>no longer interbreed</b> with the others — <b>reproductive isolation</b>. Appearance isn\u2019t the test; gene flow is.',
  15: '<b>Speciation\u2019s engine</b>: a river splits the population \u2192 each side accumulates its own drift and selection \u2192 the gene pools drift apart \u2192 even reunited, they can\u2019t breed. Geographical isolation starts it.',
  17: 'Why small isolated populations diverge fast: drift is stronger when numbers are few — a few survivors carry a lopsided sample of genes.',
  18: 'Drift + selection together: both sub-populations change, each adapted (or accidentally shifted) to its own valley — after enough generations, two species stand where one entered.',
  21: 'Classification and evolution share a logic: <b>more shared characteristics = more recent common ancestor</b>. Grouping species is literally drawing the family tree.',
  24: 'The nesting rule: species with a recent common ancestor form a small group; larger groups have more distant ancestors — the tree builds from twigs to boughs.',
  26: '<b>Homologous organs</b>: same basic structure, different jobs — the forelimbs of humans, bats, whales, birds share one bone blueprint. Common ancestry, divergent design.',
  28: '<b>Analogous organs</b>: bird wing and insect wing — same function, completely different structure. No shared origin; similar needs bred similar solutions (convergent evolution).',
  29: '<b>Fossils</b>: preserved remains or traces of ancient life — the archives of evolution. Soft parts usually decay; hard shells, bones and impressions in rock survive.',
  30: 'Two dating clocks: <b>relative</b> (deeper in the sediment = older) and <b>absolute</b> (radioactive/carbon dating measures isotope decay). Together they put dates on the story.',
  31: 'Layer-by-layer formation: die \u2192 bury \u2192 sediment covers \u2192 rock forms \u2192 millions of years stack more layers on top. Erosion later exposes the sandwich — each layer a page of time.',
  33: '<b>Eyes evolved in stages</b>: a flatworm\u2019s light-sensitive spot has survival value (direction of light = direction of food/shelter). Each improvement — pit, pinhole, lens — added advantage. Complex organs need no blueprint, only stages.',
  35: '<b>Feathers first kept dinosaurs warm</b> — flight came later, repurposing an existing structure. Evolution is a tinkerer, reusing what\u2019s at hand.',
  37: '<b>Molecular phylogeny</b>: compare DNA and protein sequences between species — differences accumulate like clock ticks, so sequence distance = evolutionary distance. It confirmed and refined the fossil-based trees.',
  40: 'Evolution is a <b>branching bush</b>, not a ladder: multiple lineages split at every stage; most branches end. There\u2019s no "higher and lower" — only surviving branches.',
  41: 'Humans and chimpanzees share a <b>common ancestor</b> — we did not descend FROM chimps. Both lineages walked away from the same fork, each in its own direction.',
  44: '<b>Human evolution</b>: Homo sapiens arose in <b>Africa</b>; fossil and DNA trails track the migration waves — Asia, Europe, across to the Americas and Australia.',
  45: 'Despite skin, face and hair differences, all humans are <b>one species</b> with trivial genetic variation — the visible differences are recent adaptations to climate, not separate "races".',
  47: 'The chapter\u2019s equality lesson: the tools of evolution — fossils, homologous structures, molecular phylogeny — all agree that human "races" are superficial. Science undermines racism\u2019s biology claim.'
};
