/* DECODE — Physics: plain-English explanations keyed by textlines block index */
window.DECODE = window.DECODE || {};

window.DECODE['phy1'] = {
  2: 'Plane-mirror image checklist: virtual, erect, <b>same size</b>, as far behind as the object is in front — and <b>laterally inverted</b> (left hand becomes right). The spoon demo shows what curvature changes.',
  3: 'Enter <b>spherical mirrors</b>: curved inward = <b>concave</b> (converging); bulging outward = <b>convex</b> (diverging). The inside of the spoon is a concave mirror; the back is a convex one.',
  5: 'Vocabulary set: <b>pole P</b> (mirror\u2019s centre), <b>centre of curvature C</b> (centre of the parent sphere — lies outside the mirror), <b>principal axis</b> (the P-C line), and the <b>radius of curvature</b> = PC.',
  9: '<b>Principal focus</b>: rays parallel to the axis of a concave mirror actually meet at F after reflection; for a convex mirror they only <b>appear</b> to come from F. Real convergence vs virtual divergence.',
  10: '<b>Focal length f = distance P to F</b>, and the golden relation <b>f = R/2</b> — the focus sits exactly halfway to the centre of curvature.',
  17: 'The concave-mirror image table to memorise: object beyond C \u2192 image between F and C (real, inverted, diminished); at C \u2192 at C (same size); between C and F \u2192 beyond C (enlarged); at F \u2192 infinity; between P and F \u2192 behind mirror (virtual, erect, magnified).',
  19: 'Ray-diagram method: any <b>two</b> reflected rays intersect at the image point. Pick the easy rays — parallel-to-axis, through-F, through-C, or aimed at P.',
  20: 'The four standard rays: (1) parallel \u2192 reflects through F; (2) through F \u2192 reflects parallel; (3) through C \u2192 reflects back on itself; (4) at the pole \u2192 symmetric bounce about the axis.',
  23: 'Every concave-mirror case in one sweep: the closer the object marches towards the mirror from infinity, the further and larger the image runs — until the object crosses inside F and the image flips virtual-erect behind the mirror.',
  25: '<b>Convex mirror verdict</b>: for ANY object position — virtual, erect, diminished, behind the mirror. No cases to juggle.',
  30: 'Why convex mirrors guard driveways and blind corners: <b>erect images</b> (no left-right inversion games) and a <b>wider field of view</b> — the very property that shrinks the image also fits more world into it.',
  32: 'The <b>New Cartesian convention</b>: origin at the pole; x-axis along the principal axis; distances <b>against</b> incident light (usually leftward) are negative; heights above the axis positive. The convention turns every mirror problem into signed algebra.',
  36: '<b>Magnification</b> m = h\u2032/h = \u2013v/u. Negative m \u2192 inverted real image; positive m \u2192 erect virtual image; |m| > 1 \u2192 enlarged.',
  38: 'Worked-example pattern (NCERT): u = \u201325, f = \u201315 \u2192 1/v = 1/f \u2013 1/u gives v = \u201337.5 cm (real, in front), m = \u2013v/u = \u20131.5, image height 1.5 \u00d7 object, inverted. Sign discipline does the whole job.',
  41: 'Refraction\u2019s everyday proofs: a lemon in water looks bigger and shifted, a pencil looks bent at the waterline, a coin at the bottom appears raised. Light changes speed between media — and bends for it.',
  48: 'Glass-slab geometry: ray bends <b>towards the normal</b> entering the denser glass, away on exit. Net effect: the emergent ray is <b>parallel</b> to the incident ray, just <b>laterally shifted</b>.',
  51: 'The <b>laws of refraction</b>: (1) incident, refracted rays and normal share one plane; (2) <b>sin i / sin r = constant</b> for a given pair of media — Snell\u2019s law.',
  53: 'The constant of Snell\u2019s law is the <b>relative refractive index</b> n\u2082\u2081 — a number measuring how strongly medium 2 bends light coming from medium 1.',
  56: 'Refractive index = speed ratio: n\u2082\u2081 = v\u2081/v\u2082. Light slows in glass (n \u2248 1.5) and water (1.33); the bend is the visible footprint of the slowdown.',
  60: 'Optical density vs mass density — different things! Kerosene (n higher) may float on water (mass denser). "Optically denser" only means light travels slower.',
  63: 'A <b>lens</b>: transparent material bound by two curved surfaces. <b>Convex</b> (middle thick) converges; <b>concave</b> (edge thick) diverges.',
  69: 'Lens geometry mirrors mirror-geometry: two centres of curvature, a principal axis through the <b>optical centre O</b>, and two foci F\u2081 and F\u2082 (symmetric) — f is measured from O.',
  71: 'For lenses too, parallel rays define the principal focus: a convex lens <b>actually converges</b> them at F\u2082; a concave lens makes them only <b>appear</b> to diverge from F\u2081.',
  75: 'The convex-lens image table: beyond 2F\u2081 \u2192 real inverted diminished between F\u2082 and 2F\u2082 (camera); at 2F\u2081 \u2192 same size at 2F\u2082; between F\u2081 and 2F\u2081 \u2192 enlarged beyond 2F\u2082 (projector); at F\u2081 \u2192 infinity; inside F\u2081 \u2192 virtual erect magnified same side (magnifying glass).',
  77: '<b>Concave lens</b>: always virtual, erect, diminished — between F\u2081 and O. The mirror twin of the convex mirror.',
  79: 'Lens ray rules: parallel ray \u2192 through F\u2082; ray through F\u2081 \u2192 emerges parallel; ray through optical centre O \u2192 passes straight (the lens is a thin slab there).',
  82: 'The <b>lens formula</b>: 1/v \u2013 1/u = 1/f — same skeleton as the mirror formula but with the minus, and u negative for real objects, f positive for convex lenses, negative for concave.',
  85: 'Worked example (concave lens): u = \u201330, f = \u201315 \u2192 v = \u201310 cm — image virtual, same side, one-third size, erect (m = +0.33). The signs tell the whole story.',
  89: '<b>Power</b> P = 1/f (f in metres), unit <b>dioptre</b> (D). Convex \u2192 positive P; concave \u2192 negative P. A 25 cm convex lens is +4.0 D.',
  91: 'Lenses in contact: <b>power adds</b> — P = P\u2081 + P\u2082. Opticians stack thin lenses to engineer a total power, which is why "powers add" is the optician\u2019s favourite rule.'
};

window.DECODE['phy2'] = {
  2: 'The eye as camera: cornea does the <b>bulk of refraction</b>, the eye-lens fine-focuses, the iris is the aperture control (pupil), and the <b>retina</b> is the film — a real, inverted, diminished image forms on it. The brain flips it upright.',
  3: 'Light detection: the retina\u2019s <b>rods</b> work in dim light (no colour), <b>cones</b> need bright light and read colour. The sharpest spot is the small cone-rich <b>yellow spot</b>.',
  4: '<b>Accmodation</b>: the ciliary muscles change the jelly-like lens\u2019s curvature — flatter for far objects, fatter for near ones — changing its focal length at will. No camera lens does this.',
  5: 'The mechanics: muscles relax \u2192 lens thin \u2192 f large \u2192 distant focus; muscles contract \u2192 lens thick \u2192 f small \u2192 near focus.',
  6: 'Two benchmark distances for a normal young adult: <b>near point 25 cm</b> (closest sharp focus) and <b>far point infinity</b>.',
  8: '<b>Myopia</b> (near-sightedness): distant objects blur — the eyeball is too long or the lens too strong, so the image forms <b>in front of the retina</b>. Fix: a <b>concave lens</b> that diverges rays before they enter.',
  9: '<b>Hypermetropia</b> (far-sightedness): near objects blur — the image would form <b>behind the retina</b> (short eyeball / weak lens). Fix: a <b>convex lens</b> that pre-converges the rays.',
  11: '<b>Presbyopia</b>: ageing — the lens stiffens and ciliary muscles weaken, so accommodation fades. Reading small print becomes hard; the near point recedes. Same fix direction as hypermetropia, different cause.',
  12: '<b>Bifocals</b>: upper half concave (distance — for the myopic), lower half convex (reading). One pair of glasses, two jobs.',
  18: 'Prism geometry: light bends <b>towards the normal</b> entering the glass, away on exit — and the two tilted faces mean the two bends <b>add</b>, not cancel. Net result: the emergent ray is deviated from its original path.',
  21: 'The prism surprise: white light through a prism paints a band of colours — the prism hasn\u2019t created them; it has <b>separated</b> what was always inside the white.',
  22: '<b>Dispersion</b> defined: the splitting of light into its component colours. The band is the <b>spectrum</b> — VIBGYOR, violet deviated most, red least.',
  23: 'Why colours split: refractive index differs slightly per colour — violet slows and bends most in glass, red least. Each colour takes its own angle.',
  24: 'Newton\u2019s clincher: a second inverted prism <b>recombined</b> the spectrum back into white. Conclusion — white light is a mixture; the prism merely sorts.',
  26: 'The rainbow: sunlight inside raindrops refracts, reflects internally, and exits dispersed — nature\u2019s prism show, always with red on top (primary bow).',
  28: '<b>Atmospheric refraction</b>: air of varying density bends light — the shimmer above a hot road, wavering images through hot air. Starlight passes through a restless density map.',
  29: 'Stars twinkle because the atmosphere\u2019s refraction keeps shifting the star\u2019s <b>apparent position</b> slightly — the starlight dances as air layers churn.',
  31: 'Planets don\u2019t twinkle (much): a planet is a tiny <b>disc</b>, not a point — its many light beams average out the fluctuations to a steady glimmer.',
  33: 'The <b>Tyndall effect</b>: a true solution stays clear, but a colloid (milk in water, smoke in air) scatters the beam — the path becomes visible. The particles must be big enough to scatter.',
  36: 'Why the sky is blue: air molecules scatter <b>short wavelengths best</b> — blue light bounces around the whole sky into your eyes. Red scatters least and travels straight.',
  37: 'The astronaut\u2019s view proves it: with no atmosphere, no scattering — space\u2019s sky is <b>black</b> even in sunshine.',
  38: 'Why danger lights are <b>red</b>: red scatters the least, so it penetrates fog, smoke and dust furthest — visible when other colours have been scattered away.'
};

window.DECODE['phy3'] = {
  2: 'An <b>electric circuit</b> = a closed, continuous loop for current. Open the switch, break the loop, and the current stops — the first and last rule of circuit wiring.',
  4: 'Direction convention: current flows <b>positive to negative</b> outside the cell — the opposite of actual electron drift. Blame history; both models give identical answers.',
  5: '<b>I = Q/t</b> — current is the rate of charge flow. One ampere = one coulomb per second. A bulb drawing 0.5 A for 10 minutes shifts 300 C.',
  6: 'Measurement rules: <b>ammeter in series</b> (the whole current passes through it, low resistance), <b>voltmeter in parallel</b> (across the component, high resistance).',
  8: 'The water analogy: charge won\u2019t move by itself any more than a canal flows level — a <b>potential difference</b> (the "height drop") must push it. The cell is the pump.',
  11: '<b>1 volt = 1 joule per coulomb</b> — V = W/Q. A 12 V battery gives each coulomb 12 joules of energy to spend in the circuit.',
  16: 'The nichrome-wire V-I graph: a <b>straight line through the origin</b> — current exactly proportional to voltage. That proportionality is Ohm\u2019s law, and the slope\u2019s inverse is R.',
  17: '<b>Ohm\u2019s law (1827, Georg Simon Ohm)</b>: at constant temperature, V \u221d I, i.e. <b>V = IR</b>. Temperature constant matters — heat the wire and the line bends.',
  18: '<b>Resistance</b> R = V/I: the conductor\u2019s friction against charge flow, unit <b>ohm (\u03a9)</b>. One ohm lets one ampere through per volt applied.',
  22: 'Different components draw different currents at the same V — each has its own resistance. The rheostat exploits this: a resistor you can slide to tune the current.',
  25: 'The four factors experiment: same length and material — <b>thicker wire, more current</b> (less R); <b>longer wire, less current</b> (more R); nichrome resists far more than copper.',
  26: 'The formula behind the experiments: <b>R = \u03c1L/A</b>. Length up \u2192 R up; area up \u2192 R down; \u03c1 (resistivity) is the material\u2019s fingerprint.',
  28: 'Materials pick jobs by resistivity: <b>copper/aluminium</b> (low \u03c1) carry current as wires; <b>nichrome</b> (high \u03c1) turns current into heat as a heating element; <b>tungsten</b> glows white-hot as a filament.',
  32: 'Classic numerical: R = \u03c1L/A — halve the diameter (quarter the area) and resistance <b>quadruples</b>. Or stretch a wire to double length: L doubles AND A halves \u2192 R becomes 4R.',
  38: '<b>Series circuit signature</b>: the ammeter reads the <b>same current everywhere</b> — one path, one stream. Voltages divide across the components.',
  42: 'Series result: <b>R\u209b = R\u2081 + R\u2082 + R\u2083 + …</b> — the equivalent is always bigger than any single resistor. One failure breaks the whole string.',
  44: 'Worked example: 20 \u03a9 lamp + 4 \u03a9 conductor in series on 6 V \u2192 R\u209b = 24 \u03a9, I = 0.25 A. The current is common; each component\u2019s voltage = IR shares the 6 V.',
  47: '<b>Parallel circuit signature</b>: same voltage across every branch; the main-line current is the <b>sum of branch currents</b>: I = I\u2081 + I\u2082 + I\u2083.',
  48: 'Parallel result: <b>1/R\u209a = 1/R\u2081 + 1/R\u2082 + …</b> — the equivalent is <b>smaller than the smallest branch</b>. Two 6 \u03a9 in parallel give 3 \u03a9. More paths, easier flow.',
  52: 'Why homes wire in parallel: every appliance gets the <b>full mains voltage</b>, switches on/off independently, and one bulb dying doesn\u2019t black out the house. Fairy-lights (series) show the alternative\u2019s flaw.',
  55: 'The <b>heating effect</b>: current through any resistance warms it — a fan running for hours heats up, wires carrying overload heat dangerously. The physics: electrons collide with the lattice, dumping energy as heat.',
  57: '<b>Joule\u2019s law of heating</b>: H = I\u00b2Rt (equivalently VIt or V\u00b2t/R). Double the current, quadruple the heat — the I\u00b2 is the fuse\u2019s whole reason to exist.',
  61: 'Heating-effect applications: electric iron, geyser, toaster, immersion rod — nichrome elements engineered to get hot; the electric bulb glows rather than merely heats.',
  62: 'Bulb engineering: tungsten filament (melts at ~3400\u00b0C, glows near 3000\u00b0C without melting), packed in <b>argon/nitrogen</b> so the white-hot metal can\u2019t oxidise.',
  63: 'The <b>fuse</b>: a low-melting-point alloy wire in the circuit\u2019s path. Overload \u2192 I\u00b2Rt spikes \u2192 the fuse melts first and breaks the circuit — a deliberate sacrificial link.',
  64: 'Fuse ratings (1 A, 2 A, 5 A, 10 A, 15 A…) must match the circuit\u2019s normal load. Too low — nuisance blowing; too high — no protection.',
  67: 'The electricity bill\u2019s unit: the <b>kilowatt-hour</b> — energy used by a 1 kW device in one hour = <b>3.6 \u00d7 10\u2076 J</b>. The meter counts kWh, not watts.',
  69: 'Bill arithmetic: 400 W fridge \u00d7 8 h/day \u00d7 30 days = 96 kWh = 96 units \u00d7 the rate. This exact pattern appears in the board exam almost every year.',
  71: 'Three control knobs: rheostat (tunes current), series/parallel (steps resistance), and voltage — everything else is bookkeeping.',
  73: 'Chapter\u2019s formula toolkit: V = IR, R = \u03c1L/A, R\u209b = \u03a3R, 1/R\u209a = \u03a31/R, H = I\u00b2Rt, P = VI = I\u00b2R = V\u00b2/R, 1 kWh = 3.6\u00d710\u2076 J. Master these seven and every numerical falls.'
};

window.DECODE['phy4'] = {
  0: 'The big reveal of this chapter: electricity and magnetism are one subject. A current <b>always</b> makes a magnetic field around it — Oersted\u2019s lucky compass discovery, 1820.',
  3: '<b>Magnetic field</b>: the region where a compass feels a force. Its direction at a point = the direction the compass needle\u2019s <b>north pole</b> settles. Iron filings trace the field\u2019s shape beautifully.',
  8: '<b>Field lines never intersect</b> — at a crossing, the compass needle would need to point two ways at once. They run N\u2192S outside the magnet, S\u2192N inside, forming closed curves, crowded where the field is strong.',
  13: 'Straight wire pattern: <b>concentric circles</b> around the wire — bigger circles as you move out (field weakens with distance).',
  16: 'Reverse the current, reverse the circles — the field direction flips with the current\u2019s direction. That is the right-hand rule\u2019s content.',
  19: '<b>Right-hand thumb rule</b>: thumb with the current, curled fingers show the field circles. One hand decodes every straight-wire direction question.',
  21: 'For a long straight wire, field strength \u221d I/r — more current, stronger field; farther away, weaker.',
  22: 'Loop the wire and the fields of every segment <b>add up inside the loop</b> — one face acts like a N-pole, the other a S-pole. Curl more loops and the effect multiplies.',
  24: 'The <b>solenoid</b>: a helical coil whose inside field is <b>uniform and parallel</b> — a bar magnet you can switch. Ends behave exactly like N and S poles.',
  25: 'Insert a <b>soft-iron core</b> into a current-carrying solenoid \u2192 a powerful <b>electromagnet</b>: crane magnets, electric bells, relays. Switch off, the magnetism vanishes — the control is the point.',
  29: 'The aluminium-rod experiment: current through the rod between magnet poles <b>displaces the rod</b> — a force acts on a current-carrying conductor in a field.',
  31: 'The force is largest when current \u22a5 field, zero when they\u2019re parallel, and reverses when either current or field reverses. Three facts, every motor question.',
  32: '<b>Fleming\u2019s left-hand rule</b>: forefinger = <b>F</b>ield, middle finger = <b>C</b>urrent, thumb = <b>M</b>otion (force) — all three mutually perpendicular. Stretch it, and direction questions solve themselves.',
  33: 'Applications of the motor principle: electric fans, washing machines, mixers — anything that converts electricity to spin.',
  37: 'The domestic supply: two insulated wires + an earth wire enter through the <b>meter</b> and main switch. The <b>live wire</b> carries 220 V; the <b>neutral</b> is at ground potential and completes the loop.',
  38: 'House wiring splits into circuits, each with its own <b>fuse</b> — typically <b>15 A</b> for heavy appliances (geyser, AC) and <b>5 A</b> for lights and fans.',
  39: 'The <b>earth wire</b>: green insulation, connects metal bodies of appliances to a buried metal plate. A live fault sends current harmlessly to earth — the fuse blows, the user survives. The cheapest life-insurance in physics.',
  41: 'The <b>fuse</b> in every circuit: melts on overload, breaking supply before wires can overheat. Its rating must match the wiring\u2019s safe capacity.',
  43: '<b>Overloading</b> = drawing more current than the wiring safely carries — too many appliances on one circuit, or a supply-voltage hike. <b>Short circuit</b> = live touches neutral directly (near-zero resistance, huge current). Both end at the fuse.',
  44: 'Anti-overload habits: don\u2019t plug many high-power devices into one socket, don\u2019t chain extension boards — every fire-safety PSA is applied Ohm\u2019s law.',
  45: 'Two rules to carry out: field direction = compass north\u2019s direction; straight-wire fields = concentric circles from the right-hand thumb rule.',
  48: 'The earth wire\u2019s one job: give leakage current a low-resistance path to ground so the body of an appliance never sits at lethal voltage.'
};

window.DECODE['phy5'] = {
  0: 'FORMATIVE-ONLY for 2026-27: the motor is back via the CBSE <b>Reading Material</b> — not in the year-end exam. A <b>motor converts electrical energy into mechanical (rotational) energy</b>: a current-carrying coil in a magnetic field experiences forces on its two sides.',
  2: 'Motor anatomy: rectangular coil ABCD between magnet poles, current fed via <b>brushes</b> pressing on a <b>split-ring commutator</b>. Opposite arms carry current in opposite directions \u2192 equal-and-opposite forces \u2192 rotation.',
  3: 'The commutator\u2019s genius: after every half-turn it <b>reverses the current direction</b> in the coil, so the torque keeps pushing the same way — the coil spins continuously instead of oscillating.',
  4: 'Commercial motors upgrade the school model: an <b>electromagnet</b> (not a permanent magnet), a soft-iron core in the coil, and current from the mains — more field, more torque.',
  5: '<b>Faraday 1831</b>: the reverse trick — a <b>moving</b> magnet near a coil induces a current. Electricity from magnetism: <b>electromagnetic induction</b>.',
  7: 'Coil-and-galvanometer rules: magnet in \u2192 needle swings one way; magnet held still \u2192 needle returns to zero; magnet out \u2192 swing the other way. Faster motion \u2192 bigger swing. Motion (change) is essential — stillness induces nothing.',
  11: 'Variation on the theme: two coils side by side — switching the current in coil-1 induces a momentary current in coil-2. A <b>changing</b> magnetic field, not a moving magnet, is the real requirement.',
  13: 'Induced current is largest when the motion is perpendicular to the field lines, zero when parallel — the right-angle geometry that generators exploit.',
  14: 'Two ways to induce current: move a magnet (or the coil) inside a coil, or change the current in a neighbouring coil. Both make the field lines "cut" the conductor.',
  15: 'The <b>electric generator</b> = motor in reverse: rotate a coil in a magnetic field mechanically (turbine) \u2192 induced current flows out. Mechanical energy \u2192 electrical energy.',
  17: 'As the coil rotates, the induced current\u2019s direction flips every half-rotation — the output is <b>alternating current (AC)</b>. Slip rings carry this alternating current out.',
  18: 'Swap the slip rings for a <b>commutator</b> and the flips cancel — the output becomes one-directional <b>direct current (DC)</b>. One component decides AC or DC.',
  19: 'DC flows one way (batteries). AC reverses direction periodically — India\u2019s grid alternates at <b>50 Hz</b>. AC\u2019s superpower: transformers can step its voltage up for low-loss long-distance transmission, then down for homes.'
};
