/* DECODE — Chemistry: plain-English explanations keyed by textlines block index */
window.DECODE = window.DECODE || {};

window.DECODE['che1'] = {
  2: 'The first signposts of a chemical reaction — <b>magnesium burning</b> (dazzling white flame), <b>zinc in acid</b> (bubbles of gas), <b>iron rusting</b>. Same rule every time: the starting substance loses its identity and something new with new properties appears.',
  3: 'A <b>word equation</b> is chemistry\u2019s first draft: magnesium + oxygen \u2192 magnesium oxide. Shorter than a sentence, it still names every player. The arrow means "gives" and reads left-to-right: reactants before it, products after.',
  4: 'Cooking, digesting, respiring, fermenting — your own body runs thousands of chemical reactions every second. That\u2019s why "food gets digested" counts as chemistry, not just biology.',
  6: 'Word equations \u2192 <b>formula equations</b>. Mg + O\u2082 \u2192 MgO is shorter but now you can count atoms — and counting shows 2 oxygen atoms on the left but only 1 on the right. The equation is <b>unbalanced</b>.',
  7: 'Balancing is book-keeping for atoms. The total mass before must equal the total mass after — nothing is created or destroyed (Lavoisier\u2019s law of conservation of mass). Fix Mg + O\u2082 \u2192 MgO by doubling the magnesium: <b>2Mg + O\u2082 \u2192 2MgO</b>. Never touch subscripts — only the numbers in front.',
  8: 'Hit-and-trial balancing: start with the most complicated formula, balance one element at a time, check hydrogen and oxygen last. The process feels clumsy but always converges — the atom count forces a unique answer.',
  9: 'State symbols make equations honest: <b>(s)</b> solid, <b>(l)</b> liquid, <b>(g)</b> gas, <b>(aq)</b> dissolved in water. Conditions ride on the arrow — heat (Δ), catalyst name, light — because a balanced equation without conditions tells only half the story.',
  12: 'Zn + H\u2082SO\u2084 \u2192 ZnSO\u2084 + H\u2082 in symbols. Balancing it: both sides need one Zn, one H\u2082SO\u2084\u2019s worth of H and SO\u2084 — it\u2019s already balanced as written. The (aq) marks on the acid and zinc sulphate show the reaction runs in solution.',
  15: 'A <b>combination reaction</b>: CaO + H\u2082O \u2192 Ca(OH)\u2082 + lots of heat. Quicklime meeting water is the classic demo — the mixture actually boils. The slaked lime formed is what whitewashes walls.',
  16: 'Whitewash chemistry, continued: Ca(OH)\u2082 spreads on the wall and slowly reacts with the air\u2019s CO\u2082 \u2192 <b>CaCO\u2083</b> (limestone!) + water. That\u2019s why a freshly whitewashed wall shines after 2-3 days — the calcium carbonate layer is still drying and settling into its crystal form.',
  19: 'Burning respiration-versus-photosynthesis confusion: <b>respiration is exothermic</b> (releases energy — you run on it), <b>photosynthesis is endothermic</b> (absorbs sunlight to build glucose). Decomposition of CaCO\u2083 is also endothermic — heat must be fed in continuously.',
  21: 'Decomposition = one compound breaking into many. NCERT\u2019s three flavours by energy source: <b>thermal</b> (ferrous sulphate heated), <b>photolytic</b> (silver chloride in sunlight — photography\u2019s older chemistry), <b>electrolytic</b> (water split by current). All absorb energy — decomposition is endothermic by nature.',
  24: 'Electrolysis of water: 2H\u2082O \u2192 2H\u2082 + O\u2082. Twice as much hydrogen as oxygen at the volume level — exactly the H\u2082:O ratio hidden in the formula H\u2082O. The ash-colour trick: hydrogen burns with a pop, oxygen relights a glowing splinter.',
  26: 'Displacement: Fe + CuSO\u2084 \u2192 FeSO\u2084 + Cu. Watch a nail dipped in blue copper sulphate — the blue fades to green (iron sulphate) while brown copper deposits on the nail. Iron is above copper in the reactivity ladder, so iron kicks copper out.',
  27: 'The <b>reactivity series</b> is displacement\u2019s referee: K > Na > Ca > Mg > Al > Zn > Fe > Pb > (H) > Cu > Hg > Ag > Au. Any metal can displace any metal below it from a compound — and metals above hydrogen free hydrogen from acids; copper and silver can\u2019t.',
  29: 'Double displacement: Na\u2082SO\u2084 + BaCl\u2082 \u2192 BaSO\u2084\u2193 + 2NaCl. The ions swap partners like dance partners — Na\u207a pairs with Cl\u207b, Ba\u00b2\u207a pairs with SO\u2084\u00b2\u207b. Barium sulphate refuses to dissolve: the white solid is a <b>precipitate</b>, marked with a down arrow.',
  32: 'Oxidation-reduction in one glance: CuO + H\u2082 \u2192 Cu + H\u2082O. Copper oxide <b>loses</b> oxygen (reduced); hydrogen <b>gains</b> oxygen (oxidised). The two always travel together — a redox reaction.',
  34: 'Black copper oxide turns shining copper-red when hydrogen flows over the hot tube — the NCERT experiment that makes "reduction" visible. Meanwhile the hydrogen burns the extra oxygen to water droplets on the cool glass.',
  36: 'Rancidity: fats and oils slowly oxidise in air and begin to smell and taste bad. Defences: <b>antioxidants</b> added to packed food (they oxidise first, sacrificing themselves), <b>nitrogen flushing</b> of chip bags (no oxygen to react), refrigeration, and air-tight storage.',
  38: 'Corrosion — the slow oxidation of metals. Rust needs <b>both</b> air and moisture; the experiment with three nails (dry air, boiled water + oil, ordinary water) proves it. Galvanising (zinc coat), painting and greasing are the everyday shields.',
  41: 'The chapter\u2019s bookkeeping trick: one equation, several classifications. CaO + H\u2082O \u2192 Ca(OH)\u2082 is combination <b>and</b> exothermic. Burning magnesium is combination and oxidation. Exam questions love these overlaps — label every reaction from every angle.'
};

window.DECODE['che2'] = {
  0: 'The opening frame: acids taste <b>sour</b> (citric in lemon, lactic in curd, oxalic in spinach), bases taste <b>bitter</b> and feel soapy. But tasting lab chemicals is dangerous — that is exactly why <b>indicators</b> exist: substances that change colour (or smell) to report acid or base without any tasting.',
  1: '<b>Olfactory indicators</b> — the smell-testers: onion, vanilla essence, clove oil. Their odour vanishes or changes in a basic solution. This indicator works even for visually impaired students — a favourite one-marker.',
  3: 'The four colour-change indicators to memorise: <b>litmus</b> (blue\u2192red in acid, red\u2192blue in base), <b>methyl orange</b> (red in acid, yellow in base), <b>phenolphthalein</b> (colourless in acid, pink in base). Turmeric stain turning red with soap = a natural indicator at work in your kitchen.',
  10: 'Acid + metal \u2192 salt + <b>hydrogen gas</b>. Zn + H\u2082SO\u2084 \u2192 ZnSO\u2084 + H\u2082. Test: bring a burning splinter — hydrogen burns with a characteristic pop. The gas bubbles you see collecting are the hydrogen.',
  11: 'Surprise: some <b>bases</b> react with metals too. Zn + 2NaOH \u2192 Na\u2082ZnO\u2082 (sodium zincate) + H\u2082. Both extreme acids and strong alkalis corrode metals — hydrogen escapes both times.',
  13: 'Acid + carbonate \u2192 salt + water + <b>CO\u2082</b>. Na\u2082CO\u2083 + 2HCl \u2192 2NaCl + H\u2082O + CO\u2082. Same with hydrogencarbonates (NaHCO\u2083). The CO\u2082 turns lime water milky — the standard confirmatory test.',
  14: 'All metal carbonates and hydrogencarbonates give CO\u2082 with acids. This is the chemistry of the <b>soda-acid fire extinguisher</b> and the antacid fizz in your stomach.',
  15: '<b>Neutralisation</b>: base + acid cancel each other — NaOH + HCl \u2192 NaCl + H\u2082O. The acid\u2019s effect "is nullified" by the base. The products are always a <b>salt + water</b>.',
  16: 'Metal oxides are mostly <b>basic</b>: CuO + 2HCl \u2192 CuCl\u2082 + H\u2082O. The black copper oxide dissolves, giving the blue-green copper chloride solution.',
  17: 'Non-metal oxides are <b>acidic</b>: CO\u2082 + Ca(OH)\u2082 \u2192 CaCO\u2083 + H\u2082O — carbon dioxide turns lime water milky. Acid-in-air + base-in-water = neutralisation again.',
  22: 'The chapter\u2019s core definition: acids produce <b>H\u207a(aq)</b> as the only cation; bases produce <b>OH\u207b(aq)</b>. Every similar property of acids (sour, conductive, turning litmus) traces back to that one ion.',
  25: 'H\u207a is too lonely alone — it rides water as the hydronium ion <b>H\u2083O\u207a</b>. Acidic character appears only in water: dry HCl gas doesn\u2019t conduct or turn litmus; dissolved in water it instantly ionises.',
  26: 'Neutralisation rewritten in ions: H\u207a + OH\u207b \u2192 H\u2082O. The anion and cation pair off as the salt. Water is always the other product.',
  27: 'Dissolving NaOH or concentrated acid in water releases <b>heat</b> — always add acid to water, never water to acid, drop by drop with stirring. The local heat can crack glass or spatter corrosive liquid.',
  29: 'The electricity test: HCl solution lights the bulb; glucose and alcohol do not. Both contain hydrogen, but only the acid breaks into <b>ions</b> in water. Acidic behaviour = ion formation, not mere hydrogen presence.',
  30: 'The <b>universal indicator</b> is a rainbow of dyes giving a colour for each pH — much finer than litmus\u2019s two-colour verdict. It measures <b>strength</b>, not just type.',
  31: 'The pH scale: 7 neutral (pure water), below 7 acidic (strength grows towards 0), above 7 basic (strength grows towards 14). pH = hydrogen-ion concentration on a log scale — each step is a tenfold change.',
  33: 'Strong vs weak: equimolar HCl and CH\u2083COOH give <b>different</b> pH. Strong acids (HCl, H\u2082SO\u2084, HNO\u2083) ionise fully; weak acids (acetic, carbonic) ionise partly. Same logic splits strong/weak bases.',
  34: '<b>pH in everyday life, part 1</b>: our body runs in a narrow pH window; blood sits near 7.4. Plants and fish are equally sensitive — acid rain kills lakes, soil acidity spoils crops.',
  37: 'Indigestion = excess HCl in the stomach. <b>Antacids</b> (milk of magnesia, Mg(OH)\u2082) neutralise it. This is neutralisation inside your body — the chapter\u2019s most-used application.',
  38: 'Tooth chemistry: enamel (calcium phosphate) starts dissolving below <b>pH 5.5</b>. Bacteria act on sugar leftovers to make acid. Brushing removes the sugar; toothpaste is mildly basic.',
  39: 'Sting chemistry: bee/ant sting injects <b>methanoic acid</b> — relief comes from baking soda (mild base). Nettle sting works the other way — the dock leaf that grows beside it is the natural base. Chemical warfare, meet neutralisation.',
  42: 'Salts come in four temperaments: strong acid + strong base \u2192 neutral salt (NaCl); strong acid + weak base \u2192 acidic salt (NH\u2084Cl); weak acid + strong base \u2192 basic salt (Na\u2082CO\u2083, CH\u2083COONa); weak + weak \u2192 depends.',
  45: 'Common salt (NaCl) — the raw material of the chemical industry: from sea water by evaporation in shallow beds (salt pans) and from underground deposits by mining.',
  47: 'The <b>chlor-alkali process</b>: electrolysis of brine (NaCl solution) gives NaOH (in solution), Cl\u2082 (anode) and H\u2082 (cathode). The name says it: chlorine + alkali. Each product feeds a whole industry chain.',
  48: '<b>Bleaching powder</b>: Ca(OH)\u2082 + Cl\u2082 \u2192 CaOCl\u2082. Uses: bleaching cotton/linen and wood pulp, disinfecting drinking water, manufacturing chloroform.',
  50: '<b>Baking soda</b> NaHCO\u2083: on heating 2NaHCO\u2083 \u2192 Na\u2082CO\u2083 + H\u2082O + CO\u2082 — the CO\u2082 raises dough. Baking powder pairs it with tartaric acid so the gas releases only when heated.',
  51: 'More NaHCO\u2083: antacid (mild base — neutralises stomach acid) and soda-acid extinguisher (CO\u2082 from the acid reaction smothers fire).',
  52: '<b>Washing soda</b> Na\u2082CO\u2083\u00b710H\u2082O — from heating baking soda then recrystallising. Uses: removing permanent hardness of water, and in glass, soap and borax industries.',
  53: 'Blue CuSO\u2084\u00b75H\u2082O heated \u2192 white anhydrous CuSO\u2084 + water lost. Moisten the white powder and the blue flashes back. <b>Water of crystallisation</b> = the fixed water molecules baked into the crystal lattice.',
  55: 'Gypsum heated to 373 K gives <b>Plaster of Paris</b> CaSO\u2084\u00b7\u00bdH\u2082O — written with half a water per formula unit. Mix with water: it sets back into hard gypsum, expanding slightly to copy every detail — hence doctors\u2019 casts and moulds. Store it airtight, or humidity sets it in the packet.'
};

window.DECODE['che3'] = {
  1: 'The metals\u2019 identity card: <b>lustrous</b> (shine when fresh), <b>hard</b> (exceptions: Na, K cut with a knife), <b>malleable</b> (beaten into sheets), <b>ductile</b> (drawn into wires), <b>sonorous</b> (ring when struck), good conductors of heat and electricity.',
  2: 'Gold is the malleability champion — a 1-gram piece can stretch into a 2 km wire, or be beaten into sheets thousands of times thinner than paper. That is how gold leaf decoration works.',
  4: 'Metals conduct both heat and electricity — silver best, copper close behind. That\u2019s why wiring is copper and Why cooking pans are metal (heat flows) with wooden/bakelite handles (heat stops).',
  5: 'Non-metals are the mirror image: no lustre (except iodine), brittle in solid state, not malleable/ductile, poor conductors — <b>except graphite</b>, whose free electrons conduct electricity. Exceptions are the exam\u2019s favourite questions.',
  7: 'Melting points: most metals are high (iron ~1500\u00b0C) but gallium can melt in your palm; mercury is liquid at room temperature. Non-metals mostly sit low. Generalisations in chemistry always carry listed exceptions.',
  9: 'Non-metals burn into <b>acidic oxides</b>: S + O\u2082 \u2192 SO\u2082, and SO\u2082 + H\u2082O \u2192 H\u2082SO\u2083 (sulphurous acid — the acid-rain chemistry). CO\u2082 \u2192 carbonic acid. A few are neutral: CO, NO, H\u2082O.',
  11: 'Metal + oxygen \u2192 metal oxide, at very different speeds: Mg burns with a dazzling white flame even as a ribbon; Na/K catch fire in seconds (stored under kerosene); Cu darkens slowly on heating; Au and Ag never oxidise in flame.',
  13: 'Metal oxides are mostly basic — but <b>amphoteric</b> ones (Al\u2082O\u2083, ZnO) react with both acids and bases. They are the boundary cases — a classic MCQ.',
  14: 'Some oxides dissolve into alkalis: Na\u2082O + H\u2082O \u2192 2NaOH. This is why sodium must be kept from moisture — the metal itself reacts with water violently.',
  15: 'Reactivity towards oxygen falls down the series: Na > Mg > Al > Zn > Fe > Cu > Au. Same ladder, different race — this ordering previews the full <b>reactivity series</b>.',
  17: '<b>Anodising</b>: making aluminium the anode of an electrolyte bath thickens its natural oxide layer into armour — the matt silver finish of anodised cookware and window frames.',
  20: 'Water reactions ladder: K/Na explode in <b>cold water</b>; Ca floats on bubbles; Mg needs <b>hot water/steam</b>; Zn and Fe react only with <b>steam</b>; Pb, Cu, Ag never. Every step down, more energy is needed.',
  21: 'The pattern: metal + water \u2192 metal oxide + H\u2082, then oxide + water \u2192 hydroxide. Ca floats because H\u2082 bubbles stick to it — the exam\u2019s "why does calcium float?" answer.',
  23: 'Steam reactions: 2Al + 3H\u2082O \u2192 Al\u2082O\u2083 + 3H\u2082; 3Fe + 4H\u2082O \u2192 Fe\u2083O\u2084 + 4H\u2082. Lead, copper, silver refuse even steam.',
  26: 'With dilute HCl, bubbling speed ranks Na > Mg > Zn > Fe; Cu gives nothing. The thermometer also shows heat released — reactive metals make exothermic reactions.',
  27: '<b>Aqua regia</b> (royal water): 3 parts conc. HCl + 1 part conc. HNO\u2083 — one of the few liquids that dissolves gold and platinum. The Nobel medals hidden from Nazis by dissolving them in aqua regia are the story behind this name.',
  30: 'The <b>reactivity series</b>, the chapter\u2019s master key: K Na Ca Mg Al Zn Fe Pb [H] Cu Hg Ag Au. Position decides everything ahead: displacement, extraction method, corrosion.',
  31: 'The displacement table read as a rule: a metal displaces only metals <b>below</b> it from salt solutions. Iron pushes copper out of CuSO\u2084, but zinc\u2019s sulphate ignores iron — zinc sits above iron.',
  33: 'Why metals lose and non-metals gain: noble-gas stability. Metals have 1-3 outer electrons — easiest to donate; non-metals need electrons to complete the shell. Chemistry\u2019s whole logic in one sentence.',
  35: 'Sodium gives its electron to chlorine: Na\u207a + Cl\u207b held by pure electrostatic attraction = the <b>ionic bond</b>. The compound\u2019s formula is fixed by charge balance, not by sharing.',
  39: 'Ionic compounds melt and boil high because tearing apart the +/\u2013 lattice takes huge energy. They dissolve in water (polar molecules pull ions free) — and the solution conducts.',
  40: 'Solid ionic compounds do NOT conduct (ions locked); molten or dissolved, the ions drift free and carry current. This one contrast answers half the ionic-properties questions.',
  42: '<b>Minerals</b> = naturally occurring elements/compounds in the crust. <b>Ores</b> = minerals from which metal extraction is profitable. Every ore is a mineral; not every mineral is an ore.',
  44: 'Extraction method follows reactivity: <b>high</b> (K \u2192 Al) needs electrolysis; <b>middle</b> (Zn \u2192 Cu) is roasted/calcined then reduced with carbon; <b>low</b> (Hg, Ag, Au) is found native or obtained by heating alone.',
  45: 'Enrichment = separating the ore from <b>gangue</b> (the rocky waste). Hydraulic washing uses density difference; froth flotation catches sulphide ores on bubbles; magnetic separation pulls magnetic ores from sand.',
  47: 'Low-reactivity extraction by heat alone: cinnabar (HgS) roasted \u2192 Hg; and the beautiful self-reduction of copper: Cu\u2082S + O\u2082 \u2192 Cu\u2082O, then Cu\u2082O + Cu\u2082S \u2192 6Cu + SO\u2082.',
  48: '<b>Calcination</b> heats carbonate ores in limited air: ZnCO\u2083 \u2192 ZnO + CO\u2082. (Roasting, its sibling, heats <b>sulphide</b> ores in excess air.) Both convert ore to oxide for reduction.',
  49: 'Reduction with carbon: ZnO + C \u2192 Zn + CO. The oxide loses oxygen (reduced); carbon gains it (oxidised) — che1\u2019s redox logic applied to metallurgy.',
  50: 'The <b>thermite reaction</b>: 3MnO\u2082 + 4Al \u2192 3Mn + 2Al\u2082O\u2083 + huge heat. Aluminium\u2019s love for oxygen reduces harder metals — used to weld railway tracks in the field.',
  52: 'High-reactivity metals are never reduced by carbon — they bond oxygen too strongly. Only <b>electrolysis</b> of the molten compound splits them: the metal plates out at the cathode.',
  55: 'Electrolytic refining: impure metal = anode, thin pure sheet = cathode, metal-salt solution = electrolyte. Metal dissolves from anode and deposits pure on cathode; insoluble impurities drop as <b>anode mud</b>.',
  56: 'Corrosion in colour: copper\u2019s brown shine greens into basic copper carbonate; silver blackens as sulphide; iron rusts to hydrated oxide. Each metal reacts with its own atmospheric enemy.',
  58: 'The three-tube rust experiment: nail in (A) ordinary water rusts; in (B) boiled water sealed with oil — no rust (no oxygen); in (C) dry air with CaCl\u2082 — no rust (no moisture). Proof: rust needs <b>both</b> air and water.',
  59: 'Prevention: painting, greasing, galvanising (zinc coat — it corrodes sacrificially), electroplating, alloying (chrome/nickel into steel). Keep oxygen or moisture away and iron stays honest.',
  61: '<b>Alloy</b> = homogeneous metal-metal or metal-non-metal mixture. Steel = Fe + C; stainless adds Cr + Ni; brass = Cu + Zn; bronze = Cu + Sn. Alloying raises hardness and corrosion resistance.',
  62: 'With mercury, the alloy is an <b>amalgam</b>. Alloying usually <b>lowers</b> electrical conductivity (pure metals conduct best) and often lowers the melting point — solder (Pb + Sn) melts low to join wires.',
  63: 'The Delhi Iron Pillar (Gupta era, ~1600 years) hasn\u2019t rusted — a natural phosphate film formed on its surface. Ancient Indian metallurgy beat corrosion without knowing why — a beloved NCERT box.'
};

window.DECODE['che4'] = {
  0: 'Carbon is everywhere: food, clothes, medicines, books, fuels — all built on the carbon atom\u2019s chemistry. The chapter\u2019s mission: why does one element build millions of compounds?',
  2: 'The numbers tell the story: compounds of carbon known are in the millions, while all non-carbon compounds are only in the hundred-thousands. Carbon\u2019s bonding habits make it chemistry\u2019s great architect.',
  3: 'Carbon has <b>4 valence electrons</b> — losing 4 or gaining 4 is energetically impossible. So carbon never ions; it <b>shares</b>. The shared-pair bond is the <b>covalent bond</b>.',
  6: 'Why sharing suits carbon: donating 4 electrons would leave a tiny C\u2074\u207a holding 2 electrons (unstable); accepting 4 makes a huge C\u2074\u207b (unstable). Sharing achieves noble-gas stability at low energy cost.',
  8: 'The covalent gallery: H\u2082 (one shared pair, single bond), O\u2082 (two pairs, double), N\u2082 (three pairs, triple). Count each atom\u2019s shared electrons — each reaches a full outer shell.',
  14: '<b>Methane CH\u2084</b>: carbon shares one pair with each of four hydrogens — the tetravalent template every organic molecule grows from.',
  15: 'Covalent molecules have no ions — so they don\u2019t conduct, and their intermolecular forces are weak (low melting/boiling points) even though the bonds inside are strong. <b>Graphite</b> is the exception — free electrons conduct.',
  16: '<b>Allotropes</b> of carbon — same element, different geometry: diamond (each C bonded to 4, hardest natural substance) and graphite (layers of hexagons, slippery conductor). Structure decides property.',
  20: 'Why carbon is unique: <b>tetravalency</b> (4 hands to bond) + <b>catenation</b> (C bonds with itself in chains/rings with strong C\u2013C bonds). Silicon also has 4 electrons but its Si\u2013Si bonds are weaker — no long chains, no millions of compounds.',
  25: '<b>Saturated</b> = all single bonds, hydrogens maxed out (alkanes). <b>Unsaturated</b> = double/triple bonds remain (alkenes/alkynes) — reactive, hungry, decolourising bromine water.',
  27: 'Ethene C\u2082H\u2084: the double bond leaves each carbon only 2 hydrogens. Ethyne C\u2082H\u2082: the triple bond leaves just 1. Count the bonds — 4 per carbon always.',
  29: 'The alkane family ladder: methane CH\u2084, ethane C\u2082H\u2086, propane C\u2083H\u2088, butane C\u2084H\u2081\u2080, pentane C\u2085H\u2081\u2082… each rung adds <b>CH\u2082</b> — the <b>homologous series</b> in action.',
  30: 'Carbon also closes chains into <b>rings</b> — benzene\u2019s hexagon (aromatic) and cyclohexane. Rings plus branches give skeletons beyond count.',
  32: 'Carbon\u2019s friendships: H plus <b>heteroatoms</b> — halogens, oxygen, nitrogen, sulphur. A heteroatom (or its group) transforms hydrocarbon behaviour: this is the <b>functional group</b>.',
  35: 'The <b>homologous series</b> recipe: same functional group, same general formula, adjacent members differ by <b>CH\u2082 (14 u)</b>, gradual physical-property change, near-identical chemistry.',
  37: 'Within a series, bigger molecules \u2192 stronger intermolecular attraction \u2192 melting and boiling points <b>rise</b> down the list. Gradation is the homologous signature.',
  39: 'IUPAC nomenclature, four steps: longest chain \u2192 number from the end nearest a substituent/group \u2192 name the functional group\u2019s prefix/suffix \u2192 fix the "ane/ene/yne" ending to match saturation.',
  42: 'The suffix table: <b>-ol</b> alcohol, <b>-al</b> aldehyde, <b>-one</b> ketone, <b>-oic acid</b> carboxylic acid; haloalkanes take prefix <b>chloro/bromo</b>. Methanol, ethanol, propanone, butanoic acid — names now decode themselves.',
  43: '<b>Combustion</b>: carbon compounds burn to CO\u2082 + H\u2082O + heat/light. Coal, wood, LPG, candle wax — the same reaction at different speeds. Balanced oxygen supply = clean blue flame.',
  45: 'Flames as fuel-testers: <b>saturated</b> hydrocarbons burn clean and blue (enough oxygen reaches every carbon); <b>unsaturated</b> ones burn yellow and sooty (the double bond demands extra oxygen, and unburnt carbon blackens the vessel bottom).',
  50: 'Beyond combustion — controlled oxidation: alcohols become acids with <b>alkaline KMnO\u2084</b> or acidified K\u2082Cr\u2082O\u2087. The oxidant\u2019s colour change (purple\u2192green for dichromate) is the visible proof.',
  52: 'Vegetable oils: long <b>unsaturated</b> chains (liquid). Animal fats: <b>saturated</b> (solid). Hydrogenating the oil with a nickel catalyst saturates it — liquid oil becomes solid vanaspati.',
  53: '<b>Substitution</b>: a saturated compound swaps an atom (not adds): CH\u2084 + Cl\u2082 \u2192 CH\u2083Cl + HCl in sunlight. Saturated = substitute; unsaturated = add. The two reaction types mirror the bond structure.',
  55: '<b>Ethanol</b> C\u2082H\u2085OH: room-temperature liquid, good solvent, mixes with water. Its reactions: sodium \u2192 sodium ethoxide + H\u2082; hot conc. H\u2082SO\u2084 \u2192 ethene (dehydration).',
  60: 'Denatured spirit: industrial ethanol poisoned with methanol/denatonium so nobody drinks it — the state\u2019s answer to solvent misuse.',
  61: 'Alcohol as fuel: sugarcane \u2192 ethanol \u2192 gasohol (petrol blend). Brazil runs cars this way — the "renewable fuel" box.',
  62: '<b>Ethanoic acid</b> CH\u2083COOH: 5-8% solution = vinegar. Pure acid freezes at 290 K — "glacial" acetic acid literally looks like ice in winter.',
  64: '<b>Esterification</b>: ethanol + ethanoic acid, heated with conc. H\u2082SO\u2084 \u2192 ethyl ethanoate (sweet smell, ester) + water. The acid catalyst speeds the reaction and absorbs water.',
  65: 'Esters + NaOH \u2192 alcohol + sodium salt of the acid = <b>saponification</b> — the soap-making reaction, running in reverse of esterification.',
  66: 'Ethanoic acid behaves as a weak acid: with NaOH \u2192 sodium ethanoate + water; with carbonates/hydrogencarbonates \u2192 CO\u2082 briskly. The CO\u2082 test identifies an acid.',
  68: 'The soap activity: oil + water shake \u2192 separate layers; oil + soap-water \u2192 a milky emulsion that rinses away. That is the whole cleaning trick, made visible.',
  70: 'The <b>soap molecule\u2019s split personality</b>: a long hydrocarbon <b>tail</b> (oil-loving, water-hating) + a charged <b>head</b> (water-loving). One molecule, two worlds.',
  71: '<b>Micelles</b> form around a grease droplet: tails point inward into oil, heads outward to water — the droplet is fully enclosed and washes away with the rinse water.',
  72: 'Micelles are big enough to scatter light — that\u2019s why soap-water looks cloudy while salt-water stays clear.',
  74: 'In <b>hard water</b>, Ca\u00b2\u207a/Mg\u00b2\u207a grab the soap anions into insoluble <b>scum</b> — cleaning power wasted until all the hardness is used up. The familiar bathtub ring.',
  75: '<b>Detergents</b> — sulphonate/ammonium salts whose heads stay dissolved even with calcium around. They clean in hard water, but many survive in rivers (non-biodegradable) — the environmental trade-off.',
  79: 'Chapter summary in one breath: tetravalency + catenation \u2192 millions of compounds; homologous series organises them; functional groups define behaviour; ethanol and ethanoic acid anchor the chemistry; soap\u2019s two-faced molecule cleans by micelles.'
};

window.DECODE['che5'] = {
  0: 'FORMATIVE-ONLY for 2026-27: this chapter returns via the official CBSE <b>Reading Material</b> (the NCERT text re-issued for Portfolio study). It will NOT appear in the year-end exam — learn the story for your Portfolio write-up.',
  2: 'Why classify at all? Same reason a shop shelves soaps together and biscuits together: grouping by shared property makes a crowd manageable and reveals patterns — 118 elements needed exactly that.',
  4: '<b>D\u00f6bereiner\u2019s triads (1817)</b>: in a trio ordered by mass, the middle element\u2019s mass \u2248 average of the other two. It worked — but only for a few triads, so the idea couldn\u2019t generalise.',
  5: 'The classic example: Li (7) + K (39), average = 23 — exactly sodium\u2019s mass. Also Ca-Sr-Ba and Cl-Br-I. A neat pattern with too few members.',
  8: '<b>Newlands\u2019 octaves (1865)</b>: elements by rising mass, every 8th behaves like the 1st — Li and Na, Be and Mg, like a piano\u2019s octave. Fun idea; worked only up to calcium.',
  9: 'Octaves broke down: newly discovered heavier elements fit no octave, and the still-undiscovered noble gases left holes in the pattern. Newlands arranged by mass alone — the flaw that Mendel\u00e9ev would soften.',
  11: '<b>Mendel\u00e9ev\u2019s bold move (1869)</b>: he used atomic mass <b>and</b> chemical behaviour (oxide formulas, hydrides) — and when the two clashed, <b>properties won</b>. He even left gaps for unknown elements.',
  13: 'His Periodic Law: "properties of elements are a periodic function of their atomic masses." Sixty-three elements fell into periods and groups — with periodic recurrence of behaviour.',
  16: 'The gaps were predictions: <b>eka-boron \u2192 scandium, eka-aluminium \u2192 gallium, eka-silicon \u2192 germanium</b>. When gallium\u2019s properties matched his forecast, the world believed the table.',
  18: 'Noble gases, discovered decades later, slotted in as a whole new group without disturbing a single row — the table\u2019s flexibility was its second triumph.',
  20: '<b>Limitation 1 — hydrogen</b>: like alkali metals it loses one electron; like halogens it gains one. No single seat fits it — even today.',
  21: '<b>Limitation 2 — isotopes</b>: same element, different masses — a mass-based law cannot say where each isotope belongs.',
  23: 'The modern fix (Moseley): base the table on <b>atomic number</b> — the proton count. Isotopes share Z (one seat), and reversed pairs like Co-Ni settle by property.',
  25: 'The Modern Table\u2019s three wins over Mendel\u00e9ev: hydrogen\u2019s anomaly is acknowledged (kept in group 1), isotopes no longer matter, and the Co/Ni-Te/I inversions vanish.',
  27: '<b>Groups = same valence-electron count</b> \u2192 same chemistry. That\u2019s why group 1 metals all fizz in water and group 17 halogens all form salts.',
  30: '<b>Periods = same number of shells</b>; period number = shell count. First period 2 elements, second 8, third 8, fourth 18 — electron capacity fills the shells.',
  32: 'Why 2n\u00b2 per shell: K = 2, L = 8, M = 18 — the shell capacity formula writes the period lengths.',
  33: 'Valency across a period: rises 1\u21924 then falls back to 0 (noble gases) — first 7 elements of period 2-3 prove the wave.',
  34: '<b>Atomic size</b>: across a period it <b>shrinks</b> — more protons pull the same shell inward. Down a group it <b>grows</b> — a fresh shell is added.',
  35: 'Remember the direction: period \u2192 stronger nuclear pull \u2192 smaller atoms. The electron count rises but the shells don\u2019t — the tug-of-war is won by the nucleus.',
  37: 'The zig-zag line: metals on the left, non-metals on the right, and the borderline <b>metalloids</b> — B, Si, Ge, As, Sb — with a foot in each camp.',
  39: 'Electropositive metals (left) lose electrons; electronegative non-metals (right) gain them. Their oxides follow suit: metallic \u2192 basic, non-metallic \u2192 acidic.'
};
