/* NDATA — Biology quiz banks (bio1-5) */
window.NDATA = window.NDATA || {};

window.NDATA['bio1'] = {
  quiz: [
    { q: 'The processes that maintain life are collectively called:', o: ['Metabolism', 'Life processes', 'Homeostasis', 'Respiration'], a: 1, w: 'Nutrition, respiration, transportation and excretion.' },
    { q: 'Single-celled organisms exchange materials with the environment by:', o: ['Active transport', 'Diffusion', 'Osmosis only', 'Blood'], a: 1, w: 'The entire surface touches the environment — no organs needed.' },
    { q: 'Molecular movement in multicellular organisms is slow over long distances, so they developed:', o: ['Larger cells', 'Specialised tissue/organ systems', 'More diffusion', 'Thinner bodies'], a: 1, w: 'Division of labour — e.g. the gut, lungs, blood.' },
    { q: 'The source of energy for all living systems is:', o: ['Glucose', 'Sun', 'ATP', 'Oxygen'], a: 1, w: 'The Sun — trapped first by photosynthesis.' },
    { q: 'Photosynthesis takes place in the:', o: ['Mitochondria', 'Chloroplast', 'Ribosome', 'Nucleus'], a: 1, w: 'Chlorophyll in the chloroplasts of mesophyll cells.' },
    { q: 'The raw materials for photosynthesis are:', o: ['CO\u2082 and water', 'O\u2082 and glucose', 'Nitrogen and water', 'CO\u2082 and O\u2082'], a: 0, w: 'Plus sunlight and chlorophyll.' },
    { q: 'The first product of carbon fixation in the Calvin cycle experiments was identified using:', o: ['Radioactive carbon', 'Microscope', 'Chromatography', 'Centrifuge'], a: 0, w: 'Radioactive C traced the carbon path into sugars.' },
    { q: 'Stomata open and close due to:', o: ['Wind', 'Guard cells changing shape with water content', 'Light only', 'CO\u2082 pressure'], a: 1, w: 'Swollen guard cells bend and open the pore.' },
    { q: 'Which is a parasitic nutrition mode?', o: ['Cuscuta on host plants', 'Bread mould', 'Amoeba', 'Green algae'], a: 0, w: 'Cuscuta (amarbel) sucks ready-made food from its host.' },
    { q: 'Digestion outside the body (saprophytic) is seen in:', o: ['Mushrooms/fungi', 'Amoeba', 'Human beings', 'Hydra'], a: 0, w: 'Fungi secrete enzymes onto dead matter, then absorb the digested product.' },
    { q: 'In amoeba, food is digested inside:', o: ['Food vacuoles', 'The nucleus', 'The pseudopodia', 'Contractile vacuole'], a: 0, w: 'The food vacuole is the mobile "stomach".' },
    { q: 'The enzyme in saliva breaks down:', o: ['Proteins', 'Starch', 'Fats', 'Vitamins'], a: 1, w: 'Salivary amylase (ptyalin) converts starch to maltose.' },
    { q: 'Peristaltic movements occur in the:', o: ['Mouth', 'Stomach only', 'Oesophagus/intestine walls', 'Liver'], a: 2, w: 'Rhythmic wave-like muscle contractions push food along.' },
    { q: 'The acid in the stomach and its function:', o: ['HCl — activates pepsin, kills germs', 'H\u2082SO\u2084 — digests fat', 'CH\u2083COOH — stores food', 'HNO\u2083 — makes mucus'], a: 0, w: 'HCl gives the acidic medium pepsin needs and destroys microbes.' },
    { q: 'Pepsin digests:', o: ['Starch', 'Proteins', 'Fats', 'None'], a: 1, w: 'A protein-digesting enzyme of the stomach.' },
    { q: 'The function of mucus in the stomach:', o: ['Digests protein', 'Protects the stomach lining from acid', 'Absorbs food', 'Kills bacteria'], a: 1, w: 'It lubricates and shields the wall from HCl and pepsin.' },
    { q: 'Bile juice from the liver:', o: ['Digests proteins', 'Emulsifies fats and makes medium alkaline', 'Absorbs water', 'Digests starch'], a: 1, w: 'No enzyme — it breaks fat into droplets and neutralises stomach acid.' },
    { q: 'Trypsin comes from the:', o: ['Stomach', 'Liver', 'Pancreas', 'Small intestine wall'], a: 2, w: 'Pancreatic juice — digests proteins in the small intestine.' },
    { q: 'Villi in the small intestine increase:', o: ['Secretion', 'Absorption surface area', 'Peristalsis speed', 'Acidity'], a: 1, w: 'Millions of finger-like folds, richly supplied with blood.' },
    { q: 'Most water is reabsorbed in the:', o: ['Small intestine', 'Large intestine', 'Stomach', 'Rectum'], a: 1, w: 'The large intestine concentrates the waste.' },
    { q: 'Respiration releases energy stored in food as:', o: ['Heat only', 'ATP', 'Glucose', 'Light'], a: 1, w: 'ATP — the energy currency of the cell.' },
    { q: 'Aerobic respiration ends in the:', o: ['Cytoplasm', 'Mitochondria', 'Nucleus', 'Chloroplast'], a: 1, w: 'Pyruvate from the cytoplasm enters mitochondria for full oxidation.' },
    { q: 'Yeast fermentation gives:', o: ['Lactic acid', 'Ethanol and CO\u2082', 'Acetic acid', 'Methane'], a: 1, w: 'Anaerobic: glucose \u2192 ethanol + CO\u2082 + little energy.' },
    { q: 'Muscle cramps after running come from:', o: ['Ethanol build-up', 'Lactic acid build-up', 'CO\u2082 build-up', 'ATP excess'], a: 1, w: 'Anaerobic breakdown in muscles \u2192 lactic acid.' },
    { q: 'In humans, the respiratory pigment is:', o: ['Chlorophyll', 'Haemoglobin', 'Melanin', 'Myosin'], a: 1, w: 'It carries oxygen in red blood cells.' },
    { q: 'The air sacs where gas exchange happens in the lungs:', o: ['Bronchi', 'Alveoli', 'Trachea', 'Pleura'], a: 1, w: 'Balloon-like, one-cell-thick, wrapped in capillaries.' },
    { q: 'Rings of cartilage in the trachea:', o: ['Filter air', 'Keep the air passage open', 'Warm the air', 'Produce mucus'], a: 1, w: 'They prevent collapse.' },
    { q: 'During inhalation:', o: ['The diaphragm flattens and the chest cavity expands', 'The diaphragm domes upward', 'Ribs move inward', 'The chest shrinks'], a: 0, w: 'Larger chest volume \u2192 lower pressure \u2192 air rushes in.' },
    { q: 'The percentage of oxygen in inhaled vs exhaled air:', o: ['Same', 'Inhaled 21%, exhaled ~16%', 'Inhaled 16%, exhaled 21%', 'Exhaled has no oxygen'], a: 1, w: 'Exhaled air still has oxygen — but more CO\u2082 (~4% vs 0.04%).' },
    { q: 'Xylem transports:', o: ['Food', 'Water and minerals', 'Hormones only', 'Oxygen'], a: 1, w: 'Upward — from roots to leaves.' },
    { q: 'Transpiration helps by:', o: ['Cooling the plant and pulling water up', 'Making food', 'Storing starch', 'Absorbing minerals'], a: 0, w: 'Evaporation suction + evaporative cooling.' },
    { q: 'Translocation of food happens through the:', o: ['Xylem', 'Phloem', 'Stomata', 'Cambium'], a: 1, w: 'Sucrose moves both ways using ATP — from source to sink.' },
    { q: 'The left side of the human heart contains:', o: ['Deoxygenated blood', 'Oxygenated blood', 'Lymph', 'Mixed blood'], a: 1, w: 'The left atrium and ventricle handle oxygenated blood.' },
    { q: 'Valves in the heart prevent:', o: ['Fast beating', 'Backflow of blood', 'Clotting', 'Leakage of air'], a: 1, w: 'One-way doors between chambers and arteries.' },
    { q: 'Arteries have thick elastic walls because they carry blood:', o: ['Under low pressure', 'Under high pressure away from the heart', 'Back to the heart', 'With no pulse'], a: 1, w: 'They withstand and even out the pumping pressure.' },
    { q: 'Capillaries are ideal for exchange because they are:', o: ['Thick and elastic', 'One cell thick', 'Valved', 'Wide'], a: 1, w: 'Substances diffuse easily across a single cell layer.' },
    { q: 'Platelets help in:', o: ['Oxygen transport', 'Blood clotting', 'Immunity', 'Digestion'], a: 1, w: 'They plug leaks — deficiency means excessive bleeding.' },
    { q: 'Lymph differs from blood because it lacks:', o: ['Plasma', 'Red blood cells/haemoglobin', 'Water', 'Wastes'], a: 1, w: 'Colourless fluid from tissue spaces, drained back into veins.' },
    { q: 'The functional unit of the kidney is:', o: ['Neuron', 'Nephron', 'Alveolus', 'Villus'], a: 1, w: 'Each kidney has about a million nephrons.' },
    { q: 'Filtration of blood happens in the:', o: ['Glomerulus', 'Tubule', 'Ureter', 'Bladder'], a: 0, w: 'Blood pressure forces filtrate into the Bowman\u2019s capsule.' },
    { q: 'Selective reabsorption in the nephron reclaims:', o: ['Urea', 'Glucose, amino acids, water, salts', 'Only urea', 'Everything'], a: 1, w: 'The tubule returns useful substances to blood.' },
    { q: 'The volume of urine depends on:', o: ['Body size only', 'How much excess water is taken and how much is sweated out', 'Age only', 'Blood group'], a: 1, w: 'A balancing act — more water in/less sweat = more urine.' },
    { q: 'In dialysis, blood is cleaned:', o: ['Inside the body', 'Outside the body through a machine with a semi-permeable membrane', 'By surgery', 'By medicines'], a: 1, w: 'The artificial kidney filters waste while clean blood returns.' },
    { q: 'How do plants get rid of excess water?', o: ['Excretion', 'Transpiration', 'Respiration', 'Storage in roots'], a: 1, w: 'Evaporation through stomata.' },
    { q: 'Nitrogenous wastes in plants are:', o: ['Excreted through roots', 'Stored in leaves that fall off, bark and old xylem', 'Burned for energy', 'Never formed'], a: 1, w: 'Isolation rather than elimination — plus resins and gums.' },
    { q: 'Aquatic plants lose extra water through:', o: ['Stomata', 'Hydathodes (guttation drops)', 'Bark', 'Roots'], a: 1, w: 'Root pressure pushes water out at leaf edges.' }
  ]
};

window.NDATA['bio2'] = {
  quiz: [
    { q: 'Control and coordination in plants is achieved by:', o: ['Nervous system', 'Chemical (hormonal) means', 'Both nerves and hormones', 'Muscles'], a: 1, w: 'No nervous tissue — hormones alone do the signalling.' },
    { q: 'A plant bending towards light shows:', o: ['Phototropism', 'Geotropism', 'Hydrotropism', 'Chemotropism'], a: 0, w: 'Shoots are positively phototropic.' },
    { q: 'Roots growing downward show:', o: ['Positive phototropism', 'Positive geotropism', 'Negative hydrotropism', 'Chemotropism'], a: 1, w: 'Positive geotropism (gravity); shoots are negatively geotropic.' },
    { q: 'The pollen tube growing towards the ovule is:', o: ['Phototropism', 'Chemotropism', 'Hydrotropism', 'Thigmotropism'], a: 1, w: 'Directional growth in response to chemicals released by the ovule.' },
    { q: 'Auxin is produced at the:', o: ['Root tip', 'Shoot tip', 'Leaves', 'Flowers'], a: 1, w: 'It diffuses towards the shaded side and elongates cells there — hence the bend.' },
    { q: 'When a tendril touches a support, it coils because:', o: ['The touched side grows faster', 'The side away from contact grows faster', 'It shrinks', 'It photosynthesises more'], a: 1, w: 'Auxin moves to the far side \u2192 that side elongates \u2192 the tendril curls around the support.' },
    { q: 'Gibberellin mainly promotes:', o: ['Cell division', 'Stem elongation', 'Wilting', 'Stomatal closure'], a: 1, w: 'It also promotes seed germination and flowering.' },
    { q: 'The hormone that promotes cell division is:', o: ['Cytokinin', 'ABA', 'Ethylene', 'Auxin'], a: 0, w: 'Found in fruits and seeds; delays leaf ageing.' },
    { q: 'The growth-inhibitor plant hormone:', o: ['Gibberellin', 'Abscisic acid', 'Cytokinin', 'Auxin'], a: 1, w: 'ABA — closes stomata under stress, causes wilting/dormancy.' },
    { q: 'Which hormone ripens fruits?', o: ['Auxin', 'Ethylene', 'Cytokinin', 'ABA'], a: 1, w: 'Ethylene — the ripening hormone of stored fruit.' },
    { q: 'The structural and functional unit of the nervous system is the:', o: ['Nephron', 'Neuron', 'Alveolus', 'Glomerulus'], a: 1, w: 'Cell body + dendrites + axon.' },
    { q: 'Dendrites of a neuron:', o: ['Carry impulses away from the cell body', 'Receive impulses towards the cell body', 'Make myelin', 'Pump ions only'], a: 1, w: 'They collect signals; the axon transmits them onward.' },
    { q: 'At the synapse, the signal crosses as:', o: ['An electric spark', 'A neurotransmitter chemical', 'Plasma', 'A hormone in blood'], a: 1, w: 'This chemical step makes synaptic transmission slightly slower.' },
    { q: 'The fastest reflex example: touching something hot results in:', o: ['Thinking, then withdrawing the hand', 'Withdrawing the hand before the brain knows', 'Sweating only', 'Pain first, no movement'], a: 1, w: 'The spinal cord\u2019s reflex arc acts before pain is felt.' },
    { q: 'The correct order of a reflex arc:', o: ['Receptor \u2192 motor \u2192 spinal cord \u2192 sensory \u2192 muscle', 'Receptor \u2192 sensory \u2192 spinal cord \u2192 motor \u2192 muscle', 'Receptor \u2192 brain \u2192 muscle', 'Muscle \u2192 spinal cord \u2192 receptor'], a: 1, w: 'Sense \u2192 relay in the cord \u2192 act.' },
    { q: 'Reflex actions are controlled mainly by the:', o: ['Cerebrum', 'Spinal cord', 'Cerebellum', 'Medulla'], a: 1, w: 'The brain is informed later — speed saves tissue.' },
    { q: 'Thinking, memory and voluntary actions are handled by the:', o: ['Cerebrum', 'Cerebellum', 'Medulla', 'Spinal cord'], a: 0, w: 'The largest part — the "thinking brain".' },
    { q: 'Posture, balance and precision of movement are the job of the:', o: ['Cerebrum', 'Cerebellum', 'Medulla', 'Hypothalamus'], a: 1, w: 'Riding a bicycle, walking straight — cerebellum skills.' },
    { q: 'Heartbeat, breathing, blood pressure and vomiting are controlled by the:', o: ['Cerebrum', 'Cerebellum', 'Medulla (brain stem)', 'Spinal cord'], a: 2, w: 'Involuntary life-maintenance jobs.' },
    { q: 'The brain and spinal cord together form the:', o: ['Peripheral nervous system', 'Central nervous system', 'Autonomic system', 'Somatic system'], a: 1, w: 'Cranial + spinal nerves form the peripheral system.' },
    { q: 'Blood pressure is monitored and controlled by the:', o: ['Cerebrum', 'Medulla', 'Cerebellum', 'Pituitary'], a: 1, w: 'The brain stem\u2019s involuntary control centre.' },
    { q: 'Insulin controls:', o: ['Blood sugar', 'Blood pressure', 'Metabolism rate', 'Growth'], a: 0, w: 'From the pancreas; failure \u2192 diabetes.' },
    { q: 'The thyroid needs which mineral?', o: ['Iron', 'Iodine', 'Calcium', 'Zinc'], a: 1, w: 'Deficiency \u2192 goitre — swollen thyroid.' },
    { q: 'The emergency hormone is:', o: ['Thyroxin', 'Adrenaline', 'Insulin', 'Oestrogen'], a: 1, w: 'From the adrenal gland — faster heart and breathing, fight-or-flight.' },
    { q: 'Adrenaline is secreted by the:', o: ['Pituitary', 'Adrenal gland', 'Pancreas', 'Thyroid'], a: 1, w: 'Sits atop the kidney.' },
    { q: 'Growth hormone is released by the:', o: ['Pituitary', 'Thyroid', 'Adrenal', 'Gonads'], a: 0, w: 'Too little \u2192 dwarfism; excess in childhood \u2192 gigantism.' },
    { q: 'Puberty changes in boys are caused by:', o: ['Oestrogen', 'Testosterone', 'Insulin', 'Thyroxin'], a: 1, w: 'Girls: oestrogen from the ovaries.' },
    { q: 'Testosterone is produced in the:', o: ['Ovaries', 'Testes', 'Adrenal', 'Pituitary'], a: 1, w: 'It also makes sperm production possible.' },
    { q: 'Hormones from the pituitary control:', o: ['Only the heart', 'Other endocrine glands (thyroid, adrenal, gonads)', 'Digestion only', 'Blood sugar only'], a: 1, w: 'The "master gland" runs the orchestra.' },
    { q: 'Which is a secondary sexual characteristic in girls at puberty?', o: ['Voice cracking', 'Breast development and menstruation', 'Beard growth', 'Adam\u2019s apple'], a: 1, w: 'Oestrogen-driven changes.' }
  ]
};

window.NDATA['bio3'] = {
  quiz: [
    { q: 'Reproduction, unlike other life processes, is essential for:', o: ['Individual survival', 'Continuity of species', 'Growth', 'Excretion'], a: 1, w: 'An individual can live without reproducing — a species cannot.' },
    { q: 'The basic event in reproduction is the making of:', o: ['Proteins', 'DNA copies', 'New membranes', 'ATP'], a: 1, w: 'Copying the blueprint — with small errors called variations.' },
    { q: 'Variations are important because they:', o: ['Make clones identical', 'Give populations survival insurance against change', 'Slow down reproduction', 'Are always harmful'], a: 1, w: 'A varied population always has some survivors.' },
    { q: 'Binary fission along any plane occurs in:', o: ['Amoeba', 'Paramoecium', 'Plasmodium', 'Yeast'], a: 0, w: 'Paramoecium divides transversely; Plasmodium shows multiple fission.' },
    { q: 'Multiple fission (many daughter cells at once) is seen in:', o: ['Yeast', 'Plasmodium', 'Hydra', 'Planaria'], a: 1, w: 'The malaria parasite — one parasite splits into many simultaneously.' },
    { q: 'Fragmentation is seen in:', o: ['Spirogyra', 'Amoeba', 'Planaria', 'Rhizopus'], a: 0, w: 'The filament breaks into pieces, each growing into a new individual.' },
    { q: 'Planaria reproduces by:', o: ['Fragmentation', 'Regeneration', 'Budding', 'Spore formation'], a: 1, w: 'Specialised cells regrow a whole organism from a cut piece.' },
    { q: 'Budding occurs in:', o: ['Yeast and Hydra', 'Amoeba and Paramoecium', 'Spirogyra', 'Ferns'], a: 0, w: 'A bud grows on the parent, develops and detaches.' },
    { q: 'Potatoes reproduce vegetatively through:', o: ['Leaf margins', 'Eyes (buds on the tuber)', 'Seeds only', 'Roots'], a: 1, w: 'Each eye can sprout into a new potato plant.' },
    { q: 'Bryophyllum reproduces through:', o: ['Stem cuttings', 'Plantlets on leaf margins', 'Roots', 'Spores'], a: 1, w: 'Buds along the leaf margin drop off and grow.' },
    { q: 'Rhizopus (bread mould) spreads through:', o: ['Binary fission', 'Sporangia releasing spores', 'Budding', 'Seeds'], a: 1, w: 'Thick-walled spores survive unfavourable conditions.' },
    { q: 'Flowers are the:', o: ['Food factories', 'Reproductive structures of plants', 'Excretory organs', 'Storage organs'], a: 1, w: 'They produce gametes and seeds.' },
    { q: 'The male reproductive part of a flower:', o: ['Pistil', 'Stamen', 'Sepal', 'Petal'], a: 1, w: 'Anther + filament; the anther makes pollen.' },
    { q: 'Pollination is:', o: ['Fusion of gametes', 'Transfer of pollen from anther to stigma', 'Seed dispersal', 'Fruit formation'], a: 1, w: 'Self (same flower) or cross (another plant) — cross brings more variation.' },
    { q: 'Double fertilisation in flowering plants involves:', o: ['One male gamete', 'Fusion of male gamete with egg \u2014 embryo forms', 'Only the endosperm', 'Two eggs'], a: 1, w: 'In the syllabus: the male gamete fuses with the egg in the ovule forming the zygote.' },
    { q: 'After fertilisation the ovule becomes the:', o: ['Fruit', 'Seed', 'Flower', 'Stem'], a: 1, w: 'And the ovary becomes the fruit.' },
    { q: 'After fertilisation, petals and sepals generally:', o: ['Grow larger', 'Wither and fall', 'Turn green', 'Become seeds'], a: 1, w: 'Their job of attracting pollinators is over.' },
    { q: 'The testes lie outside the body in the scrotum because:', o: ['Space shortage', 'Sperm formation needs a lower temperature', 'They must be visible', 'For protection'], a: 1, w: 'About 3 K below body temperature.' },
    { q: 'Common duct that carries both urine and sperm in males:', o: ['Vas deferens', 'Urethra', 'Ureter', 'Seminal vesicle'], a: 1, w: 'The urethra — urine and semen never pass at the same time.' },
    { q: 'Seminal vesicles and prostate add:', o: ['Sperm', 'Nutritive fluid (semen) for sperm', 'Hormones', 'Urine'], a: 1, w: 'The medium that carries and nourishes sperm.' },
    { q: 'Fertilisation in humans normally occurs in the:', o: ['Uterus', 'Fallopian tube (oviduct)', 'Ovary', 'Vagina'], a: 1, w: 'The sperm meets the egg in the tube; the zygote then travels to implant.' },
    { q: 'Implantation of the embryo happens in the:', o: ['Ovary', 'Uterus', 'Fallopian tube', 'Cervix'], a: 1, w: 'It embeds in the thick uterine lining.' },
    { q: 'The placenta:', o: ['Protects the baby from all viruses', 'Supplies nutrition/oxygen and removes wastes via the mother\u2019s blood', 'Makes eggs', 'Produces urine for the foetus'], a: 1, w: 'Villi greatly increase the exchange surface — but harmful substances can also cross.' },
    { q: 'The average human gestation period:', o: ['6 months', '9 months', '12 months', '3 months'], a: 1, w: 'About 280 days from the last menstrual period.' },
    { q: 'Puberty in girls generally begins at:', o: ['8-9 years', '10-12 years', '15-16 years', '18 years'], a: 1, w: 'Boys: about 13-14 years.' },
    { q: 'Which contraceptive is a barrier method that also blocks STIs?', o: ['Oral pill', 'Condom', 'Copper-T', 'Tubectomy'], a: 1, w: 'The only one protecting against infection as well as pregnancy.' },
    { q: 'Oral contraceptive pills work by:', o: ['Killing sperm', 'Changing hormonal balance so no egg is released', 'Blocking the uterus', 'Preventing implantation chemically'], a: 1, w: 'Hormones trick the body into "thinking" it is already pregnant.' },
    { q: 'Copper-T is a(n):', o: ['Barrier', 'IUCD placed in the uterus', 'Hormone pill', 'Surgical method'], a: 1, w: 'The copper ion device prevents implantation.' },
    { q: 'Vasectomy involves:', o: ['Removing the testes', 'Cutting/tying the vas deferens', 'Blocking the fallopian tubes', 'Hormone injection'], a: 1, w: 'Sperm never reach the urethra — the tube is cut.' },
    { q: 'Tubectomy blocks the:', o: ['Ureter', 'Fallopian tubes', 'Vagina', 'Uterus'], a: 1, w: 'The egg cannot reach the uterus — the female surgical method.' },
    { q: 'HIV is NOT transmitted by:', o: ['Sexual contact', 'Sharing needles', 'Hugging/sharing food', 'Mother to child via placenta'], a: 2, w: 'HIV needs body fluids — casual contact is safe.' },
    { q: 'Which of these STIs is caused by a virus?', o: ['Gonorrhoea', 'Syphilis', 'HIV/AIDS', 'None'], a: 2, w: 'Gonorrhoea and syphilis are bacterial (curable); HIV and warts are viral.' },
    { q: 'Surgical methods of contraception are:', o: ['Reversible anytime', 'Generally permanent', 'Only for women', 'Only for men'], a: 1, w: 'Best for couples who want no more children.' },
    { q: 'The most important reason for spacing children:', o: ['Tradition', 'Protecting the mother\u2019s health and each child\u2019s care', 'Fashion', 'Saving money only'], a: 1, w: 'Repeated pregnancies harm health, education and family resources.' }
  ]
};

window.NDATA['bio4'] = {
  quiz: [
    { q: 'Mendel worked on:', o: ['Garden pea', 'Fruit fly', 'Maize', 'Sunflower'], a: 0, w: 'Pisum sativum — seven clear either/or traits.' },
    { q: 'A tall pea plant crossed with a pure dwarf gives F\u2081 offspring that are:', o: ['All dwarf', 'All tall', 'Half tall half dwarf', 'Medium height'], a: 1, w: 'Tall (T) is dominant — every F\u2081 plant is Tt.' },
    { q: 'The F\u2082 phenotypic ratio of a monohybrid cross is:', o: ['1:2:1', '3:1', '9:3:3:1', '1:1'], a: 1, w: '3 tall : 1 dwarf; the 1:2:1 is the genotypic ratio hidden beneath.' },
    { q: 'The F\u2082 genotypic ratio of a monohybrid cross is:', o: ['3:1', '1:2:1', '9:3:3:1', 'All TT'], a: 1, w: '1 TT : 2 Tt : 1 tt.' },
    { q: 'A cross between a pure tall (TT) and a pure dwarf (tt) plant gives offspring with genotype:', o: ['TT', 'Tt', 'tt', 'TT or tt'], a: 1, w: 'Every offspring gets T from one parent and t from the other.' },
    { q: 'The F\u2082 ratio of a dihybrid cross (round-yellow \u00d7 wrinkled-green) is:', o: ['3:1', '1:2:1', '9:3:3:1', '12:3:1'], a: 2, w: '9 round-yellow : 3 round-green : 3 wrinkled-yellow : 1 wrinkled-green.' },
    { q: 'New combinations in a dihybrid F\u2082 (e.g. round-green) prove:', o: ['Traits blend', 'Traits are inherited independently', 'Dominance fails', 'Lethal genes'], a: 1, w: 'Mendel\u2019s law of independent assortment.' },
    { q: 'Mendel\u2019s law of segregation states:', o: ['Alleles blend in offspring', 'Paired alleles separate during gamete formation', 'All traits are dominant', 'Traits always assort independently'], a: 1, w: 'Each gamete carries only one allele of a pair.' },
    { q: 'A trait that shows up even when only one copy is present is:', o: ['Recessive', 'Dominant', 'Sex-linked', 'Lethal'], a: 1, w: 'T masks t in Tt.' },
    { q: 'The visible expression of a trait (e.g. "tall") is the:', o: ['Genotype', 'Phenotype', 'Allele', 'Gene'], a: 1, w: 'Genotype is the underlying allele pair (Tt).' },
    { q: 'Humans have how many pairs of chromosomes?', o: ['22', '23', '44', '46'], a: 1, w: '23 pairs = 46 chromosomes; pairs 1-22 autosomes + 1 sex pair.' },
    { q: 'Gametes (sperm/egg) contain how many chromosomes in humans?', o: ['46', '23', '22', '44'], a: 1, w: 'Meiosis halves the set — fertilisation restores 46.' },
    { q: 'All human eggs carry which sex chromosome?', o: ['X', 'Y', 'X or Y', 'XY'], a: 0, w: 'Only sperm differ: half X, half Y.' },
    { q: 'The sex of a child is determined by:', o: ['The mother\u2019s egg', 'The father\u2019s sperm (X or Y)', 'The placenta', 'Nutrition'], a: 1, w: 'X-sperm \u2192 XX girl; Y-sperm \u2192 XY boy — blaming mothers is biologically wrong.' },
    { q: 'A human male\u2019s chromosome pattern is:', o: ['XX', 'XY', 'YY', 'XO'], a: 1, w: 'Females are XX.' },
    { q: 'In some reptiles, sex determination depends on:', o: ['Chromosomes', 'Incubation temperature', 'The father\u2019s gene', 'Diet'], a: 1, w: 'Some turtles\u2019 sex is set by nest temperature.' },
    { q: 'Which of these is an acquired trait?', o: ['Eye colour', 'Low weight of beetles due to poor nutrition', 'Blood group', 'Detached earlobes'], a: 1, w: 'Acquired in the lifetime — does not touch germ-cell DNA.' },
    { q: 'Cutting the tails of mice for generations produces tailless babies:', o: ['Always', 'Never — acquired traits are not inherited', 'Sometimes', 'Only in males'], a: 1, w: 'Body-cell changes never reach the germ cells.' },
    { q: 'For a trait to be inherited, the change must occur in the DNA of:', o: ['Any body cell', 'Germ cells (reproductive cells)', 'Skin cells', 'Muscle cells'], a: 1, w: 'Only germ-cell DNA passes to the next generation.' },
    { q: 'Mendel\u2019s experiments worked because he:', o: ['Used large sample sizes and statistics', 'Studied one trait at a time', 'Chose either/or traits', 'All of these'], a: 3, w: 'Plus the pea\u2019s self-pollinating habit and short generation time.' },
    { q: 'The probability that a heterozygous (Tt \u00d7 Tt) cross yields a dwarf offspring is:', o: ['0', '25%', '50%', '75%'], a: 1, w: '1 out of 4 (tt) = 25%.' },
    { q: 'A tall plant of unknown genotype is test-crossed with a dwarf. Half the offspring are dwarf. The parent\u2019s genotype is:', o: ['TT', 'Tt', 'tt', 'Impossible to say'], a: 1, w: 'Only Tt \u00d7 tt gives 1:1 tall:dwarf.' }
  ]
};

window.NDATA['bio5'] = {
  quiz: [
    { q: 'In NCERT\u2019s beetle story, green beetles survived because:', o: ['They were stronger', 'Crows could not spot them on green bushes', 'They bred faster', 'They were bigger'], a: 1, w: 'Natural selection acting on a colour variation.' },
    { q: 'The elephant-caused bush fire that randomly killed most red beetles illustrates:', o: ['Natural selection', 'Genetic drift', 'Speciation', 'Migration'], a: 1, w: 'Accidental survival — chance, not advantage.' },
    { q: 'Genetic drift changes gene frequencies most strongly in:', o: ['Huge populations', 'Small populations', 'Plants only', 'Asexual organisms'], a: 1, w: 'A few survivors carry a non-representative gene pool.' },
    { q: 'Mice tails cut for generations still produce tailed offspring — this shows:', o: ['Acquired traits are inherited', 'Acquired traits are NOT inherited', 'Tails are dominant', 'DNA changes with injury'], a: 1, w: 'Only germ-cell (inherited) variations reach the next generation.' },
    { q: 'Speciation occurs when two populations can no longer:', o: ['Live in the same country', 'Interbreed (reproductive isolation)', 'Eat the same food', 'Look alike'], a: 1, w: 'Geographical isolation + drift/selection \u2192 separate species.' },
    { q: 'Geographical isolation will NOT cause speciation in:', o: ['Cattle', 'Self-pollinating plants', 'Birds', 'Fish'], a: 1, w: 'No cross-pollination partner is needed — no gene flow to stop.' },
    { q: 'Homologous organs have:', o: ['Same structure, different functions', 'Different structures, same function', 'No relation', 'Identical functions only'], a: 0, w: 'Forelimbs of humans, bats, whales — common ancestry.' },
    { q: 'The wing of a bird and the wing of an insect are:', o: ['Homologous', 'Analogous', 'Vestigial', 'Identical in origin'], a: 1, w: 'Different design, same job — convergent evolution.' },
    { q: 'Which is a vestigial organ in humans?', o: ['Appendix (vermiform)', 'Heart', 'Liver', 'Lungs'], a: 0, w: 'A remnant of a larger, functional organ in our ancestors.' },
    { q: 'Deeper fossils in the earth are:', o: ['Younger', 'Older', 'The same age', 'Always human'], a: 1, w: 'Sediments stack — depth orders time.' },
    { q: 'Absolute dating of fossils uses:', o: ['Carbon dating (radioactive decay)', 'Depth only', 'Colour', 'Size'], a: 0, w: 'Depth gives relative age; isotope decay gives absolute age.' },
    { q: 'Archaeopteryx is a missing link between:', o: ['Fish and amphibians', 'Reptiles and birds', 'Apes and humans', 'Amphibians and reptiles'], a: 1, w: 'Feathers + teeth, claws and a bony tail.' },
    { q: 'Feathers are believed to have evolved initially for:', o: ['Flight', 'Warmth (insulation)', 'Display only', 'Swimming'], a: 1, w: 'Dinosaurs used them as insulation; flight came later — evolution by stages.' },
    { q: 'Even a rudimentary eye (a light-sensitive spot) has survival value — this supports:', o: ['Sudden appearance of complex organs', 'Evolution by stages', 'Vitalism', 'Lamarckism'], a: 1, w: 'Each small improvement aids survival — flatworm eye \u2192 human eye.' },
    { q: 'Molecular phylogeny compares:', o: ['Fossil shapes', 'DNA and protein sequences', 'Behaviour only', 'Geography'], a: 1, w: 'More sequence differences = more distant common ancestor.' },
    { q: 'Charles Darwin\u2019s classic work is:', o: ['Origin of Species', 'Principles of Geology', 'Micrographia', 'Historia Plantarum'], a: 0, w: '1859 — evolution by natural selection.' },
    { q: 'Darwin\u2019s natural selection says:', o: ['All individuals survive equally', 'The best-adapted variants survive and reproduce more', 'Organisms choose their traits', 'Species never change'], a: 1, w: 'Variation + limited resources + selection.' },
    { q: 'All modern humans belong to:', o: ['Several species', 'One species — Homo sapiens', 'Two species', 'Different genera'], a: 1, w: 'One African-origin species that migrated worldwide.' },
    { q: 'Human "races" are:', o: ['Biologically distinct species', 'Superficial variations within one species', 'Different genera', 'Unrelated lineages'], a: 1, w: 'Skin/face differences are minor adaptations — no biological race divide.' },
    { q: 'NOTE for 2026-27: Evolution is:', o: ['In the year-end exam', 'Formative-only (Portfolio/Periodic Assessment)', 'Deleted', 'Practical-only'], a: 1, w: 'Re-added by CBSE but assessed formatively.' }
  ]
};
