/* NDATA — Chemistry quiz banks (che1-5) */
window.NDATA = window.NDATA || {};

window.NDATA['che1'] = {
  quiz: [
    { q: 'Which of these is NOT a sign that a chemical reaction has occurred?', o: ['Change in state', 'Change in colour', 'Change in temperature', 'Melting of ice'], a: 3, w: 'Melting is a physical change — no new substance forms.' },
    { q: 'Magnesium ribbon burns in air to form:', o: ['MgCO\u2083', 'MgO', 'Mg(NO\u2083)\u2082', 'MgCl\u2082'], a: 1, w: '2Mg + O\u2082 \u2192 2MgO — a dazzling white flame leaves white magnesium oxide.' },
    { q: 'Why is magnesium ribbon cleaned before burning?', o: ['To remove water', 'To remove the protective layer of basic magnesium carbonate', 'To make it thin', 'To remove magnesium oxide only'], a: 1, w: 'The layer of basic carbonate would otherwise interfere with burning.' },
    { q: 'A balanced chemical equation obeys:', o: ['Law of constant proportion', 'Law of conservation of mass', 'Law of multiple proportion', 'Boyle\u2019s law'], a: 1, w: 'Atoms are neither created nor destroyed — equal on both sides.' },
    { q: 'The correct balanced form of Fe + H\u2082O \u2192 Fe\u2083O\u2084 + H\u2082 is:', o: ['Fe + 2H\u2082O \u2192 Fe\u2083O\u2084 + H\u2082', '3Fe + 4H\u2082O \u2192 Fe\u2083O\u2084 + 4H\u2082', 'Fe + H\u2082O \u2192 Fe\u2083O\u2084 + H\u2082', '2Fe + 3H\u2082O \u2192 Fe\u2083O\u2084 + 3H\u2082'], a: 1, w: 'Count: 3 Fe, 4 H\u2082O giving 4 H\u2082 — all atoms balance.' },
    { q: 'In the symbol (aq) written after a substance in an equation, the substance is:', o: ['A gas', 'A liquid', 'Dissolved in water', 'A solid'], a: 2, w: '(aq) = aqueous — the substance is dissolved in water.' },
    { q: 'CaO + H\u2082O \u2192 Ca(OH)\u2082 is an example of:', o: ['Decomposition', 'Combination', 'Displacement', 'Double displacement'], a: 1, w: 'Two reactants combine to give a single product — a combination reaction.' },
    { q: 'Quicklime is used for whitewashing because:', o: ['It is white', 'Ca(OH)\u2082 reacts with CO\u2082 to form a shiny CaCO\u2083 layer', 'It is cheap', 'It dissolves in water'], a: 1, w: 'Ca(OH)\u2082 + CO\u2082 \u2192 CaCO\u2083 + H\u2082O — the shiny finish appears in 2-3 days.' },
    { q: 'On heating, ferrous sulphate crystals first lose water and then decompose to give:', o: ['FeO and SO\u2082', 'Fe\u2082O\u2083, SO\u2082 and SO\u2083', 'Fe and S', 'FeS and O\u2082'], a: 1, w: '2FeSO\u2084 \u2192 Fe\u2082O\u2083 + SO\u2082 + SO\u2083 — the green crystals turn brown.' },
    { q: 'Decomposition of AgBr in sunlight is used in:', o: ['Cooking', 'Black-and-white photography', 'Fireworks', 'Batteries'], a: 1, w: '2AgBr \u2192 2Ag + Br\u2082 — photolytic decomposition.' },
    { q: 'In the electrolysis of water, the volume of gas collected at the cathode versus the anode is:', o: ['1:1', '1:2', '2:1', '1:8'], a: 2, w: 'H\u2082 (cathode) is double O\u2082 (anode) — water is H\u2082O.' },
    { q: 'In electrolysis of water, the gas at the anode is:', o: ['Hydrogen', 'Oxygen', 'Chlorine', 'Nitrogen'], a: 1, w: 'Oxygen is liberated at the anode; it relights a glowing splinter.' },
    { q: 'Iron nails dipped in copper sulphate solution:', o: ['Turn the solution green and get a brown coating', 'Turn the solution blue and shine', 'Dissolve completely', 'Show no change'], a: 0, w: 'Fe + CuSO\u2084 \u2192 FeSO\u2084 (green) + Cu (brown deposit) — displacement.' },
    { q: 'A displacement reaction is possible when:', o: ['A less reactive metal meets a salt of a more reactive metal', 'A more reactive metal meets a salt of a less reactive metal', 'Two salts react', 'A non-metal reacts with a metal'], a: 1, w: 'Only a more reactive element can push out a less reactive one.' },
    { q: 'Na\u2082SO\u2084 + BaCl\u2082 \u2192 BaSO\u2084 + 2NaCl is:', o: ['Displacement', 'Combination', 'Double displacement with precipitation', 'Decomposition'], a: 2, w: 'Ions exchange partners and insoluble white BaSO\u2084 precipitates.' },
    { q: 'In CuO + H\u2082 \u2192 Cu + H\u2082O:', o: ['CuO is oxidised, H\u2082 reduced', 'CuO is reduced, H\u2082 oxidised', 'Both are reduced', 'Both are oxidised'], a: 1, w: 'CuO loses oxygen (reduced); H\u2082 gains oxygen (oxidised) — a redox pair.' },
    { q: 'Oxidation is:', o: ['Gain of hydrogen', 'Loss of oxygen', 'Gain of oxygen or loss of hydrogen', 'Loss of electrons by an atom only'], a: 2, w: 'In this chapter\u2019s terms: gain of O or loss of H.' },
    { q: 'When fats and oils are oxidised, their smell and taste change. This is called:', o: ['Corrosion', 'Rancidity', 'Tarnishing', 'Galvanisation'], a: 1, w: 'Rancidity — prevented by antioxidants, nitrogen flushing, refrigeration.' },
    { q: 'Rusting of iron requires:', o: ['Only air', 'Only water', 'Both air and moisture', 'Only carbon dioxide'], a: 2, w: 'The nail in boiled water + oil, or with anhydrous CaCl\u2082, does not rust.' },
    { q: 'Which is an exothermic process?', o: ['Decomposition of CaCO\u2083', 'Electrolysis of water', 'Respiration', 'Photosynthesis'], a: 2, w: 'Respiration releases energy — decomposition and photosynthesis absorb it.' },
    { q: 'Decomposition of vegetable matter into compost is:', o: ['Endothermic', 'Exothermic', 'Neither', 'Photochemical'], a: 1, w: 'A common trap — composting releases heat, so it is exothermic.' },
    { q: 'In the reaction ZnO + C \u2192 Zn + CO:', o: ['ZnO is reduced and C is oxidised', 'ZnO is oxidised and C is reduced', 'Both are reduced', 'No redox occurs'], a: 0, w: 'ZnO loses oxygen; carbon gains it.' },
    { q: 'The reaction 2H\u2082 + O\u2082 \u2192 2H\u2082O is best classified as:', o: ['Decomposition', 'Combination', 'Displacement', 'Double displacement'], a: 1, w: 'Two elements combine into one compound.' },
    { q: 'A reaction in which heat is absorbed from the surroundings is:', o: ['Exothermic', 'Endothermic', 'Neutralisation', 'Combination'], a: 1, w: 'Endothermic — e.g. decomposition of limestone on heating.' },
    { q: 'Silver chloride turns grey in sunlight because:', o: ['It melts', 'It decomposes to silver and chlorine', 'It combines with sunlight', 'It sublimes'], a: 1, w: '2AgCl \u2192 2Ag + Cl\u2082 — photolytic decomposition; used in photography too.' },
    { q: 'Which information is NOT conveyed by a balanced chemical equation?', o: ['Physical states of reactants and products', 'Conditions like temperature and catalyst', 'The speed of the reaction', 'The number of molecules taking part'], a: 2, w: 'A balanced equation says nothing about reaction rate.' },
    { q: 'Lead nitrate on heating gives brown fumes of:', o: ['NO\u2082', 'SO\u2082', 'CO\u2082', 'O\u2082'], a: 0, w: '2Pb(NO\u2083)\u2082 \u2192 2PbO + 4NO\u2082 (brown) + O\u2082.' },
    { q: 'Before burning in air, magnesium ribbon is rubbed with:', o: ['Water', 'Sandpaper', 'Oil', 'Dilute acid'], a: 1, w: 'Cleaning removes the basic magnesium carbonate layer.' },
    { q: 'The white precipitate formed when sodium sulphate solution is mixed with barium chloride is:', o: ['NaCl', 'BaSO\u2084', 'BaCl\u2082', 'Na\u2082SO\u2084'], a: 1, w: 'Barium sulphate — insoluble in water.' },
    { q: 'Which of the following is a redox reaction?', o: ['NaOH + HCl \u2192 NaCl + H\u2082O', 'Zn + CuSO\u2084 \u2192 ZnSO\u2084 + Cu', 'CaCO\u2083 \u2192 CaO + CO\u2082', 'AgNO\u2083 + NaCl \u2192 AgCl + NaNO\u2083'], a: 1, w: 'Zn is oxidised (loses electrons), Cu\u00b2\u207a is reduced.' },
    { q: 'The correct coefficients to balance Fe\u2082O\u2083 + Al \u2192 Fe + Al\u2082O\u2083 are:', o: ['2, 2, 2, 3', '1, 2, 2, 1', '1, 3, 2, 1\u00bd', '2, 1, 1, 2'], a: 1, w: 'Fe\u2082O\u2083 + 2Al \u2192 2Fe + Al\u2082O\u2083 — the thermite reaction.' },
    { q: 'Colour change when dilute sulphuric acid is added to zinc granules and the gas is tested with a burning match:', o: ['The gas burns with a pop sound', 'The gas turns limewater milky', 'The flame turns green', 'No gas forms'], a: 0, w: 'Zn + H\u2082SO\u2084 \u2192 ZnSO\u2084 + H\u2082 — hydrogen\u2019s classic pop test.' },
    { q: 'Which reaction type absorbs energy overall?', o: ['Burning of natural gas', 'Respiration', 'Decomposition of calcium carbonate', 'Slaking of lime'], a: 2, w: 'Thermal decomposition — CaCO\u2083 must be heated continuously.' },
    { q: 'Chemical reactions in which heat is released are called:', o: ['Endothermic', 'Exothermic', 'Photochemical', 'Electrochemical'], a: 1, w: 'Exothermic — heat exits the system.' }
  ]
};

window.NDATA['che2'] = {
  quiz: [
    { q: 'The acid present in curd is:', o: ['Citric acid', 'Lactic acid', 'Acetic acid', 'Oxalic acid'], a: 1, w: 'Lactic acid gives curd its sour taste.' },
    { q: 'Acids furnish which ion in aqueous solution?', o: ['OH\u207b', 'H\u207a (aq)', 'Na\u207a', 'Cl\u207b'], a: 1, w: 'All acid properties come from H\u207a ions in water.' },
    { q: 'A base in water furnishes:', o: ['H\u207a ions', 'OH\u207b ions', 'O\u00b2\u207b', 'Both H\u207a and OH\u207b'], a: 1, w: 'Bases give hydroxide ions in solution.' },
    { q: 'Which is an olfactory indicator?', o: ['Litmus', 'Phenolphthalein', 'Onion', 'Methyl orange'], a: 2, w: 'Onion loses its smell in a basic solution — an indicator for visually impaired students.' },
    { q: 'Litmus solution is obtained from:', o: ['Lichens', 'Turmeric', 'Red cabbage', 'Petals'], a: 0, w: 'Lichens — the purple dye that turns red in acid and blue in base.' },
    { q: 'Metal + dilute acid \u2192 :', o: ['Salt + H\u2082', 'Salt + H\u2082O', 'Salt + CO\u2082', 'Oxide + H\u2082'], a: 0, w: 'Zn + 2HCl \u2192 ZnCl\u2082 + H\u2082 — verified by the pop test.' },
    { q: 'Sodium hydroxide reacts with zinc to give:', o: ['No reaction', 'Sodium zincate and hydrogen gas', 'Zinc oxide and water', 'Zinc hydroxide'], a: 1, w: '2NaOH + Zn \u2192 Na\u2082ZnO\u2082 + H\u2082 — some metals react with strong bases.' },
    { q: 'Na\u2082CO\u2083 + 2HCl \u2192 2NaCl + H\u2082O + X. X is:', o: ['H\u2082', 'O\u2082', 'CO\u2082', 'SO\u2082'], a: 2, w: 'Acid + carbonate \u2192 salt + water + carbon dioxide.' },
    { q: 'CO\u2082 passed through lime water first makes it:', o: ['Red', 'Milky', 'Blue', 'Colourless instantly'], a: 1, w: 'Ca(OH)\u2082 + CO\u2082 \u2192 CaCO\u2083 (milky); excess CO\u2082 clears it.' },
    { q: 'Which gas is released when dilute acid is poured on baking soda?', o: ['Hydrogen', 'Oxygen', 'Carbon dioxide', 'Nitrogen'], a: 2, w: 'NaHCO\u2083 + acid \u2192 CO\u2082 — the extinguisher/antacid gas.' },
    { q: 'Acid + base \u2192 :', o: ['Salt + water', 'Salt + CO\u2082', 'Base + acid', 'Hydrogen'], a: 0, w: 'Neutralisation: HCl + NaOH \u2192 NaCl + H\u2082O.' },
    { q: 'A strong acid is one that:', o: ['Ionises completely in water', 'Ionises partially', 'Does not ionise', 'Turns blue litmus red only'], a: 0, w: 'HCl, H\u2082SO\u2084, HNO\u2083 ionise completely; CH\u2083COOH is weak.' },
    { q: 'Which of these is a weak acid?', o: ['HCl', 'H\u2082SO\u2084', 'CH\u2083COOH', 'HNO\u2083'], a: 2, w: 'Acetic acid ionises only partially in water.' },
    { q: 'Tooth decay starts when the mouth pH falls below:', o: ['7.0', '6.5', '5.5', '4.0'], a: 2, w: 'Below 5.5, tooth enamel (calcium phosphate) starts dissolving — bacteria make acid from sugar.' },
    { q: 'The remedy for indigestion (excess HCl in the stomach):', o: ['Milk of magnesia', 'Vinegar', 'Lemon juice', 'Baking soda in excess'], a: 0, w: 'Mg(OH)\u2082 — a mild base that neutralises excess acid.' },
    { q: 'Formic acid is injected by:', o: ['Bees', 'Ant stings', 'Mosquitoes', 'Wasps only'], a: 1, w: 'Ant/nettle sting is methanoic (formic) acid — relieved by baking soda.' },
    { q: 'When soil is too acidic, farmers add:', o: ['Quicklime/slaked lime', 'More fertiliser', 'Vinegar', 'Common salt'], a: 0, w: 'CaO/Ca(OH)\u2082 neutralises soil acidity.' },
    { q: 'In the chlor-alkali process, the gas at the anode is:', o: ['Hydrogen', 'Chlorine', 'Oxygen', 'Ammonia'], a: 1, w: 'Cl\u2082 at the anode, H\u2082 at the cathode, NaOH remains in solution.' },
    { q: 'Products of electrolysis of brine are:', o: ['NaOH, Cl\u2082, H\u2082', 'NaCl, H\u2082O, O\u2082', 'Na, Cl\u2082, H\u2082O', 'NaOH, HCl, O\u2082'], a: 0, w: 'Chlor-alkali: chlor = chlorine, alkali = NaOH.' },
    { q: 'Bleaching powder is chemically:', o: ['CaOCl\u2082', 'CaCl\u2082', 'Ca(OCl)\u2082 only', 'CaCO\u2083'], a: 0, w: 'Ca(OH)\u2082 + Cl\u2082 \u2192 CaOCl\u2082 + H\u2082O.' },
    { q: 'Bleaching powder is used for all EXCEPT:', o: ['Bleaching cotton', 'Disinfecting drinking water', 'Making chloroform', 'Baking bread'], a: 3, w: 'Baking uses sodium hydrogencarbonate, not bleaching powder.' },
    { q: 'Baking soda is:', o: ['Na\u2082CO\u2083', 'NaHCO\u2083', 'CaSO\u2084\u00bdH\u2082O', 'NaOH'], a: 1, w: 'Sodium hydrogencarbonate.' },
    { q: 'On heating, baking soda gives:', o: ['Na\u2082CO\u2083 + H\u2082O + CO\u2082', 'NaOH + CO\u2082', 'NaCl + H\u2082O', 'Na\u2082O + CO\u2082'], a: 0, w: '2NaHCO\u2083 \u2192 Na\u2082CO\u2083 + H\u2082O + CO\u2082 — the gas raises the cake.' },
    { q: 'Baking powder contains baking soda and:', o: ['CaCl\u2082', 'Tartaric acid', 'NaOH', 'NaCl'], a: 1, w: 'The mild edible acid releases CO\u2082 on heating.' },
    { q: 'Washing soda is:', o: ['Na\u2082CO\u2083\u00b710H\u2082O', 'NaHCO\u2083', 'CaOCl\u2082', 'CaSO\u2084\u00b72H\u2082O'], a: 0, w: 'Sodium carbonate decahydrate.' },
    { q: 'Plaster of Paris is obtained by heating gypsum to:', o: ['273 K', '373 K', '473 K', '573 K'], a: 1, w: 'Heating gypsum (CaSO\u2084\u00b72H\u2082O) to 373 K gives CaSO\u2084\u00b7\u00bdH\u2082O.' },
    { q: 'Plaster of Paris sets to a hard mass because it:', o: ['Loses water', 'Gains water and re-forms gypsum', 'Is oxidised', 'Sublimes'], a: 1, w: 'CaSO\u2084\u00b7\u00bdH\u2082O + 1\u00bdH\u2082O \u2192 CaSO\u2084\u00b72H\u2082O.' },
    { q: 'Blue copper sulphate crystals on heating turn:', o: ['Green', 'White', 'Black', 'Red'], a: 1, w: 'CuSO\u2084\u00b75H\u2082O loses water of crystallisation \u2192 white anhydrous CuSO\u2084.' },
    { q: 'Adding water to anhydrous copper sulphate:', o: ['Turns it blue again', 'Keeps it white', 'Turns it green', 'Dissolves with no colour'], a: 0, w: 'Hydrated CuSO\u2084 is blue — the classic reversible demo.' },
    { q: 'The universal indicator colour at pH 2 is:', o: ['Green', 'Blue', 'Red', 'Purple'], a: 2, w: 'Strongly acidic — red on the universal indicator scale.' },
    { q: 'A solution turns red litmus blue. Its pH is likely:', o: ['2', '4', '7', '10'], a: 3, w: 'Basic solutions turn red litmus blue; pH above 7.' },
    { q: 'Which salt is used in soda-acid fire extinguishers?', o: ['Washing soda', 'Baking soda', 'Common salt', 'Bleaching powder'], a: 1, w: 'NaHCO\u2083 + acid \u2192 CO\u2082 smothers the fire.' },
    { q: 'Sodium hydroxide is manufactured by:', o: ['Solvay process', 'Chlor-alkali electrolysis', 'Haber process', 'Ostwald process'], a: 1, w: 'Electrolysis of aqueous NaCl (brine).' },
    { q: 'An aqueous solution of which salt is basic in nature?', o: ['NH\u2084Cl', 'CH\u2083COONa', 'NaCl', 'KNO\u2083'], a: 1, w: 'Sodium acetate (weak acid + strong base salt) hydrolyses to give a basic solution.' },
    { q: 'The pH range of the human blood stays near:', o: ['7.0', '7.4', '5.5', '8.5'], a: 1, w: 'Blood is slightly basic, pH \u2248 7.4 — a favourite 1-marker.' }
  ]
};

window.NDATA['che3'] = {
  quiz: [
    { q: 'Which metal is liquid at room temperature?', o: ['Sodium', 'Mercury', 'Bromine', 'Gallium'], a: 1, w: 'Mercury — the only liquid metal.' },
    { q: 'Which non-metal is a good conductor of electricity?', o: ['Sulphur', 'Graphite', 'Phosphorus', 'Iodine'], a: 1, w: 'Graphite\u2019s free delocalised electrons conduct.' },
    { q: 'The metal stored in kerosene is:', o: ['Magnesium', 'Sodium', 'Zinc', 'Aluminium'], a: 1, w: 'Sodium reacts violently with air and water, so it is kept under kerosene.' },
    { q: 'Metals are malleable, meaning they can be:', o: ['Drawn into wires', 'Beaten into sheets', 'Cut easily', 'Pulverised'], a: 1, w: 'Malleable = hammered into thin sheets; ductile = drawn into wires.' },
    { q: 'Which is the most malleable metal?', o: ['Iron', 'Gold', 'Aluminium', 'Copper'], a: 1, w: 'Gold — a foil 1000 times thinner than paper can be beaten.' },
    { q: 'Sodium reacts with cold water to give:', o: ['NaOH and H\u2082', 'Na\u2082O and H\u2082', 'NaH and O\u2082', 'No reaction'], a: 0, w: '2Na + 2H\u2082O \u2192 2NaOH + H\u2082 — a violent, exothermic reaction.' },
    { q: 'Which metal reacts with steam but not cold water?', o: ['Sodium', 'Calcium', 'Magnesium', 'Gold'], a: 2, w: 'Mg reacts slowly with hot water and vigorously with steam.' },
    { q: 'The metal that does NOT react with dilute HCl is:', o: ['Zn', 'Fe', 'Cu', 'Mg'], a: 2, w: 'Copper is below hydrogen in the reactivity series.' },
    { q: 'Aqua regia is a mixture of:', o: ['HCl + HNO\u2083 (3:1)', 'H\u2082SO\u2084 + HCl', 'HNO\u2083 + H\u2082O', 'HCl + H\u2082O'], a: 0, w: '3 parts conc. HCl + 1 part conc. HNO\u2083 — dissolves gold and platinum.' },
    { q: 'The correct reactivity order is:', o: ['Na > Mg > Zn > Cu', 'Cu > Zn > Mg > Na', 'Mg > Na > Cu > Zn', 'Zn > Na > Mg > Cu'], a: 0, w: 'K > Na > Ca > Mg > Al > Zn > Fe > Pb > (H) > Cu > Hg > Ag > Au.' },
    { q: 'The salt solution that will show no reaction with an iron nail is:', o: ['CuSO\u2084', 'ZnSO\u2084', 'AgNO\u2083', 'Pb(NO\u2083)\u2082'], a: 1, w: 'Zinc is above iron in the series — iron cannot displace it.' },
    { q: 'In an ionic bond:', o: ['Electrons are shared', 'Electrons are transferred from metal to non-metal', 'Protons are transferred', 'Neutrons are shared'], a: 1, w: 'Metal donates electrons \u2192 cation; non-metal accepts \u2192 anion.' },
    { q: 'Ionic compounds have high melting points because:', o: ['They are made of molecules', 'Strong electrostatic forces between ions', 'They contain hydrogen bonds', 'They are gases'], a: 1, w: 'Considerable energy is needed to break the ionic lattice.' },
    { q: 'Ionic compounds conduct electricity:', o: ['As solids', 'In solution or molten state', 'Never', 'Only at 0 K'], a: 1, w: 'Free-moving ions carry the current; solids have locked ions.' },
    { q: 'The most abundant metal in the earth\u2019s crust is:', o: ['Iron', 'Aluminium', 'Calcium', 'Sodium'], a: 1, w: 'Aluminium — the most abundant metal; oxygen is the most abundant element.' },
    { q: 'Metals high in the reactivity series are extracted by:', o: ['Reduction with carbon', 'Electrolysis of molten compounds', 'Heating in air', 'Roasting only'], a: 1, w: 'Na, K, Ca, Mg, Al are too reactive — electrolysis is needed.' },
    { q: 'Calcination is heating of:', o: ['Sulphide ore in excess air', 'Carbonate ore in limited air', 'Metal in oxygen', 'Oxide with coke'], a: 1, w: 'Carbonate \u2192 oxide + CO\u2082; roasting is for sulphides.' },
    { q: 'Roasting converts:', o: ['Sulphide ore to oxide', 'Carbonate to sulphide', 'Oxide to metal', 'Metal to ore'], a: 0, w: 'Sulphide + O\u2082 \u2192 oxide + SO\u2082.' },
    { q: 'In electrolytic refining, pure metal deposits at the:', o: ['Anode', 'Cathode', 'Both electrodes', 'Neither'], a: 1, w: 'Cations move to the cathode and deposit as pure metal; impurities collect as anode mud.' },
    { q: 'The thermite reaction is used for:', o: ['Joining railway tracks', 'Galvanising iron', 'Making steel', 'Purifying copper'], a: 0, w: 'Fe\u2082O\u2083 + Al \u2192 Fe (molten) + Al\u2082O\u2083 — the heat welds cracked machine parts too.' },
    { q: 'Galvanisation is coating iron with:', o: ['Tin', 'Zinc', 'Chromium', 'Nickel'], a: 1, w: 'Zinc corrodes before iron does (sacrificial protection).' },
    { q: 'Stainless steel contains:', o: ['Fe, C', 'Fe, Cr, Ni', 'Cu, Zn', 'Cu, Sn'], a: 1, w: 'Chromium and nickel make it rust-proof.' },
    { q: 'Brass is an alloy of:', o: ['Cu and Zn', 'Cu and Sn', 'Pb and Sn', 'Fe and C'], a: 0, w: 'Brass = copper + zinc; bronze = copper + tin.' },
    { q: 'Solder is an alloy of:', o: ['Cu and Zn', 'Pb and Sn', 'Fe and Cr', 'Al and Cu'], a: 1, w: 'Low melting point — used to join electrical wires.' },
    { q: 'The green coating on copper is:', o: ['CuO', 'Basic copper carbonate', 'CuSO\u2084', 'CuS'], a: 1, w: 'Copper reacts with moist CO\u2082 to form basic carbonate.' },
    { q: 'Which non-metal is the hardest natural substance?', o: ['Graphite', 'Diamond', 'Silicon', 'Iodine'], a: 1, w: 'Diamond — an allotrope of carbon.' },
    { q: 'Amphoteric oxides react with:', o: ['Only acids', 'Only bases', 'Both acids and bases', 'Neither'], a: 2, w: 'Al\u2082O\u2083 and ZnO are amphoteric.' },
    { q: 'Anodising is:', o: ['Coating iron with zinc', 'Thickening the oxide layer on aluminium', 'Electroplating silver', 'Heating aluminium'], a: 1, w: 'Al is made the anode; the oxide layer resists corrosion further.' },
    { q: 'Which gas is released when a metal reacts with a dilute acid?', o: ['CO\u2082', 'H\u2082', 'O\u2082', 'SO\u2082'], a: 1, w: 'Metal + acid \u2192 salt + hydrogen.' },
    { q: 'Froth flotation is used to concentrate:', o: ['Oxide ores', 'Sulphide ores', 'Carbonate ores', 'Native metals'], a: 1, w: 'Sulphide particles attach to froth bubbles and float.' },
    { q: 'Which metal does not corrode easily?', o: ['Iron', 'Gold', 'Copper', 'Zinc'], a: 1, w: 'Gold is least reactive — it stays shiny for centuries.' },
    { q: 'Sodium, potassium and calcium are stored how, respectively?', o: ['Open air, water, oil', 'Kerosene, kerosene, open', 'Kerosene, kerosene, kerosene', 'Water, water, water'], a: 2, w: 'All three react with air/moisture — stored under kerosene.' },
    { q: 'The gangue in an ore is:', o: ['The metal', 'The rocky impurity', 'The flux', 'The slag'], a: 1, w: 'Gangue = impurities; it is removed during enrichment.' },
    { q: 'Why is aluminium used for making cooking vessels?', o: ['It is heavy', 'It is a good conductor of heat and has an oxide coating', 'It reacts with food', 'It is cheap only'], a: 1, w: 'Good conduction + protective oxide layer + light weight.' }
  ]
};

window.NDATA['che4'] = {
  quiz: [
    { q: 'Carbon shows covalency because it:', o: ['Gains 4 electrons', 'Loses 4 electrons', 'Shares its 4 valence electrons', 'Loses 2 electrons'], a: 2, w: 'Gaining/losing 4 electrons is energetically impossible — so it shares.' },
    { q: 'The bond in an N\u2082 molecule is:', o: ['Single', 'Double', 'Triple', 'Ionic'], a: 2, w: 'N\u2261N — three shared electron pairs.' },
    { q: 'Covalent compounds generally have:', o: ['High melting points', 'Low melting and boiling points', 'High electrical conductivity', 'Ionic lattices'], a: 1, w: 'Weak intermolecular forces between molecules (though the bonds inside are strong).' },
    { q: 'Covalent compounds do not conduct electricity because they:', o: ['Are gases', 'Produce no ions in solution (generally)', 'Are too hard', 'Have free electrons'], a: 1, w: 'No charged particles — except graphite with its free electrons.' },
    { q: 'Catenation is:', o: ['Bonding with oxygen', 'Self-linking of carbon atoms into chains and rings', 'Gaining electrons', 'Conducting electricity'], a: 1, w: 'The strong C\u2013C bond lets carbon link with itself — unique among elements.' },
    { q: 'The general formula of alkanes is:', o: ['C\u2099H\u2082\u2099', 'C\u2099H\u2082\u2099\u208a\u2082', 'C\u2099H\u2082\u2099\u208b\u2082', 'C\u2099H\u2099'], a: 1, w: 'Saturated, single bonds: C\u2099H\u2082\u2099\u208a\u2082.' },
    { q: 'The general formula of alkynes is:', o: ['C\u2099H\u2082\u2099\u208a\u2082', 'C\u2099H\u2082\u2099', 'C\u2099H\u2082\u2099\u208b\u2082', 'C\u2099H\u2082\u2099\u208a\u2081OH'], a: 2, w: 'One triple bond: C\u2099H\u2082\u2099\u208b\u2082 (e.g. ethyne C\u2082H\u2082).' },
    { q: 'Which hydrocarbon decolourises bromine water?', o: ['Methane', 'Ethane', 'Ethene', 'Propane'], a: 2, w: 'Unsaturated hydrocarbons undergo addition with Br\u2082 — saturated ones do not.' },
    { q: 'Two consecutive members of a homologous series differ by:', o: ['12 u', '14 u', '16 u', '18 u'], a: 1, w: 'A \u2013CH\u2082\u2013 unit: carbon (12) + 2 hydrogens (2) = 14 u.' },
    { q: 'Which pair represents a homologous series?', o: ['CH\u2084 and C\u2082H\u2086', 'C\u2082H\u2086 and C\u2082H\u2084', 'CH\u2084 and CH\u2083OH', 'C\u2082H\u2082 and C\u2082H\u2086'], a: 0, w: 'Same family (alkanes), differ by CH\u2082.' },
    { q: 'The IUPAC name of CH\u2083CH\u2082CH\u2082OH is:', o: ['Propanal', 'Propanol', 'Propanone', 'Propanoic acid'], a: 1, w: 'Three carbons + OH group \u2192 propan-1-ol (propanol).' },
    { q: 'The functional group \u2013COOH is called:', o: ['Aldehyde', 'Ketone', 'Carboxylic acid', 'Alcohol'], a: 2, w: 'Carboxylic acid — e.g. ethanoic acid CH\u2083COOH.' },
    { q: 'The functional group of propanone is:', o: ['\u2013OH', '\u2013CHO', '\u2013CO\u2013', '\u2013COOH'], a: 2, w: 'A ketone — the C=O sits between two carbons.' },
    { q: 'Bromine attached to a carbon chain makes it a:', o: ['Halogen derivative', 'Alcohol', 'Acid', 'Ester'], a: 0, w: 'Haloalkane — e.g. bromoethane C\u2082H\u2085Br.' },
    { q: 'Hydrogenation of vegetable oil uses which catalyst?', o: ['Iron', 'Nickel', 'Platinum wire', 'Copper'], a: 1, w: 'Unsaturated oil + H\u2082 + Ni \u2192 saturated fat (vanaspati).' },
    { q: 'Hydrogenation of oils converts:', o: ['Saturated to unsaturated', 'Unsaturated to saturated', 'Acid to ester', 'Alcohol to acid'], a: 1, w: 'Double bonds are broken by adding hydrogen.' },
    { q: 'Saturated hydrocarbons on combustion give:', o: ['Sooty flame', 'Clean blue flame', 'Yellow flame', 'No flame'], a: 1, w: 'Complete combustion of saturated fuels is clean; unsaturated fuels burn sooty in limited air.' },
    { q: 'Oxidation of ethanol with acidified K\u2082Cr\u2082O\u2087 gives:', o: ['Ethene', 'Ethanoic acid', 'Ethane', 'Ester'], a: 1, w: 'Primary alcohol \u2192 aldehyde \u2192 acid.' },
    { q: 'Ethanol on heating with conc. H\u2082SO\u2084 at 443 K gives:', o: ['Ethane', 'Ethene', 'Ethyne', 'Ethanoic acid'], a: 1, w: 'Dehydration — H\u2082SO\u2084 removes the OH and an H, forming a double bond.' },
    { q: 'Ethanol reacts with sodium to give:', o: ['Sodium ethoxide + H\u2082', 'Sodium ethanoate', 'No reaction', 'Ethene'], a: 0, w: '2C\u2082H\u2085OH + 2Na \u2192 2C\u2082H\u2085ONa + H\u2082.' },
    { q: 'Ethanoic acid reacts with sodium hydrogencarbonate to release:', o: ['H\u2082', 'CO\u2082', 'O\u2082', 'SO\u2082'], a: 1, w: 'Brisk effervescence of CO\u2082 — the test for acids.' },
    { q: 'Esterification is the reaction between:', o: ['Acid and base', 'Alcohol and acid (with catalyst)', 'Alkene and hydrogen', 'Alcohol and sodium'], a: 1, w: 'Ester + water, heated with an acid catalyst — sweet-smelling esters.' },
    { q: 'Esters are used in:', o: ['Fuels', 'Perfumes and flavourings', 'Fertilisers', 'Bleaching'], a: 1, w: 'Sweet fruity smells — perfume and food-flavour industry.' },
    { q: 'Saponification is the hydrolysis of an ester with:', o: ['An acid', 'A base (NaOH)', 'Water only', 'Alcohol'], a: 1, w: 'Ester + NaOH \u2192 soap (sodium salt of the acid) + alcohol.' },
    { q: 'The soap molecule has:', o: ['A ionic head that likes oil', 'A hydrocarbon tail that likes oil and an ionic head that likes water', 'Two ionic ends', 'Two hydrocarbon ends'], a: 1, w: 'Hydrophobic tail, hydrophilic head — the micelle story.' },
    { q: 'In a soap micelle, the hydrocarbon tails:', o: ['Face the water', 'Point inward, trapping oil', 'Dissolve', 'React with water'], a: 1, w: 'Tails (oil-loving) point inside towards the grease; heads face outward to the water.' },
    { q: 'Soap is not effective in hard water because:', o: ['It evaporates', 'Ca\u00b2\u207a/Mg\u00b2\u207a form insoluble scum with soap', 'Hard water is hot', 'It reacts with oxygen'], a: 1, w: 'The scum wastes soap; detergents avoid this.' },
    { q: 'Detergents work in hard water because their ammonium/sulphonate heads:', o: ['Do not form scum with calcium/magnesium', 'React with the salts', 'Are insoluble', 'Evaporate'], a: 0, w: 'That is their advantage over soap — though many are non-biodegradable.' },
    { q: 'The number of covalent bonds in ethane (C\u2082H\u2086) is:', o: ['5', '6', '7', '4'], a: 2, w: 'One C\u2013C bond + six C\u2013H bonds = 7.' },
    { q: 'Combustion of methane gives:', o: ['CO\u2082 + H\u2082O + heat', 'CO + H\u2082', 'C + H\u2082O', 'CO\u2082 + H\u2082'], a: 0, w: 'CH\u2084 + 2O\u2082 \u2192 CO\u2082 + 2H\u2082O + heat/light.' },
    { q: 'Substitution reaction is shown by:', o: ['Alkanes', 'Alkenes', 'Alkynes', 'Alcohols'], a: 0, w: 'Saturated compounds substitute (e.g. CH\u2084 + Cl\u2082 in sunlight); unsaturated ones add.' },
    { q: 'Vinegar contains about:', o: ['5-8% ethanoic acid', '5-8% ethanol', '95% acetic acid', '5% HCl'], a: 0, w: 'A dilute solution of acetic acid in water.' },
    { q: 'Glacial acetic acid is so named because it freezes at:', o: ['0\u00b0C', '17\u00b0C (290 K)', '\u201340\u00b0C', '50\u00b0C'], a: 1, w: 'Pure ethanoic acid freezes like ice at 290 K.' },
    { q: 'The suffix \u2013al in a name indicates a(n):', o: ['Alcohol', 'Aldehyde', 'Ketone', 'Acid'], a: 1, w: 'Ethanal CH\u2083CHO — aldehyde group \u2013CHO.' }
  ]
};

window.NDATA['che5'] = {
  quiz: [
    { q: 'D\u00f6bereiner grouped elements in:', o: ['Triads', 'Octaves', 'Periods', 'Blocks'], a: 0, w: 'Groups of three — the middle element\u2019s mass \u2248 average of the other two.' },
    { q: 'Which is a D\u00f6bereiner triad?', o: ['Li, Na, K', 'C, N, O', 'Fe, Co, Ni', 'Na, Mg, Al'], a: 0, w: '(7+39)/2 = 23 — sodium\u2019s mass. Also Ca-Sr-Ba and Cl-Br-I.' },
    { q: 'Newlands\u2019 Law of Octaves stated:', o: ['Every 8th element resembles the 1st', 'Every element pairs', 'Mass doubles each row', 'Noble gases end periods'], a: 0, w: 'Like musical octaves — worked only up to calcium.' },
    { q: 'Mendel\u00e9ev\u2019s periodic table was based on:', o: ['Atomic number', 'Atomic mass', 'Number of neutrons', 'Valence electrons'], a: 1, w: 'He arranged the 63 known elements by increasing atomic mass.' },
    { q: 'Mendel\u00e9ev left gaps in his table to:', o: ['Balance the mass', 'Predict undiscovered elements', 'Fit hydrogen', 'Place isotopes'], a: 1, w: 'Eka-boron (Sc), eka-aluminium (Ga), eka-silicon (Ge) — all found later.' },
    { q: 'Mendel\u00e9ev\u2019s periodic law says properties are a periodic function of:', o: ['Atomic number', 'Atomic mass', 'Electron shells', 'Density'], a: 1, w: 'The modern law replaced mass with atomic number.' },
    { q: 'The Modern Periodic Table arranges elements by:', o: ['Atomic mass', 'Atomic number', 'Isotopic abundance', 'Chemical reactivity'], a: 1, w: 'Moseley\u2019s atomic number — number of protons.' },
    { q: 'In the Modern Table, a group contains elements with the same:', o: ['Number of shells', 'Number of valence electrons', 'Atomic mass', 'Density'], a: 1, w: 'Same valence-electron count \u2192 similar chemical properties.' },
    { q: 'The number of elements in the 2nd period is:', o: ['2', '8', '18', '32'], a: 1, w: 'Li to Ne — 8 elements; the period number equals the number of shells.' },
    { q: 'Across a period, atomic radius:', o: ['Increases', 'Decreases', 'Stays constant', 'Doubles'], a: 1, w: 'Rising nuclear charge pulls the same-shell electrons closer.' },
    { q: 'Down a group, metallic character:', o: ['Increases', 'Decreases', 'Is unchanged', 'Vanishes'], a: 0, w: 'New shells make electron loss easier.' },
    { q: 'Which pair could not be accommodated in Mendel\u00e9ev\u2019s table properly?', o: ['Isotopes', 'Halogens', 'Alkali metals', 'Noble gases discovered later'], a: 0, w: 'Isotopes have different masses but identical properties — mass-based order broke.' },
    { q: 'Hydrogen\u2019s position is anomalous because it resembles:', o: ['Only alkali metals', 'Only halogens', 'Both alkali metals and halogens', 'Noble gases'], a: 2, w: 'It can lose one electron (like Na) or gain one to complete its shell (like Cl).' },
    { q: 'Metalloids like silicon lie along the:', o: ['Left edge', 'Zig-zag boundary between metals and non-metals', 'Right edge', 'Bottom rows'], a: 1, w: 'B, Si, Ge, As, Sb, Te — properties of both sides.' },
    { q: 'Which element\u2019s oxide is most acidic?', o: ['Na', 'Mg', 'Al', 'S'], a: 3, w: 'Non-metallic character rises across a period \u2192 acidic oxides (SO\u2082).' },
    { q: 'In Newlands\u2019 table, the element after lithium (in octaves) was:', o: ['Beryllium', 'Sodium', 'Boron', 'Carbon'], a: 1, w: 'Li(1) \u2192 Na(8th) — sodium repeated lithium\u2019s properties.' },
    { q: 'The Modern Periodic Table has how many groups?', o: ['7', '8', '18', '32'], a: 2, w: '18 groups and 7 periods.' },
    { q: 'Elements of Group 1 are called:', o: ['Alkali metals', 'Alkaline earth metals', 'Halogens', 'Noble gases'], a: 0, w: 'Group 2 = alkaline earth; 17 = halogens; 18 = noble gases.' },
    { q: 'Noble gases were discovered after Mendel\u00e9ev\u2019s table and were:', o: ['Given new groups', 'Accommodated without disturbing the table', 'Ignored', 'Placed with halogens'], a: 1, w: 'A whole new group fitted cleanly — a triumph of the periodic idea.' },
    { q: 'Electronegativity across a period:', o: ['Decreases', 'Increases', 'Constant', 'Zero'], a: 1, w: 'More nuclear charge + same shell = stronger pull on bonding electrons.' },
    { q: 'NOTE for 2026-27: Periodic Classification is:', o: ['In the year-end exam', 'Formative-only (Portfolio/Periodic Assessment)', 'Deleted entirely', 'Only for practicals'], a: 1, w: 'Re-added by CBSE but assessed formatively, not in the board exam.' }
  ]
};
