/* 200-question bank — part 2 (Q101-200: secularism, census data, caste, exercises) */
window.QUIZ_BANK.push(
{q:"The Constitution provides all individuals and communities freedom to:",o:["Profess, practise and propagate any religion — or not follow any","Follow only the majority religion","Change religion only with state approval","Practise religion only at home"],a:0},
{q:"The Constitution prohibits discrimination on grounds of:",o:["Wealth","Religion","Age","Education"],a:1},
{q:"The Constitution allows the state to intervene in matters of religion in order to:",o:["Promote one religion","Ensure equality within religious communities","Collect temple taxes","Appoint priests"],a:1},
{q:"An example of the state intervening in religion to ensure equality is:",o:["The ban on untouchability","Funding places of worship","State-run schools","Religious taxation"],a:0},
{q:"In India, secularism is:",o:["Just an ideology of some parties or persons","One of the foundations of our country","A recent amendment","A foreign concept never adopted"],a:1},
{q:"Communalism should not be seen as a threat to some people — it threatens:",o:["The very idea of India","Only politicians","Only the majority","Only the army"],a:0},
{q:"A secular Constitution like ours is ___ to combat communalism:",o:["Sufficient","Necessary but not sufficient","Unnecessary","Harmful"],a:1},
{q:"Communal prejudices and propaganda need to be countered:",o:["In everyday life","Only in courts","Only in Parliament","Never"],a:0},
{q:"Religion-based mobilisation needs to be countered:",o:["In the arena of politics","By banning elections","By silence","Only abroad"],a:0},
{q:"The Census of India records the religion of each Indian:",o:["Every year","After every ten years","Every five years","Only once"],a:1},
{q:"If a person tells the Census she has 'no religion', the form records:",o:["Hinduism by default","Exactly that — 'no religion' or 'atheist'","A blank","The head of family's religion"],a:1},
{q:"Since Independence, the total population of each religious community has:",o:["Declined","Stayed constant","Increased substantially","Disappeared"],a:2},
{q:"Since Independence, the proportion of religious communities in India's population has:",o:["Changed dramatically","Not changed much","Completely reversed","Doubled"],a:1},
{q:"In percentage terms, which communities have declined marginally since 1961?",o:["Hindus, Jains and Christians","Muslims, Sikhs and Buddhists","Buddhists only","Christians and Muslims"],a:0},
{q:"The proportion of which communities has increased slightly since 1961?",o:["Hindus and Jains","Muslims, Sikhs and Buddhists","Christians and Jains","None"],a:1},
{q:"The common but mistaken impression about India's religious future is that:",o:["Christians will become a majority","The proportion of Muslims is going to overtake other religious communities","Jains will disappear","All religions will vanish"],a:1},
{q:"The Prime Minister's High Level Committee is popularly known as:",o:["The Mandal Commission","The Sachar Committee","The Kelkar Committee","The Kaka Kalelkar Commission"],a:1},
{q:"Sachar Committee expert estimates show the Muslim proportion may rise by about ___ in the next 50 years:",o:["3 to 4 per cent","20 per cent","50 per cent","0.1 per cent"],a:0},
{q:"Overall, the population balance of different religious communities in India is:",o:["Likely to change drastically","Not likely to change in a big way","Certain to reverse","Impossible to measure"],a:1},
{q:"Hindus formed what share of India's population in 2011?",o:["79.8 per cent","64 per cent","50 per cent","92 per cent"],a:0},
{q:"Muslims formed what share of India's population in 2011?",o:["14.2 per cent","2.3 per cent","9 per cent","25 per cent"],a:0},
{q:"Christians formed what share of India's population in 2011?",o:["2.3 per cent","1.7 per cent","0.7 per cent","5 per cent"],a:0},
{q:"Sikhs formed what share of India's population in 2011?",o:["1.7 per cent","2.3 per cent","0.4 per cent","4 per cent"],a:0},
{q:"Buddhists formed what share of India's population in 2011?",o:["0.7 per cent","2 per cent","1.7 per cent","5 per cent"],a:0},
{q:"Jains formed what share of India's population in 2011?",o:["0.4 per cent","1.7 per cent","0.7 per cent","2 per cent"],a:0},
{q:"India's second largest religious community is:",o:["Christians","Muslims","Sikhs","Buddhists"],a:1},
{q:"(NCERT exercise) Communal politics is based on the belief that — which statements are correct? A: one religion is superior; C: followers of a religion constitute one community:",o:["A, B, C and D","A, B and D","A and C","B and D"],a:2,w:"B and D describe equal coexistence — the opposite of communalism."},
{q:"(NCERT exercise) Which statement about India's Constitution is WRONG?",o:["It prohibits discrimination on grounds of religion","It gives official status to one religion","It provides freedom to profess any religion","It ensures equality within religious communities"],a:1,w:"India gives no religion official status."},
{q:"Unlike gender and religion, caste division is:",o:["Universal","Special to India","Found only in Europe","Purely economic"],a:1},
{q:"All societies have:",o:["No inequality","Some kind of social inequality and some form of division of labour","Caste systems","The same occupations"],a:1},
{q:"The caste system is an extreme form of:",o:["Democracy","Hereditary occupational division","Urbanisation","Secularism"],a:1},
{q:"What made the caste system different from occupational inheritance in other societies?",o:["Its hereditary division was sanctioned by rituals","It had no occupations","It was created by an 1857 law","It applied only to kings"],a:0},
{q:"Members of the same caste group were supposed to:",o:["Practise the same occupation, marry within the group and not eat with other castes","Marry outside the caste","Change jobs every year","Live only in cities"],a:0},
{q:"The caste system was based on exclusion of and discrimination against:",o:["'Outcaste' groups","Kings","Traders","Priests"],a:0},
{q:"The 'outcaste' groups were subjected to the inhuman practice of:",o:["Untouchability","Heavy taxation","Exile","Forced labour abroad"],a:0},
{q:"Which leaders advocated and worked for a society without caste inequalities?",o:["Jotiba Phule, Gandhiji, B.R. Ambedkar and Periyar Ramaswami Naicker","Only viceroys","Only judges","Only merchants"],a:0},
{q:"Jyotirao (Jotiba) Phule was a 19th-century social reformer from:",o:["Bengal","Maharashtra","Punjab","Kerala"],a:1},
{q:"Gandhiji referred to 'untouchables' as:",o:["Dalits","Harijans — children of God","Adivasis","Twice-born"],a:1},
{q:"Dr B.R. Ambedkar is best known in this chapter as:",o:["A nationalist poet","The Constitution's chief architect who fought untouchability","A British official","A merchant leader"],a:1},
{q:"Periyar Ramaswami Naicker led which movement?",o:["The Self-Respect Movement","The Quit India Movement","The Khilafat Movement","The Chipko Movement"],a:0},
{q:"Castes changed partly due to the reformers and partly due to:",o:["Other socio-economic changes","Foreign conquest","Religious conversion","Natural disasters"],a:0},
{q:"Which forces broke down the old notions of caste hierarchy?",o:["Economic development, urbanisation, literacy and education, occupational mobility, weakening of landlords","Wars and famines","Isolation of villages","Abolition of money"],a:0},
{q:"Urbanisation is the:",o:["Shift of population from rural areas to urban areas","Shift from urban to rural areas","Building of temples","Growth of castes"],a:0},
{q:"Occupational mobility usually occurs when:",o:["A new generation takes up occupations other than those practised by their ancestors","Caste rules harden","Landlords grow stronger","People stop working"],a:0},
{q:"In urban areas today, the chapter notes, it does not matter much:",o:["Who is walking next to us on a street or eating at the next table","What job we hold","Where we study","How we travel"],a:0},
{q:"The Constitution of India prohibited:",o:["Any caste-based discrimination","Inter-caste friendship","All hereditary work","Private property"],a:0},
{q:"If a person who lived a century ago returned to India, she would be:",o:["Bored","Greatly surprised at the change that has come about","Exactly at home","Unable to recognise anything"],a:1},
{q:"Which older aspect of caste has persisted?",o:["Most people still marry within their own caste or tribe","Occupations are fixed by law","Nobody eats in restaurants","All castes have merged"],a:0},
{q:"Untouchability today:",o:["Has completely ended","Has not ended completely despite constitutional prohibition","Is legal in some states","Never existed"],a:1},
{q:"Caste groups that had access to education under the old system:",o:["Have done very well in acquiring modern education as well","Refuse modern education","Were banned from schools","Remain illiterate"],a:0},
{q:"There is a disproportionately large presence of which group among the urban middle classes?",o:["'Upper caste'","Dalits","Adivasis","OBCs"],a:0},
{q:"Caste continues to be closely linked to:",o:["Economic status","The weather","Language only","Sports"],a:0},
{q:"Casteism, like communalism, is rooted in the belief that:",o:["Caste is the sole basis of social community","Class is everything","Religion is the only identity","The nation has no communities"],a:0},
{q:"Caste is one aspect of our experience, but it is:",o:["The only important one","Not the only relevant or the most important aspect","Completely irrelevant","Of foreign origin"],a:1},
{q:"When parties choose candidates in elections, they keep in mind:",o:["The caste composition of the electorate","The candidates' heights","Blood groups","Only education levels"],a:0},
{q:"When governments are formed, parties usually take care that:",o:["Representatives of different castes and tribes find a place","Only one caste is included","No caste is represented","Only relatives get posts"],a:0},
{q:"Some political parties are:",o:["Known to favour some castes and are seen as their representatives","Forbidden from caste appeals by tradition","Allowed one caste each","Completely caste-blind"],a:0},
{q:"Universal adult franchise and one-person-one-vote compelled political leaders to:",o:["Gear up to mobilising and securing political support","Resign from office","Restrict the vote","Abolish parties"],a:0},
{q:"Universal adult franchise also brought new consciousness among:",o:["Castes that were hitherto treated as inferior and low","Only upper castes","Colonial rulers","Foreign investors"],a:0},
{q:"No parliamentary constituency in the country has:",o:["A clear majority of one single caste","Any registered voters","Multiple castes","Urban voters"],a:0},
{q:"Because no caste is a majority in any constituency, every candidate needs:",o:["The confidence of more than one caste and community","Only family votes","Party funding","Media support alone"],a:0},
{q:"No party wins:",o:["The votes of all the voters of a caste or community","Any election ever","Urban seats","Rural seats"],a:0},
{q:"Saying a caste is a 'vote bank' of a party means:",o:["A large proportion of the voters of that caste vote for that party","Every member votes for that party","Members cannot vote","The party owns the caste"],a:1},
{q:"If one caste dominates an electorate, several parties may:",o:["Put up candidates from the same caste","Refuse to contest","Cancel the election","Merge into one party"],a:0},
{q:"In such a situation, some voters have more than one candidate from their caste, while many voters have:",o:["No candidate from their caste","Two votes each","No voter ID","To abstain"],a:0},
{q:"The ruling party and the sitting MP or MLA in our country:",o:["Never lose elections","Frequently lose elections","Are appointed for life","Cannot contest twice"],a:1},
{q:"Frequent defeats of incumbents prove that castes and communities are:",o:["Frozen in their political preferences","Not frozen — preferences change","Banned from voting","Uniformly loyal"],a:1},
{q:"Voters' attachment to political parties is often:",o:["Weaker than caste attachment","Stronger than their attachment to caste or community","Nonexistent","Decided by lottery"],a:1},
{q:"People within the same caste or community have different interests depending on their:",o:["Economic condition","Birthdays","Blood groups","Favourite foods"],a:0},
{q:"Rich and poor, or men and women, from the same caste often:",o:["Vote identically","Vote very differently","Do not vote at all","Live in different countries"],a:1},
{q:"Besides caste, what is often decisive in Indian elections?",o:["People's assessment of government performance and the popularity of leaders","The weather","Cricket results","Horoscopes"],a:0},
{q:"The relationship between caste and politics is:",o:["One-way only","Two-way — politics also influences caste and caste identities","Nonexistent","Purely legal"],a:1},
{q:"Complete the quote: 'It is not politics that gets caste-ridden, it is ___ that gets politicised.'",o:["Religion","The caste","The economy","The city"],a:1},
{q:"Each caste group tries to become bigger by:",o:["Incorporating within it neighbouring castes or sub-castes earlier excluded","Splitting into fragments","Migrating abroad","Banning members"],a:0},
{q:"In the political arena, caste groups enter into:",o:["Coalitions with other castes or communities — dialogue and negotiation","Duel battles","Litigation only","Permanent exile"],a:0},
{q:"New kinds of caste groups that have come up in the political arena are:",o:["'Backward' and 'forward' caste groups","'Tall' and 'short' groups","'Rainy' and 'dry' groups","'Old' and 'new' nations"],a:0},
{q:"Expression of caste differences in politics gives many disadvantaged communities:",o:["The space to demand their share of power","Automatic wealth","Court jobs","Instant land titles"],a:0},
{q:"Caste politics has helped which groups gain better access to decision-making?",o:["People from Dalit and OBC castes","Only upper castes","Foreign companies","Only bureaucrats"],a:0},
{q:"Political and non-political organisations have been demanding:",o:["An end to discrimination against particular castes, more dignity, more access to land, resources and opportunities","Higher taxes","Fewer schools","A ban on elections"],a:0},
{q:"Exclusive attention to caste can divert attention from pressing issues like:",o:["Poverty, development and corruption","Festivals","Sports","Space research"],a:0},
{q:"In some cases, caste division leads to:",o:["Tensions, conflict and even violence","Peace treaties","Economic booms","Rapid urbanisation"],a:0},
{q:"Politics based on caste identity alone is described as:",o:["Very healthy for democracy","Not very healthy in a democracy","Mandatory by law","The ideal system"],a:1},
{q:"Caste is an important source of economic inequality because it regulates:",o:["Access to resources of various kinds","The weather","Voting machines","Media ownership"],a:0},
{q:"In the past, the so-called 'untouchable' castes were denied:",o:["The right to own land","Clothing","Names","Freedom of movement"],a:0},
{q:"Only the so-called 'twice born' castes had the right to:",o:["Education","Voting","Travel abroad","Owning banks"],a:0},
{q:"A change from even twenty or thirty years ago: today it is possible to find:",o:["Very rich and very poor people in every caste, 'low' or 'high'","Rich people only among the 'lowest' castes","No poor among upper castes","No rich people at all"],a:0},
{q:"The average economic status of caste groups today still follows:",o:["The old hierarchy — 'upper' castes best off, Dalits and Adivasis worst off, backward classes in between","Alphabetical order","Population size","Random chance"],a:0},
{q:"The proportion living in extreme poverty is:",o:["Much higher for the lowest castes and much lower for the upper castes","Exactly equal for all castes","Higher for upper castes","Zero everywhere"],a:0},
{q:"Among the rich, the upper castes are:",o:["Heavily over-represented","Completely absent","Under-represented","Legally banned"],a:0},
{q:"The Census of India counts which two broad social groups?",o:["Scheduled Castes and Scheduled Tribes","Rich and poor","Men and women","Rural and urban"],a:0},
{q:"Why the prefix 'Scheduled' in Scheduled Castes and Scheduled Tribes?",o:["Their castes or tribes are listed in an official Schedule","They follow timetables","They were appointed by kings","It means 'wealthy'"],a:0},
{q:"The Scheduled Castes are commonly known as:",o:["Adivasis","Dalits","Harijans only","Twice-born"],a:1},
{q:"The Scheduled Tribes are often referred to as:",o:["Dalits","Adivasis","OBCs","Forward castes"],a:1},
{q:"The Scheduled Tribes include communities that:",o:["Led a secluded life usually in hills and forests and did not interact much with the rest of society","Lived only in capitals","Were rulers","Arrived recently from abroad"],a:0},
{q:"The Scheduled Castes include those previously regarded as:",o:["'Outcaste' in the Hindu social order, subjected to exclusion and untouchability","Kings and queens","Priests only","Traders only"],a:0},
{q:"In 2011, the Scheduled Castes were what share of India's population?",o:["16.6 per cent","8.6 per cent","41 per cent","2.3 per cent"],a:0},
{q:"In 2011, the Scheduled Tribes were what share of India's population?",o:["16.6 per cent","8.6 per cent","4 per cent","25 per cent"],a:1},
{q:"The National Sample Survey of 2004-05 estimated the Other Backward Classes at about:",o:["41 per cent","16.6 per cent","8.6 per cent","60 per cent"],a:0},
{q:"The SC, ST and OBC together account for about:",o:["Two-thirds of the country's population (and about three-fourths of Hindus)","One-tenth of the population","98 per cent of the population","Half of one per cent"],a:0},
{q:"The Census does not yet count which group?",o:["The Other Backward Classes","The Scheduled Castes","The Scheduled Tribes","Any religion"],a:0},
{q:"In the 1999-2000 NSS, which group had the highest rural poverty at 45.8 per cent?",o:["Scheduled Tribes","Hindu Upper Castes","Sikh Upper Castes","Other Upper Castes"],a:0},
{q:"In the same NSS, Hindu Upper Castes' rural poverty was only:",o:["11.7 per cent","45.8 per cent","35.9 per cent","27 per cent"],a:0},
{q:"(NCERT exercise) Social divisions based on _________ are peculiar to India.",o:["Gender","Religion","Caste","Language"],a:2,w:"Caste division — hereditary occupational division sanctioned by rituals — is special to India."},
{q:"(NCERT exercise) A person who believes in equal rights and opportunities for women and men is a:",o:["Communalist","Feminist","Secularist","Castiest"],a:1},
{q:"(NCERT exercise) A person who says that religion is the principal basis of community is a:",o:["Feminist","Communalist","Secularist","Castiest"],a:1},
{q:"(NCERT exercise) A person who thinks caste is the principal basis of community is a:",o:["Feminist","Communalist","Secularist","Castiest"],a:3},
{q:"(NCERT exercise) A person who does not discriminate against others on the basis of religious beliefs is a:",o:["Secularist","Communalist","Castiest","Feminist"],a:0}
);
