/* 200-question bank — part 1 (Q1-100: Gender + Religion) */
window.QUIZ_BANK = [
{q:"When we speak of 'gender division' in this chapter, we refer to:",o:["Biological differences between men and women","Unequal roles assigned by the society to men and women","The unequal child sex ratio","Absence of voting rights for women"],a:1,w:"Gender division rests on social expectations and stereotypes, not biology."},
{q:"The gender division is 'understood as natural and unchangeable', but it is actually based on:",o:["Biology","Genetics","Social expectations and stereotypes","Geography"],a:2,w:"NCERT: it is not based on biology but on social expectations and stereotypes."},
{q:"Which form of social division is 'seen everywhere' yet rarely recognised in the study of politics?",o:["Religion","Caste","Region","Gender"],a:3,w:"Gender division is universal, yet rarely recognised in politics."},
{q:"Boys and girls are brought up to believe that women's main responsibility is:",o:["Earning for the family","Housework and bringing up children","Governance","Farming only"],a:1},
{q:"The system in which all work inside the home is done by the women of the family, or organised by them through domestic helpers, is called:",o:["Occupational mobility","Sexual division of labour","Patriarchy","Caste hierarchy"],a:1,w:"Exact NCERT definition of sexual division of labour."},
{q:"In most families, work inside the home is done by:",o:["Men","Women","Children","Guests"],a:1},
{q:"Which fact proves men take up 'women's work' when it is paid?",o:["Most tailors or cooks in hotels are men","Men do most laundry at home","Men rarely work","Only men sew"],a:0,w:"When jobs like cooking and tailoring are paid, men are ready to take them up."},
{q:"In villages, women's work outside the home includes:",o:["Fetching water, collecting fuel and working in the fields","Driving trains","Running banks","Mining"],a:0},
{q:"In urban areas, poor women commonly work as:",o:["Domestic helpers in middle-class homes","Airline pilots","Factory owners","Judges"],a:0},
{q:"The majority of women:",o:["Do no paid work","Do some sort of paid work in addition to domestic labour","Earn more than men","Only do office work"],a:1},
{q:"Although women work long hours, their work is:",o:["Highly paid","Not valued and does not get recognition","Always counted in GDP","Limited to offices"],a:1},
{q:"Women constitute how much of humanity?",o:["One-third","One-fourth","Half","Two-thirds"],a:2},
{q:"In earlier times, who alone could participate in public affairs, vote and contest elections?",o:["Only men","Only women","All adults","Priests only"],a:0},
{q:"More radical women's movements that aimed at equality in personal and family life are called:",o:["Communal movements","Feminist movements","Trade unions","Environmental movements"],a:1},
{q:"A feminist is:",o:["Only a woman who opposes men","A woman or a man who believes in equal rights and opportunities for women and men","A person who wants women to dominate","A member of a women's club"],a:1,w:"Exact NCERT definition — note a man can also be a feminist."},
{q:"'Patriarchy' literally means:",o:["Rule by mother","Rule by father","Rule by elders","Rule of the state"],a:1},
{q:"Patriarchy refers to a system that:",o:["Values men more and gives them power over women","Values women more","Treats all genders equally","Is based on wealth"],a:0},
{q:"Women's agitations demanded enhancing political and legal status plus:",o:["Only voting rights","Improved educational and career opportunities","Property for queens","Military ranks"],a:1},
{q:"Which professions were 'earlier not considered suitable' for women but now employ many women?",o:["Scientists, doctors, engineers, lawyers, managers, university teachers","Only nursing","Only weaving","None — nothing changed"],a:0},
{q:"In which countries is women's participation in public life 'very high'?",o:["Sweden, Norway and Finland (Scandinavian)","India and Pakistan","Egypt and Iran","China and Japan"],a:0},
{q:"Despite improvement since Independence, Indian society is still described as:",o:["Matriarchal","Egalitarian","Male-dominated and patriarchal","Classless"],a:2},
{q:"The literacy rate among women cited in the chapter is about:",o:["76 per cent","54 per cent","90 per cent","33 per cent"],a:1,w:"54% among women compared with 76% among men."},
{q:"When we look at school results, girls:",o:["Always lag behind boys","Perform as well as boys, if not better","Never finish school","Study only till Class 5"],a:1},
{q:"Girls drop out of higher studies mainly because:",o:["Parents prefer to spend resources on boys' education","Schools refuse admission","Law prohibits girls' education","They are needed only in cities"],a:0,w:"The reason is parental spending preference, not performance."},
{q:"On average, an Indian woman works ___ than an average man every day:",o:["One hour less","Two hours less","One hour more","Exactly the same"],a:2},
{q:"Much of women's work is not valued because it is:",o:["Done by machines","Not paid","Less skilled","Done outdoors"],a:1},
{q:"The Equal Remuneration Act was passed in:",o:["1947","1956","1976","1991"],a:2},
{q:"The Equal Remuneration Act, 1976 provides that:",o:["Equal wages should be paid for equal work","Women get double wages","Wages depend on caste","Only men get bonuses"],a:0},
{q:"Despite the equal wages law, women are paid less than men in:",o:["Only agriculture","Only sports","Almost all areas — sports, cinema, factories, fields","Nowhere"],a:2},
{q:"Sex-selective abortion has led to a decline in the:",o:["Literacy rate","Child sex ratio","Employment rate","Sexual division of labour"],a:1},
{q:"Child sex ratio means:",o:["Number of girl children per thousand boys","Number of boys per thousand girls","Births per woman","Women per thousand men"],a:0},
{q:"The child sex ratio declined to merely ___ (Census 2011):",o:["950","919","1000","890"],a:1,w:"919 girls per thousand boys; below 850 or even 800 in some states."},
{q:"In some states the child sex ratio has fallen below:",o:["950 or 900","850 or even 800","1000","1200"],a:1},
{q:"Which statement about women's safety does the chapter make?",o:["Urban areas are safe at night","Women are not safe even within their own homes","Villages have no violence","Rural women face no violence"],a:1,w:"Beating, harassment and domestic violence continue inside homes."},
{q:"The time-use survey cited by NCERT was conducted in:",o:["Two states","Six states","All states","Ten states"],a:1},
{q:"According to the time-use survey, an average woman works every day for:",o:["A little over seven and a half hours","Six hours","Four hours","Ten hours"],a:0},
{q:"According to the time-use survey, an average man works every day for:",o:["Eight hours","Six and a half hours","Five hours","Three hours"],a:1},
{q:"Men's work is more visible because:",o:["It is done in cities","Most of it leads to generation of income","It uses machines","It is unpaid"],a:1},
{q:"The bulk of women's work is:",o:["Paid and visible","Household related — unpaid and invisible","Industrial","Government service"],a:1},
{q:"In the time-use table, time spent on income-generating work — men vs women — is:",o:["6:00 vs 2:40","2:40 vs 6:00","5:00 vs 0:30","8:00 vs 8:00"],a:0},
{q:"In the time-use table, women spend about how long on household and related work?",o:["30 minutes","1 hour","5 hours","8 hours"],a:2,w:"Women 5:00 vs men 0:30 — a ten-fold gap."},
{q:"Feminists concluded that women's problems will get adequate attention only when:",o:["Women control power","Men become kinder","Laws are removed","Media intervenes"],a:0},
{q:"One way to ensure women control power is:",o:["More women as elected representatives","Only appointments","Only protests","Donations"],a:0},
{q:"The percentage of elected women members in the Lok Sabha touched 14.36 per cent for the first time in:",o:["1984","2009","2014","2019"],a:3},
{q:"Women's share in state assemblies is:",o:["More than 30 per cent","Less than 5 per cent","About 25 per cent","Exactly 14.36 per cent"],a:1},
{q:"In women's legislative representation, India ranks among:",o:["Top ten nations","The bottom group of nations","The middle group","The Nordic group"],a:1},
{q:"India is behind the averages for women's representation of:",o:["Only the USA","Several developing countries of Africa and Latin America","Only China","No country"],a:1},
{q:"Which region has the highest share of women in national parliaments (about 42 per cent)?",o:["Nordic countries","Arab States","Asia","Pacific"],a:0,w:"Nordic countries 42.3% — the world's highest."},
{q:"In the IPU graph, India's share of women in parliament was roughly:",o:["The world's highest","About 11.8 per cent — near the bottom","Equal to the Nordics","About 40 per cent"],a:1},
{q:"Even when a woman becomes Chief Minister or Prime Minister, cabinets are:",o:["Half women","Largely all-male","All women","Disbanded"],a:1},
{q:"What made it legally binding to have a fair proportion of women in elected local bodies?",o:["The Supreme Court","The Panchayati Raj","The Finance Commission","The Planning Commission"],a:1},
{q:"What fraction of seats in panchayats and municipalities is reserved for women?",o:["One-half","One-third","One-tenth","Two-thirds"],a:1},
{q:"There are now more than how many elected women representatives in rural and urban local bodies?",o:["One thousand","Ten thousand","Ten lakh (one million)","One crore"],a:2},
{q:"Women's organisations demanded a similar one-third reservation in:",o:["The cabinet","Lok Sabha and State Assemblies","The judiciary","The civil services"],a:1},
{q:"The Women's Reservation Bill was pending before Parliament for:",o:["A few months","One year","Many decades","A century"],a:2},
{q:"The Nari Shakti Vandan Adhiniyam was passed in:",o:["1996","2010","2019","2023"],a:3},
{q:"The Women's Reservation Act, 2023 provides what percentage of reserved seats?",o:["25 per cent","33 per cent","50 per cent","40 per cent"],a:1},
{q:"The 2023 Act reserves seats for women in:",o:["Lok Sabha, State Legislative Assemblies and the Delhi Assembly","Only the Lok Sabha","Only the Rajya Sabha","Cabinet posts"],a:0},
{q:"'Nari Shakti Vandan Adhiniyam' is also known as:",o:["The Women's Reservation Act, 2023","The Equal Remuneration Act","The Panchayati Raj Act","The Dowry Prohibition Act"],a:0},
{q:"Gender division is an example that:",o:["Social divisions should never enter politics","Some form of social division needs to be expressed in politics","Only economics matters","Politics creates all divisions"],a:1},
{q:"Disadvantaged groups do benefit when:",o:["Social divisions become a political issue","They stay silent","Divisions are hidden","The state ignores them"],a:0,w:"Political expression of division brought women the vote, laws and reserved seats."},
{q:"Women in different parts of the world organised and agitated especially for:",o:["Extension of voting rights to women","Lower taxes","Bigger armies","Closing schools"],a:0},
{q:"Which arrangement reflects the sexual division of labour in urban areas?",o:["Men cook the daily meals","Middle-class women work in offices while poor women work as domestic helpers","Children do the housework","Nobody does housework"],a:1},
{q:"The chapter reproduces a poster from Bengal affirming:",o:["Women's strength","Child labour","Religious harmony","Caste unity"],a:0},
{q:"The chapter's 'Mummy always says I don't work' strip highlights that:",o:["Housewives truly do not work","A housewife's non-stop work is invisible because it is unpaid","Only office work counts for men","Children exaggerate"],a:1},
{q:"Compared to gender division, religious division is:",o:["More universal","Not as universal","Identical","Purely economic"],a:1},
{q:"Religious diversity in the world today is:",o:["Rare","Fairly widespread","Confined to India","Disappearing"],a:1},
{q:"The Northern Ireland example shows that:",o:["Religions never conflict","Even when most people follow the same religion, there can be serious differences about how it is practised","Only one religion is divided","All Christians agree"],a:1},
{q:"Unlike gender differences, religious differences are:",o:["Never political","Often expressed in the field of politics","Purely economic","Always invisible"],a:1},
{q:"Who said that religion can never be separated from politics?",o:["Gandhiji","Ambedkar","Nehru","Periyar"],a:0},
{q:"Gandhiji's 'religion' in that statement meant:",o:["Hinduism only","Islam only","Moral values that inform all religions","A new religion"],a:2,w:"Not any particular religion — ethics common to all faiths."},
{q:"Gandhiji believed politics must be guided by:",o:["Wealth","Ethics drawn from religion","The army","Foreign powers"],a:1},
{q:"Human rights groups demanded that the government should:",o:["Ban all religions","Take special steps to prevent communal riots and protect religious minorities","Promote one religion","Ignore minorities"],a:1},
{q:"The women's movement argued that family laws of all religions:",o:["Are perfectly equal","Discriminate against women","Apply only to men","Do not exist"],a:1},
{q:"Family laws deal with:",o:["Marriage, divorce, adoption, inheritance","Taxation","Defence","Foreign trade"],a:0},
{q:"In India, family laws:",o:["Are identical for all religions","Are different for followers of different religions","Apply only to Hindus","Were abolished in 1976"],a:1},
{q:"Ideas and values drawn from religion may play a role in politics as long as:",o:["One religion is favoured","Every religion is treated equally","The state funds temples","Only festivals are public holidays"],a:1,w:"The litmus test of legitimate religion-politics contact is equal treatment."},
{q:"Those who hold political power may regulate the practice of religion in order to:",o:["Promote one faith","Prevent discrimination and oppression","Collect religious taxes","Close places of worship"],a:1},
{q:"The problem of communalism begins when:",o:["Religion is seen as the basis of the nation","People pray daily","Religions coexist peacefully","The state stays neutral"],a:0},
{q:"Using religion in politics in exclusive and partisan terms is called:",o:["Secularism","Communal politics","Federalism","Socialism"],a:1},
{q:"Communal politics is based on the idea that:",o:["Class is the principal basis of community","Religion is the principal basis of social community","Gender is the basis of community","The nation is above religion"],a:1},
{q:"Communalism holds that followers of a particular religion:",o:["Must belong to one community","Can belong to many communities","Share nothing in common","Should not vote"],a:0},
{q:"Communalism assumes the fundamental interests of co-religionists are:",o:["Different","The same","Irrelevant","Purely economic"],a:1},
{q:"Communalism believes people who follow different religions:",o:["Cannot belong to the same social community","Always cooperate","Share all interests","Are identical"],a:0},
{q:"In its extreme form, communalism leads to the belief that:",o:["People of different religions cannot live as equal citizens within one nation","All religions merge","The state disappears","Voting is compulsory"],a:0,w:"Either one religion dominates the rest, or separate nations must be formed."},
{q:"The communal belief is 'fundamentally flawed' because:",o:["Religions do not exist","People of one religion do not have the same interests and aspirations in every context","All religions are identical","Nations do not exist"],a:1},
{q:"Everyone in society has:",o:["Only one identity","Several other roles, positions and identities","No identity","Only a religious identity"],a:1},
{q:"There are many voices inside every community, and all of them:",o:["Must be suppressed","Have a right to be heard","Are irrelevant","Belong to one leader"],a:1},
{q:"The most common expression of communalism is in:",o:["Everyday beliefs","Court judgments","Five-year plans","Budget speeches"],a:0,w:"Prejudices, stereotypes and beliefs of superiority — so common we fail to notice them."},
{q:"Everyday communalism is so common that:",o:["It is illegal everywhere","We often fail to notice it, even when we believe in it","It has disappeared","Only scholars detect it"],a:1},
{q:"For those belonging to the majority community, the quest for political dominance takes the form of:",o:["Separatism","Majoritarian dominance","Silence","Migration"],a:1},
{q:"For those belonging to the minority community, communalism can take the form of:",o:["A desire to form a separate political unit","Majoritarian dominance","Complete withdrawal","Denial of religion"],a:0},
{q:"Political mobilisation on religious lines uses:",o:["Sacred symbols, religious leaders, emotional appeal and plain fear","Economic manifestos","Education policy","Scientific debate"],a:0},
{q:"In electoral politics, communal mobilisation often involves:",o:["Special appeal to the interests or emotions of voters of one religion","Appeals to all religions equally","Only development plans","Civil service reform"],a:0},
{q:"The 'most ugly form' of communalism is:",o:["Everyday stereotypes","Communal violence, riots and massacre","Court cases","Political speeches"],a:1},
{q:"India and Pakistan suffered some of the worst communal riots at the time of:",o:["The Green Revolution","The Partition","The Emergency","The Non-Aligned Movement"],a:1},
{q:"Aware of the challenge of communalism, the makers of our Constitution chose:",o:["A theocratic state","The model of a secular state","A monarchy","A military state"],a:1},
{q:"The Indian state has:",o:["Hinduism as its official religion","No official religion","Islam as its official religion","Two official religions"],a:1},
{q:"Buddhism enjoys a special status in:",o:["Sri Lanka","Pakistan","England","Nepal"],a:0},
{q:"In the chapter's comparison, Islam has a special status in:",o:["Sri Lanka","Pakistan","England","India"],a:1},
{q:"Christianity is linked to the state church of:",o:["England","France","Germany","Italy"],a:0}
];
