/* Line-by-line decodes — Economics (keyed to textlines_eco.js block indexes) */
(function () {
  window.DECODE = window.DECODE || {};

  window.DECODE.eco1 = {
    2: 'The chapter\u2019s opening questions: what do we need for a good life, and <b>who decides what "better" means</b>? The answers differ by person — that is the whole point.',
    6: 'Development goals are <b>what people seek to fulfil their aspirations</b> — a landless labourer wants work, a girl wants freedom equal to her brother, a farmer wants fair prices.',
    7: 'Two farmers, two goals: one wants assured <b>high support prices</b>, another\u2019s goal may be affordable schooling — income is central but not everything.',
    8: '<b>Conflicting goals</b>: a girl\u2019s demand for equal freedom vs her family\u2019s expectations; an industrialist\u2019s dam vs a tribal\u2019s forest — one group\u2019s development can be another\u2019s loss.',
    9: 'The two clear conclusions: <b>different persons have different goals</b>, and <b>what is development for one may be destructive for another</b>.',
    10: 'Income matters most because <b>most other goals depend on it</b> — food, house, education, health all cost money. But people also seek equal treatment, freedom, security, respect.',
    11: 'Some things <b>money cannot buy</b>: a pollution-free environment, unadulterated medicines, equal treatment — the non-market goods.',
    13: 'A mix of goals: if women are engaged in paid work and get respected for it, development happens on several fronts at once.',
    14: 'Since individuals differ in goals, states and nations need <b>common indicators to compare development</b> — enter income and other criteria.',
    18: 'To compare, we choose <b>criteria</b> — and different criteria give different winners; comparison is always about <b>which yardstick</b> you pick.',
    22: 'For countries, <b>income is the most-used criterion</b> — higher income usually means more of the things development needs.',
    23: 'But <b>total income is misleading</b> for comparison — countries have different populations — so we compare <b>average (per capita) income</b>.',
    24: 'The <b>World Bank</b> classifies countries by per capita income (World Development Report): rich, middle-income and low-income countries.',
    28: 'The classic five-citizens example: the same average income hides very different lives — <b>averages hide distribution</b>.',
    30: 'Income is not enough: two states/countries with similar PCI can differ hugely in health and education — so we look at <b>other criteria too</b>.',
    31: 'The NCERT comparison: <b>Haryana (highest PCI), Kerala, Bihar (lowest)</b> — and the surprise that income rank ≠ human-development rank.',
    32: 'Haryana\u2019s per capita income (₹3,25,759 in 2017–18) far above Kerala\u2019s and Bihar\u2019s — money says Haryana leads.',
    34: '<b>Literacy rate</b>: share of the 7-and-above population that can read and write with understanding; <b>Net Attendance Ratio</b>: share of 6–17-year-olds attending school.',
    35: 'The Kerala surprise: out of 1,000 children born, only <b>6 die before age one in Kerala vs 30 in Haryana</b> — better public health and nutrition at lower income.',
    37: 'What money cannot buy: a <b>pollution-free environment</b> or an unadulterated medicine — no market sells these; policy and public action must provide them.',
    38: 'The cheapest, best way to provide what matters: <b>public facilities</b> — schools, hospitals, drinking water, sanitation — shared by all.',
    39: 'Schooling works as a public system: you study because everyone can study — collective provision creates individual opportunity.',
    42: 'Case: in Tamil Nadu, 90% of people living in rural areas used <b>public distribution system shops</b> — public provision reaching the poor.',
    44: 'The chapter\u2019s summary: development needs <b>health and education for all</b> — income, plus the public systems that convert income into wellbeing.',
    45: '<b>Table 1.6 — India and neighbours</b>: Sri Lanka, India, Pakistan, Nepal, Bangladesh, Myanmar compared on GNI, HDI, literacy and more.',
    47: 'The <b>BMI activity</b>: weight (kg) ÷ height² (m²); below 18.5 = underweight; above 25 = overweight — a self-check of nutrition.',
    50: 'The big lesson from Table 1.6: <b>Sri Lanka, and even Nepal and Bangladesh on some indicators, beat India despite lower per capita income</b> — income is not destiny.',
    51: '<b>Sustainability Example 1 — groundwater</b>: a renewable resource only if use ≤ recharge; overuse in farming districts means the next generation inherits dry wells.',
    52: 'Groundwater overuse is concentrated in <b>agriculturally prosperous regions</b> — Punjab, Haryana, western UP — prosperity itself is draining the aquifer.',
    53: 'The sustainability slogan to quote: <b>"We have not inherited the world from our forefathers — we have borrowed it from our children."</b>',
    56: 'The politics of oil: countries like the USA with low reserves want to <b>secure oil fields abroad</b> — resource sustainability becomes geopolitics.',
    57: '<b>Non-renewable resources</b> — crude oil, natural gas — exhaust with use; <b>renewable</b> ones (groundwater, solar, wind) renew within human time — if we let them.',
    60: 'The chapter\u2019s close: development is sustainable only if the <b>present generation leaves enough for the future</b> — the idea of intergenerational equity.'
  };

  window.DECODE.eco2 = {
    3: '<b>Primary sector</b>: natural products used directly — dairy, farming, fishing, forestry, mining. Called primary because it is the <b>base</b> of all other activity.',
    4: '<b>Secondary sector</b>: natural products are <b>changed into other forms</b> — manufacturing, industry; cotton to cloth, sugarcane to sugar.',
    5: '<b>Tertiary sector</b>: activities that <b>help develop</b> the primary and secondary sectors — transport, storage, communication, banking, trade. Called the service sector.',
    6: 'Tertiary activities in daily life: telephone, letters, banking, transport — services support production and life without producing a good.',
    7: 'The tertiary sector also includes <b>essential services</b> — teachers, doctors, washermen, barbers, administrative and defence staff — needed even when they make nothing you can touch.',
    9: 'Interdependence: without a spinner buying cotton, cotton farming collapses — the three sectors form one <b>chain of production</b>.',
    14: 'How to count total production: add the <b>value of goods and services</b> produced — 5,000 coconuts × ₹15 = ₹75,000; value, not volume, makes things addable.',
    16: 'The great precaution: count only <b>final goods and services</b> — counting intermediate goods would be <b>double counting</b>.',
    17: 'The biscuit example: flour at ₹20 becomes biscuits at ₹80 — count the final ₹80 only; the flour\u2019s value is inside it.',
    19: 'One good, three sectors: wheat (primary) → flour (secondary) → biscuit in a shop (tertiary trade) — the reason for the sectoral framework.',
    22: '<b>GDP — Gross Domestic Product</b>: the sum of value of all final goods and services in all three sectors in a year.',
    23: 'In India, GDP is measured by a <b>central government agency</b> (the Central Statistical Organisation / MoSPI) — data from all sectors.',
    25: '<b>Historical change</b>: in developed economies the primary sector gave way to secondary (industry), then to tertiary — the classic shift.',
    27: 'Over time, the <b>secondary sector became the largest producer and employer</b> in industrial economies, and then services overtook even that.',
    28: 'The Indian data story: over four decades, the <b>tertiary sector became the largest contributor to GDP</b> — more than half of output.',
    32: 'Why services grow: <b>basic services</b> expand first — hospitals, education, banking, transport — in any developing country.',
    34: 'Third driver: <b>rising incomes</b> create demand for tourism, restaurants, shopping — consumer services explode as the middle class grows.',
    35: 'But not all services grow equally — the sector hides both high-end IT and <b>low-paid casual work</b>; the service share is not all shine.',
    37: 'The Indian twist: although tertiary leads GDP, <b>employment never left the primary sector</b> the way output did.',
    38: 'The mismatch in one number: <b>more than half of Indian workers are still in agriculture</b>, which produces a much smaller share of GDP.',
    39: '<b>Laxmi\u2019s case</b>: a two-hectare unirrigated plot worked by the whole family — three people doing what one could — the definition of <b>disguised unemployment</b>.',
    40: 'Disguised unemployment is <b>hidden</b> — everyone looks busy, no one is counted jobless, yet extra hands add nothing to output.',
    41: 'If Sukhram hires two family members away, farm output <b>does not fall</b> — proof the labour was surplus.',
    42: 'There are lakhs of Laxmis — India could move a huge workforce out of farms <b>without losing any output</b>, if jobs existed.',
    43: 'Urban underemployment: the cart-pusher or day labourer with many idle days — irregular, badly paid work in the service sector.',
    45: 'The fix begins with <b>irrigation</b>: two crops a year on Laxmi\u2019s plot doubles work days on the same land.',
    48: '<b>Infrastructure creates jobs</b>: roads, transport and storage for crops; construction employs and multiplies local commerce.',
    49: 'Laxmi also needs <b>credit</b> for seeds and fertilisers, and a market to sell in — employment grows when farm systems grow.',
    50: 'Another route: <b>identify, promote and locate industries</b> in semi-rural areas — where the surplus labour actually lives.',
    51: 'Agro-processing near farms — pickles, jam, gur — <b>value-adds the crop where it grows</b> and employs locally.',
    52: 'India\u2019s <b>demographic dividend</b>: about 60% of the population is working-age — a huge opportunity, if jobs and skills match.',
    54: '<b>MGNREGA 2005 — the Right to Work</b>: 100 days of guaranteed wage employment per rural household; if work is not given, an <b>unemployment allowance</b> is paid.',
    55: 'Education spending creates jobs twice — teachers and builders now, educated earners later: a <b>building-blocks</b> strategy for employment.',
    60: '<b>Organised sector defined</b>: registered enterprises with fixed terms of work — Kanta gets a salary, paid leave, provident fund, medical benefits, gratuity.',
    61: 'Kanta\u2019s salary extras: <b>provident fund per rules</b>, medical allowances, paid holidays — the security package of organised work.',
    63: 'Kamal\u2019s contrast: <b>unorganised sector</b> — no contract, no benefits, rules exist but are not enforced; a day without work is a day without pay.',
    67: 'Reality check: organised-sector jobs are few — <b>the vast majority of Indians work unorganised</b>, which is why this classification matters.',
    68: 'Unorganised work means <b>low, irregular earnings</b> and no security — work and income are the same thing.',
    69: 'Rural unorganised: <b>landless labourers, small and marginal farmers, sharecroppers</b> — the invisible majority of the fields.',
    70: 'Urban unorganised: <b>small-scale industry workers, street vendors, casual construction labour</b> — self-employment and piece work.',
    71: 'When factories close, regular workers end up <b>selling goods or pushing carts</b> — a slide from organised to unorganised.',
    74: '<b>Public vs private sector</b>: railways and post offices are public; Tata Motors and Reliance are private — ownership decides the label.',
    75: 'The private sector works for <b>profit</b>; the public sector works for <b>public welfare</b> — different motors, different jobs.',
    76: 'Why public provision? Some things the whole society needs — roads, street lights, defence — that <b>private profit will not supply to all</b>.',
    77: 'If private firms did supply public goods, they would <b>charge high rates</b> — access would follow money, not need.',
    79: 'The government as buyer of last resort: <b>wheat and rice at a "fair price"</b> from farmers — supporting producers where markets fail.',
    80: 'Health and education for all — <b>public provision</b> of the two services that build human capital.',
    82: 'The Indian trend: services grow in output, yet their <b>employment quality is mixed</b> — growth and good jobs must be separated in analysis.'
  };

  window.DECODE.eco3 = {
    1: 'Transactions are <b>exchanges</b> — goods and services flow one way, money flows back; money is the hinge of every modern exchange.',
    2: 'Why money? Because a person selling shoes may not want what you grow — money removes the need for mutual wants.',
    3: '<b>Double coincidence of wants</b>: in barter, both sides must want exactly what the other offers — the bottleneck money solves.',
    4: 'With money, the shoe-seller sells to anyone for money, then buys wheat — the <b>medium of exchange</b> splits one hard trade into two easy ones.',
    6: '<b>Modern currency</b>: paper notes and coins — unlike early coins, they have <b>no intrinsic value</b>; the government authorises them as legal tender.',
    7: '<b>The Reserve Bank of India</b> issues currency notes <b>on behalf of the central government</b>; no other agency may issue notes — rupees are guaranteed by the RBI.',
    8: 'The second form of money: <b>bank deposits</b> — held in current, savings, fixed accounts; a cheque moves deposits without cash.',
    11: '<b>Demand deposits share the essential features of money</b> — payable on demand, transferable by cheque — so deposits ARE money.',
    12: 'The <b>cheque</b>: account number, bank code, amount, signature — a written instruction the bank must honour.',
    14: 'Banks keep only about <b>15% of deposits as cash</b> — enough for daily withdrawals, because all depositors never withdraw at once.',
    15: 'Banks lend the rest — <b>loans are the bank\u2019s main business</b>: they charge borrowers more interest than they pay depositors.',
    16: 'The banking cycle: deposits → interest to depositors → loans to borrowers → repayment with interest — the bank is the middleman of money.',
    17: 'Salim\u2019s story: the shoemaker takes <b>working-capital credit</b> (leather, advance from the trader) to complete festive orders — credit as production\u2019s fuel.',
    18: '<b>Swapna\u2019s story</b>: a small groundnut farmer borrowing from the moneylender at high interest before sowing — the setup for the debt trap.',
    19: 'A normal crop still leaves Swapna unable to clear old debts — high interest eats the harvest; she must borrow again and finally <b>sell part of her land</b>.',
    20: 'The pattern: crop loans at season\u2019s start, repayment after harvest — when the crop fails, the chain snaps.',
    22: 'The lesson of Salim vs Swapna: credit that funds production <b>raises income</b>; credit at high cost after a shock <b>ruins the borrower</b> — credit has two faces.',
    23: '<b>Collateral</b>: the asset a borrower pledges — land, building, vehicle, livestock, gold deposit — which the lender can sell if the loan is not repaid.',
    28: 'The trader-lender\u2019s extra terms: besides interest, farmers must <b>sell the harvest to him at low prices</b> — informal credit bites twice.',
    30: 'Sonpur\u2019s case: <b>Salim gets a bank loan at 8.5%</b> for cultivation while Shyamal borrows from the agricultural trader at <b>36%</b> — formal vs informal in one village.',
    33: '<b>Cooperatives</b> — farmers\u2019, workers\u2019, consumers\u2019 — pool members\u2019 savings and lend within: another formal channel.',
    34: 'The <b>Krishak Cooperative</b> funds implements and irrigation at low rates — the working model of cooperative credit.',
    36: 'The <b>informal sector has no supervisor</b> — moneylenders and traders lend on their own terms; that is why they can charge 36% and demand the crop.',
    37: 'The <b>RBI supervises the formal sector</b>: banks report periodically, follow collateral and rate rules — borrowers get legal protection.',
    38: 'The 2019 rural credit graph: cooperatives and commercial banks supply <b>about two-thirds</b> of rural credit — but the moneylender\u2019s share is still large among the poor.',
    39: 'Informal lenders charge <b>much higher interest</b> — 36% against the bank\u2019s 8.5% — the cost of being excluded from formal credit.',
    40: 'The policy conclusion: banks and cooperatives <b>must lend more to the poor</b> — cheap credit is a development input, not a favour.',
    41: 'The numbers: <b>54% of urban poor households\u2019 loans are informal</b> — exclusion from banks crosses the rural-urban line.',
    42: 'For the <b>rich, it inverts</b>: only about 17% of their loans are informal — formal credit follows assets, not need.',
    46: 'Beyond lending more, formal loans must be <b>timely</b> — a seed loan after sowing season is worthless.',
    47: 'Even where banks exist, a bank loan is <b>harder to get</b> — paperwork, collateral, procedures the poor cannot meet.',
    49: '<b>SHGs — the key institution</b>: about 15–20 (mostly women) pool small savings, lend internally, then borrow from banks <b>without collateral</b>.',
    50: 'The bank loan is sanctioned <b>in the group\u2019s name for self-employment</b> — the group\u2019s collective record replaces the missing mortgage papers.',
    51: '<b>Group responsibility for repayment</b>: any default by a member is the group\u2019s burden — peer pressure is the collateral.',
    52: 'SHGs beat the collateral barrier — small timely loans at reasonable interest — and so free borrowers from moneylenders.',
    55: '<b>Muhammad Yunus</b>, founder of Grameen Bank, won the <b>2006 Nobel Peace Prize</b> for micro-credit — the global seal on the SHG idea.',
    56: 'The <b>Grameen Bank of Bangladesh</b>: the biggest success in reaching the poor — tiny collateral-free loans, near-total repayment.'
  };

  window.DECODE.eco4 = {
    2: 'The everyday evidence of globalisation: the <b>latest global models</b> — cameras, phones, TVs — on Indian shelves within months of launch.',
    3: 'This wide choice is <b>recent</b> — before the 1990s, Indian markets held mostly what India made: the change is a policy choice, not fate.',
    6: '<b>The MNC definition</b>: a company that <b>owns or controls production in more than one nation</b> — headquarters in one country, production across many.',
    8: 'The MNC playbook: not just selling globally, but <b>producing globally</b> — design in one country, parts from several, assembly in the cheapest.',
    9: 'India\u2019s advantages for MNCs: <b>educated, English-speaking youth</b> for customer care — why the BPO industry grew here.',
    10: 'The advantage of spreading production: <b>cost falls</b> — MNCs pick the cheapest point for every stage of the chain.',
    11: 'MNC location logic: <b>close to markets, skilled and cheap labour, and guaranteed conditions</b> — profit geography decides.',
    12: 'Investment by MNCs is called <b>foreign investment</b> — buying land, machines, buildings abroad to produce and profit.',
    13: '<b>Cargill Foods</b>: the American MNC that bought Parakh Foods — now a top Indian edible-oil maker (Fortune, Sweekar brands): the buy-out route.',
    14: 'Scale: top MNCs have <b>wealth exceeding the entire budgets of developing countries</b> — the power asymmetry of global markets.',
    15: 'Local firms become <b>MNC suppliers</b>: they manufacture to MNC standards, MNCs sell under their own brands — global production chains reach Indian workshops.',
    16: 'The chain\u2019s longest end: <b>women in Ludhiana stitching footballs at home</b> for global brands — production networks reach the household.',
    20: '<b>Foreign trade</b> lets producers reach <b>beyond domestic markets</b> and buyers reach beyond local goods — the classic integration of markets.',
    21: '<b>Ford Motors</b>: the American auto giant that set up Indian production with Mahindra — joint venture as the entry ticket.',
    22: 'The update: Ford <b>stopped selling cars in India but kept exporting from its plant</b> — India as a global manufacturing base.',
    24: 'The <b>Chinese toys example</b>: imports captured Indian shops because they were cheaper — competition\u2019s harsh face for local toy-makers.',
    27: 'With open trade, goods travel to where the price is best — <b>markets integrate</b> across borders, producers compete globally.',
    28: 'For two-three decades, MNCs have moved production to <b>low-cost regions</b> — the geography of production has been rebuilt.',
    30: 'The result of greater foreign investment + trade = <b>greater integration of production and markets</b> — the working definition of globalisation.',
    32: '<b>Containers</b>: goods sealed in steel boxes, moved from ship to truck without unloading — transport costs crashed, trade exploded.',
    34: '<b>IT and communication technology</b>: instant transfer of orders, designs and money across the planet — the second great enabler.',
    36: 'A London magazine <b>designed and printed in Delhi</b> — services trade by wire; distance itself has become cheap.',
    38: 'Imports face <b>taxes (tariffs)</b> — making the foreign good costlier is the classic protection device.',
    39: 'After Independence, India placed <b>barriers on foreign trade and investment</b> — protecting domestic producers was the declared aim.',
    40: 'Around <b>1991, far-reaching policy changes</b> — the crisis-driven turn to openness; India decided to liberalise.',
    41: '<b>Liberalisation defined</b>: removing government barriers and restrictions — businesses free to import, export and invest across borders.',
    43: 'The <b>WTO (1995)</b> was to ensure free and fair trade for all — the rules body of globalisation; developing countries expected fairer access.',
    45: 'The catch: while demanding free trade in services, <b>rich countries kept their agricultural subsidies</b> — the unfairness developing countries protest.',
    46: 'The US farm example: agriculture is a tiny share of GDP and employment — yet hugely subsidised and protected.',
    47: 'A US cotton farm spans <b>thousands of corporate acres</b> vs the small Indian holding — unequal competitors on paper-equal rules.',
    48: 'The impact is <b>uneven</b>: some producers and workers gain, others lose — globalisation has a scoreboard, not a verdict.',
    52: 'Globalisation created <b>new opportunities for services</b> — especially IT-enabled services India could deliver globally.',
    53: 'Some large <b>Indian companies became MNCs themselves</b> — Tata Motors, Infosys, Asian Paints, Ranbaxy: globalisation flows both ways.',
    55: 'To attract investment, government allowed <b>flexibility in labour laws</b> — firms can hire for flexible terms; the workers\u2019 side pays.',
    56: 'Companies still demand <b>more flexibility</b> — the permanent tug-of-war between investment and job security.',
    57: 'The squeezed list: <b>batteries, capacitors, plastics, toys, tyres, dairy, vegetable oil</b> — small Indian producers hit by imports.',
    60: 'Case: <b>Ravi\u2019s capacitor factory</b> — producing less than half of year-2000 output after restrictions were removed.',
    61: 'His struggle began when the government <b>removed restrictions</b> on imports — cheaper foreign parts flooded in.',
    63: '<b>Sushila\u2019s story</b>: the garment worker leaving home 7:30 am, returning 8:30 pm, seven days a week — globalisation\u2019s labour bill.',
    64: 'To win export orders, garment exporters <b>cut costs — mostly labour costs</b>: the pressure rolls downhill to the worker.',
    65: 'Long hours, night shifts, no overtime — the employment conditions behind "competitive" exports.',
    67: 'Workers like Sushila <b>no longer get organised-sector protection</b> — flexibilisation converts formal jobs into informal conditions.',
    68: '<b>People\u2019s organisations campaign</b> — for fairer labour rules and trade justice; pressure politics is globalisation\u2019s counterweight.',
    69: 'The chapter\u2019s final question is not "for or against" but <b>how to make globalisation fairer</b> — a policy question.',
    72: 'The definition to write in exams: <b>globalisation is the rapid integration of countries through trade, investment, technology and movement of people</b>.',
    73: 'The summary verdict: globalisation has benefited <b>well-off consumers and skilled producers</b>, while small producers and unskilled workers struggle — the uneven ledger.'
  };
})();
