/* Line-by-line decodes — Geography (keyed to textlines_geo.js block indexes) */
(function () {
  window.DECODE = window.DECODE || {};

  window.DECODE.geo1 = {
    0: 'The <b>full definition of a resource</b> — memorise all three conditions: <b>technologically accessible, economically feasible, culturally acceptable</b>. A thing in nature becomes a resource only when all three boxes tick.',
    1: 'Resources are <b>not free gifts of nature</b> — a classic assertion–reason trap. Humans <b>transform</b> natural material into resources; people themselves are part of the resource system.',
    2: 'Indiscriminate use caused the <b>three classic problems</b>: depletion for the greed of a few, accumulation in few hands (haves vs have-nots), and ecological crisis — global warming, ozone depletion, pollution, land degradation.',
    3: 'The <b>Brundtland definition of sustainable development</b>: development without damaging the environment, present needs without compromising <b>future generations</b>. Quote it verbatim in 3-mark answers.',
    4: 'The <b>Agenda 21</b> signed at Rio — a blueprint for sustainable development in the 21st century, with forests, biodiversity and climate at its heart.',
    6: 'The <b>resource–development mismatch</b>: Arunachal has water but no infrastructure; Rajasthan lacks water but has solar and wind development. Resources alone don\u2019t develop a region — <b>technology and institutions</b> do.',
    8: '<b>Colonialism was resource-driven</b> — rich resources attracted colonisers, who indiscriminately exploited them. This is why resource-rich nations can still be poor.',
    10: 'Gandhi\u2019s line at the edge of the 1987 Congress: "The earth provides enough <b>for everybody\u2019s need and not for anybody\u2019s greed</b>" — the moral core of the conservation section.',
    11: 'The <b>three steps of resource planning</b>: (i) survey–mapping–estimation, (ii) evolving technology to use resources, (iii) matching plans with national development goals.',
    12: '<b>Resource planning in India</b> spans Five-Year Plans, the Indian Bureau of Mines, Geological Survey of India and ISRO remote sensing — planning alone, though, fails without implementation and equity.',
    14: 'India\u2019s <b>relief profile</b>: plains 43%, mountains 30%, plateau 27%. The plateau holds most <b>minerals and fossil fuels</b>; plains support agriculture and cities; mountains give forests and water.',
    15: 'The <b>land-use categories</b> — forest, barren/waste, non-agricultural use, permanent pasture, tree crops, fallow (current: under 1 year; other: 1–5 years), net sown area. Learn the pairs for MCQs.',
    18: '<b>Land is a finite resource</b> — we live on it, farm it, build on it. 93% of India\u2019s area is surveyed; "wasteland" means land not usable without treatment, not useless land.',
    19: 'Why net sown area data stops at 93%: <b>occupied Jammu & Kashmir</b> areas were never surveyed — an exam favourite.',
    21: 'The <b>pattern the data shows</b>: forest area is far below the 33% policy target; some states (NE states, Arunachal) are forest-rich, others (Haryana, Punjab) have under 10%.',
    22: '<b>Permanent pasture has shrunk</b> yet India feeds a huge human and cattle population — the answer is higher yields on shrinking grazing land, and pressure on common lands.',
    23: '<b>Land degradation</b>: continuous use without conservation, plus deforestation, overgrazing, mining and quarrying. India has about <b>130 million hectares</b> degraded.',
    25: '<b>Over-irrigation causes waterlogging and salinity</b> — Punjab, Haryana, western UP. The solution is matching crop to water availability.',
    27: 'The <b>soil conservation toolkit</b>: shelter belts, grazing control, sand-dune stabilisation, terracing, strip cropping, contour ploughing, check dams — match each to its region for 5-mark answers.',
    28: '<b>Soil formation</b> takes millions of years; the factors: <b>relief, parent rock, climate, vegetation, time</b>. Soil is living — it holds organic matter, water, air.',
    30: '<b>Alluvial soil</b> — the most widespread and important. The entire northern plain is alluvial. Khadar (new, fine) vs bangar (old, kankar). Deficient in nitrogen and humus, rich in potash and lime.',
    32: '<b>Black (regur) soil</b> — black from lava flows, clayey, moisture-retentive (good for cotton), self-ploughing via deep cracks. Rich in iron, lime, magnesium; poor in nitrogen and phosphorus.',
    33: 'Black soil covers the <b>Deccan trap plateau</b>: Maharashtra, Saurashtra, Malwa, MP, Chhattisgarh — a map-work favourite.',
    35: 'Kankar (lime nodules) mark old alluvium; black soils crack wide in summer — the "self-ploughing" property that aerates them.',
    37: '<b>Red soil</b> gets its colour from <b>ferric oxide</b> diffused in crystalline igneous rocks. Generally less fertile, needs fertiliser.',
    38: '<b>Laterite soil</b> — from Latin <i>later</i>, brick. Forms in high rainfall with alternating wet–dry seasons; intense <b>leaching</b> strips humus and silica. Used as building brick; cashew grows on it.',
    39: 'Laterite regions are <b>prone to erosion</b> because the soil sits on slopes and hardens when exposed — hence terrace cultivation there.',
    40: '<b>Arid soil</b> — red to brown, sandy, saline, moisture-deficient; calcium-rich lower layer. Becomes productive when irrigated.',
    41: '<b>Forest (mountain) soils</b> — in hills with sufficient rainfall; valley soils are fertile; high-slope soils are thin, acidic, denuded.',
    43: '<b>Gully erosion</b> — running water cuts deep channels (gullies), making ravines like the <b>Chambal badlands</b>. Check dams stop them.',
    44: '<b>Sheet erosion</b> — water washes off the topsoil as a thin sheet over large areas; the silent killer of fertility.',
    45: 'The anti-erosion summary: <b>terrace cultivation</b> on slopes, contour bunding, strip cropping, shelter belts — each method matches a landform.'
  };

  window.DECODE.geo2 = {
    0: 'The chapter opens with the idea of <b>sharing the planet</b> — humans are only one of millions of species, yet the most dangerous one. India is one of the world\u2019s <b>megadiverse</b> countries.',
    1: 'India\u2019s biodiversity: about <b>8% of global species</b>, 47,000+ plant species, 90,000+ animal species — the numbers behind "megadiversity".',
    3: 'NCERT\u2019s classification: <b>normal species</b>, <b>endangered</b> (numbers falling to critical), <b>vulnerable</b> (declining, nearing danger), <b>rare</b> (small population, scattered), <b>endemic</b> (found in one area only), and <b>extinct</b> species.',
    4: 'Among the <b>critically endangered</b>: the pink-headed duck and the <b>Asiatic cheetah</b> — both gone from India.',
    6: '<b>Deforestation facts</b>: between 1951–1980 about 26,200 sq km of forest was diverted for river valley projects alone; the loss is staggering and continuing.',
    7: '<b>Vulnerable species</b> examples: the blue sheep, Asiatic elephant, Gangetic dolphin — declining but not yet critical.',
    8: '<b>Endemic species</b> examples: Maldive frog, Andaman teal, Nicobar pigeon — found nowhere else. Endemism makes habitat loss fatal.',
    10: 'Why the cheetah vanished: <b>habitat decline, prey loss, and hunting</b> — including for "sport" by princes and the British.',
    11: 'Even well-meaning forestry hurts: <b>monoculture</b> (teak, chir pine, eucalyptus) replaces diverse natural forest and fails local needs.',
    12: '<b>Development projects</b> — dams, mines, roads, towns — cleared vast forest since 1951. The 1950s Narmada Sagar and other projects alone submerged huge areas.',
    14: 'The colonial state nationalised forests, evicting communities; post-1947 the same forests fuelled <b>industrial and commercial demand</b>, not community need.',
    16: 'The causes of depletion in one line: <b>habitat destruction, hunting/poaching, over-exploitation, pollution, forest fires</b> — the standard 5-mark list.',
    17: 'Case study: the <b>Himalayan Yew</b> — a cancer-treating medicinal plant now endangered from over-harvesting for Taxol.',
    18: '<b>Project Tiger</b> — launched 1973 to save India\u2019s national animal. Tigers are an "umbrella species": protecting them protects whole ecosystems.',
    20: 'The conservation answer: a <b>national wildlife protection programme</b>, the <b>Indian Wildlife (Protection) Act 1972</b>, then national parks and sanctuaries across states.',
    21: 'The Act banned hunting, gave legal protection to habitats, and set up <b>national parks and wildlife sanctuaries</b> — central and state governments both acted.',
    26: 'Tiger threats: <b>poaching for trade, shrinking habitat, declining prey</b>. Project Tiger began with 9 reserves — now 50+.',
    27: 'Project Tiger\u2019s payoff: from under 2,000 tigers in the 1970s to nearly 3,000 today — among the world\u2019s most publicised conservation campaigns.',
    28: 'The 1980/1986 Act amendments protected <b>insects, butterflies and moths</b> too — even crocodiles, and banned trade in serpentine snake skins.',
    29: 'Forest types by ownership: <b>Reserved</b> (over half, state-managed), <b>Protected</b> (restricted village use), <b>Unclassed</b> (forests and wastelands, community or private).',
    30: 'Madhya Pradesh has the largest forest area; Mizoram the largest <b>percentage</b> under forest — area vs percentage, a classic MCQ pair.',
    32: 'Case study: five villages in Alwar declared <b>1,200 hectares Bhairodev Dakav "Sonchuri"</b> — villagers protecting blackbuck and nilgai by their own rules, no government help.',
    34: 'Sacred groves and revered trees — communities preserving nature through <b>faith</b>: peepal, banyan, neem protected for generations.',
    36: 'The <b>Chipko movement</b> — Himalayan villages (Reni, Gopeshwar) hugged trees to stop contractors\u2019 axes. It showed successful <b>community resistance</b> and the economic value of forest products.',
    37: '<b>Joint Forest Management (JFM)</b> — state-village partnership: communities protect degraded forest in exchange for forest produce and share in benefits.',
    38: 'The chapter\u2019s conclusion: environmental destruction and reconstruction are both driven by <b>people and institutions</b> — conservation succeeds when communities lead.'
  };

  window.DECODE.geo3 = {
    0: 'The paradox that opens the chapter: <b>three-fourths of the earth is water, yet only 2.5% is freshwater</b> — and most of that is frozen. India gets 4% of world rain but holds 16% of world population.',
    1: 'Renewable yet scarce: water renews through the hydrological cycle, but <b>overuse and pollution</b> outpace renewal — availability varies wildly over space and time.',
    3: '<b>Irrigated agriculture is the largest consumer</b> of India\u2019s water; with the population growing, farming must produce <b>more crop per drop</b>.',
    4: 'Scarcity is not only natural: a region can have ample water and still face shortage because of <b>unequal access and bad management</b> — the socio-economic view.',
    6: 'Multipurpose projects were imagined as the answer: <b>irrigation, flood control, water supply, electricity, navigation, fishery, tourism</b> — "the temples of modern India" in Nehru\u2019s words.',
    8: 'Dams continued an ancient tradition — but modern India built them huge, often displacing lakhs without fair resettlement.',
    10: 'The shift in thought: from concrete mega-projects toward <b>water conservation and management</b> — harvesting, watershed development.',
    13: 'A dam is defined as a <b>barrier across flowing water</b> that obstructs, directs or retards flow, creating a reservoir. <b>Bhakra on the Sutlej, Hirakud on the Mahanadi</b> — multipurpose examples.',
    15: 'Dams by height: <b>large/major dams</b> (and mini/micro) — but size is not virtue; siltation and displacement grow with scale.',
    17: 'The <b>Maikin Dai song</b> — villagers\u2019 prayer to the Damodar to reduce floods. Folk culture recorded dependence on rivers long before engineering.',
    18: '<b>Criticism of big dams</b>: they displace lakhs, silt up reservoirs, flood forests, and the benefits flow to industry and cities — not the displaced poor.',
    19: 'The irony NCERT underlines: <b>dams built to control floods have triggered floods</b> — by siltation and sudden release during heavy rain.',
    20: 'Irrigation changed <b>cropping patterns</b>: water-hungry crops like rice and sugarcane displaced millets — the water-intensity trap of Punjab\u2019s Green Revolution.',
    21: 'Government responses: the <b>Hydrology Project, watershed development, and (2009) the "Nirmal Ganga"/Clean Ganga missions</b> — access plus quality.',
    23: 'The Narmada debate: Sardar Sarovar would irrigate the drought-prone Kachchh–Saurashtra command — but only by submerging villages. <b>Benefits vs displacement</b> — the case that defined anti-dam politics.',
    26: 'Before big dams, India had a <b>sophisticated harvesting tradition</b> — each region its own system: khadins and tanks in Rajasthan, kulhs in Himachal, bamboo drip in the Meghalaya hills.',
    27: '<b>Rain-fed storage structures</b> — in arid regions, fields themselves stored water (khadin); embankments and lakes worked with the terrain.',
    28: 'In Bikaner, Phalodi and Barmer, almost every house had a <b>tanka</b> — an underground rooftop rainwater store. Rooftop rainwater harvesting is old science, not new fashion.',
    31: 'In hill and forest areas, <b>kulhs (Himachal) and bamboo drip irrigation (Meghalaya)</b> move water by gravity with astonishing economy.',
    33: '<b>Shillong, Meghalaya</b>: rooftop harvesting meets nearly the whole water demand of some localities — 15–25% of total water need despite heavy rain.',
    34: 'The decline of rooftop harvesting in western Rajasthan: <b>government tanker supply and Indira Canal water</b> made the tanka seem obsolete — a lesson in how policy can erase wisdom.',
    36: 'The Thar practice, revived: rainwater from rooftops to underground <b>tankas</b> for drinking — the book\u2019s answer to "water is a renewable but scarce resource".'
  };

  window.DECODE.geo4 = {
    0: 'India is an <b>agricultural country</b>: two-thirds of people depend on it, it feeds the nation and supplies industry raw material — the sector with the largest employment.',
    1: 'Farming types: <b>primitive subsistence</b>, <b>intensive subsistence</b>, <b>commercial</b> and <b>plantation</b> — learn the inputs and outputs of each.',
    2: '<b>Primitive subsistence farming</b> — slash and burn: clear a patch, cultivate, move on when fertility dies. "Slash and burn" is the definition to quote.',
    3: 'Local names of slash-and-burn: <b>jhumming</b> in the north-east, <i>bewar/divaha</i> in MP, <i>podu</i> in Andhra, <i>kumari</i> in Kerala — an MCQ favourite.',
    6: 'Subsistence vs commercial: <b>output is for the family in subsistence</b>; for the market in commercial. The same crop can be either — context decides.',
    7: 'A crop can be <b>food in one region, commercial in another</b> — e.g. rice (staple vs export). The boundary runs through economics, not botany.',
    8: '<b>Plantation farming</b>: single-crop, capital-intensive estates with processing and export — tea, coffee, rubber, sugarcane, banana. Introduced by the British.',
    10: '<b>Cropping seasons</b>: <b>rabi</b> (winter, Oct–Dec sow, Apr–Jun harvest), <b>kharif</b> (monsoon), <b>zaid</b> (summer short season) — memorise the months.',
    11: 'Rabi crops: <b>wheat, barley, peas, gram, mustard</b>; the Green Revolution made Punjab–Haryana–west UP its heartland.',
    13: 'Kharif crops: <b>rice, maize, jowar, bajra, tur, cotton, jute, groundnut</b> — sown with the monsoon\u2019s arrival.',
    14: '<b>Zaid</b> season: watermelons, cucumber, fodder — between rabi harvest and kharif sowing.',
    15: '<b>Rice</b> — staple of most Indians; kharif crop needing high temperature (25°C+) and rainfall 100 cm+ (or irrigation). Bengal–Assam to the coast; Punjab grows it with irrigation.',
    17: '<b>Wheat</b> — rabi; needs 50–75 cm rainfall, cool growing season and warm ripening. Punjab, Haryana, UP, MP, Rajasthan lead.',
    18: '<b>Bajra</b> grows on sandy and shallow black soils — Rajasthan is the top producer; jowar is rain-fed and the third major millet.',
    20: '<b>Maize</b> needs moderate temperature and rainfall; use of HYV seeds has spread it across seasons and states.',
    22: '<b>Oilseeds</b> cover ~12% of the cropped area: groundnut (half of oilseed output), mustard, coconut, sesamum, soybean, castor, linseed — India is a major producer yet imports edible oil.',
    23: 'Groundnut = kharif; mustard/linseed = rabi. Gujarat and Rajasthan lead oilseed states.',
    24: '<b>Tea</b>: deep, fertile, well-drained soil; warm, moist, frost-free climate with frequent showers — hence Assam and the Nilgiri–Darjeeling hills.',
    25: '<b>Pulses</b>: India is the world\u2019s <b>largest producer AND consumer</b> of pulses — the protein of the poor, grown in rotation to fix nitrogen.',
    27: '<b>Coffee</b>: Arabica, from Yemeni seeds Baba Budan brought — grown in the Baba Budan hills of Karnataka; Coorg, Chikmagalur, Nilgiris.',
    28: 'Horticulture: India is the <b>largest producer of fruits and vegetables</b> — mangoes of Maharashtra–AP–UP, oranges of Nagpur, bananas, grapes of Nashik.',
    30: 'India is second in vegetables output: peas, cauliflower, onion, cabbage, tomato — the "produce basket" facts that pepper MCQs.',
    31: '<b>Rubber</b>: equatorial climate, 200+ cm rainfall, Kerala\u2019s Malabar coast; calls and computer keyboards all carry it.',
    32: 'The <b>reform era</b>: after Independence, zamindari abolition, land ceiling, and Green + White Revolutions; the goal was raising output AND fairness.',
    33: 'The government\u2019s support kit: <b>Minimum Support Price (MSP)</b>, subsidies on power and fertiliser, crop insurance, credit — and the critique that subsidies burden budgets.',
    34: 'Revolutions named by colour: <b>Green</b> (wheat, HYV), <b>White</b> (milk, Operation Flood), <b>Blue</b> (fish), <b>Yellow</b> (oilseeds) — a famous MCQ list.',
    35: '<b>Fibre crops</b>: cotton, jute, hemp, silk — cotton the "king of fibres", jute the "golden fibre".',
    36: '<b>Cotton</b>: high temperature, light rain or irrigation, <b>210 frost-free days</b>, black cotton soil — the Gujarat–Maharashtra–Telangana belt.',
    37: 'Rubber, as the box reminds: list everyday items — tyres, bands, footwear — to feel the dependence.',
    38: 'Institutional support: <b>Kisan Credit Card</b>, weather bulletins (DD Kisan), agri-universities and mandi infrastructure — "tech + institutional reforms" is the 5-mark phrase.',
    39: '<b>Bhoodan–Gramdan</b>: Vinoba Bhave, Gandhi\u2019s spiritual heir, walked villages asking landowners to gift land to the landless — the "bloodless revolution".',
    40: 'At Pochampalli (Telangana), after Vinoba\u2019s appeal, <b>Ram Chandra Reddy offered 80 acres</b> — the Bhoodan movement was born.',
    41: 'Later, villages like Mendha Lekha (Maharashtra) declared <b>Gramdan</b> — whole-village land gifts making the village the owner.'
  };

  window.DECODE.geo5 = {
    0: 'The chapter opens in the everyday: <b>everything metal we touch is mineral-born</b> — pots, buses, trains, toothpaste sparkles. Minerals are the base of modern life.',
    1: 'Machines and power resources together run civilisation — <b>minerals + energy</b> are the twin foundations of industry.',
    3: 'A light bulb alone holds many minerals — tungsten filament, glass from silica, copper wires — the "dig deeper" box that makes the point concrete.',
    5: 'The <b>definition of a mineral</b>: "a homogenous, naturally occurring substance with a definable internal structure" — geologists\u2019 wording, quote-worthy.',
    6: '<b>Formation conditions</b>: the combination of elements, temperature and pressure decides which mineral forms — hence uneven geographic distribution.',
    8: 'Where minerals occur: <b>igneous and metamorphic rocks</b> (veins and lodes of tin, copper, zinc), <b>sedimentary rocks</b> (coal, iron in beds), <b>decomposition</b> (bauxite), <b>alluvial sands</b> (gold, monazite), and <b>ocean water</b> (salt, magnesium, bromine).',
    10: '<b>Ferrous minerals</b> — iron ore and manganese — account for <b>three-fourths of the value</b> of all metallic minerals India produces.',
    11: '<b>Iron ore types</b>: magnetite (finest, 70% iron), hematite (most used industrially, ~50–60%), limonite, siderite — export quality comes from the Bailadila and Bellary belts.',
    12: 'India\u2019s mineral fortune is <b>varied but unevenly spread</b> — the peninsular plateau rocks hold most of it; the Himalayas hold almost none (older rock was eroded away).',
    13: '<b>Bailadila</b> — "the hump of the ox" in Chhattisgarh — 14 peaks of iron ore with its own rail line to Vizag port for export.',
    14: '<b>Manganese</b>: mainly for steel and ferro-manganese alloys; also bleaching, disinfectants, insecticides. Odisha leads production.',
    16: 'Iron-ore state shares (2018–19): <b>Odisha leads</b>, then Karnataka, Chhattisgarh, Goa, Jharkhand — map work follows these belts.',
    17: '<b>Bauxite</b> — the ore of aluminium, formed by lateritic decomposition of aluminium-rich rocks. Mostly in the Amarkantak plateau and Odisha hills.',
    18: 'Why aluminium matters: <b>strength of metals + lightness + conductivity + resistance to corrosion</b> — from cookware to wires to aircraft.',
    20: '<b>Mica</b>: unmatched di-electric strength and insulation — hence every electrical industry uses it. India is the world\u2019s largest producer/exporter.',
    21: 'Mica\u2019s home: the <b>northern Chota Nagpur edge — Koderma–Gaya–Hazaribagh belt</b> of Jharkhand.',
    23: 'Mining\u2019s dark side: water contamination, waste dumping, <b>rat-hole mining deaths</b> in Meghalaya — the environmental cost block.',
    24: 'The answer: <b>stricter safety laws, environmental regulation, and public pressure</b> — conservation is a political task, not just technical.',
    25: 'The core problem: mineral formation is <b>geologically slow</b> — replenishment cannot match extraction. Minerals are <b>non-renewable and exhaustible</b>.',
    26: 'Consequences of continued extraction: <b>rising costs as mining goes deeper</b>, falling quality, and eventual exhaustion — the rationale for conservation and recycling.',
    28: '<b>Non-conventional sources</b>: solar, wind, tidal, geothermal, biogas, atomic — the renewable future vs coal\u2019s 67% hold on electricity.',
    29: 'Biomass still fuels rural kitchens — firewood, dung cakes, crop waste: over <b>70% of rural energy</b> comes from such traditional sources.',
    30: '<b>Coal formation</b>: compression of plant material over millions of years — Gondwana (98% of reserves, 200 million years old) vs tertiary coals.',
    31: 'Coal grades: <b>bituminous</b> is the popular commercial coal; metallurgical bituminous (coking) makes steel; anthracite is highest quality and rare in India.',
    32: 'Indian coal occurs in two rock series: <b>Gondwana (250–200 mya, 98% of reserves)</b> — Jharia, Bokaro, Raniganj, Talcher — and tertiary coals of the NE and J&K.',
    34: 'Coal is bulky and ash-heavy — so <b>thermal plants sit at the pitheads</b>, and transport economics shapes location.',
    35: 'Oil occurs in <b>anticlines and fault traps</b> — geologists read the map\u2019s folds to find it; Mumbai High, Gujarat and Assam are India\u2019s petroleum lands.',
    36: 'Offshore <b>Mumbai High</b> is the top producer; Digboi (Assam) is the oldest field — the map-work pair.',
    37: 'Natural gas: clean fuel for power, fertiliser and LPG — the energy source growing fastest in the gas pipeline network.',
    38: 'The <b>HVJ pipeline</b> (Hazira–Vijaipur–Jagdishpur, 1,700 km) carries gas to industry — energy geography you can draw.',
    39: '<b>Electricity</b>: thermal (coal, gas, oil), hydro, nuclear — the three-way split for every "classify power plants" question.',
    40: '<b>Hydropower</b> comes from fast-flowing water — renewable; India\u2019s potential is in the Himalayan rivers and peninsular plateaus (about 25% of installed capacity).',
    42: 'The problem with fossils: <b>serious environmental damage</b> — greenhouse gases and acid rain — pushing the case for non-conventional sources.',
    43: 'India\u2019s renewable luck: abundance of <b>sunlight, water, wind and biomass</b>, with the world\u2019s largest programmes for solar cooking and lighting.',
    45: '<b>Wind power</b>: the largest cluster from <b>Nagercoil to Kanyakumari in Tamil Nadu</b> — where the monsoon winds funnel.',
    46: '<b>Biogas</b> plants — municipal, cooperative, individual — use dung and waste; shrubs, farm waste and animal waste all become gas.',
    47: 'Biogas gives the farmer <b>twin benefits</b>: energy plus <b>improved manure</b> — the slurry is better fertiliser than raw dung.',
    48: '<b>Geothermal</b>: India has several hundred hot springs (Manikaran in HP, Puga valley in Ladakh) — usable for electricity and healing baths.',
    49: 'The closing argument: a <b>sustainable energy path</b> — judicious use of conventional plus a determined shift to renewables.',
    50: 'The slogan to quote: <b>"energy saved is energy produced"</b> — conservation is the cheapest source of all.',
    51: '<b>Tidal energy</b>: the Gulf of Khambhat, Gulf of Kachchh and the Sundarbans deltas have the ranges to run tidal power — the final map-fact of the chapter.'
  };
})();
