/* Line-by-line decodes — History (keyed to textlines_hist.js block indexes) */
(function () {
  window.DECODE = window.DECODE || {};

  window.DECODE.hist1 = {
    0: 'The chapter opens with <b>Frédéric Sorrieu\u2019s 1848 prints</b> — his dream of a world of "democratic and social Republics": distinct nations as separate figures, joined by a banner of fraternity.',
    1: 'In the foreground lie the <b>shattered remains of absolutism</b> — Sorrieu\u2019s message: the age of kings is over.',
    4: 'From heaven, Christ and the saints bless the scene — in 1848, even radical republicans imagined fraternity in Christian terms.',
    5: 'The ideas Sorrieu drew — nation, citizenship, self-government — were new then; this chapter traces how they <b>remade Europe and the world</b>.',
    6: 'In a modern state, sovereignty rests with the <b>people</b>; in a <b>nation-state</b>, the majority of citizens — not just its rulers — share a common identity and rule themselves.',
    7: '<b>Ernst Renan, "What is a Nation?" (Sorbonne, 1882)</b>: a nation is the culmination of a long past of sacrifices and glory — a shared memory and a shared will.',
    8: 'Renan\u2019s famous line: nations are a <b>"daily plebiscite"</b> — the people renew their togetherness every day, and forgetting past divisions is part of nation-building.',
    9: 'The <b>French Revolution (1789)</b> transferred sovereignty from the monarchy to <b>the citizens</b> — the political spark of modern nationalism.',
    10: 'Revolutionary symbols: the <b>tricolour</b> replaced the royal standard; new hymns, oaths and a centralised administrative system bound the nation.',
    11: 'A common language was imposed — <b>Paris French</b> replaced regional dialects; uniform weights, measures and laws followed.',
    12: 'Jacobin clubs spread revolutionary ideas; <b>French armies carried nationalism abroad</b> — Holland, Switzerland, Italy — as "liberation" that turned to occupation.',
    14: 'The <b>Napoleonic Code (1804)</b>: equality before law, abolition of privilege, secured property — but in conquered lands it came with taxation and conscription.',
    16: 'Middle-class Europeans initially welcomed Napoleonic reforms — <b>businessmen and small producers</b> saw opportunity in uniform laws.',
    17: 'The backlash: in places like Tyrol and Spain, French rule met <b>armed popular resistance</b> — imposed "modernity" bred national resentment.',
    20: 'In 1815 <b>Germany, Italy, Switzerland</b> were patchworks of kingdoms, duchies and cantons — the Habsburg empire alone stitched 11 peoples together.',
    22: 'The Habsburg patchwork: Magyar-speakers in Hungary amid Germans, Bohemians, Slovaks, Slovenes, Croats — the ethnic mosaic nationalism would crack.',
    23: 'The dominant class of Europe: a <b>landed aristocracy</b> united by family ties and French manners — but numerically tiny.',
    24: 'To the west, land was farmed by tenants and small owners; to the east, vast estates with serfs — the social base differed across Europe.',
    28: 'Nationalism was allied with <b>liberalism</b>: the nation built on individual freedom, equality before law, constitutional government.',
    29: 'But political liberalism <b>did not mean universal suffrage</b> — property and gender limits kept parliaments narrow.',
    30: '<b>Economic liberalism</b>: free markets and abolition of tariff barriers — the <b>Zollverein</b>, the German customs union of 1834, its great monument.',
    31: 'The 1833 merchant\u2019s journey: dozens of customs posts, a dozen currencies, a Bremen-kg vs a Frankfurt-kg — barriers strangled German trade.',
    33: 'After 1815, conservative regimes modernised cautiously — <b>modern army, efficient bureaucracy</b> — but resisted democracy and nationalism.',
    35: 'The <b>Congress of Vienna (1815)</b>: Britain, Russia, Prussia, Austria redrew Europe to <b>undo the Napoleonic changes</b> and restore monarchy.',
    38: 'Vienna\u2019s settlements: the Netherlands (with Belgium) built in the north, Prussia strengthened on the Rhine, <b>39 German states</b> in a loose German Confederation.',
    39: 'The regimes of 1815 were <b>autocratic</b> — censorship and secret police stamped out criticism; the plaque\u2019s question: "the most important question of the day" was constitutionalism.',
    42: 'Fear of repression drove liberal-nationalists <b>underground</b> — into clubs and secret societies preparing the revolutions of 1848.',
    43: '<b>Giuseppe Mazzini</b> (born 1807, Genoa): Italian revolutionary, founder of <b>Young Italy and Young Europe</b> — nationalism as a democratic, popular creed.',
    44: 'Mazzini\u2019s belief: nations are the <b>natural units of mankind</b> — Italy must rise as one democratic republic; Metternich called him "the most dangerous enemy of our social order".',
    46: 'The first upheaval: <b>France, July 1830</b> — the Bourbon king overthrown, a constitutional July monarchy installed; Belgium broke from the Netherlands.',
    47: 'The <b>Greek war of independence (1821–32)</b> — the mobilising event for European elites; poets and artists championed Greece against Ottoman rule.',
    48: '<b>Lord Byron</b> organised funds and fought — and died — in Greece: philhellenism as Europe\u2019s romantic cause.',
    49: 'Nationalism grew not only by war and statecraft but by <b>culture</b> — art, poetry, stories and music expressed the national spirit.',
    50: '<b>Delacroix\u2019s "Liberty Leading the People"</b> (1830): the French nation as Liberty carrying the tricolour — romantic nationalism on canvas.',
    51: 'The German philosopher <b>Herder</b>: true German culture lay in the <b>volk</b> — folk songs, poetry and dance; culture as nation-builder.',
    52: 'The <b>Grimm Brothers</b> collected folktales to claim a German cultural identity; their 33 volumes of tales were declared the nation\u2019s authentic voice.',
    54: 'Folklore and vernacular language were political weapons: <b>Karol Kurpinski</b>\u2019s operas celebrated Polish struggle when Poland itself was partitioned.',
    55: 'Language carried nationalism — Polish suppressed after partition returned in print and song: culture kept the nation alive without a state.',
    56: 'The clergy\u2019s fight for Polish: priests and bishops jailed or sent to Siberia — even the Church became a nationalist actor.',
    58: '<b>The 1830s: economic hardship</b> — huge population rise, rural poverty, unemployment in cities; the grounds for 1848.',
    60: '<b>1848 in France</b>: food shortage and unemployment brought Paris to barricades; the National Assembly proclaimed a Republic with <b>universal male suffrage</b>.',
    63: 'The <b>Silesian weavers\u2019 revolt (1845)</b> — Heine\u2019s poem "The Song of the Silesian Weavers" captured weavers doomed by cheap British machine-made cloth.',
    65: 'Parallel to the poor\u2019s revolts, the <b>educated middle classes</b> pushed for national unification and constitutional freedom — 1848 was two revolutions at once.',
    67: 'In the German regions, 18,000 political associations pressed for a <b>German parliament</b> — elections were held, and 831 deputies met at <b>Frankfurt</b>.',
    68: 'The Frankfurt Parliament offered the crown to <b>King Friedrich Wilhelm IV of Prussia</b> — he refused "a crown from the gutter" of elected commoners.',
    69: 'The Frankfurt assembly was dispersed by troops — <b>liberal nationalism defeated in 1848</b>, monarchy and military restored.',
    71: 'The women\u2019s question inside the liberal revolution: Carl Welcker\u2019s answer confined women to <b>"the home, children, family"</b> — equality stopped at the door.',
    74: 'The anonymous woman\u2019s retort: if even the stupidest cattle-herder has rights, why not women? — the voice 1848 ignored.',
    76: 'The outcome of 1848: conservatives won, but were forced to <b>abolish serfdom and bonded labour</b> in the Habsburg lands and Russia — feudalism had lost.',
    78: 'After 1848, nationalism <b>allied with conservatism, not democracy</b> — unification would come from above, led by monarchies and armies.',
    79: 'Prussia took leadership of German unification; <b>Chief Minister Bismarck</b> with the Prussian army and bureaucracy did it — by "blood and iron".',
    81: '<b>18 January 1871, Versailles</b>: the proclamation of the German Empire — the Prussian King Wilhelm I as <b>Kaiser</b> of a united Germany.',
    82: 'Anton von Werner\u2019s "Mirrors at Versailles": Bismarck in white at the centre — the painting of unification-from-above.',
    83: '<b>Italy\u2019s fragmentation</b>: like Germany, a patchwork — during the middle years only <b>Sardinia-Piedmont</b> was ruled by an Italian princely house.',
    84: 'Mazzini\u2019s programme of the 1830s failed in 1848-49 — the initiative passed to <b>Sardinia-Piedmont</b> under its ruler and his minister <b>Cavour</b>.',
    87: '<b>Count Camillo de Cavour</b> — the diplomatic architect: he allied with France to oust Austria from northern Italy (1859).',
    88: 'Then <b>Garibaldi</b>: in 1860 his Red Shirts marched into the Kingdom of the Two Sicilies and won the south — handing it to the King of Sardinia-Piedmont.',
    90: 'The nation-state model, some argue, is <b>Great Britain</b> — built over centuries, not in one revolution.',
    92: 'The English parliament seized power from the monarchy in <b>1688</b> — the "Glorious Revolution" that made Britain a parliamentary nation.',
    93: 'The <b>Act of Union 1707</b> fused England and Scotland into "Great Britain" — Scottish Highland clans repressed after 1745 rebellion.',
    94: '<b>Ireland</b>: a deeply Catholic country was forcibly incorporated into the UK — nationalism there would burn for two centuries.',
    95: 'The symbols of new Britain: <b>Union Jack, the national anthem, the English language</b> — a British nation built over older identities.',
    97: 'The Italian unification cast: Mazzini the prophet, Cavour the diplomat, Garibaldi the soldier, Victor Emmanuel II the king — the cartoon of the "boot".',
    99: 'The famous English caricature: Garibaldi helping Victor Emmanuel II "pull on the boot" of Italy — unification completed around 1870 with Rome.',
    100: 'The <b>female allegory</b>: artists personified the nation as a woman — Marianne (France) with the tricolour; not any real woman, an abstract of the nation.',
    102: '<b>Germania</b>: the German allegory — a fallen crown at her feet, the German oak, the breastplate of strength; hung from the Frankfurt Parliament\u2019s hall in 1848.',
    104: 'Germania\u2019s symbols decoded: <b>broken chains = freedom won</b>, breastplate = strength, olive branch = peace — symbolism questions are exam favourites.',
    108: 'By the late 19th century, nationalism <b>allied with imperialism</b> — the two would together produce the First World War.',
    109: 'The Balkans — the most serious source of tension after 1871: Ottoman decline + Slavic nationalities = the "powder keg of Europe".',
    111: 'Slavic struggles in the Balkans became fights the <b>great powers backed for their own gain</b> — Russia, Germany, England, Austria-Hungary all manoeuvring.',
    113: 'The chapter\u2019s warning: <b>nationalism + imperialism led Europe to disaster in 1914</b> — the First World War.'
  };

  window.DECODE.hist2 = {
    0: 'The chapter\u2019s frame: in Europe nationalism came with the nation-state; <b>in India, anti-colonial nationalism</b> — the nation born in the fight against British rule.',
    1: 'Congress under Gandhi tried to unite groups — "our" nation bridging caste, religion, region; every class and community joined with its own aspiration.',
    4: 'WWI\u2019s burden on India: <b>war loans and increased taxes</b>, forced recruitment in villages — the war years primed mass anger.',
    5: 'The war brought hardship then <b>disappointment</b>: the expectation that hardships would end was dashed, and <b>influenza (1918-19)</b> killed 12–13 million.',
    6: '<b>Gandhi returned in January 1915</b> from South Africa — his method already tested: satyagraha.',
    8: 'The satyagrahi\u2019s rule: <b>no vengeance, no aggression — appeal to the conscience of the oppressor through truth</b>.',
    9: '<b>Three early satyagrahas</b>: <b>Champaran 1917</b> (indigo), <b>Kheda 1917-18</b> (crop failure, tax relief), <b>Ahmedabad 1918</b> (mill workers) — Gandhi\u2019s Indian apprenticeship.',
    10: 'In 1919, the nationwide satyagraha against the <b>Rowlatt Act</b> — passed on colonial recommendations to crush political "conspiracy"; it allowed detention without trial.',
    11: '6 April 1919 hartal: rallies, railway strikes — the Rowlatt Satyagraha took the struggle beyond a single issue to a <b>mass confrontation</b>.',
    15: '<b>Jallianwala Bagh, 13 April 1919</b>: General Dyer blocked the exits and fired on a peaceful crowd — the atrocity that radicalised a generation.',
    16: 'The aftermath: north Indian towns in fury, brutal repression — Gandhi called off the movement as it turned violent.',
    17: 'The Rowlatt movement was widespread but <b>still city-limited</b> — the next step had to reach the villages.',
    18: 'The <b>Khilafat issue</b>: the Ottoman Sultan (Khalifa) dispossessed after WWI — a Muslim grievance Gandhi united with his own, launching a united mass movement.',
    19: 'In <b>Hind Swaraj (1909)</b>, Gandhi\u2019s claim: British rule survived on Indian cooperation — <b>withdraw cooperation and it collapses</b>.',
    20: 'The Non-Cooperation programme: <b>surrender of titles</b>, boycott of civil services, courts, schools, foreign goods — a step-by-step unmaking of cooperation.',
    21: 'Gandhi and Shaukat Ali toured through 1920; Calcutta (Sept) and <b>Nagpur (Dec 1920)</b> Congress sessions launched the Non-Cooperation-Khilafat Movement.',
    23: 'The cities in movement: thousands of students left schools, lawyers gave up practices, council elections boycotted — the middle-class wave.',
    24: 'The economic front: <b>foreign cloth boycotted, bonfires lit; imports halved</b> between 1921–22; Indian mills\u2019 cloth sales soared.',
    25: 'Why the cities slowed: <b>khadi was costly</b>; no alternative Indian institutions for the boycotted courts and schools; and the movement had no jobs for those who left.',
    26: 'The countryside: at <b>Awadh, Baba Ramchandra</b> led tenants against talukdars — rent reduction, no begar, social boycott of oppressive landlords.',
    28: 'The <b>Oudh Kisan Sabha (October 1920)</b> — Jawaharlal Nehru and others joined: over 300 branches in a month, linking village grievances to the national movement.',
    30: '<b>Begar defined</b> — unpaid forced labour. The vocabulary block every exam uses.',
    32: 'The <b>Bardoli Satyagraha, 1928</b>: Vallabhbhai Patel led the refusal of a 22% revenue hike — "Bardoli" became a national synonym for determined peasant resistance.',
    34: 'In the Gudem Hills of Andhra, <b>Alluri Sitaram Raju</b> led tribals — colonial forest laws closed their lands; he claimed special powers and praised Gandhi — but chose arms.',
    36: 'The Gudem rebels attacked police stations and died fighting — militancy where satyagraha could not reach.',
    38: 'The tribals\u2019 own swaraj: a world without forest laws and exploitative traders, where Gudem fighters thought Gandhi\u2019s name made them bulletproof.',
    40: '<b>Chauri Chaura, February 1922</b>: a peaceful demonstration burned a police station with policemen inside — Gandhi, shocked by violence, <b>called off Non-Cooperation</b>.',
    41: 'Within the Congress, the Swarajists (C.R. Das, Motilal Nehru) wanted to contest council elections; others wanted to keep out of the colonial machine.',
    43: 'The Tory government\u2019s <b>Statutory Commission (1927)</b>, all-white, to review India\u2019s constitutional future — "Simon Go Back" echoed nationwide.',
    44: 'Lord Irwin\u2019s offer of <b>dominion status and a Round Table Conference</b> failed to satisfy; the Lahore Congress (Dec 1929) demanded <b>complete independence (Purna Swaraj)</b>.',
    46: 'The radicals and liberals dropped away; Gandhi had to find a demand that touched everyone — <b>salt</b>: taxed, needed by rich and poor alike.',
    47: '<b>31 January 1930 — the Salt March</b>: from Sabarmati to Dandi, 240 miles, 24 days, 78 followers — breaking the salt law with a fistful of salt on 6 April.',
    49: 'The <b>Civil Disobedience Movement</b> begins: break the salt law, refuse taxes, defy colonial authority — disobedience as mass statement.',
    51: 'Thousands broke the salt law; <b>Abdul Ghaffar Khan was arrested</b> (beatings in Peshawar), Gandhi detained weeks later — repression fed the movement.',
    52: 'The government\u2019s iron hand: peaceful satyagrahis beaten, 90,000 arrested — the world watched through press reports.',
    53: 'Gandhi-Irwin Pact (March 1931): Gandhi paused the movement to attend the <b>Second Round Table Conference</b> — it failed, and the movement resumed.',
    56: 'The rich peasants of <b>Gujarat and Bihar (Patidars, Jats)</b> joined Civil Disobedience to fight the revenue hike — their fight was for the full abolition of the revenue settlement.',
    57: 'The poorer peasants wanted <b>rent remission</b>, not just revenue cuts — Congress, wary of upsetting landlords, could not promise it.',
    59: 'The young revolutionaries: <b>Bhagat Singh and Batukeswar Dutta, April 1929</b> — a bomb in the Assembly "to make the deaf hear"; Inquilab Zindabad became the cry.',
    60: 'Bhagat Singh\u2019s ideals: freedom as the birthright of all; his popularity terrified the British, who hanged him in 1931.',
    61: 'The business classes: <b>FICCI (1927)</b>, Purshottamdas Thakurdas and G.D. Birla — initially strong Civil Disobedience supporters against colonial trade restrictions.',
    63: 'After the Round Table failure, business groups withdrew — worried by militant socialism spreading within the movement.',
    64: 'The industrial working classes stayed mostly out — the Congress <b>did not include labour\u2019s radical demands</b> to keep industrialists on board.',
    66: 'The Congress\u2019s calculation: workers\u2019 demands would divide the anti-imperial front — a coalition choice with a cost.',
    69: 'Gandhi\u2019s summons drew thousands of <b>women</b> — processions, salt-making, picketing; but the movement made <b>no change to women\u2019s domestic role</b> — the limits of participation.',
    71: 'For the first time, women moved into public life on this scale — Gandhi\u2019s own insistence that they were partners, not symbols.',
    72: 'Women\u2019s organisations demanded reserved seats and equal franchise — <b>the 1931 Karachi session resolution</b> committed the Congress to gender equality.',
    73: '<b>Dr B. R. Ambedkar</b>: organised Dalits into the Depressed Classes Association (1930) — demanding separate electorates, clashing with Gandhi at the Round Table Conference.',
    74: 'The <b>Poona Pact (September 1932)</b>: instead of separate electorates, the Depressed Classes got <b>reserved seats</b> in provincial legislatures — signed after Gandhi\u2019s fast.',
    75: 'Muslim political organisations were <b>lukewarm</b> to Civil Disobedience — large sections felt excluded from a Congress appearing Hindu-majority in culture.',
    76: 'Efforts to renegotiate the Congress-League alliance (1927) stalled on <b>seat-sharing</b>; Muhammad Ali Jinnah\u2019s fourteen points (1929) were answered with silence.',
    79: '<b>Sir Muhammad Iqbal\u2019s 1930 presidential address</b>: the principle of democracy suited only consolidated majorities — the seed of the two-nation idea.',
    82: 'Iqbal\u2019s communitarian argument: India\u2019s units are communities, not individuals — Muslims as a separate community within (and later, without) India.',
    84: '<b>The Sense of Collective Belonging</b> — the last section: how Indians came to feel "we" — through image, history, folklore, icon and song.',
    85: 'Collective belonging grew through <b>shared struggles</b> — but also through cultural imagination: figures everyone could love.',
    86: 'The image of <b>Bharat Mata</b>: first painted by <b>Abanindranath Tagore</b> — ascetic, radiant, dispensing learning and food; the nation as mother.',
    87: '<b>Vande Mataram</b> (Bankim\u2019s Anandamath) — sung through the Swadeshi movement: the anthem of the imagined nation.',
    88: 'Folklore revival: nationalists collected songs, tales and legends to restore the "authentic" national culture that print would spread.',
    91: 'Hindutva history-telling: the past as Hindu golden age followed by decline — a memory politics that alienated others.',
    93: 'The swadeshi flag design: <b>eight lotuses (eight provinces)</b> and a crescent — symbolism meant to include, read by some as excluding.',
    94: '<b>Reinterpretation of history</b>: a glorious ancient past, a medieval decline, national pride rebuilt on the past — powerful, and contested.',
    96: 'The problem with a Hindu-tinged nationalism: Muslims, Christians and others felt cast as outsiders — unity\u2019s cultural project had its shadow.',
    100: '<b>8 August 1942, Bombay — the Quit India resolution</b>: Gandhi\u2019s "Do or Die" — the final mass upsurge.',
    101: 'Quit India brought in <b>thousands of ordinary people</b> — workers, peasants, students — after the leaders were jailed in a day.'
  };

  window.DECODE.hist3 = {
    0: 'The chapter\u2019s method: trace <b>globalisation\u2019s long history</b> — from silk routes to Bretton Woods to the present.',
    1: 'All through history societies interlinked — via trade, travel, migration, conquest and religion; "global" is older than we think.',
    2: 'The spread of <b>disease-carrying germs</b> is ancient globalisation\u2019s darkest channel — it would remake the Americas.',
    4: 'The <b>silk routes</b> — pre-modern trade and cultural exchange, linking Asia with Europe and North Africa; goods, ideas, religions (Buddhism to China) all travelled.',
    5: 'Christianity and Islam travelled the same routes — merchants, pilgrims and missionaries carried faith as cargo.',
    6: 'Food globalisation: <b>potatoes, maize, tomatoes, chillies, sweet potatoes</b> — American crops that reshaped diets everywhere after the sixteenth century.',
    7: 'Europe\u2019s poor ate better because of American potatoes — "common foods" carry the history of empires.',
    9: 'The pre-modern world <b>shrank in the sixteenth century</b> when European sailors found sea routes to the Americas — a genuinely global economy began.',
    10: 'America\u2019s isolation ended: goods, germs, people and metal (silver!) began flowing both ways across the oceans.',
    11: 'The conquest of America was won decisively by <b>germs — smallpox and measles</b> — killing millions who had no immunity.',
    12: 'The <b>Irish potato famine (1845-)</b>: Europe\u2019s own food-globalisation tragedy — dependence on one crop met one disease.',
    14: 'Until the 18th century, <b>China and India were the world\u2019s richest</b> economies — Asia\u2019s fall came only with the rise of Atlantic trade.',
    15: '<b>Slavery</b>: the triangular trade — manufactured goods from Europe to Africa, enslaved people to the Americas, plantation goods back to Europe.',
    16: 'Economists name <b>three flows</b> in the 19th-century world economy: goods, labour and capital — the framework of this chapter\u2019s middle section.',
    17: 'The story of food: 18th-century Britain, enclosed land and a <b>growing urban population</b> — grain imports became a political question.',
    18: 'The <b>Corn Laws</b> restricted food imports to protect British landlords\u2019 rents — until industrialists and urban dwellers forced their repeal.',
    19: 'After the Corn Laws fell, food poured in cheaper — <b>British living standards rose as agriculture spread overseas</b>: the global division of labour begins.',
    20: 'Lands were cleared, then <b>railways built to port</b> — settler agriculture (America, Australia, New Zealand) plugged into world markets.',
    21: '<b>50 million Europeans emigrated</b> to America and Australia in the 19th century — one of history\u2019s great migrations.',
    24: 'The arriving worker\u2019s experience: back-breaking work, but <b>higher wages and better living standards</b> than at home — globalisation\u2019s draw.',
    26: '<b>Technology\u2019s role</b>: railways, steamships, the telegraph — the 19th century\u2019s transport-and-communication revolution.',
    27: 'The trade in meat: refrigerated ships meant <b>meat from America and Australia reached Europe fresh</b> — the poor of Europe could eat meat.',
    29: 'Trade flourished but <b>not equally</b> — the late 19th century was also the age of colonisation: markets were often coerced.',
    32: 'The late 19th century: vast colonial additions by <b>Britain and France</b>, Belgium and Germany joining the scramble — Africa carved up.',
    34: 'Geographical exploration paved conquest: <b>Stanley and the Congo</b> — maps, guns and flags in one expedition.',
    36: 'The <b>Rinderpest in Africa (1890s)</b>: a cattle plague that killed 90% of the herds — the case study of a global germ reshaping a continent.',
    38: 'Why Europe wanted Africa: resources and markets — <b>minerals, land and trade routes</b>.',
    39: 'The loss of cattle destroyed African livelihoods — <b>labour for mines and plantations</b> was all that remained: rinderpest as imperial recruiter.',
    42: 'The <b>indentured labour system</b> from India: contracts, migration to Caribbean, Mauritius, Fiji — the second great labour flow.',
    43: 'Indian indentured workers came mostly from <b>eastern UP, Bihar, central India and the Tamil districts</b> — pushed by distress, pulled by agents.',
    45: '<b>Indentured labour defined</b>: a bonded labourer under contract — the vocabulary of the chapter.',
    46: 'Tamil migrants went to Ceylon and Malaya; indentured workers became a <b>global Indian diaspora</b>.',
    47: 'The verdict: indenture was "a <b>new system of slavery</b>" — hard labour, legal bondage, brutal conditions.',
    48: 'Cultural fusion in diaspora: the <b>Hosay (Muharram) carnival in Trinidad, chutney music, the "Rastafarian" hat from Trinidad</b> — the global world\u2019s cultural making.',
    50: 'Most indentured workers <b>stayed on after contracts ended</b> — communities that still speak Bhojpuri and Tamil across the oceans.',
    51: 'From the 1900s, <b>Gandhi and Indian nationalists opposed indenture</b> — abolished in 1921: anti-colonial politics meets global labour.',
    52: 'Plantations needed <b>capital</b>: banks and financial houses funded global agriculture — the third flow, of capital.',
    54: 'Industrialisation reversed trade: <b>India\u2019s fine cotton exports collapsed</b>, and India became a supplier of raw cotton to British mills.',
    58: 'India\u2019s raw cotton exports to Britain: from <b>5% to 35% between 1812 and 1871</b> — the colony\u2019s restructuring in one figure.',
    59: 'British manufactures flooded India; food grains and raw materials flowed out — <b>a classic colonial pattern</b>: an open economy serving the metropole.',
    60: '<b>Multilateral settlement</b>: India\u2019s deficits with some countries were settled by surpluses with others through Britain — the invisible mechanism of empire.',
    62: 'The <b>First World War (1914-18)</b>: Central Powers vs Allied Powers — the first modern industrial war.',
    63: 'Machine guns, tanks, aircraft, chemical weapons — <b>9 million dead, civilians scarred</b>: industrial war\u2019s harvest.',
    64: 'Working-age men died or were maimed — societies of widows and orphans; labour shortage reshaped economies.',
    66: 'Post-war Britain struggled: it had financed allies, lost markets and its pre-war position — <b>war debt</b> burdened recovery.',
    67: 'The war boom then bust: wartime demand masked weakness; agriculture\u2019s over-expansion crashed prices after 1920.',
    68: 'Wheat\u2019s story: expanded acreage in the war, then collapse — the farm crisis that fed the Depression.',
    70: '<b>Henry Ford</b>: the assembly line adapted from a Chicago slaughterhouse — the car built by conveyor; 1 car every 3 minutes by 1914.',
    71: 'The assembly line\u2019s human cost: no worker could delay the belt — <b>machine-paced labour</b>.',
    72: 'Ford doubled the wage to $5 a day to cut turnover — workers could now buy the cars they made: <b>mass production meets mass consumption</b>.',
    73: '<b>Fordism</b> spread; consumer demand for cars, refrigerators, washing machines boomed in 1920s America — the decade of instalment-fuelled prosperity.',
    75: 'In 1923, the US resumed exporting capital and became the world\u2019s lender — the boom\u2019s fragile foundation.',
    76: 'The <b>Great Depression (1929 – mid-1930s)</b>: collapse of production, employment, incomes and trade across the capitalist world.',
    77: 'Causes stacked: overproduction, agricultural collapse, and a <b>web of loans</b> that transmitted the crash worldwide.',
    78: 'The mid-1920s credit house of cards: <b>US loans to Europe</b> financed recovery — and dependent economies.',
    80: 'When US lenders recalled loans, <b>the crash went global</b> — banks failed, currencies crashed, exports collapsed worldwide.',
    81: 'The US itself was hit hardest in industry: <b>unemployment reached about 17 million</b>.',
    83: 'The Depression reached India through <b>trade</b> — jute and wheat prices collapsed — proof the empire had welded India into the world economy.',
    86: 'The Bengal jute growers: the raw jute price crashed, but <b>rents and debts did not</b> — peasant impoverishment deepened.',
    87: '<b>Keynes\u2019 observation</b>: India\u2019s gold exports (peasants selling gold to pay dues) actually steadied the world economy — the colony as shock absorber.',
    89: 'The Second World War: <b>60 million dead, 3% of the world\u2019s population</b> — and cities rebuilt on a new plan.',
    91: 'Two lessons shaped reconstruction: (1) <b>mass unemployment and instability</b> must never return; (2) economies are interdependent — institutions must manage that.',
    94: '<b>Bretton Woods, New Hampshire (1944)</b>: the <b>IMF and the World Bank (IBRD)</b> founded — the twin pillars of the post-war economy.',
    95: 'The <b>international monetary system</b> linking currencies — with the dollar anchored to gold, its design dominated by the Western allies.',
    96: 'Bretton Woods inaugurated an era of <b>unprecedented trade and income growth</b> in the industrial West (1950s–60s).',
    99: 'As Europe and Japan rebuilt, they needed the developing world\u2019s raw materials less — and sold manufactures to it more.',
    101: 'MNCs of the US and Europe invested abroad — <b>the developing world\u2019s resources and markets in the post-war web</b>.',
    102: 'The demand for a <b>NIEO — New International Economic Order</b>: real control over natural resources, better prices, fairer trade for the developing world (UN, 1974).',
    104: 'High import tariffs of Western powers hurt developing exporters — the NIEO\u2019s chief grievance.',
    105: 'From the late 1970s, unemployment and crisis returned to the West — the Bretton Woods era\u2019s stability ended.',
    106: 'The financial system changed: <b>markets freed, capital moved globally</b> — the modern face of globalisation emerges.',
    108: 'Low wages in China and Asia attracted production — the <b>world factory</b> shift that defines our era.'
  };

  window.DECODE.hist4 = {
    0: 'The chapter opens by making print strange: a world without paper is unimaginable — yet print has a <b>500-year history</b> that shaped the modern mind.',
    2: 'The journey: <b>East Asia (China, Japan)</b> → <b>Europe and Gutenberg</b> → the print revolution → the reading mania → <b>India</b> and censorship.',
    4: 'The earliest print: <b>China, Japan, Korea</b> — handprinting on paper from about <b>594 CE</b> in China.',
    5: 'For centuries, the Chinese imperial state was print\u2019s biggest producer — the <b>civil service exam</b> system created a huge textbook demand.',
    6: 'By the 17th century, urban China printed everything — fiction, poetry, scholars\u2019 works — print as popular culture, women writers included.',
    8: 'Buddhist missionaries carried handprinting to <b>Japan</b> — the oldest printed book, the <b>Buddhist Diamond Sutra (868 CE)</b>, is Chinese.',
    10: '<b>Kitagawa Utamaro</b> (Edo, 1753): his woodblocks of "The Ten Hours of the Yoshiwara" show print\u2019s artistic power in Japan.',
    12: 'In medieval Europe, parchment and vellum were costly — <b>11th-century Chinese paper</b> reached Europe via the silk route and made manuscripts possible.',
    13: 'Book fairs multiplied; booksellers exported manuscripts — yet <b>hand-copying could not meet demand</b>.',
    15: 'The need: quicker, cheaper reproduction — the demand that Gutenberg\u2019s press answered.',
    18: '<b>Gutenberg (son of a merchant, Mainz, Germany)</b>: goldsmith by training, perfected the press by <b>1448</b>; first printed book: the <b>Bible</b>.',
    19: 'Between 1450 and 1550, presses spread across Europe — the print revolution begins.',
    22: 'Books now printed <b>250 sheets an hour</b> — vs a scribe\u2019s page; print industrialised the word.',
    26: 'The <b>print revolution</b>: a new reading public emerged as the cost of books collapsed — access spread beyond the elite.',
    27: 'A shift in the act of reading itself: from <b>public recitation to private, silent reading</b> — the printed book changed minds\u2019 relationship to texts.',
    29: 'The transition was not simple: the "literates" were few; oral culture persisted — <b>printers began publishing ballads and folktales for the illiterate</b>.',
    31: 'Print enabled the <b>Protestant Reformation</b>: <b>Martin Luther\u2019s Ninety Five Theses (1517)</b> printed and spread within weeks — a religious revolution through print.',
    33: 'Fear of print: if anyone could print and read anything, <b>rebellious and irreligious thoughts might spread</b> — the censor\u2019s anxiety is as old as print.',
    35: 'Luther\u2019s New Testament translation sold <b>5,000 copies in weeks</b> — the Reformation as print\u2019s first mass movement.',
    38: 'The Church\u2019s answer: the <b>Index of Prohibited Books (1558)</b> and the Inquisition — censorship as counter-revolution.',
    41: 'Menocchio\u2019s fate: the miller who read and reasoned for himself was executed — print\u2019s danger to authority made flesh.',
    43: 'The 17th-18th century <b>"reading mania"</b>: literacy grew and books flooded — chapbooks, almanacs, romances.',
    45: 'France\u2019s <b>Bibliothèque Bleue</b>: low-priced small books for common readers — mass-market publishing\u2019s ancestor.',
    46: 'The periodical press — newspapers and journals carrying news, debate and argument — created the <b>public sphere</b>.',
    47: 'The works of <b>Paine, Voltaire, Rousseau</b> spread ideas of reason and liberty — print as the Enlightenment\u2019s engine.',
    49: 'James Lackington\u2019s 1791 diary: the reading public had multiplied beyond all expectation — booksellers\u2019 memoirs as evidence.',
    51: 'The 18th-century conviction: books are a <b>medium of enlightenment</b> that would destroy the basis of superstition.',
    53: 'Historians\u2019 thesis: <b>print culture created the conditions for the French Revolution</b> — by spreading critical thought.',
    54: 'Print\u2019s triad of subversion: attacked the <b>Church\u2019s sacred authority</b> and the <b>despotic power of kings</b>.',
    55: 'By the 1780s, literature <b>mocked royalty</b> circulated — caricature as political weapon.',
    58: 'Underground literature fed hostility to the monarchy — yet print <b>did not shape opinions by itself</b>: readers interpreted for themselves.',
    60: 'The 19th century: <b>mass literacy</b> leaps — primary education became compulsory; children became a print market.',
    63: 'Women entered print as readers and writers — <b>penny magazines, manuals on housekeeping, fiction</b> written by and for women.',
    64: 'Lending libraries and reading rooms spread knowledge beyond ownership — the working class self-educated.',
    67: 'Technical leaps: <b>power-driven metal presses</b>, printing millions of sheets an hour by the late 19th century.',
    69: 'Innovations of the era: the dust jacket, cheap "shilling series", paperbacks — the modern book industry takes shape.',
    71: 'India\u2019s manuscript tradition: Sanskrit, Arabic, Persian — handwritten on palm leaf and paper; <b>but no printing until the 16th century</b>.',
    74: 'The press first came to <b>Goa with Portuguese missionaries (mid-16th century)</b>; by 1674, 50 books had been printed in Konkani and Kanara.',
    75: 'The <b>English-language press grew late</b> — Indian-language journalism (Bengali, Tamil) came first after 1810 (Ganga Kishore Bhattacharya\u2019s Bengali weekly).',
    76: 'James Augustus Hicky\u2019s <b>Bengal Gazette (1780)</b> — gossip about Company officials and India\u2019s first newspaper.',
    78: 'From the early 19th century: intense <b>religious reform debates in print</b> — tracts and newspapers between reformers and orthodoxy.',
    80: 'The <b>ulama</b>, anxious about colonial power and Muslim decline, used print to publish Persian and Urdu translations and teach the faithful.',
    82: 'Among Hindus, print spread the reading of <b>religious texts in vernaculars</b> — Ramcharitmanas everywhere: faith through cheap print.',
    84: 'The newspaper notice: <b>Krishnaji Trimbuck Ranade (Pune, 1849)</b> intends to publish a newspaper — Indian print entrepreneurship in an advertisement.',
    87: 'The <b>novel</b> — a European form — prospered in Indian languages; print created new literary publics.',
    88: 'By the century\u2019s end, a <b>new visual culture</b>: woodblock and lithograph prints, mass images of gods and heroes.',
    89: 'By the 1870s, <b>caricature and cartoons</b> appeared in journals — satire as Indian political speech.',
    90: 'Women\u2019s lives in vivid print: novels, journals, autobiographies — the "scripture she could own".',
    92: 'Conservative fear: <b>literate women would be widowed</b> — superstition meeting the reading woman.',
    93: 'From the 1860s, <b>Kailashbashini Debi</b> and other Bengali women wrote on household bondage — women\u2019s print voices.',
    94: 'The Tamil novel\u2019s heroine: reading as liberation — "for a woman, the book was her companion".',
    96: '<b>Begum Rokeya Sakhawat Hossein (1926)</b> — the educationist-reformer writing on women\u2019s freedom: print as feminist weapon.',
    97: 'Journals discussed <b>women\u2019s education, widowhood, widow remarriage</b> — the reform agenda spread page by page.',
    102: 'By the late 19th century, <b>caste discrimination was written about publicly</b> — Jyotiba Phule, Ambedkar, E.V. Ramasamy (Periyar) in print.',
    103: 'Factory workers were too overworked to write — <b>mill libraries and schools</b>, sponsored by social workers, carried print to them.',
    106: '<b>Print and censorship</b>: before 1798, colonial officials vetted content; then the <b>1798 Censorship of Press Act</b> — deportation for recalcitrant editors.',
    107: 'By the <b>1820s, the Calcutta Supreme Court</b> passed regulations controlling press freedom.',
    108: 'After the <b>1857 revolt</b>, the enraged Raj demanded stronger control — the Vernacular Press Act (1878) targeted Indian-language papers.',
    109: 'The sedition mechanism: a warning first; then, on repeat, <b>press equipment seized</b> — the machinery of silencing.',
    110: 'Despite repression, <b>nationalist newspapers multiplied</b> — Tilak\u2019s Kesari galvanised the freedom movement.',
    112: 'The closing argument: the power of the printed word is proven by <b>how much governments fear it</b> — censorship as the tribute tyranny pays to print.',
    113: 'At WWII\u2019s outbreak, the <b>Defence of India Act</b> allowed detention for anti-war writing — the Raj\u2019s last gag.',
    114: '<b>Gandhi, 1922</b>: "Liberty of speech... liberty of the press... liberty of association" — the freedom fight\u2019s core trio.'
  };
})();
