/* Line-by-line decodes — Political Science (keyed to textlines_pol.js block indexes) */
(function () {
  window.DECODE = window.DECODE || {};

  window.DECODE.pol1 = {
    2: 'Belgium\u2019s basic facts: <b>smaller than Haryana</b>, one crore people, <b>59% Dutch (Flemish, north), 40% French (Wallonia, south), 1% German</b> — and <b>80% of Brussels speaks French</b> though the Dutch are the national majority.',
    3: 'The twist that made Belgium tense: the <b>French-speaking minority was richer and powerful</b> — a population minority with economic majority. The Dutch majority resented this.',
    4: 'Sri Lanka\u2019s facts: island nation off India\u2019s <b>southern</b> coast, about 2 crore people; <b>74% Sinhala-speakers</b> (mostly Buddhist), <b>18% Tamil</b> (13% Sri Lankan Tamils + 5% Indian Tamils, mostly Hindu).',
    5: 'Religion overlays language in Sri Lanka: Sinhala–Buddhist majority vs Tamil–Hindu/Christian minority — identity stacking that sharpened the conflict.',
    6: '<b>Majoritarianism begins</b>: after 1948 independence, Sinhala leaders made <b>Sinhala the only official language (1956 Act)</b>, favoured Buddhists, and gave Sinhala applicants preferential university seats and jobs.',
    7: 'Result of the majoritarian measures: Tamils felt ignored and excluded; distrust grew between communities — the road to war.',
    8: 'The <b>Belgian model</b>: between 1970 and 1993, the constitution was amended four times — equal Dutch-French ministers, majority from each community for key laws, and separate <b>community governments</b> for culture, education and language.',
    9: 'Sri Lanka\u2019s spiral: distrust → conflict → demands for a separate <b>Tamil Eelam</b> → civil war (1983–2009), thousands dead, families uprooted.',
    10: 'The chapter\u2019s verdict on Sri Lanka: when a <b>majority community rules by majority alone</b>, unity dies. Elections alone did not save democracy there.',
    11: 'The Belgian model is complicated — but that complexity is the price of keeping every community a shareholder in power. Brussels got a separate government with <b>equal representation</b> for both language groups.',
    13: '<b>Prudential reason</b> for power sharing: it <b>reduces conflict</b> and instability. Prudence = calculation of consequences.',
    14: '<b>Moral reason</b>: power sharing is the <b>very spirit of democracy</b> — people have a right to be consulted about how they are governed. A legitimate government is built on participation, not just victory.',
    15: 'Prudential vs moral in one line: prudential says power sharing <b>works better</b>; moral says it is <b>right</b>.',
    18: '<b>Lebanon\u2019s case</b>: after the civil war, leaders agreed that the <b>President must be Maronite Christian, PM a Sunni Muslim, Speaker a Shia Muslim</b> — power shared by community, at fixed ratios.',
    20: 'Lebanon\u2019s 1989 agreement: <b>equal Christians and Muslims in Parliament</b> — like Belgium, sharing power among social groups.',
    22: 'The elders\u2019 warning to Khalil: complicated power sharing is better than the bloodshed of "clean" majority rule — the chapter\u2019s lesson in one cartoon.',
    24: '<b>Form 1 — horizontal power sharing</b>: legislature, executive and judiciary at the <b>same level</b> check each other (checks and balances).',
    25: 'The judiciary checking the executive — judges are appointed by the executive yet can declare its acts unconstitutional: <b>horizontal sharing</b> in action.',
    26: '<b>Form 2 — vertical power sharing</b>: governments at different <b>levels</b> — central, state/provincial, local — each supreme in its own sphere.',
    27: 'In a democracy, the basic principle is that power flows from the people — so it must not concentrate in one person or office.',
    29: 'The federal logic: in big, diverse countries, power is divided among <b>levels of government</b>, each with constitutional protection.',
    30: '<b>Form 3 — power sharing among social groups</b>: community governments (Belgium), <b>reserved constituencies for SCs/STs in India</b> — giving disadvantaged groups a guaranteed share.',
    32: '<b>Form 4 — power sharing among parties, pressure groups and movements</b>: opposition parties, coalitions, trade unions, business associations — competing claims keep power dispersed.',
    33: 'Coalition alliances are a <b>direct</b> form of sharing among parties; pressure groups share it indirectly by influencing decisions.'
  };

  window.DECODE.pol2 = {
    3: '<b>Federalism defined</b>: a system in which power is divided between a <b>central authority and constituent political units</b> (states/provinces), each level supreme in its own sphere.',
    4: 'The test of federalism: <b>both levels enjoy their power independent of the other</b> — neither can abolish the other.',
    5: 'The three features of an ideal federation: (i) two or more levels, (ii) each with its own <b>jurisdiction</b> written in the constitution, (iii) changes need <b>consent of both levels</b> — plus courts as umpire and clear revenue sources.',
    6: 'The <b>two routes to federation</b>: "coming together" (USA, Switzerland, Australia — independent states unite) vs "holding together" (India, Spain, Belgium — a large country divides power to stay united).',
    8: 'In a federal system, <b>the centre cannot simply order a state</b> — state governments are not agents of the centre.',
    9: 'Federations are <b>jurisdictional</b>: the constitution specifies who legislates on what, and courts resolve disputes.',
    12: 'India is a "holding together" federation: the Constitution (1950) <b>did not use the word "federation"</b> — it described India as a <b>Union of States</b>, with a deliberately strong centre.',
    13: 'The <b>three lists</b>: <b>Union (97 subjects</b> — defence, foreign affairs, currency), <b>State (66</b> — police, public health, agriculture), <b>Concurrent (47</b> — education, forests); on conflict in Concurrent, <b>central law prevails</b>.',
    15: 'Parliament can redraw state boundaries <b>only with the consent of the affected states</b> — India\u2019s federation can be reshaped, but not by decree.',
    17: 'Special cases: Jammu & Kashmir\u2019s earlier special status, and some NE states\u2019 protections — "holding together" federations give <b>unequal units</b> asymmetric powers.',
    18: '<b>Union Territories</b> — like Chandigarh, Lakshadweep — enjoy little power and are run by the centre through administrators; too small or too distinct to be full states.',
    20: 'The courts <b>interpret the constitution</b> and settle Centre–State disputes — the judiciary as federal umpire.',
    21: '<b>Linguistic states</b>: from 1947\u2019s fear of breakup to Andhra Pradesh (1953) and the 1956 reorganisation — states redrawn by language actually <b>strengthened unity</b>.',
    22: 'Later states were created on culture and geography: Nagaland, Uttarakhand, Jharkhand (and Chhattisgarh) in 2000 — identity accommodated within federalism.',
    23: 'The verdict NCERT records: the <b>fear of fragmentation proved wrong</b> — linguistic states made administration closer to the people and deepened the union.',
    24: 'Language policy: <b>Hindi in Devanagari is the official (not national) language</b> — it is the mother tongue of only about 40% of Indians.',
    25: 'India\u2019s cautious path: unlike Sri Lanka, no single language was imposed — <b>English stayed as an associate official language</b>, and states chose their own official languages.',
    26: 'The centre promotes Hindi but <b>cannot impose it on states</b> that have not adopted it — the safeguards of the language policy.',
    27: 'Before 1990, one-party dominance at Centre and states made India look quasi-federal; the <b>Emergency (1975–77)</b> turned it practically unitary.',
    28: 'After <b>1990</b>: the rise of regional parties and coalition governments gave states real voice — the era when <b>federalism strengthened</b>.',
    30: 'A major Supreme Court judgement made it difficult for the centre to dismiss state governments (Article 356 used sparingly) — judicial deepening of federalism.',
    31: 'The 2011 census recorded <b>1300+ languages</b>; 22 are <b>Scheduled Languages</b> (Eighth Schedule) — India\u2019s linguistic pluralism in numbers.',
    35: 'Why a <b>third tier</b>: India\u2019s states are huge and diverse; many states are larger than countries — democracy needs to reach the village and town.',
    37: 'Decentralisation\u2019s rationale: local problems are best understood locally, and direct participation is the deepest form of democracy.',
    38: 'The <b>73rd and 74th Amendments (1992)</b> gave constitutional status to rural (Panchayati Raj) and urban local government — a third tier with elections every five years.',
    39: 'The rural ladder: <b>Gram Panchayat (village) → Panchayat Samiti (block) → Zila Parishad (district)</b>; seats reserved for SC, ST, OBC and <b>one-third for women</b> (many states 50%).',
    40: 'Urban local government: <b>municipal corporations</b> for big cities, <b>municipalities</b> for towns — the 74th Amendment\u2019s contribution.',
    42: 'Local government\u2019s gains: deeper democracy and representation — but <b>money, functions and functionaries (the 3 Fs problem)</b> remain partly unmet.',
    43: 'The famous <b>Kerala People\u2019s Plan</b>: panchayats decide a share of the plan budget — <b>20,000 people participating yearly</b> in direct decision making.'
  };

  window.DECODE.pol4 = {
    4: 'The <b>meaning of a political party</b>: a group that <b>contests elections</b> to hold power in government. Three parts: <b>leaders, active members, followers</b>.',
    6: 'Parties perform the <b>fill-and-hold function</b>: they contest elections, win, form and run governments — and the losing side becomes the opposition.',
    7: 'Parties put forward <b>policies and programmes</b>; voters choose among them — parties turn a thousand opinions into a few clear choices.',
    8: 'Parties <b>make laws</b>: the legislative majority belongs to the party that won; laws are drafted and passed along party lines.',
    9: 'Parties <b>form and run governments</b>: from the PM/CM down to ministers, the party decides who governs — parliamentarians are mostly party candidates.',
    10: 'Parties that lose play <b>opposition</b>: criticising government, voicing different views, mobilising opposition to laws. Parties also <b>shape public opinion</b> — lakh-strong activists and front organisations.',
    11: 'Parties give <b>access to government welfare</b> — the ordinary citizen\u2019s bridge to state machinery — and that is why people feel close to them even while distrusting them.',
    12: 'The anti-party thought experiment: with no parties, every candidate independent, no majority, no coherent policy — <b>modern democracies cannot exist without parties</b>.',
    14: 'Parties are the mechanism of <b>accountability</b>: a known label means a known promise — the voter can reward or punish the party.',
    16: 'The question "how many parties?" — democracies are free to evolve any number; the system emerges from history and society.',
    17: '<b>One-party systems</b> (China): legally only one party rules — elections offer no real choice; not a democratic option.',
    18: '<b>Two-party systems</b> (USA, UK): power alternates between two main parties; others exist but rarely win.',
    19: '<b>Multi-party systems with coalition</b> (India): several parties compete; alliances — <b>NDA, UPA, the Left front</b> — form governments when no single party has a majority.',
    20: 'Which is best? <b>No single answer</b> — each country evolves the system suited to it.',
    23: 'Every party must <b>register with the Election Commission</b>; big parties get a unique, reserved symbol so even an illiterate voter can find them.',
    24: 'Recognition criteria: a national party needs (broadly) <b>6% votes in 4+ states plus 4 Lok Sabha seats</b> and recognition in 4 states; state parties need the same within one state.',
    26: '<b>AAP</b> — formed 2012, sweeping Delhi within a year — the newest entry among national parties.',
    27: '<b>BSP</b> (1984, Kanshi Ram): draws inspiration from <b>Sahu Maharaj, Mahatma Phule, Ambedkar</b>; core support among Dalits, especially UP; symbol — the elephant.',
    29: '<b>BJP</b> (1980): cultural nationalism, uniform civil code, stronger centre; symbol — the lotus.',
    30: '<b>CPI(M)</b> (1964 split): Marxism-Leninism, secularism, democracy; strongholds — Kerala, West Bengal, Tripura; symbol — hammer, sickle and star.',
    31: '<b>INC</b> — founded <b>1885</b>, the oldest party; centrist, umbrella character; led the freedom movement; symbol — the hand.',
    33: '<b>NPP</b> (2013, P. A. Sangma, Meghalaya): the only national party from the North-East; symbol — the book.',
    34: '<b>State parties</b>: Biju Janata Dal, Sikkim Democratic Front, Mizo National Front — ruling their states; over 40 such parties matter in the Lok Sabha\u2019s arithmetic.',
    36: 'Rise of state parties since 1990: no central majority without regional allies — <b>states gained a say in national policy</b>.',
    37: 'The chapter turns to the <b>challenges</b> — lack of internal democracy, dynastic succession, money and muscle, and no meaningful choice.',
    38: '<b>Challenge 1 — no internal democracy</b>: no regular organisational elections; ordinary members have no information or voice; power sits with one or a few leaders.',
    39: 'Because leaders concentrate power, <b>disagreement means exit</b> — splits, and loyalty to persons over party.',
    40: '<b>Challenge 2 — dynastic succession</b>: top posts stay in one family; outsiders with ability cannot rise — closed doors breed family rule.',
    41: '<b>Challenge 3 — money and muscle</b>: parties nominate the rich and connected; tickets go to those who can fund campaigns — criminals sometimes included for muscle.',
    42: '<b>Challenge 4 — no meaningful choice</b>: when major parties converge on economic policy, the voter\u2019s "choice" changes little.',
    44: 'Reform steps so far: the <b>anti-defection law (52nd Amendment, 1985)</b> ended Aaya Ram Gaya Ram politics; the Supreme Court ordered <b>affidavits</b> — candidates must declare assets, liabilities and criminal cases.',
    46: 'Proposed reforms: compulsory registration of party members; a law to regulate <b>internal party elections</b>; state funding of elections — proposals, not yet law.',
    47: 'A caution from NCERT: laws alone cannot fix parties — <b>over-regulation can kill their independence</b>; public pressure must do the deep work.',
    49: 'The final reform is <b>people power</b>: quality people joining parties, and citizens demanding better — democracy gives voters the lever.'
  };
})();
