/* NDATA — Political Science chapters (1, 2, 4): full notes + randomised quiz banks */
window.NDATA = window.NDATA || {};

window.NDATA['pol1'] = {
  notes: [
    { h: 'The chapter in one paragraph', b: 'Why should power be shared? Belgium and Sri Lanka are the paired case studies. In <b>Belgium</b>, 59% Dutch-speaking Flemish and 40% French-speaking Walloons share power through an ingenious <b>Belgian model</b> — the country stayed united. In <b>Sri Lanka</b>, Sinhala <b>majoritarianism</b> (the 1956 Sinhala Only Act) alienated Tamils and fuelled a brutal <b>civil war (1983-2009)</b>. Power sharing is justified by <b>prudential</b> reasons (stability) and <b>moral</b> reasons (democracy\u2019s spirit), and takes four forms: horizontal, vertical, among communities, and among parties and groups.' },
    { h: 'Belgium: a divided society', b: 'Belgium\u2019s population: <b>59% Flemish</b> (Dutch, in the north), <b>40% Walloon</b> (French, in the south), <b>1% German</b>. In the capital <b>Brussels</b>, the ratio flips: 80% French speakers in a Dutch-majority country. The minority French community was relatively rich and powerful — a dangerous mismatch that produced acute tension in the 1950s-60s.' },
    { h: 'The Belgian model', b: 'Between 1970 and 1993, Belgium\u2019s constitution was amended four times to build power sharing: <b>equal numbers of Dutch and French-speaking ministers</b> in the central government; <b>no single community</b> can take unilateral decisions; <b>state governments are not subordinate</b> to the centre; and separate <b>community governments</b> handle culture, education and language. Brussels has a separate government where both communities are represented.' },
    { h: 'Sri Lanka: majoritarianism', b: 'Sri Lanka\u2019s people: <b>74% Sinhala</b> speakers, 18% Tamil speakers (Sri Lankan Tamils plus Indian Tamils), 7% Muslims. In 1956, an Act recognised <b>Sinhala as the only official language</b>, disregarding Tamil; preferential policies favoured Sinhalese in university seats and jobs; a new constitution promoted Buddhism. Tamils felt excluded; parties asked for autonomy, were denied, and civil war erupted — the <b>LTTE</b> fought the state until 2009.' },
    { h: 'Why power sharing is desirable', b: '<b>Prudential reasons</b>: power sharing reduces conflict between groups and avoids the tyranny of the majority; it gives everyone a stake and makes the state more stable. <b>Moral reasons</b>: power sharing is the very <b>spirit of democracy</b> — people have a right to be consulted on how they are governed, and a legitimate government is one that involves all.' },
    { h: 'Form 1: horizontal power sharing', b: 'Power is shared among <b>organs of government at the same level</b> — legislature, executive and judiciary. Each checks the others: judges are appointed by the executive, laws are made by the legislature, and courts can strike down unconstitutional acts — the <b>system of checks and balances</b>.' },
    { h: 'Form 2: vertical power sharing', b: 'Power shared among <b>levels of government</b> — a higher (union/federal) government for national matters and lower (state, provincial, local) governments for regional matters. The constitution defines each level\u2019s jurisdiction, as in India\u2019s Union-State-local structure.' },
    { h: 'Forms 3 and 4: communities and parties', b: 'Power may be shared among <b>social groups</b> — religious and linguistic communities get representation through reserved seats or community governments (Belgium, India\u2019s reserved constituencies). It is also shared among <b>political parties, pressure groups and movements</b> — coalition governments, and the competition between workers\u2019 unions and business associations, ensure competing interests share influence.' },
    { h: 'The verdict of the two cases', b: 'Belgium accommodated diversity through constitutional power sharing and survived; Sri Lanka suppressed it through majoritarianism and paid a catastrophic price. The lesson: in a democracy, <b>accommodation, not domination</b>, is the route to unity.' }
  ],
  quiz: [
    { q: 'The percentage of Dutch-speaking people in Belgium is about:', o: ['40%','50%','59%','74%'], a: 2, w: '59% live in the Flemish region.' },
    { q: 'In Brussels, the capital, about 80% of people speak:', o: ['Dutch','French','German','English'], a: 1, w: 'Brussels is 80% French-speaking though it lies in the Dutch-majority region.' },
    { q: 'The Belgian model was created through constitutional amendments between:', o: ['1948-1960','1970-1993','1995-2005','2010-2015'], a: 1, w: 'Four amendments between 1970 and 1993 built it.' },
    { q: 'In Belgium\u2019s central government:', o: ['Only Dutch speakers sit','Ministers are half Dutch, half French speaking','The king appoints all','Only French speakers sit'], a: 1, w: 'Equal representation of both communities is the model\u2019s core.' },
    { q: 'Community governments in Belgium handle:', o: ['Defence and foreign affairs','Culture, education and language issues','Railways','Currency'], a: 1, w: 'Each community runs its cultural and educational affairs.' },
    { q: 'Sri Lanka\u2019s major social groups are:', o: ['Sinhala speakers and Tamil speakers','Flemish and Walloons','Germans and French','Christians and Muslims only'], a: 0, w: '74% Sinhala and 18% Tamil speakers.' },
    { q: 'The Sinhala Only Act was passed in:', o: ['1948','1956','1972','1983'], a: 1, w: 'In 1956, Sinhala was made the sole official language.' },
    { q: 'Majoritarianism in Sri Lanka constitutionally promoted:', o: ['Hinduism','Buddhism','Islam','All religions equally'], a: 1, w: 'The new constitution gave Buddhism "foremost place".' },
    { q: 'The Sri Lankan civil war ended in:', o: ['1983','1991','2009','2015'], a: 2, w: 'The LTTE was defeated in 2009, after 26 years of war.' },
    { q: 'A "prudential" reason for power sharing is one based on:', o: ['Moral principle','Careful calculation of consequences','Religion','Tradition'], a: 1, w: 'Prudence: it reduces conflict — a practical consideration.' },
    { q: 'The moral reason for power sharing is that:', o: ['It is cheaper','People have a right to be consulted; it is the spirit of democracy','It wins elections','It pleases foreign powers'], a: 1, w: 'Democratic legitimacy requires involving the governed.' },
    { q: 'Horizontal power sharing is among:', o: ['Levels of government','Organs of government at the same level','Social groups','Political parties'], a: 1, w: 'Legislature, executive and judiciary check one another.' },
    { q: 'Vertical power sharing is among:', o: ['Different organs of government','Different levels of government (union, state, local)','Different communities','Different parties'], a: 1, w: 'Power divided between higher and lower levels of government.' },
    { q: 'The system of checks and balances operates through:', o: ['Each organ checking the others','One organ ruling all','The army','Referendums only'], a: 0, w: 'Legislature, executive and judiciary restrain each other.' },
    { q: 'Reserved constituencies in India are an example of power sharing among:', o: ['Organs','Levels','Social groups','Parties'], a: 2, w: 'Scheduled Castes and Tribes get reserved seats.' },
    { q: 'A coalition government shares power among:', o: ['Political parties','Judges','States only','Religious heads'], a: 0, w: 'Two or more parties govern together.' },
    { q: 'Which country\u2019s experience shows majoritarianism undermines unity?', o: ['Belgium','Sri Lanka','Switzerland','France'], a: 1, w: 'Sri Lanka\u2019s majoritarianism led to civil war.' },
    { q: 'Which country shows successful accommodation of diversity?', o: ['Sri Lanka','Belgium','Pakistan (1971)','Yugoslavia'], a: 1, w: 'Belgium\u2019s model held the country together.' },
    { q: 'Sri Lankan Tamils\u2019 parties demanded:', o: ['Unitary rule','Regional autonomy and equality of language','Separate religion','Abolition of elections'], a: 1, w: 'They wanted autonomy for Tamil-majority regions and language rights.' },
    { q: 'By 1983 in Sri Lanka:', o: ['Peace was achieved','The demand for a separate Tamil Eelam turned into civil war','Belgium intervened','The Act was repealed'], a: 1, w: 'Distrust escalated into decades of armed conflict.' },
    { q: 'Power sharing between workers\u2019 unions and employers\u2019 associations is an example of sharing among:', o: ['Organs of government','Levels of government','Political parties, pressure groups and movements','Communities'], a: 2, w: 'Interest groups too share power in democracies.' },
    { q: 'In a democracy, rulers are:', o: ['Elected by the people and accountable to them','Appointed by the army','Hereditary','Chosen by courts'], a: 0, w: 'Elected, accountable rule — the reason consultation matters.' },
    { q: 'Tyranny of the majority means:', o: ['The majority ignores the needs and rights of the minority','The majority suffers','Courts rule','Coalitions fail'], a: 0, w: 'Pure majority rule can oppress minorities — power sharing prevents this.' },
    { q: 'Belgium and Sri Lanka are compared in NCERT to show:', o: ['Two similar successes','How accommodation works and majoritarianism fails','Economic development','Colonial history'], a: 1, w: 'The classic paired case study of this chapter.' },
    { q: 'German speakers in Belgium are about:', o: ['1%','18%','40%','59%'], a: 0, w: 'A small 1% German-speaking community.' },
    { q: 'Which of these is NOT one of the four forms of power sharing?', o: ['Horizontal','Vertical','Among social groups','Among dynasties'], a: 3, w: 'The fourth form is among parties, pressure groups and movements.' },
    { q: 'Community government is unique to:', o: ['Belgium\u2019s model','Sri Lanka\u2019s model','USA','China'], a: 0, w: 'Belgium\u2019s elected community governments are the distinctive innovation.' }
  ]
};

window.NDATA['pol2'] = {
  notes: [
    { h: 'The chapter in one paragraph', b: 'Federalism divides government between levels — each supreme in its own sphere, guaranteed by a written constitution and courts. Federations are "coming together" (USA) or "holding together" (India). India is a <b>three-tier federation</b> with <b>Union, State and Concurrent lists</b>, residuary powers with the Centre, and strong central features — "federal in form, unitary in spirit". Language policy (no national language; 22 Scheduled languages) and <b>linguistic states</b> accommodated diversity; the <b>73rd/74th Amendments (1992)</b> made local government a constitutional third tier with <b>one-third reservation for women</b>.' },
    { h: 'What federalism is', b: 'Federalism has two or more levels of government, each with its own <b>jurisdiction</b> — areas of authority — enshrined in a <b>written constitution</b>. Neither level can unilaterally change the arrangement; <b>independent courts</b> interpret it. Each level collects its own taxes for its functions. Citizens are governed by both levels simultaneously.' },
    { h: 'Coming together vs holding together', b: '<b>Coming-together federations</b> (USA, Switzerland, Australia): independent states pool sovereignty for common goals; states are strong. <b>Holding-together federations</b> (India, Spain, Belgium): a large power devolves authority to preserve unity; the centre tends to stay stronger.' },
    { h: 'The three lists', b: 'The <b>Union List</b> (formerly 100 subjects — defence, foreign affairs, banking, currency) is Parliament\u2019s exclusive domain. The <b>State List</b> (61 subjects — police, public health, agriculture) belongs to states. The <b>Concurrent List</b> (52 subjects — education, forests, marriage) is shared; on conflict, central law prevails. <b>Residuary subjects</b> (like cyberspace) rest with the Union.' },
    { h: 'How India is federal — and how it isn\u2019t', b: 'States are not indestructible — Parliament can redraw boundaries; <b>Article 356</b> allows President\u2019s Rule; all-India services (IAS, IPS) and emergency powers strengthen the Centre; the Governor is a central appointee. Yet states have their own constitutions of power, courts protect the division, and no level can simply abolish another — hence <b>"federal in form, unitary in spirit"</b>.' },
    { h: 'Linguistic states and language policy', b: 'Since <b>1956</b>, states were reorganised on language (Andhra Pradesh first). Far from dividing India, linguistic states strengthened unity by making governance inclusive. On language: <b>Hindi is an official language, not the national language</b>; English remains an associate official language; the <b>22 Scheduled Languages</b> (8th Schedule) get official protection.' },
    { h: 'Centrism to federal cooperation', b: 'For long the centre dominated (one-party era, frequent use of Article 356). Since the 1990s, coalition politics, strong regional parties and the rise of state-level autonomy claims made Indian federalism more genuinely <b>cooperative</b>.' },
    { h: 'Decentralisation: the 73rd and 74th Amendments (1992)', b: 'Democracy is incomplete without local self-government — yet local bodies were weak, dependent and superseded. The 1992 amendments gave them constitutional status: a <b>three-tier panchayati raj</b> (village, intermediate, district), direct elections every <b>five years</b>, <b>one-third of seats reserved for women</b> (SC/ST reservation by proportion), a <b>State Election Commission</b>, and State Finance Commissions for funds. Municipalities got parallel treatment (74th). Local governments handle 29 subjects — water, roads, schools.' },
    { h: 'Why decentralisation matters', b: 'India\u2019s vast size and diversity make one remote centre unworkable. Local governments know local needs, enable ordinary people to participate directly, train leadership from villages upward, and reduce the burden on states. The evolution of "local" into a constitutional tier is called the third stratum of Indian democracy.' }
  ],
  quiz: [
    { q: 'Federalism involves:', o: ['One central authority only','Two or more levels of government, each with its own jurisdiction','Army rule','Rule by courts'], a: 1, w: 'Each level is supreme in its own sphere.' },
    { q: 'The USA is an example of:', o: ['Holding-together federation','Coming-together federation','Confederation','Unitary state'], a: 1, w: 'Independent states united — coming together.' },
    { q: 'India is an example of:', o: ['Coming-together federation','Holding-together federation','Unitary state','Monarchy'], a: 1, w: 'A large country devolving power to hold together.' },
    { q: 'Defence and foreign affairs belong to the:', o: ['Union List','State List','Concurrent List','Residuary powers'], a: 0, w: 'Only the Union can legislate on them.' },
    { q: 'Police and public health belong to the:', o: ['Union List','State List','Concurrent List','Municipal List'], a: 1, w: 'State List subjects.' },
    { q: 'Education and forests fall under the:', o: ['Union List','State List','Concurrent List','Residuary'], a: 2, w: 'Concurrent List — both can legislate; central law wins conflicts.' },
    { q: 'Residuary powers in India rest with:', o: ['States','The Union government','Local bodies','Courts'], a: 1, w: 'Subjects not in any list, like cyberspace, go to the Centre.' },
    { q: 'Article 356 of the Constitution provides for:', o: ['Emergency due to war','President\u2019s Rule in a state','Reservation for women','Language rights'], a: 1, w: 'State governments can be dismissed and central rule imposed.' },
    { q: 'India is often described as:', o: ['Truly federal','Federal in form, unitary in spirit','A confederation','Fully unitary'], a: 1, w: 'A strong centre within a federal structure.' },
    { q: 'States in India were first reorganised on linguistic lines in:', o: ['1947','1950','1956','1966'], a: 2, w: 'The States Reorganisation Act, 1956; Andhra Pradesh came first in 1953.' },
    { q: 'The number of languages in the Eighth Schedule is:', o: ['14','18','22','25'], a: 2, w: '22 Scheduled Languages enjoy official recognition.' },
    { q: 'Which is India\u2019s national language?', o: ['Hindi','No language is the national language','Sanskrit','English'], a: 1, w: 'Hindi is an official language, not "national" — India has none.' },
    { q: 'The 73rd Amendment (1992) deals with:', o: ['Municipalities','Panchayati Raj','Fundamental duties','Anti-defection'], a: 1, w: 'It constitutionalised rural local government.' },
    { q: 'The 74th Amendment (1992) deals with:', o: ['Panchayats','Urban municipalities','Education','GST'], a: 1, w: 'Urban local bodies became constitutional.' },
    { q: 'Panchayati Raj has how many tiers?', o: ['Two','Three','Four','Five'], a: 1, w: 'Village, intermediate (block) and district panchayats.' },
    { q: 'Reservation for women in panchayats is:', o: ['One-fourth','One-third','Half','None'], a: 1, w: 'One-third of all seats and chairperson posts.' },
    { q: 'Panchayat elections are held every:', o: ['3 years','4 years','5 years','6 years'], a: 2, w: 'Direct elections every five years.' },
    { q: 'State Election Commissions conduct:', o: ['Parliament elections','State legislature and local body elections','Judicial elections','Party elections'], a: 1, w: 'Free and fair local elections need an independent body.' },
    { q: 'Local governments handle subjects listed in:', o: ['The Union List','11 subjects of the state list (29 for panchayats)','The Concurrent List','Residuary list'], a: 1, w: 'The 11th Schedule lists 29 panchayat subjects.' },
    { q: 'An IAS officer serving a state is a symbol of:', o: ['State autonomy','Central presence in states (all-India services)','Judicial power','Local self-rule'], a: 1, w: 'All-India services are controlled by the Centre.' },
    { q: 'Which of these strengthens the Centre vis-à-vis states?', o: ['State Election Commission','The Governor appointed by the President','Panchayati raj','Finance Commission'], a: 1, w: 'The Governor is a central appointee over a state.' },
    { q: 'Jammu & Kashmir\u2019s special status (Article 370) — as per NCERT\u2019s account of Indian federalism — was an example of:', o: ['Asymmetric federalism','Unitary rule','Confederation','Municipal autonomy'], a: 0, w: 'Some units enjoy special arrangements — asymmetric federalism.' },
    { q: 'A big reason for decentralisation in India is:', o: ['Small population','Vast size and diversity','Too many parties','Foreign pressure'], a: 1, w: 'Local needs vary; local governments address them best.' },
    { q: 'On a subject in the Concurrent List, if state and central laws conflict:', o: ['State law prevails','Central law prevails','Courts decide each time','Both lapse'], a: 1, w: 'Union law overrides state law under Article 254.' },
    { q: 'The phrase "cooperative federalism" refers to:', o: ['Centre and states working together','States competing','Centre ruling alone','Judicial supremacy'], a: 0, w: 'GST councils and commissions exemplify cooperation.' },
    { q: 'Local self-government in India is called the:', o: ['First stratum','Second stratum','Third stratum of democracy','Fourth estate'], a: 2, w: 'Below Union and states — the third stratum.' },
    { q: 'State Finance Commissions review:', o: ['Centre\u2019s budget','Financial position of panchayats and municipalities','Party funds','Defence spending'], a: 1, w: 'They recommend how local bodies are financed.' }
  ]
};

window.NDATA['pol4'] = {
  notes: [
    { h: 'The chapter in one paragraph', b: 'Political parties are the machinery of democracy: they contest elections, offer policy choices, form governments, voice opposition and shape public opinion. Party systems may be <b>one-party, two-party or multi-party</b>; India is a multi-party system with <b>coalition</b> governments since 1989. Parties are recognised as <b>national or state parties</b> by the Election Commission using vote-and-seat criteria. They face serious challenges — no internal democracy, dynastic succession, money and muscle — which reforms like the <b>anti-defection law (1985)</b> and court-mandated disclosures try to address.' },
    { h: 'What is a political party?', b: 'A political party is a <b>group of people who come together to contest elections and hold power in government</b>, agreeing on some policies and programmes for society. Parties put forward different visions; voters choose among them — that is how a government gets a mandate, and opposition gets a voice.' },
    { h: 'Functions of parties', b: 'Parties: <b>contest elections</b> (selecting candidates); <b>put forward policies and programmes</b> voters can choose among; <b>make laws</b> (legislatures run by party members); <b>form and run governments</b> (recruiting leaders, ministers); <b>play the opposition</b> — criticising government and offering alternatives; <b>shape public opinion</b> through campaigns and media; and <b>provide access</b> — an ordinary citizen\u2019s welfare petitions and ambitions flow through party channels.' },
    { h: 'Why parties are necessary', b: 'Without parties, democracies cannot aggregate millions of preferences into coherent choices. Assemblies without parties would be a crowd of individuals with no collective direction. Candidates need parties for labels voters can trust; governments need parties to stay stable; opposition needs parties to hold rulers accountable. Modern democracies "cannot exist without parties".' },
    { h: 'Party systems', b: '<b>One-party systems</b> (China — Communist Party alone may rule; elections offer no real choice) are not democracies in the full sense. <b>Two-party systems</b> (USA, UK) see power alternate between two dominant parties. <b>Multi-party systems</b> (India) allow several parties to compete — often forming <b>coalitions</b>; this is not political instability but open competition, and usually gives voters more choice.' },
    { h: 'National and state parties', b: 'A party with <b>6% of votes in four or more states plus four Lok Sabha seats</b> — and recognition in four states — is a <b>national party</b> (INC, BJP, BSP, CPI(M), NPP — the first from the North-East). A <b>state party</b> (regional party) meets similar thresholds within one state (e.g., DMK, BJD, TMC) — many grow nationally influential, especially in coalitions.' },
    { h: 'Challenges facing parties', b: '<b>Lack of internal democracy</b> — power concentrated in leaders, no open elections or membership registers. <b>Dynastic succession</b> — closed leadership recruitment by family, unfair to ordinary workers. <b>Money and muscle power</b> — elections need big money; parties nominate wealthy candidates, sometimes with criminal cases, because they "win". <b>Often no meaningful choice</b> — parties look increasingly alike, leaving voters cynical.' },
    { h: 'Reforms and the road ahead', b: 'The Supreme Court made candidates file <b>affidavits</b> of assets, education and criminal cases. The Election Commission mandates regular <b>audited accounts</b> and tax returns of parties, and filed cases of corruption against MPs/MLAs must be decided within months. The <b>anti-defection law (52nd Amendment, 1985)</b> disqualifies legislators who defect. Proposed — but pending — reforms include regulating internal party elections and state funding of elections. Ultimately, an alert public and pressure from within can democratise parties.' }
  ],
  quiz: [
    { q: 'A political party is a group that:', o: ['Only campaigns outside elections','Contests elections to hold power in government','Runs courts','Controls the army'], a: 1, w: 'Contesting elections and seeking power defines a party.' },
    { q: 'Which of these is a function of political parties?', o: ['Appointing judges','Playing the opposition by criticising government','Commanding the army','Printing currency'], a: 1, w: 'Opposition parties criticise and offer alternatives.' },
    { q: 'The party that loses elections:', o: ['Is banned','Plays the role of opposition','Joins the government','Disbands'], a: 1, w: 'Losing parties form the opposition, keeping government accountable.' },
    { q: 'China\u2019s party system is:', o: ['Multi-party','Two-party','One-party','Coalition'], a: 2, w: 'Only the Communist Party is permitted to rule.' },
    { q: 'The USA and UK have:', o: ['One-party systems','Two-party systems','Multi-party systems','No parties'], a: 1, w: 'Power alternates between two major parties.' },
    { q: 'India has a:', o: ['One-party system','Two-party system','Multi-party system with coalitions','Partyless democracy'], a: 2, w: 'Several national and many state parties; coalitions since 1989.' },
    { q: 'A multi-party system is a sign of:', o: ['Political instability','Democratic vibrancy and choice','Failure','Corruption'], a: 1, w: 'Competition among many parties widens voter choice.' },
    { q: 'To be recognised as a national party, a party needs (broadly):', o: ['6% votes in 4 states plus 4 Lok Sabha seats','2% national votes','50% of states won','Prime ministerial candidate'], a: 0, w: 'The EC\u2019s vote-and-seat criteria across states.' },
    { q: 'Which is a national party of India?', o: ['DMK','Biju Janata Dal','Bahujan Samaj Party (BSP)','Telugu Desam'], a: 2, w: 'BSP is recognised nationally; the others are state parties.' },
    { q: 'NPP, a recognised national party, is based in:', o: ['Meghalaya (North-East)','Kerala','Punjab','Gujarat'], a: 0, w: 'The National People\u2019s Party was the first national party from the North-East.' },
    { q: 'The anti-defection law was passed by the:', o: ['42nd Amendment','52nd Amendment (1985)','61st Amendment','73rd Amendment'], a: 1, w: 'The 52nd Amendment disqualifies defectors.' },
    { q: 'Defection means:', o: ['Losing an election','An elected representative leaving the party on whose symbol they were elected','Campaigning abroad','Cross-voting in local bodies'], a: 1, w: 'Party-hopping for office — now punished with loss of seat.' },
    { q: 'Which challenge of parties does "dynastic succession" describe?', o: ['Too many primaries','Leadership passed within families, closing entry to others','Frequent elections','Judicial interference'], a: 1, w: 'Closed family control undermines internal democracy.' },
    { q: 'Money and muscle in elections lead parties to:', o: ['Nominate wealthy candidates who can fund campaigns','Rely only on volunteers','Publish all donations','Avoid elections'], a: 0, w: 'Candidates\u2019 ability to spend matters more than merit.' },
    { q: 'The Supreme Court\u2019s affidavit order requires candidates to declare:', o: ['Only income tax returns','Assets, liabilities, education and criminal cases','Party manifestos','Vote share'], a: 1, w: 'Full disclosure before nomination.' },
    { q: 'Which reform is only a proposal, not law, in India?', o: ['Anti-defection law','Audit of party accounts by EC','State funding of elections','Affidavits by candidates'], a: 2, w: 'State funding remains debated, not implemented.' },
    { q: 'Parties shape public opinion by:', o: ['Running campaigns, movements and media cells','Banning newspapers','Appouncing judges','Controlling schools'], a: 0, w: 'They raise and highlight issues to build support.' },
    { q: 'The "opposition" in a democracy:', o: ['Co-governs secretly','Criticises the government and presents alternatives','Is illegal','Runs the army'], a: 1, w: 'Formal opposition is a democratic institution.' },
    { q: 'Partisanship means:', o: ['Neutral analysis','Loyalty to one\u2019s party, often blind to its faults','Judicial review','Voting independently'], a: 1, w: 'Firm party loyalty, frequently uncritical.' },
    { q: 'Election Commission\u2019s mandatory requirement for parties:', o: ['Hold internal elections','File audited accounts annually','Publish MPs\u2019 taxes','Fund candidates equally'], a: 1, w: 'Regular audited accounts and tax returns are compulsory.' },
    { q: 'An "affidavit" is:', o: ['A signed legal declaration of facts','A party manifesto','A court verdict','An election symbol'], a: 0, w: 'Candidates swear their details on affidavit.' },
    { q: 'A state (regional) party:', o: ['Cannot win Lok Sabha seats','Is recognised in one state but may be influential nationally','Is always separatist','Cannot join coalitions'], a: 1, w: 'Regional parties often kingmakers in coalitions.' },
    { q: 'The era of coalition governments at the Centre began around:', o: ['1947','1971','1989','2014'], a: 2, w: 'Since 1989 no single party won a majority until 2014.' },
    { q: 'Laws in a legislature are usually debated and passed by:', o: ['Civil servants','Party members elected to the legislature','Judges','Governors'], a: 1, w: 'Legislatures are organised by parties.' },
    { q: 'The real choice in an election comes when:', o: ['Parties offer genuinely different programmes','Only one candidate stands','Ballots are digital','Turnout is low'], a: 0, w: 'Meaningful choice requires distinct party platforms.' },
    { q: 'What can ordinary citizens do about party failures?', o: ['Nothing','Petition, protest and vote against undemocratic parties','Join the judiciary','Ban parties'], a: 1, w: 'Public pressure is the ultimate corrective in a democracy.' },
    { q: 'The Election Commission of India is a:', o: ['Party organ','Constitutional body regulating elections','Private company','Court'], a: 1, w: 'An independent constitutional authority.' }
  ]
};
