/* NDATA — Economics chapters: full notes + randomised quiz banks */
window.NDATA = window.NDATA || {};

window.NDATA['eco1'] = {
  notes: [
    { h: 'The chapter in one paragraph', b: 'Different people want different things from development — a job, security, equality, a clean environment — so <b>development goals vary</b>, and what is development for one may be destruction for another. <b>Income is the most important goal but not the only one</b>: we compare countries using <b>per capita income</b> (World Bank categories), but also <b>literacy, IMR, net attendance and the HDI</b>. <b>Public facilities</b> — health, education, water — determine well-being beyond private income, as Kerala\u2019s record shows. And development must be <b>sustainable</b>: exhausting groundwater, crude oil or forests steals from the future.' },
    { h: 'Development goals differ', b: 'A landless labourer wants land and regular wages; a prosperous farmer wants cheap labour and good prices; an urban youth wants a job; a girl wants education and freedom from discrimination. What looks like development to one group may harm another — a dam means electricity to the city and displacement to the valley.' },
    { h: 'Income and other goals', b: 'People seek not just income but <b>equal treatment, freedom, security and respect</b>. A job may be preferred over a slightly higher-paying insecure one. Women may prefer work closer home with safe conditions. Development is a mix of goals — material and non-material.' },
    { h: 'Comparing income: per capita averages', b: 'For comparing countries or states, we use <b>average income — total income ÷ population (per capita income)</b>. The World Bank classifies countries: rich (per capita income above ~US$ 53,000 per year, e.g. the USA) vs low-income (~US$ 2,500 or less, e.g. Mozambique). India sits in the <b>lower-middle income</b> group. Averages, however, hide distribution — they say nothing about how many are poor.' },
    { h: 'Income and other criteria', b: 'Money cannot buy a pollution-free environment, unadulterated medicines or national security. So we compare <b>literacy rates, net attendance ratios, infant mortality rates (IMR)</b> and the <b>Human Development Index (HDI)</b> — UNDP\u2019s composite of health (life expectancy), education and income. Haryana\u2019s higher per capita income than Kerala hasn\u2019t matched Kerala\u2019s life expectancy and literacy.' },
    { h: 'Infant mortality and public health', b: '<b>IMR</b> — deaths of children under one year per 1,000 live births — indicates health services, nutrition and sanitation. <b>Kerala\u2019s IMR (~11)</b> is a fraction of Bihar\u2019s (~47). The difference lies in <b>public facilities</b>: Kerala\u2019s health centres, schools and PDS reach ordinary people, whatever their private income.' },
    { h: 'Public facilities', b: 'Clean drinking water, sanitation, electricity, public transport, schools and hospitals are <b>public facilities</b> — best provided collectively by government. Private markets sell only to those who can pay; safe drinking water, especially, cannot be left to price alone. Kerala\u2019s and some other states\u2019 better outcomes flow from such collective provision.' },
    { h: 'Sustainability of development', b: 'Development that exhausts resources is self-defeating. <b>Groundwater</b> is being over-drawn (crude oil and groundwater stocks have a finite extraction horizon); forests once cut regenerate over centuries; emissions change the climate for everyone. <b>Sustainable development</b> — using resources so future generations can meet their needs — is the only rational goal.' },
    { h: 'How we know and decide', b: 'Development decisions need <b>data</b> — tables of income, schooling, health and environment indicators — and judgement about what matters. NCERT\u2019s exercise on comparing states shows: the question "which is more developed?" has no single answer; it depends on which goals we weigh.' }
  ],
  quiz: [
    { q: 'Per capita income equals:', o: ['Total income of the country','Total income ÷ population','Income of the richest person','Tax collection per family'], a: 1, w: 'Average income = total income divided by population.' },
    { q: 'The World Bank classifies India as a:', o: ['Rich country','Low-income country','Lower-middle income country','High-income country'], a: 2, w: 'India is in the lower-middle income group.' },
    { q: 'Which of these CANNOT be bought in the market?', o: ['A car','A pollution-free environment','Medicines','Education at a private school'], a: 1, w: 'Clean air and environment are public goods, not market commodities.' },
    { q: 'IMR stands for:', o: ['Indian Market Rate','Infant Mortality Rate','Internal Migration Rate','Income Median Ratio'], a: 1, w: 'Deaths under one year of age per 1,000 live births.' },
    { q: 'Kerala\u2019s low IMR compared to Bihar\u2019s is mainly due to:', o: ['Higher rainfall','Better public facilities — health, nutrition, schooling','More industries','Bigger cities'], a: 1, w: 'Public provision, not private income, explains the gap.' },
    { q: 'The Human Development Index is published by the:', o: ['World Bank','UNDP','IMF','WTO'], a: 1, w: 'The UN Development Programme since 1990.' },
    { q: 'The HDI combines:', o: ['Only income','Health, education and income','Defence and trade','Population and area'], a: 1, w: 'Life expectancy, schooling and per capita income.' },
    { q: 'Which state shows high human development despite moderate income?', o: ['Kerala','Bihar','Odisha','UP'], a: 0, w: 'Kerala\u2019s literacy and life expectancy outrun its income rank.' },
    { q: '"Money cannot buy all goods and services" refers to:', o: ['Inflation','Public goods like clean air and security','Barter','Taxation'], a: 1, w: 'Some vital goods exist outside markets.' },
    { q: 'Sustainable development means:', o: ['Fast growth forever','Using resources so future generations can also meet their needs','No industry','Only agriculture'], a: 1, w: 'Intergenerational fairness is the core idea.' },
    { q: 'Groundwater is an example of a resource that is:', o: ['Unlimited','Being over-used beyond recharge','Created by factories','Imported'], a: 1, w: 'Extraction exceeds recharge in much of India.' },
    { q: 'Which of these is a public facility?', o: ['Private car','Public transport','Luxury watch','Club membership'], a: 1, w: 'Collectively provided services are public facilities.' },
    { q: 'Two persons may have conflicting development goals when:', o: ['Both want jobs','A factory means profit for owners but pollution for villagers','Both want schools','Both pay taxes'], a: 1, w: 'One group\u2019s gain can be another\u2019s loss.' },
    { q: 'Besides income, people value:', o: ['Nothing','Equal treatment, security, freedom and respect','Only gold','Only imports'], a: 1, w: 'Non-material goals matter equally.' },
    { q: 'For comparing development between countries, the most used measure is:', o: ['Population','Average (per capita) income','Area','Army size'], a: 1, w: 'Averages allow comparison, though imperfectly.' },
    { q: 'Averages hide:', o: ['Nothing','Distribution — how income is shared among people','Currency values','Weather'], a: 1, w: 'A high average can coexist with deep poverty.' },
    { q: 'The per capita income criterion is used by:', o: ['UNDP only','The World Bank to classify countries','The WTO','The UN Security Council'], a: 1, w: 'The World Bank\u2019s income classification.' },
    { q: 'Life expectancy at birth measures:', o: ['Literacy','Average years a newborn is expected to live','Income','Birth rate'], a: 1, w: 'A core health indicator of the HDI.' },
    { q: 'Net Attendance Ratio measures:', o: ['Voters present','Children of school age actually attending school','Workers at factories','Hospital beds'], a: 1, w: 'Attendance of 6-17 year-olds, age-specific.' },
    { q: 'Which resource raises the inter-generational equity question most sharply?', o: ['Solar energy','Crude oil reserves','Wind','Tides'], a: 1, w: 'Finite fossil stocks — using them now forecloses the future.' },
    { q: 'Development for a girl in a patriarchal family may mean:', o: ['More gold','Education and freedom to choose her life','Bigger farm','More cattle'], a: 1, w: 'NCERT\u2019s example of differing goals.' },
    { q: 'A safe job with less pay may be preferred because:', o: ['Pay is irrelevant','Job security and other goals matter too','Taxes are lower','It is illegal to refuse'], a: 1, w: 'Security is a development goal beyond income.' },
    { q: 'Public facilities are best provided by:', o: ['Private companies only','The government/collective action','Foreign donors','No one'], a: 1, w: 'Markets alone exclude those who cannot pay.' },
    { q: 'Which statement about averages is correct?', o: ['Averages reveal everything','Averages hide inequality and distribution','Averages are always wrong','Averages equal income of all'], a: 1, w: 'They summarise but conceal distribution.' },
    { q: 'Bihar\u2019s higher IMR than Kerala indicates:', o: ['Better health in Bihar','Weaker public health and nutrition systems in Bihar','Colder climate','More doctors in Bihar'], a: 1, w: 'IMR is a sensitive proxy for health systems.' },
    { q: 'Sustainability concerns arose because present patterns of resource use:', o: ['Are too slow','May exhaust resources and destabilise the climate','Favour villages','Reduce profits'], a: 1, w: 'Over-extraction and emissions threaten the future.' }
  ]
};

window.NDATA['eco2'] = {
  notes: [
    { h: 'The chapter in one paragraph', b: 'The economy works in three <b>sectors</b>: <b>primary</b> (natural products), <b>secondary</b> (manufacturing), <b>tertiary</b> (services). As economies develop, output shifts to secondary and then tertiary — but India\u2019s service-led growth hasn\u2019t moved a similar share of workers out of agriculture, creating <b>underemployment</b>. Employment is split between an <b>organised</b> minority and a vast <b>unorganised</b> sector without security. The <b>MGNREGA 2005</b> guarantees 100 days of rural work; other strategies include education, credit, infrastructure and export zones.' },
    { h: 'The three sectors', b: '<b>Primary sector</b>: agriculture, fishing, forestry, mining — natural products; the largest employer. <b>Secondary sector</b>: industry — transforming raw materials into goods (cotton to cloth, sugarcane to sugar). <b>Tertiary sector</b>: services that support both — transport, banking, communication, IT, tourism, teachers, shopkeepers. In advanced economies the tertiary sector produces the most GDP and employs the most people.' },
    { h: 'Interdependence and GDP', b: 'The three sectors interlock: farmers need banks and traders; factories need transport and energy; everything needs labour and services. Their combined value of final goods and services produced in a year is the <b>GDP</b> — in India, estimated by the <b>Central Statistical Organisation (CSO)</b>. Comparing GDP shares across decades shows the structural shift toward services.' },
    { h: 'Employment vs output — the Indian paradox', b: 'Agriculture employs over half of workers but produces only about a <b>sixth of the GDP</b>. Many farm workers are <b>underemployed</b> (disguised unemployment: two people doing one person\u2019s work). In contrast, secondary and tertiary employ fewer people but generate more output. The shift of workers from agriculture to industry and services — and raising farm productivity — is the core of India\u2019s development challenge.' },
    { h: 'Organised and unorganised sectors', b: '<b>Organised</b>: registered enterprises, fixed hours, formal contracts, job security and benefits — a small minority of workers. <b>Unorganised</b>: ~90% of Indian workers — small farms, street vendors, homeworkers, casual labour — no job security, no benefits, low pay, often hazardous conditions.' },
    { h: 'Protecting unorganised workers', b: 'Because unorganised workers cannot bargain on equal terms, protection is a public responsibility: <b>minimum wages</b> enforcement, equal pay, safe conditions, overtime rules — and social security for old age, sickness and maternity. Yet enforcement is weakest precisely where employment is informal.' },
    { h: 'MGNREGA — the Right to Work', b: 'The <b>Mahatma Gandhi National Rural Employment Guarantee Act (2005)</b> guarantees <b>100 days of wage employment per year</b> to every rural household willing to do unskilled manual work. If the government fails to provide work, it pays an allowance. It builds village infrastructure while creating a wage floor — a landmark social protection law.' },
    { h: 'Employment strategies and NITI Aayog', b: 'Besides MGNREGA, employment grows through human capital (education, skills — "demographic dividend"), infrastructure investment, credit for small enterprises, and SEZ/export promotion. <b>NITI Aayog</b> (2015) — replacing the Planning Commission — frames these strategies, from agriculture modernisation ("zero budget" ideas in NCERT discussions) to Make in India manufacturing.' }
  ],
  quiz: [
    { q: 'A farmer growing wheat belongs to the:', o: ['Primary sector','Secondary sector','Tertiary sector','Organised sector'], a: 0, w: 'Agriculture produces natural goods — primary.' },
    { q: 'A cotton textile mill is part of the:', o: ['Primary sector','Secondary sector','Tertiary sector','Quaternary sector'], a: 1, w: 'Manufacturing transforms raw cotton into cloth.' },
    { q: 'A bank employee works in the:', o: ['Primary sector','Secondary sector','Tertiary sector','Agriculture'], a: 2, w: 'Banking is a service — tertiary.' },
    { q: 'The value of all final goods and services produced in a year is:', o: ['GNP','GDP','NNP','FDI'], a: 1, w: 'GDP — Gross Domestic Product.' },
    { q: 'GDP estimates in India are made by the:', o: ['RBI','Central Statistical Organisation','SEBI','Planning Commission'], a: 1, w: 'The CSO compiles national accounts.' },
    { q: 'In India, the sector employing the most people is:', o: ['Primary','Secondary','Tertiary','Government'], a: 0, w: 'Agriculture remains the largest employer.' },
    { q: 'Disguised unemployment means:', o: ['Open unemployment','More people employed than needed — extra workers add nothing to output','Seasonal jobs','Job loss'], a: 1, w: 'Common in family farming: removing a worker changes nothing.' },
    { q: 'The unorganised sector covers about what share of Indian workers?', o: ['About 10%','About 30%','About 90%','About 50%'], a: 2, w: 'The vast majority work informally.' },
    { q: 'Which is a feature of the organised sector?', o: ['No fixed hours','Job security and benefits like pensions','Daily wage cash payments','No written contract'], a: 1, w: 'Registered firms provide formal terms of work.' },
    { q: 'MGNREGA (2005) guarantees rural employment for:', o: ['30 days a year','60 days a year','100 days a year','Whole year'], a: 2, w: '100 days of guaranteed wage work per rural household.' },
    { q: 'MGNREGA work is:', o: ['Skilled factory work','Unskilled manual labour on public works','Only for urban youth','Only for graduates'], a: 1, w: 'Wells, roads, water conservation — manual public works.' },
    { q: 'If work is not provided under MGNREGA, the government must:', o: ['Do nothing','Pay an unemployment allowance','Build a factory','Impose a fine on workers'], a: 1, w: 'The guarantee includes an allowance in lieu of work.' },
    { q: 'Tertiary sector growth in India has been driven especially by:', o: ['Only railways','IT, communication and services','Only farming','Mining'], a: 1, w: 'Software, BPOs, telecom, finance and trade.' },
    { q: 'Which of these is NOT a primary sector activity?', o: ['Fishing','Dairy','Bakery','Mining'], a: 2, w: 'A bakery manufactures — secondary.' },
    { q: 'The underemployment problem is greatest in:', o: ['Agriculture','Banking','Software','Tourism'], a: 0, w: 'Too many workers on too little land.' },
    { q: 'NITI Aayog replaced the:', o: ['Finance Commission','Planning Commission','Election Commission','RBI'], a: 1, w: 'In 2015 — from plan centralisation to cooperative federalism.' },
    { q: 'A street vendor belongs to:', o: ['Organised sector','Unorganised sector','Government service','Secondary sector'], a: 1, w: 'Self-employed, informal, no benefits — unorganised.' },
    { q: 'Which sector contributes the largest share of India\u2019s GDP today?', o: ['Primary','Secondary','Tertiary','None'], a: 2, w: 'Services lead both output and growth.' },
    { q: 'The mismatch in India is that the primary sector:', o: ['Employs most workers but produces the smallest GDP share','Employs few but produces most GDP','Has no workers','Is fully mechanised'], a: 0, w: 'Half the workers, a sixth of the GDP.' },
    { q: 'Which of these helps workers move out of agriculture?', o: ['Education and skills','Lower literacy','Less credit','Fewer roads'], a: 0, w: 'Human capital opens secondary/tertiary jobs.' },
    { q: 'Mahatma Gandhi\u2019s vision emphasised:', o: ['Heavy industry only','Village and cottage industries','Import dependence','No farming'], a: 1, w: 'Self-sufficient villages and khadi-based local production.' },
    { q: 'An SEZ is a:', o: ['Tax-free industrial zone with world-class facilities for exports','School zone','Farm belt','Cantonment'], a: 0, w: 'Special Economic Zones attract investment and exports.' },
    { q: 'During COVID-19 (2020), the hardest-hit workers were:', o: ['Government staff','Informal and migrant workers in the unorganised sector','Bank employees','Software engineers'], a: 1, w: 'Lockdowns destroyed informal livelihoods overnight.' },
    { q: 'Which of these is a tertiary activity supporting agriculture?', o: ['Ploughing','Cold storage and transport of produce','Weaving','Mining coal'], a: 1, w: 'Storage/logistics are services in the supply chain.' },
    { q: 'The "demographic dividend" refers to:', o: ['A young workforce that can boost growth if skilled','Population decline','More old people','Rising death rate'], a: 0, w: 'Skilling converts a young population into growth.' },
    { q: 'A worker in a factory with a written contract and PF benefits is:', o: ['Unorganised','Organised sector worker','Agricultural labourer','Self-employed'], a: 1, w: 'Formal terms define the organised sector.' }
  ]
};

window.NDATA['eco3'] = {
  notes: [
    { h: 'The chapter in one paragraph', b: 'Money solves barter\u2019s core problem — the <b>double coincidence of wants</b> — by acting as a medium of exchange. Modern money includes bank deposits payable by cheque. Banks keep a fraction of deposits as reserves and lend the rest — credit that creates <b>debt traps</b> when terms turn hostile (Swapna) or fuels growth when fair (Salim). India\u2019s <b>formal</b> sector (banks, cooperatives — supervised by the <b>RBI</b>) meets barely half of credit needs; the poor rely on costly <b>informal</b> lenders. <b>Self-Help Groups</b> bridge the gap, building savings and creditworthiness from below.' },
    { h: 'Money and the end of barter', b: 'In barter, a shoe-maker needing grain must find a farmer wanting shoes — a <b>double coincidence of wants</b>. Money — anything generally accepted in payment — removes the obstacle: sell shoes for money, buy grain with money. Early money was commodity (grain, cattle); modern money is currency and coins, and above all <b>bank deposits</b>, transferable by cheque — safer for large payments.' },
    { h: 'Modern money and deposits', b: 'A bank <b>deposit</b> is also money: salaries, payments and savings held in accounts can be transferred by <b>cheque</b> without cash. Cheques require no immediate counting or carrying of notes — the deposit itself circulates. In India, only the <b>Reserve Bank of India (RBI)</b> issues currency notes on behalf of the government.' },
    { h: 'How banks mediate credit', b: 'Banks hold only about <b>15% of deposits as cash reserves</b> to meet daily withdrawals; the rest is lent. Loans earn interest — the bank\u2019s main income — part of which returns to depositors as interest on savings. The loan-deposit cycle lets a rupee of deposits support several rupees of credit — banks "create" money through lending.' },
    { h: 'Terms of credit', b: 'Every loan carries <b>terms: the interest rate, collateral, documentation and repayment mode</b>. <b>Collateral</b> is the asset pledged — land, house, gold — forfeited on default. The poor lack collateral, so they are denied formal loans or pay far higher informal rates — the central mechanism of credit inequality.' },
    { h: 'Two borrowers: Salim and Swapna', b: '<b>Salim</b>, a fertiliser trader, takes a bank loan to complete a big order — credit <b>expands</b> his business and income. <b>Swapna</b>, a small cotton farmer whose crop fails, borrows from the <b>moneylender at a far higher rate</b>, pledging her land; the next good harvest barely repays the debt — the <b>debt trap</b>. Same credit system, opposite outcomes — because their terms of credit differ.' },
    { h: 'Formal and informal credit sources', b: '<b>Formal sources</b> — banks and cooperative societies — charge regulated rates and are supervised by the <b>RBI</b>, which checks lending to whom, at what terms. <b>Informal sources</b> — moneylenders, traders, employers, relatives, landowners — charge high rates, use coercion, and no one monitors them. The poor and small enterprises depend disproportionately on informal credit, so the RBI and banks push formal-sector expansion — branches, no-frills accounts, priority-sector lending.' },
    { h: 'Self-Help Groups', b: 'An <b>SHG</b> pools the small savings of 15-20 members (often rural women); members lend internally at decided rates, and after six months of regular saving the group can borrow from the bank — often without collateral — for needs from seeds to sewing machines. Timely repayment builds a credit record, and the group\u2019s collective discipline substitutes for collateral. The Grameen Bank of Bangladesh (Muhammad Yunus) pioneered the model; India has lakhs of SHGs linked to banks.' },
    { h: 'Credit and development', b: 'Cheap, timely, fair credit enables farmers to buy inputs, traders to stock goods, households to cope with emergencies — <b>credit is central to growth</b>. The policy task: grow formal credit, protect borrowers from usury, and build institutions (SHGs, cooperatives) that reach those banks hesitate to serve.' }
  ],
  quiz: [
    { q: 'The problem solved by money is:', o: ['Inflation','Double coincidence of wants','Taxation','Unemployment'], a: 1, w: 'Money removes the need for mutual wants.' },
    { q: 'Double coincidence of wants means:', o: ['Both parties must want what the other offers','Two loans at once','Double prices','Two currencies'], a: 0, w: 'Barter\u2019s core constraint.' },
    { q: 'Which of these is modern money?', o: ['Only notes','Bank deposits transferable by cheque','Cattle','Grain'], a: 1, w: 'Deposits and cheques are money as much as currency.' },
    { q: 'In India, currency notes are issued by:', o: ['SBI','The Reserve Bank of India','Ministry of Finance','NITI Aayog'], a: 1, w: 'The RBI issues currency on behalf of the government.' },
    { q: 'Banks keep roughly what fraction of deposits as cash reserves?', o: ['100%','50%','15%','1%'], a: 2, w: 'About 15% — the rest is lent out.' },
    { q: 'A bank\u2019s main source of income is:', o: ['Depositors\u2019 fees','The difference between lending and deposit interest','Printing notes','Government grants'], a: 1, w: 'The interest spread on loans.' },
    { q: 'Collateral is:', o: ['A fee for opening an account','An asset pledged against a loan, forfeited on default','A type of cheque','Interest rate'], a: 1, w: 'Land, house or gold commonly serve as collateral.' },
    { q: 'The four terms of credit are:', o: ['Interest rate, collateral, documentation, repayment mode','Price, tax, subsidy, discount','Name, age, address, income','Bank, branch, IFSC, PAN'], a: 0, w: 'These define any loan contract.' },
    { q: 'Swapna\u2019s story illustrates:', o: ['Successful banking','The debt trap — borrowing at high informal rates after crop failure','Money laundering','Insurance'], a: 1, w: 'Crop failure + moneylender + pledged land = debt trap.' },
    { q: 'Salim\u2019s story shows:', o: ['The debt trap','Credit enabling a trader to complete orders and earn more','Barter','Cashless economy'], a: 1, w: 'Timely formal credit expands business.' },
    { q: 'Which is a formal credit source?', o: ['Moneylender','Bank','Trader','Landowner'], a: 1, w: 'Banks and cooperatives are formal; supervised by the RBI.' },
    { q: 'The supervisor of the formal credit system is:', o: ['SEBI','The RBI','NITI Aayog','Election Commission'], a: 1, w: 'The RBI sets norms and monitors bank lending.' },
    { q: 'The poor rely mainly on:', o: ['Formal banks','Informal moneylenders','Foreign banks','Stock markets'], a: 1, w: 'No collateral pushes them to costly informal credit.' },
    { q: 'A Self-Help Group typically has:', o: ['2 members','15-20 members','1000 members','Only men'], a: 1, w: 'Small groups pool savings and lend internally.' },
    { q: 'SHGs can borrow from banks without collateral because:', o: ['Banks are charitable','Regular group savings and discipline build creditworthiness','Law bans collateral','Government pays the bank'], a: 1, w: 'The group\u2019s record substitutes for collateral.' },
    { q: 'The Grameen Bank model originated in:', o: ['India','Bangladesh (Muhammad Yunus)','USA','UK'], a: 1, w: 'Micro-credit for the poor began in Bangladesh.' },
    { q: 'Cheap and timely credit helps a farmer to:', o: ['Buy seeds and fertilisers before sowing','Avoid sowing','Pay higher moneylender rates','Stop farming'], a: 0, w: 'Working capital at the right time raises output.' },
    { q: 'Which of these is informal credit?', o: ['Cooperative society loan','Borrowing from a trader','Commercial bank loan','Regional rural bank loan'], a: 1, w: 'Traders and moneylenders are informal lenders.' },
    { q: 'Depositors keep money in banks because:', o: ['Banks force them','Of safety and interest earnings','Notes are banned','Cheques are decorative'], a: 1, w: 'Safety plus returns — deposits are money that earns.' },
    { q: 'The loan that "creates" money works because:', o: ['Printers run faster','Deposits are lent and re-deposited, multiplying credit','Banks hide cash','Interest is zero'], a: 1, w: 'The deposit-loan cycle expands credit beyond cash.' },
    { q: 'Higher informal interest rates reflect:', o: ['Better service','Monopoly and risk without regulation','Lower costs','Government subsidy'], a: 1, w: 'Unregulated lenders exploit borrowers\u2019 desperation.' },
    { q: 'A cheque is preferred for large payments because it is:', o: ['Prettier','Safer — no cash to carry or count','Colourful','Always free to print'], a: 1, w: 'Security and convenience of transfers.' },
    { q: 'RBI supervision of banks includes:', o: ['Setting lending norms and ensuring fair credit flow','Setting crop prices','Running panchayats','Fixing school fees'], a: 0, w: 'The RBI checks whom banks lend to, on what terms.' },
    { q: 'A debt trap deepens when:', o: ['Loans are repaid on time','Borrowing continues to repay earlier high-interest debt','Interest falls','Incomes rise'], a: 1, w: 'Each loan adds interest burden to the last.' },
    { q: 'Which group benefits most from SHGs?', o: ['Rich farmers','Rural women without collateral','Urban traders','Foreign investors'], a: 1, w: 'SHGs give the unbanked access to credit.' },
    { q: 'Formal credit in rural India meets roughly:', o: ['All needs','About half (or less) of credit needs','None','Double the need'], a: 1, w: 'The rest flows from informal sources.' }
  ]
};

window.NDATA['eco4'] = {
  notes: [
    { h: 'The chapter in one paragraph', b: '<b>Globalisation</b> is the deepening integration of economies through trade, investment, technology and migration of people. <b>MNCs</b> drive it — owning or controlling production in several countries, cutting costs via cheap labour and loose regulation. India <b>liberalised</b> after 1991, dismantling trade barriers; the <b>WTO (1995)</b> frames global rules, though critics say rich nations practise double standards. Impacts are mixed: consumers gain choice and low prices; efficient producers thrive (Maruti-Suzuki); but small producers (batteries, garments) and workers face brutal competition. The goal is <b>fair globalisation</b> — sharing its gains.' },
    { h: 'What is globalisation and what drives it', b: 'Globalisation = rapid <b>integration of markets and production</b> across countries: goods, services, investment, technology and people flow as never before. Its engines: <b>technology</b> — IT and telecommunications (a call-centre order crosses the planet instantly), cheap <b>container shipping</b> — plus policies of liberalisation. In policy since the 1990s, it is also as old as trade itself — the silk route trader was a globaliser too.' },
    { h: 'MNCs and cross-border production', b: 'An <b>MNC owns or controls production in more than one nation</b>. It locates factories where costs are lowest (China\u2019s labour, India\u2019s software skills) and markets are big. Devices: buying up local firms (Cargill\u2019s acquisition of Parakh Foods), joint ventures (Maruti-Suzuki — from import substitute to global exporter), and tightly managed supply chains where the MNC controls brand, design and quality while local firms manufacture.' },
    { h: 'Foreign trade and market integration', b: 'Foreign trade connects markets: Chinese toys in Indian shops, Indian software abroad. Producers compete across borders; prices tend to equalise. Trade lets countries specialise where they are efficient — but also exposes domestic producers to competition that can wipe out those who cannot upgrade (Indian toy and battery makers\u2019 experience).' },
    { h: 'Liberalisation after 1991', b: 'Till 1991 India was heavily protected: <b>tariffs</b> (import taxes) raised foreign prices, <b>quotas</b> limited quantities, and licensing restricted what could be produced or imported. The 1991 crisis forced reform: barriers were reduced — <b>liberalisation</b> — opening Indian markets to foreign goods and investment while letting Indian firms export and borrow abroad.' },
    { h: 'The WTO and its critics', b: 'Established in <b>1995</b>, the <b>World Trade Organisation</b> aims to make trade <b>free, fair and predictable</b> through negotiated rules — and it says freer trade benefits all. Critics point to double standards: rich countries continue to heavily subsidise and protect their own agriculture while pressing developing nations to open their markets — the reason talks like Doha have stalled.' },
    { h: 'Impacts: winners and losers', b: 'Winners: consumers (more choice — 800 TV channels, global brands), skilled professionals, firms that upgraded (Maruti-Suzuki, IT). Losers: small producers facing cheap imports (battery, capacitors, garment units closing), casual workers whose bargaining power erodes, farmers exposed to world price crashes. Employment has grown mainly in services, not the stable industrial jobs expected.' },
    { h: 'Fair globalisation', b: 'The answer is not to opt out of the world economy but to <b>spread its benefits</b>: enforce <b>labour laws</b> (minimum wages, safety) so competition doesn\u2019t ride on exploitation; support small producers with <b>credit, technology and marketing</b>; use <b>negotiation</b> — jointly with other developing countries at the WTO — rather than unilateral surrender. Globalisation should be a policy choice, not compulsion.' },
    { h: 'The balance so far', b: 'Globalisation has raised growth and ambitions — "India everywhere", from software to cinema — but its gains are unevenly distributed by class, region and skill. The measure of success NCERT sets: not GDP alone, but whether the gains reach workers, small enterprises and farmers.' }
  ],
  quiz: [
    { q: 'Globalisation is best described as:', o: ['Isolation of economies','Rapid integration of markets and production across countries','Colonisation','Only cultural exchange'], a: 1, w: 'Integration through trade, investment, technology and migration.' },
    { q: 'An MNC is a company that:', o: ['Exports only','Owns or controls production in more than one country','Is always small','Sells only locally'], a: 1, w: 'Multi-country production control defines an MNC.' },
    { q: 'Cargill in NCERT\u2019s example acquired:', o: ['Parakh Foods','Maruti','Amul','Tata Steel'], a: 0, w: 'The acquisition made Cargill a big player in Indian edible oils.' },
    { q: 'Maruti-Suzuki illustrates:', o: ['Failure of joint ventures','A joint venture that became a global small-car exporter','Import substitution','A cooperative'], a: 1, w: 'Indo-Japanese JV — from Indian roads to world markets.' },
    { q: 'MNCs set up production where:', o: ['Costs are lowest — cheap labour, favourable regulation','Taxes are highest','Land is frozen','Only in their home country'], a: 0, w: 'Cost-cutting drives location decisions.' },
    { q: 'Tariffs are:', o: ['Import taxes','Export gifts','Quotas','Subsidies'], a: 0, w: 'Taxes on imports raise their domestic price.' },
    { q: 'Removing trade barriers is called:', o: ['Globalisation','Liberalisation','Nationalisation','Privatisation'], a: 1, w: 'Liberalisation dismantled tariffs, quotas and licensing.' },
    { q: 'India liberalised its economy in:', o: ['1947','1971','1991','2010'], a: 2, w: 'The 1991 balance-of-payments crisis triggered reforms.' },
    { q: 'The WTO was established in:', o: ['1945','1991','1995','2001'], a: 2, w: '1995 — to frame global trade rules.' },
    { q: 'The WTO\u2019s stated goal is:', o: ['Protecting only rich countries','Making trade free, fair and predictable','Banning imports','Fixing exchange rates'], a: 1, w: 'Rules-based, predictable trade for all members.' },
    { q: 'A major criticism of rich nations at the WTO is:', o: ['They import too much','They subsidise their own agriculture while demanding open markets from the poor','They charge no tariffs','They obey every rule'], a: 1, w: 'Double standards that stall negotiations like Doha.' },
    { q: 'Cheaper Chinese toys in Indian shops illustrate:', o: ['Market integration through foreign trade','Import bans','Quotas','Barter'], a: 0, w: 'Foreign trade links and disciplines domestic markets.' },
    { q: 'Fair globalisation requires:', o: ['Banning all trade','Enforcing labour laws and supporting small producers','Only cheap labour','No negotiation'], a: 1, w: 'Share the gains — protect workers and small enterprises.' },
    { q: 'Globalisation has benefited most directly:', o: ['Small weavers','Skilled professionals and consumers with more choice','Landless labourers only','Nobody'], a: 1, w: 'IT professionals and consumers gained first and most visibly.' },
    { q: 'Workers\u2019 bargaining power weakens when:', o: ['Labour laws are enforced','Companies threaten to move jobs elsewhere','Wages rise','Unions strengthen'], a: 1, w: 'Exit threats discipline labour across borders.' },
    { q: 'Call centres and BPOs exemplify:', o: ['Agricultural trade','Services traded globally via IT and telecom','Heavy industry','Barter'], a: 1, w: 'Technology enables services to cross borders instantly.' },
    { q: 'The 1991 reforms were triggered by:', o: ['A foreign exchange crisis','A flood','War with China','A stock boom'], a: 0, w: 'Reserves barely covered two weeks of imports.' },
    { q: 'Quotas restrict trade by:', o: ['Taxing imports','Limiting the quantity of imports','Banning exports forever','Subsidising exports'], a: 1, w: 'Quantitative restrictions on how much may enter.' },
    { q: 'Indian battery and capacitor makers were squeezed by:', o: ['Rising demand','Competition from imports after liberalisation','Power cuts','Monsoons'], a: 1, w: 'NCERT\u2019s example of small producers hit by open markets.' },
    { q: 'Ford\u2019s India plant making cars with local inputs for export shows:', o: ['Global production chains','Self-reliance','Barter','Import substitution'], a: 0, w: 'Production is fragmented across countries to exploit advantages.' },
    { q: 'Special Economic Zones offer:', o: ['World-class facilities and duty-free export incentives','Free housing for all','Farming subsidies','Schools only'], a: 0, w: 'SEZs attract MNCs with infrastructure and tax benefits.' },
    { q: 'Globalisation of media means:', o: ['Fewer channels','Consumers enjoy vast choice — hundreds of TV channels and brands','Only local news','Radio only'], a: 1, w: 'Choice explosion is the consumer\u2019s clearest gain.' },
    { q: 'Farmers exposed to world prices face:', o: ['Guaranteed income','Price volatility from global markets','No change','Only profits'], a: 1, w: 'Boom-and-bust cycles pass through to small farmers.' },
    { q: 'Developing countries can strengthen their WTO position by:', o: ['Negotiating jointly','Surrendering individually','Leaving the WTO','Silence'], a: 0, w: 'Collective bargaining gives poor nations weight.' },
    { q: 'Employment gains from globalisation in India came mainly in:', o: ['Services','Heavy industry','Agriculture','Mining'], a: 0, w: 'IT, telecom and retail services absorbed most new jobs.' },
    { q: '"Globalisation by choice, not compulsion" means:', o: ['Isolation','Engaging with the world economy on fair, negotiated terms','No trade policy','Only imports'], a: 1, w: 'Active policy to share gains — not passive acceptance.' }
  ]
};
