/* PYQ-pattern supplements — Geography (tops each chapter to 100 MCQs) */
(function () {
  var N = window.NDATA;

  /* ==================== GEO1 · Resources and Development (27 + 73 = 100) ==================== */
  N.geo1.quiz.push(
    { q: 'Resources are a function of:', o: ['Human wants', 'Nature only', 'Technology only', 'Government policy'], a: 0, w: 'Nature creates matter; humans create resources.', p: 1 },
    { q: 'Which pairing is correct?', o: ['Biotic — flora; abiotic — rocks', 'Biotic — rocks; abiotic — fauna', 'Both biotic', 'Both abiotic'], a: 0, w: 'Living vs non-living.', p: 1 },
    { q: 'Community-owned resources include:', o: ['Village grazing grounds', 'Private farms', 'Family jewels', 'Personal cars'], a: 0, w: 'Accessible to all villagers.', p: 1 },
    { q: 'International resources are governed by:', o: ['Ocean resources beyond 200 km of the coast', 'River water', 'Farm land', 'City parks'], a: 0, w: 'The ocean\u2019s resources beyond national jurisdiction.', p: 1 },
    { q: 'Potential resources are those:', o: ['Found in a region but not yet used', 'Fully exhausted', 'Imported', 'Privately owned'], a: 0, w: 'E.g. Rajasthan\u2019s solar potential.', p: 1 },
    { q: 'Wind farms in Rajasthan are an example of:', o: ['Potential → developed resource', 'Stock', 'Reserve', 'Non-renewable'], a: 0, w: 'Technology turned potential into actual supply.' },
    { q: 'Assertion (A): Resources are free gifts of nature. Reason (R): Nature provides matter; humans add utility.', o: ['Both true, R explains A', 'A false, R true', 'A true, R false', 'Both false'], a: 1, w: 'They\u2019re not free gifts — human effort makes them.', p: 1 },
    { q: 'The problem created by indiscriminate resource use is:', o: ['Accumulation in few hands', 'Equal distribution', 'Abundance', 'Sustainability'], a: 0, w: 'Plus depletion and global warming.', p: 1 },
    { q: 'Agenda 21 is:', o: ['A sustainable development programme', 'A war treaty', 'A trade pact', 'A space mission'], a: 0, w: 'Adopted at Rio, 1992.', p: 1 },
    { q: 'The Rio Summit aimed to combine:', o: ['Economic growth with environmental protection', 'Growth with pollution', 'War with peace', 'Industry with mining'], a: 0, w: 'Development that lasts.' },
    { q: 'India\u2019s land area is about:', o: ['3.28 million sq km', '2.4 million sq km', '5 million sq km', '1.3 million sq km'], a: 0, w: '2.4% of the world\u2019s area.' },
    { q: 'Which relief feature of India occupies the largest share?', o: ['Plains — 43%', 'Mountains — 30%', 'Plateaus — 27%', 'Deserts'], a: 0, w: 'Plains: agriculture and industry.', p: 1 },
    { q: 'Mountains in India account for what share of land?', o: ['30%', '43%', '27%', '10%'], a: 0, w: 'Forests, tourism, water towers.', p: 1 },
    { q: 'The permanent pastures of India have:', o: ['Declined over time', 'Expanded', 'Stayed constant', 'Doubled'], a: 0, w: 'Grazing land shrank as cultivation spread.' },
    { q: 'The barren and wasteland category includes:', o: ['Rocky, arid, desert areas', 'Dense forests', 'Canals', 'Cities'], a: 0, w: 'Land unfit for cultivation without treatment.' },
    { q: 'Land put to non-agricultural uses includes:', o: ['Roads, buildings, industry', 'Fallow land', 'Forests', 'Pastures'], a: 0, w: 'Settlement and infrastructure swallow farmland.' },
    { q: 'Net sown area means:', o: ['Area sown at least once a year', 'Total land', 'Forest land', 'Fallow only'], a: 0, w: 'The actual crop footprint.' },
    { q: 'The current fallow is land left uncultivated for:', o: ['One or less than one year', 'Ten years', 'Five years', 'Forever'], a: 0, w: 'Short rest to regain fertility.', p: 1 },
    { q: 'Assertion (A): Land-use data shows cultivation expanding into pastures. Reason (R): Population pressure demands more food land.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The classic trade-off.', p: 1 },
    { q: 'The total degraded land of India is about:', o: ['130 million hectares', '13 million hectares', '300 million hectares', '30 million hectares'], a: 0, w: 'Approx 28% of land area.', p: 1 },
    { q: 'Water erosion is responsible for degrading about:', o: ['56% of degraded land', '10%', '90%', '5%'], a: 0, w: 'The biggest single cause.' },
    { q: 'Which state has degraded land from mining?', o: ['Jharkhand', 'Kerala', 'Punjab', 'Goa'], a: 0, w: 'Chhattisgarh, MP, Odisha too.', p: 1 },
    { q: 'Over-irrigation causes:', o: ['Waterlogging and salinity', 'Laterite', 'Black soil', 'Glaciers'], a: 0, w: 'Punjab, Haryana, W. UP.', p: 1 },
    { q: 'The mineral processing dust degrades land in:', o: ['Jharkhand-Chhattisgarh belt', 'Kerala coast', 'Rann of Kutch', 'Nilgiris'], a: 0, w: 'Also MP, Odisha.' },
    { q: 'Assertion (A): Terrace cultivation checks soil erosion. Reason (R): Steps on slopes slow running water.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Slower water carries less soil.' },
    { q: 'Shelter belts help in:', o: ['Checking wind erosion on plain lands', 'Irrigation', 'Mining', 'Fishing'], a: 0, w: 'Rows of trees shield fields.', p: 1 },
    { q: 'Strip cropping means:', o: ['Alternating crops in strips across the slope', 'One crop yearly', 'No crops', 'Rice only'], a: 0, w: 'Strips of grass slow run-off.' },
    { q: 'Contour ploughing is done:', o: ['Across the slope', 'Down the slope', 'In circles', 'Randomly'], a: 0, w: 'Plough lines act as tiny dams.' },
    { q: 'The soil of the northern plains is mainly:', o: ['Alluvial', 'Black', 'Laterite', 'Arid'], a: 0, w: 'River-deposited and fertile.' },
    { q: 'Alluvial soil is deficient in:', o: ['Nitrogen and humus', 'Potash', 'Lime', 'Iron'], a: 0, w: 'Needs fertiliser supplementation.', p: 1 },
    { q: 'Bangar differs from khadar because bangar:', o: ['Is older alluvium with kankar', 'Is newer', 'Has no lime', 'Is red'], a: 0, w: 'Old vs new flood deposits.', p: 1 },
    { q: 'Khadar is:', o: ['New alluvium, fine and fertile', 'Old alluvium', 'Black soil', 'Desert sand'], a: 0, w: 'Fresh flood renewal each year.' },
    { q: 'Which soil is ideal for cotton?', o: ['Black/regur', 'Laterite', 'Arid', 'Alluvial'], a: 0, w: 'Moisture-retentive clay.', p: 1 },
    { q: 'Black soil is formed from:', o: ['Basaltic lava', 'Granite', 'River silt', 'Wind dust'], a: 0, w: 'Deccan trap weathering.' },
    { q: 'Black soil is rich in:', o: ['Iron, lime, magnesium, alumina and potash', 'Nitrogen', 'Humus', 'Phosphorus'], a: 0, w: 'But poor in nitrogen and phosphorus.', p: 1 },
    { q: 'A unique property of black soil is that it is:', o: ['Moisture-retentive — self-ploughing', 'Quick-draining', 'Always saline', 'Pure sand'], a: 0, w: 'Deep cracks aerate it in summer.' },
    { q: 'Red soil gets its colour from:', o: ['Ferric oxide', 'Humus', 'Lime', 'Potash'], a: 0, w: 'Formed from crystalline igneous rocks.' },
    { q: 'Red soils are generally:', o: ['Less fertile, needing fertiliser', 'The most fertile', 'Saline', 'Perfect for cotton'], a: 0, w: 'Coarse and porous.' },
    { q: 'Laterite soil develops in:', o: ['High rainfall areas with alternate wet-dry seasons', 'Deserts', 'Glaciers', 'Deltas'], a: 0, w: 'Intense leaching strips nutrients.', p: 1 },
    { q: 'Laterite soil is used as:', o: ['Building material', 'Cement', 'Fuel', 'Paint'], a: 0, w: 'Hardened laterite becomes brick.', p: 1 },
    { q: 'Cashew grows well in:', o: ['Laterite soil', 'Black soil', 'Alluvial khadar', 'Peaty soil'], a: 0, w: 'And in hilly areas with depth.' },
    { q: 'Arid soil is:', o: ['Sandy and saline', 'Black and deep', 'Red and moist', 'Rich in humus'], a: 0, w: 'Lacks moisture and humus, high calcium.' },
    { q: 'Arid soil becomes cultivable when:', o: ['Irrigated', 'Heated', 'Flooded by sea', 'Left alone'], a: 0, w: 'Water transforms the desert margin.' },
    { q: 'Forest soils in snowy areas are:', o: ['Thin and acidic', 'Deep and alkaline', 'Black', 'Saline'], a: 0, w: 'Valley soils are fertile though.' },
    { q: 'The soil useful for tea in Assam is:', o: ['Forest/mountain soil', 'Arid', 'Laterite of Rajasthan', 'Black'], a: 0, w: 'Moist, fertile valley loam.' },
    { q: 'Gully erosion produces:', o: ['Ravines — like the Chambal badlands', 'Deltas', 'Beaches', 'Glaciers'], a: 0, w: 'Deep channels cut by runoff.', p: 1 },
    { q: 'Sheet erosion means:', o: ['Topsoil washed off as a thin layer', 'Deep gullies', 'Wind piles', 'Landslides'], a: 0, w: 'Water flows as a sheet.' },
    { q: 'Assertion (A): Soil is a renewable resource but takes centuries to form. Reason (R): Erosion can destroy it in a few years.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: '1 cm of soil = hundreds of years.', p: 1 },
    { q: 'The leading cause of soil erosion in India is:', o: ['Deforestation and overgrazing', 'Afforestation', 'Terrace farming', 'Shelter belts'], a: 0, w: 'Vegetation loss exposes topsoil.' },
    { q: 'Fill in the blank: Everything available in the environment satisfying human needs is a ______.', o: ['Resource', 'Product', 'Service', 'Commodity'], a: 0, w: 'Provided it\u2019s usable.' },
    { q: 'Fill in the blank: Resources classified on exhaustibility are renewable and ______.', o: ['Non-renewable', 'Biotic', 'National', 'Potential'], a: 0, w: 'Minerals, fossil fuels.' },
    { q: 'Fill in the blank: The ______ Summit adopted Agenda 21.', o: ['Rio de Janeiro', 'Paris', 'Kyoto', 'Geneva'], a: 0, w: 'June 1992.' },
    { q: 'Fill in the blank: Land degrades through mining, overgrazing and over-______.', o: ['Irrigation', 'Education', 'Plantation', 'Afforestation'], a: 0, w: 'Waterlogging and salinity follow.' },
    { q: 'Fill in the blank: The ______ soil is also called regur.', o: ['Black', 'Red', 'Laterite', 'Alluvial'], a: 0, w: 'From Marathi "kabar" — black cotton soil.' },
    { q: 'Fill in the blank: Khadar and bangar are varieties of ______ soil.', o: ['Alluvial', 'Arid', 'Forest', 'Laterite'], a: 0, w: 'New vs old deposits.' },
    { q: 'Match: (A) Alluvial (B) Black (C) Laterite (D) Arid with (1) cotton (2) northern plains (3) Rajasthan (4) leached:', o: ['A-2, B-1, C-4, D-3', 'A-2, B-4, C-1, D-3', 'A-1, B-2, C-4, D-3', 'A-2, B-1, C-3, D-4'], a: 0, w: 'Soil-crop-geography pairs.', p: 1 },
    { q: 'Match: (A) Contour ploughing (B) Terrace farming (C) Strip cropping (D) Shelter belts with (1) steps on slopes (2) ploughing across slope (3) tree rows (4) alternate strips:', o: ['A-2, B-1, C-4, D-3', 'A-2, B-4, C-1, D-3', 'A-1, B-2, C-4, D-3', 'A-2, B-1, C-3, D-4'], a: 0, w: 'The four conservation methods.', p: 1 },
    { q: 'Match: (A) Jharkhand (B) Punjab (C) Chambal (D) Rajasthan with (1) over-irrigation salinity (2) mining waste (3) arid soil (4) gully ravines:', o: ['A-2, B-1, C-4, D-3', 'A-2, B-4, C-1, D-3', 'A-1, B-2, C-4, D-3', 'A-2, B-1, C-3, D-4'], a: 0, w: 'Degradation geography.', p: 1 },
    { q: 'Which of the following statements is/are true? (I) Alluvial soil covers the largest area. (II) Black soil retains moisture. (III) Laterite is highly fertile.', o: ['I and II', 'II and III', 'I and III', 'All'], a: 0, w: 'Laterite is leached and poor.', p: 1 },
    { q: 'Which is NOT a cause of land degradation?', o: ['Afforestation', 'Mining', 'Overgrazing', 'Industry'], a: 0, w: 'Afforestation heals land.' },
    { q: 'The state with the largest area under permanent pastures declines due to:', o: ['Overgrazing', 'More rain', 'Fewer cattle', 'Irrigation'], a: 0, w: 'Pressure of livestock.' },
    { q: 'Assertion (A): Black soil needs less irrigation for cotton. Reason (R): Its clay holds moisture for long.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Moisture retention is its signature.' },
    { q: 'Assertion (A): Laterite soils are fertile. Reason (R): Heavy rainfall leaches silica and nutrients.', o: ['Both true, R explains A', 'A false, R true', 'A true, R false', 'Both false'], a: 1, w: 'Leaching makes them infertile.', p: 1 },
    { q: 'The first international Earth Summit was held in:', o: ['1992', '1972', '2002', '1987'], a: 0, w: 'Rio de Janeiro, 1992.' },
    { q: 'The concept of sustainable development came from:', o: ['Brundtland Commission report', 'Kyoto Protocol', 'WTO', 'IMF'], a: 0, w: '1987 "Our Common Future".', p: 1 },
    { q: 'Soil erosion by wind is most severe in:', o: ['Arid Rajasthan', 'Kerala', 'Assam', 'Bengal delta'], a: 0, w: 'Loose dry sand blows away.' },
    { q: 'Which soil covers about 40% of India\u2019s land?', o: ['Alluvial', 'Black', 'Red', 'Laterite'], a: 0, w: 'The most extensive.' },
    { q: 'Which crop suits black soil best after cotton?', o: ['Sugarcane', 'Tea', 'Jute', 'Apple'], a: 0, w: 'Cane also loves the moisture-holding clay.' },
    { q: 'The right sequence of soil horizons from top is:', o: ['Topsoil, subsoil, parent rock', 'Parent rock, topsoil, subsoil', 'Subsoil, topsoil, rock', 'Random'], a: 0, w: 'O/A → B → C/R horizons.', p: 1 },
    { q: 'Which of the following is a stock rather than a resource?', o: ['Ocean water without desalination tech', 'Coal in mines', 'Wind energy', 'Farm soil'], a: 0, w: 'No economic technology yet.', p: 1 },
    { q: 'National resources include:', o: ['Railways, forests, wildlife within territory', 'Private cars', 'Household savings', 'Family lands'], a: 0, w: 'Owned by the nation-state.' }
  );

  /* ==================== GEO2 · Forest and Wildlife (26 + 74 = 100) ==================== */
  N.geo2.quiz.push(
    { q: 'Biodiversity is richest in which forest type?', o: ['Tropical rainforest', 'Thorn forest', 'Montane', 'Mangrove'], a: 0, w: 'Maximum species density on earth.', p: 1 },
    { q: 'India is one of the world\u2019s:', o: ['17 mega-biodiverse countries', '5 mega-rich countries', '100+ biodiverse countries', 'Least biodiverse'], a: 0, w: 'With 8% of species on 2.4% land.' },
    { q: 'Genetic diversity means:', o: ['Variation within a species', 'Number of ecosystems', 'Number of species', 'Habitat variety'], a: 0, w: 'E.g. 1,000+ rice varieties in India.', p: 1 },
    { q: 'Ecosystem diversity refers to:', o: ['Variety of habitats/ecosystems', 'Gene pools', 'Species counts', 'Individuals'], a: 0, w: 'Deserts to coral reefs.' },
    { q: 'Which is an endangered species?', o: ['Black buck', 'Crow', 'Peacock', 'Sparrow'], a: 0, w: 'NCERT\u2019s example.', p: 1 },
    { q: 'Which is a vulnerable species?', o: ['Gangetic dolphin', 'House sparrow', 'Cattle', 'Dog'], a: 0, w: 'One step before endangered.', p: 1 },
    { q: 'Blue sheep and wild mango are:', o: ['Rare species', 'Extinct', 'Endemic', 'Normal'], a: 0, w: 'Small localised populations.', p: 1 },
    { q: 'Mithun of Arunachal is an example of:', o: ['Endemic species', 'Extinct', 'Migratory', 'Vulnerable'], a: 0, w: 'Found only there.' },
    { q: 'Asiatic cheetah is:', o: ['Extinct in India', 'Abundant', 'Endemic', 'Vulnerable'], a: 0, w: 'Some survive only in Iran.', p: 1 },
    { q: 'Pink-headed duck is:', o: ['Extinct', 'Endemic', 'Common', 'Migratory'], a: 0, w: 'Gone forever.' },
    { q: 'Assertion (A): Species extinction is irreversible. Reason (R): Once gone, genetic material cannot be recovered naturally.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The finality of extinction.', p: 1 },
    { q: 'Main causes of depletion are:', o: ['Habitat loss, poaching, over-exploitation', 'Afforestation', 'Conservation', 'Rainfall'], a: 0, w: 'Human pressure in all forms.', p: 1 },
    { q: '"Jhum" causes deforestation because:', o: ['Repeated slash-and-burn cycles shorten fallow', 'It plants trees', 'It irrigates', 'It builds parks'], a: 0, w: 'Land gets no time to recover.', p: 1 },
    { q: 'River valley projects destroy forests by:', o: ['Submerging large tracts', 'Irrigating them', 'Planting trees', 'Fencing'], a: 0, w: 'Narmada Sagar, Tehri examples.', p: 1 },
    { q: 'Which is a reason for poaching?', o: ['Illegal trade in hides, horns, feathers', 'Afforestation', 'Zoos', 'Rainfall'], a: 0, w: 'Money drives the slaughter.' },
    { q: 'Assertion (A): Colonial forest laws alienated communities. Reason (R): The state reserved trees and criminalised customary use.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The roots of community conflict.', p: 1 },
    { q: 'Reserved forests are:', o: ['Govt-controlled, no local rights', 'Open to all', 'Village-owned', 'Private'], a: 0, w: 'The most protected.', p: 1 },
    { q: 'Protected forests allow:', o: ['Subsistence use by locals', 'Total prohibition', 'Clear felling', 'Industry only'], a: 0, w: 'Limited rights.' },
    { q: 'Unclassed forests belong to:', o: ['Communities or individuals', 'The Centre', 'Industry', 'The army'], a: 0, w: 'Especially in NE states.' },
    { q: 'Madhya Pradesh has the largest area under:', o: ['Reserved forests', 'Unclassed', 'Mangroves', 'None'], a: 0, w: 'Followed by other big states.' },
    { q: 'The Wildlife Protection Act came in:', o: ['1972', '1980', '1988', '1952'], a: 0, w: 'Along with Forest Conservation Act 1980.', p: 1 },
    { q: 'Project Tiger began in:', o: ['1973', '1969', '1985', '1992'], a: 0, w: '27 reserves now.', p: 1 },
    { q: 'Project Tiger was launched from:', o: ['Jim Corbett National Park', 'Kaziranga', 'Gir', 'Periyar'], a: 0, w: 'Corbett — first tiger reserve.', p: 1 },
    { q: 'The tiger is an "umbrella species" because:', o: ['Protecting it protects whole ecosystems', 'It is biggest', 'It flies', 'It eats plants'], a: 0, w: 'Habitat saved for tiger = habitat for all.', p: 1 },
    { q: 'National Forest Policy targets forest cover of:', o: ['33% of the country', '50%', '20%', '10%'], a: 0, w: '60% in hills, 33% plains.', p: 1 },
    { q: 'Assertion (A): Actual forest cover is below target. Reason (R): Enforcement and regeneration lag behind degradation.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: '~25% actual.' },
    { q: 'Amrita Devi Bishnoi died protecting:', o: ['Khejri trees', 'Tigers', 'Rivers', 'Land records'], a: 0, w: '1730 — 363 Bishnois fell with her.', p: 1 },
    { q: 'The Bishnois live mainly in:', o: ['Rajasthan', 'Kerala', 'Assam', 'Punjab'], a: 0, w: 'Marwar\u2019s desert ecologists.' },
    { q: 'The Chipko movement\u2019s iconic action was:', o: ['Tree hugging', 'Fasting in Delhi', 'Court cases', 'Elections'], a: 0, w: 'Women hugged trees to save them.' },
    { q: 'Chipko began in the village of:', o: ['Reni (Garhwal)', 'Jallianwala', 'Champaran', 'Bardoli'], a: 0, w: 'Gaura Devi led the women of Reni.', p: 1 },
    { q: 'Chipko\u2019s most famous leader was:', o: ['Sunderlal Bahuguna', 'Medha Patkar', 'Rajendra Singh', 'Amrita Devi'], a: 0, w: 'He carried Chipko across the Himalaya.' },
    { q: 'Beej Bachao Andolan conserves:', o: ['Traditional seeds', 'Tigers', 'Rivers', 'Soil'], a: 0, w: 'Tehri\u2019s farmers save native varieties.', p: 1 },
    { q: 'Joint Forest Management started in:', o: ['Odisha (1988)', 'Kerala (1972)', 'MP (2000)', 'UP (1950)'], a: 0, w: 'Arabari\u2019s experiment scaled up.', p: 1 },
    { q: 'Under JFM, communities get:', o: ['A share of forest produce', 'Cash only', 'Nothing', 'Salaries'], a: 0, w: 'Usufruct rights in return for protection.' },
    { q: 'Which is a keystone mangrove species?', o: ['Sundari tree', 'Teak', 'Pine', 'Bamboo'], a: 0, w: 'Sundarbans\u2019 namesake.', p: 1 },
    { q: 'The Himalayan yew is threatened because:', o: ['Its extract (taxol) fights cancer', 'It is poisonous', 'It is ugly', 'It is fast-growing'], a: 0, w: 'Over-harvest for medicine.', p: 1 },
    { q: 'Fill in the blank: The ______ community sacrificed lives for khejri trees in 1730.', o: ['Bishnoi', 'Santhal', 'Gond', 'Meena'], a: 0, w: 'Amrita Devi Bishnoi.' },
    { q: 'Fill in the blank: Chipko means to ______.', o: ['Hug/stick', 'Cut', 'Burn', 'Sell'], a: 0, w: 'Hug the trees.' },
    { q: 'Fill in the blank: The ______ Amendment made local forest protection participatory via JFM.', o: ['1988 National Forest Policy', '1972 Act', '1952 policy', '2005 Act'], a: 0, w: '1988 policy enabled JFM.' },
    { q: 'Fill in the blank: Project Tiger began with ______ reserves.', o: ['9', '27', '50', '2'], a: 0, w: 'Nine, now grown many-fold.' },
    { q: 'Fill in the blank: ______ forests are legally the most strictly protected.', o: ['Reserved', 'Protected', 'Unclassed', 'Village'], a: 0, w: 'No local rights.' },
    { q: 'Match: (A) Amrita Devi (B) Sunderlal Bahuguna (C) Rajendra Singh (D) Medha Patkar with (1) Chipko (2) waterman/johads (3) Bishnoi/khejri (4) Narmada:', o: ['A-3, B-1, C-2, D-4', 'A-3, B-2, C-1, D-4', 'A-1, B-3, C-2, D-4', 'A-3, B-1, C-4, D-2'], a: 0, w: 'Four movements, four leaders.', p: 1 },
    { q: 'Match: (A) Kaziranga (B) Gir (C) Periyar (D) Simlipal with (1) lions (2) rhinos (3) elephants (4) Odisha biosphere:', o: ['A-2, B-1, C-3, D-4', 'A-2, B-3, C-1, D-4', 'A-1, B-2, C-3, D-4', 'A-2, B-1, C-4, D-3'], a: 0, w: 'The map-work parks.', p: 1 },
    { q: 'Match: (A) 1972 (B) 1973 (C) 1730 (D) 1988 with (1) Project Tiger (2) Amrita Devi (3) Wildlife Act (4) JFM/NFP:', o: ['A-3, B-1, C-2, D-4', 'A-3, B-2, C-1, D-4', 'A-1, B-3, C-2, D-4', 'A-3, B-1, C-4, D-2'], a: 0, w: 'Conservation timeline.', p: 1 },
    { q: 'Which of the following statements is/are true? (I) India has 8% of world species. (II) Species loss is accelerating. (III) All endangered species are protected perfectly.', o: ['I and II', 'II and III', 'I and III', 'All'], a: 0, w: 'Protection is incomplete — III false.', p: 1 },
    { q: 'Which of these is NOT a threat to biodiversity?', o: ['Afforestation', 'Poaching', 'Jhum', 'Dams'], a: 0, w: 'Planting trees restores habitat.' },
    { q: 'Which forest type covers the highest share of India\u2019s forest area?', o: ['Tropical deciduous (monsoon)', 'Rainforest', 'Thorn', 'Alpine'], a: 0, w: 'Monsoon forests dominate.', p: 1 },
    { q: ' Assertion (A): Deciduous forests shed leaves. Reason (R): This conserves water in the dry season.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Adaptation to seasonality.', p: 1 },
    { q: 'Mangrove roots adapt by:', o: ['Breathing roots (pneumatophores)', 'Deep tap roots', 'Shedding', 'Flying'], a: 0, w: 'They poke above the salty mud.', p: 1 },
    { q: 'Sundarbans\u2019 flagship animal is:', o: ['Royal Bengal tiger', 'Lion', 'Snow leopard', 'Elephant'], a: 0, w: 'Swimming tigers of the delta.', p: 1 },
    { q: 'Which is a wildlife corridor conservation success?', o: ['Elephant corridors', 'Metro lines', 'Canals', 'Dams'], a: 0, w: 'Corridors connect fragmented habitats.', p: 1 },
    { q: 'In situ conservation means:', o: ['Protecting species in natural habitat', 'Zoos only', 'Seed banks only', 'Lab breeding'], a: 0, w: 'Parks, sanctuaries, reserves.', p: 1 },
    { q: 'Ex situ conservation includes:', o: ['Zoos, seed/gene banks', 'National parks', 'Sanctuaries', 'Biosphere reserves'], a: 0, w: 'Off-site protection.', p: 1 },
    { q: 'Biosphere reserves combine:', o: ['Core (strict), buffer (research) and transition (use) zones', 'Only cores', 'Only cities', 'Only farms'], a: 0, w: '18 in India.', p: 1 },
    { q: 'The Nilgiri Biosphere Reserve spans:', o: ['Kerala, TN, Karnataka', 'Bengal only', 'Assam', 'Punjab'], a: 0, w: 'The first and most famous.', p: 1 },
    { q: 'Assertion (A): Local communities are essential to conservation. Reason (R): Their livelihoods depend on forests and they hold traditional knowledge.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The lesson of Bishnoi, Chipko, JFM.', p: 1 },
    { q: 'Which state has the maximum forest cover in India (per recent surveys)?', o: ['Madhya Pradesh', 'Haryana', 'Punjab', 'Delhi'], a: 0, w: 'By area — MP leads.', p: 1 },
    { q: 'The forest cover share of India\u2019s area is about:', o: ['21-25%', '33%', '40%', '10%'], a: 0, w: 'Below the policy target.', p: 1 },
    { q: ' Assertion (A): Protected forests face less degradation than reserved ones. Reason (R): Reserved forests have stricter legal protection.', o: ['A false, R true', 'Both true, R explains A', 'Both true, R does not explain A', 'A true, R false'], a: 0, w: 'Reserved are better protected — A inverted.' },
    { q: 'The case of the Arabari forest (WS Bengal) showed:', o: ['Community protection can regrow forests', 'Sal is worthless', 'Villagers destroy forests always', 'Only police work'], a: 0, w: 'The seed of JFM.', p: 1 },
    { q: 'Which of these is a globally threatened Indian vulture\u2019s cause of death?', o: ['Diclofenac (cattle drug)', 'Cold', 'Rain', 'Tourism'], a: 0, w: 'Vultures died eating treated carcasses.', p: 1 },
    { q: 'Cold desert fauna includes:', o: ['Snow leopard, ibex', 'Tiger, rhino', 'Elephant, gaur', 'Lion, deer'], a: 0, w: 'Ladakh\u2019s high-altitude wildlife.', p: 1 },
    { q: 'Gharial is a:', o: ['Fish-eating crocodilian of rivers', 'Bird', 'Goat', 'Fish'], a: 0, w: 'Critically endangered.', p: 1 },
    { q: 'Fill in the blank: India\u2019s forest policy aims at 33% cover including 60% in ______.', o: ['Hills/mountains', 'Plains', 'Deserts', 'Coasts'], a: 0, w: 'Hill slopes need trees for stability.' },
    { q: 'Fill in the blank: The conservation approach protecting entire ecosystems is called ______ conservation.', o: ['In situ', 'Ex situ', 'Captive', 'Digital'], a: 0, w: 'In place.' },
    { q: 'Which is the largest biosphere reserve of India?', o: ['Gulf of Mannar', 'Nilgiri', 'Sundarbans', 'Nanda Devi'], a: 0, w: 'Gulf of Mannar (area-wise).', p: 1 },
    { q: 'Assertion (A): Sacred groves protect biodiversity. Reason (R): Communities conserve forest patches for religious reasons.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'E.g. Sarnas of central India, devarakadus of Karnataka.', p: 1 },
    { q: 'Which of the following best describes "biotic interference"?', o: ['Human/living impact on forests', 'Machine damage', 'Climate change', 'Meteor strikes'], a: 0, w: 'Grazing, lopping, firewood collection.' },
    { q: 'Wildlife crime control in India is led by:', o: ['WCCB and forest departments', 'Army', 'Navy', 'Municipality'], a: 0, w: 'Wildlife Crime Control Bureau.', p: 1 },
    { q: 'The introduction of exotic species (like lantana) harms forests by:', o: ['Invasively replacing native plants', 'Adding shade', 'Fixing nitrogen', 'Attracting rain'], a: 0, w: 'Invasive weeds choke natives.', p: 1 },
    { q: 'Which pair is matched correctly?', o: ['Kaziranga — Assam — rhino', 'Gir — Assam — lion', 'Periyar — Rajasthan — tiger', 'Simlipal — Kerala — elephant'], a: 0, w: 'The classic map-work pair.', p: 1 },
    { q: 'Forest Survey of India publishes:', o: ['The State of Forest Report', 'Census', 'Budget', 'GDP data'], a: 0, w: 'Biennial forest-cover assessment.', p: 1 }
  );

  /* ==================== GEO3 · Water Resources (26 + 74 = 100) ==================== */
  N.geo3.quiz.push(
    { q: 'The total renewable water resources of India rank us:', o: ['4th in the world', '1st', '50th', 'Last'], a: 0, w: 'Rich in total, poor per head.', p: 1 },
    { q: 'Per capita water availability in India has:', o: ['Fallen steadily', 'Risen', 'Doubled', 'Stayed fixed'], a: 0, w: 'Population up, water same.', p: 1 },
    { q: 'India receives rainfall mainly in:', o: ['4 monsoon months', 'All 12 months', 'January', 'December'], a: 0, w: 'Concentrated, hence floods+scarcity.' },
    { q: 'Assertion (A): India\u2019s water crisis is of quality as much as quantity. Reason (R): Rivers carry untreated domestic and industrial waste.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Pollution shrinks usable water.', p: 1 },
    { q: 'Groundwater overuse is most intense in:', o: ['Punjab-Haryana-western UP', 'Kerala', 'Arunachal', 'Ladakh'], a: 0, w: 'Green Revolution water mining.', p: 1 },
    { q: 'Free/subsidised electricity leads to:', o: ['Over-pumping of groundwater', 'Water conservation', 'Rain harvesting', 'River cleaning'], a: 0, w: 'Zero-cost power = zero restraint.', p: 1 },
    { q: 'The majority of India\u2019s freshwater is used by:', o: ['Agriculture', 'Industry', 'Homes', 'Parks'], a: 0, w: '~80% irrigation.', p: 1 },
    { q: 'Hydropower share in India\u2019s electricity is about:', o: ['A quarter', '90%', '5%', '1%'], a: 0, w: 'Roughly 25%.' },
    { q: 'The first multipurpose project of India (1948) was:', o: ['Damodar Valley Corporation', 'Bhakra', 'Tehri', 'Sardar Sarovar'], a: 0, w: 'Modeled on TVA.', p: 1 },
    { q: 'DVC was modeled on the USA\u2019s:', o: ['Tennessee Valley Authority', 'Hoover Dam', 'Grand Coulee', 'NASA'], a: 0, w: 'Flood control + power + navigation.' },
    { q: 'Which dam is on the Sutlej?', o: ['Bhakra-Nangal', 'Hirakud', 'Tehri', 'Nagarjuna Sagar'], a: 0, w: 'The highest gravity dam era icon.', p: 1 },
    { q: 'Hirakud is on the:', o: ['Mahanadi', 'Krishna', 'Kaveri', 'Godavari'], a: 0, w: 'Odisha, one of the longest dams.', p: 1 },
    { q: 'Nagarjuna Sagar is on the:', o: ['Krishna', 'Narmada', 'Tapi', 'Son'], a: 0, w: 'Andhra-Telangana border.', p: 1 },
    { q: 'Tehri dam stands on:', o: ['Bhagirathi + Bhilangana', 'Alaknanda only', 'Yamuna', 'Mandakini'], a: 0, w: 'India\u2019s tallest.' },
    { q: 'Sardar Sarovar is on:', o: ['Narmada', 'Tapi', 'Mahi', 'Sabarmati'], a: 0, w: 'Gujarat\u2019s giant.', p: 1 },
    { q: 'Assertion (A): Nehru later criticised the dam mania. Reason (R): He saw big projects displacing people and destroying nature.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'His "temples" sermon evolved.', p: 1 },
    { q: 'Resistance movements against dams include:', o: ['Narmada Bachao Andolan', 'Chipko', 'Beej Bachao', 'Swadeshi'], a: 0, w: 'Medha Patkar\u2019s NBA.', p: 1 },
    { q: 'The Sardar Sarovar oustees’ core issue was:', o: ['Incomplete rehabilitation', 'Water taste', 'Power tariffs', 'Fish size'], a: 0, w: 'Resettlement promises unkept.', p: 1 },
    { q: 'Which of the following is NOT a usual purpose of multipurpose dams?', o: ['Software development', 'Irrigation', 'Flood control', 'Power'], a: 0, w: 'Dams don\u2019t code.' },
    { q: 'Sedimentation of reservoirs:', o: ['Reduces storage capacity', 'Purifies water', 'Increases power', 'Helps fish'], a: 0, w: 'Silt fills the bed.' },
    { q: 'Canal irrigation causes:', o: ['Waterlogging and soil salinity', 'Laterite', 'Erosion by wind', 'Glaciers'], a: 0, w: 'The Indira Gandhi Canal\u2019s lesson.', p: 1 },
    { q: 'The World Commission on Dams concluded:', o: ['Dams underperform promises while social costs are high', 'All dams must go', 'Dams are perfect', 'Only small dams exist'], a: 0, w: 'A global audit of big dams.', p: 1 },
    { q: 'Assertion (A): Rainwater harvesting is the sustainable path. Reason (R): It recharges groundwater where it falls.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Decentralised water security.', p: 1 },
    { q: 'Khadins are traditional harvesting structures of:', o: ['Rajasthan', 'Assam', 'Kerala', 'Bengal'], a: 0, w: 'Embanked fields hold rain.' },
    { q: 'Johads are:', o: ['Small earthen check dams', 'Wells', 'Canals', 'Tanks on roofs'], a: 0, w: 'Revived by Tarun Bharat Sangh.' },
    { q: 'Tankas are used to store:', o: ['Roof-collected rainwater', 'River water', 'Sea water', 'Sewage'], a: 0, w: 'Bikaner\u2019s underground tanks.' },
    { q: 'Bamboo drip irrigation belongs to:', o: ['Meghalaya', 'Punjab', 'Gujarat', 'Tamil Nadu'], a: 0, w: '200-year-old tribal technique.', p: 1 },
    { q: 'Kuls are irrigation channels of:', o: ['Himachal hills', 'Kerala backwaters', 'Rajasthan desert', 'Bengal delta'], a: 0, w: 'Gravity channels from streams.' },
    { q: 'The rooftop harvesting law (2003) was passed by:', o: ['Tamil Nadu', 'Bihar', 'Odisha', 'Goa'], a: 0, w: 'First state to mandate it.', p: 1 },
    { q: 'Rajendra Singh\u2019s johad revival happened in:', o: ['Alwar, Rajasthan', 'Patna, Bihar', 'Coimbatore, TN', 'Nagpur'], a: 0, w: 'Five dried rivers flowed again.', p: 1 },
    { q: 'Assertion (A): The Arvari river came back to life. Reason (R): Community johads recharged its aquifer.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Alwar\u2019s miracle of water.' },
    { q: 'Fill in the blank: The ______ canal transformed NW Rajasthan\u2019s agriculture.', o: ['Indira Gandhi', 'Suez', 'Panama', 'Upper Ganga'], a: 0, w: 'But also brought salinity.' },
    { q: 'Fill in the blank: ______ is called the "waterman of India".', o: ['Rajendra Singh', 'Medha Patkar', 'Bahuguna', 'Sarabhai'], a: 0, w: 'For johad revival.' },
    { q: 'Fill in the blank: The ______ Valley project was India\u2019s first multipurpose scheme.', o: ['Damodar', 'Narmada', 'Krishna', 'Kaveri'], a: 0, w: '1948, DVC.' },
    { q: 'Fill in the blank: Tankas collect ______ water in Bikaner.', o: ['Rain', 'Sea', 'River', 'Waste'], a: 0, w: 'Rooftop rain harvesting.' },
    { q: 'Fill in the blank: ______ dams trap silt and shrink reservoir life.', o: ['Large', 'Tiny', 'No', 'Underground'], a: 0, w: 'Sedimentation.' },
    { q: 'Fill in the blank: The Sardar Sarovar height was raised after Supreme Court orders in ______.', o: ['1999-2000', '1947', '1975', '2015'], a: 0, w: 'NBA fought it to the apex court.' },
    { q: 'Match: (A) Bhakra (B) Hirakud (C) Nagarjuna Sagar (D) Tehri with (1) Krishna (2) Sutlej (3) Bhagirathi (4) Mahanadi:', o: ['A-2, B-4, C-1, D-3', 'A-2, B-1, C-4, D-3', 'A-4, B-2, C-1, D-3', 'A-2, B-4, C-3, D-1'], a: 0, w: 'The map-work dams.', p: 1 },
    { q: 'Match: (A) Khadin (B) Tankas (C) Bamboo drip (D) Kul with (1) Bikaner roofs (2) Meghalaya (3) Himachal (4) Rajasthan fields:', o: ['A-4, B-1, C-2, D-3', 'A-4, B-2, C-1, D-3', 'A-1, B-4, C-2, D-3', 'A-4, B-1, C-3, D-2'], a: 0, w: 'Traditional water wisdom.', p: 1 },
    { q: 'Match: (A) 1948 (B) 1973 (C) 1985-91 (D) 2003 with (1) NBA begins (2) DVC (3) TN rooftop law (4) Narmada clearance era:', o: ['A-2, B-4, C-1, D-3', 'A-2, B-1, C-4, D-3', 'A-2, B-4, C-3, D-1', 'A-4, B-2, C-1, D-3'], a: 0, w: 'Water politics timeline.', p: 1 },
    { q: 'Which of the following statements is/are true? (I) Dams displace millions. (II) Big irrigation creates waterlogging. (III) Dams are free of ecological cost.', o: ['I and II', 'II and III', 'I and III', 'All'], a: 0, w: 'III is false — costs are real.', p: 1 },
    { q: 'Which of these is NOT a traditional water structure?', o: ['Khadin', 'Johad', 'Tankas', 'Skyscraper'], a: 3, w: 'Obvious intruder.' },
    { q: 'The hydrological cycle\u2019s engine is:', o: ['The sun', 'Dams', 'Wind only', 'Moon'], a: 0, w: 'Solar evaporation drives it.' },
    { q: 'Assertion (A): Water is a renewable resource. Reason (R): The hydrological cycle replenishes it — but overuse outpaces renewal locally.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Renewable ≠ unlimited.', p: 1 },
    { q: 'The Noyyal\u2019s pollution case (NCERT box) concerned:', o: ['Textile dyeing effluents', 'Sewage only', 'Oil spills', 'Mining'], a: 0, w: 'Tirupur\u2019s rivers ran coloured.', p: 1 },
    { q: 'Fluorosis is caused by:', o: ['Excess fluoride in groundwater', 'Salt', 'Iron', 'Lead'], a: 0, w: 'Geogenic contamination.', p: 1 },
    { q: 'Arsenic contamination plagues:', o: ['Bengal delta aquifers', 'Rajasthan dunes', 'Deccan traps', 'Kerala coast'], a: 0, w: 'Shallow tube wells.', p: 1 },
    { q: 'Which Indian river is the most polluted stretch near Delhi?', o: ['Yamuna', 'Brahmaputra', 'Mahanadi', 'Godavari'], a: 0, w: 'Barely flows in the capital.' },
    { q: 'Assertion (A): Urban flooding has worsened. Reason (R): Concreting over recharge zones kills infiltration.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Chennai, Mumbai lessons.', p: 1 },
    { q: 'Virtual water refers to:', o: ['Water embedded in producing goods (e.g. crops)', 'Distilled water', 'Sea water', 'Bottled water'], a: 0, w: 'Exporting rice exports water.', p: 1 },
    { q: 'Cropping rice in Punjab is water-risky because:', o: ['It is a water-guzzler outside its natural zone', 'It needs no water', 'It fixes nitrogen', 'It is rainfed'], a: 0, w: 'Paddy in a semi-arid zone = mining.', p: 1 },
    { q: 'Drip irrigation saves up to:', o: ['40-60% water vs flood irrigation', '5%', 'Nothing', 'Uses more'], a: 0, w: 'Precise root-zone delivery.', p: 1 },
    { q: 'Sprinkler irrigation suits:', o: ['Lawns and row crops on sandy soils', 'Paddy only', 'Fisheries', 'Nothing'], a: 0, w: 'Uniform gentle coverage.' },
    { q: 'Watershed development includes:', o: ['Ridge-to-valley treatment, check dams, afforestation', 'Dams only', 'Canals only', 'Nothing'], a: 0, w: 'Integrated catchment care.', p: 1 },
    { q: 'The Pani Panchayat model of equitable sharing came from:', o: ['Maharashtra', 'Assam', 'Kashmir', 'Kerala'], a: 0, w: 'Village water budgets.', p: 1 },
    { q: 'Assertion (A): Inter-state river disputes persist. Reason (R): Rivers cross state lines while water is a state subject.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Cauvery, Krishna tribunals.', p: 1 },
    { q: 'Which of the following is a flood-mitigation dam benefit?', o: ['Holding peak flows in reservoirs', 'Raising riverbeds', 'Freeing floodplains for building', 'Rain making'], a: 0, w: 'Moderated release.' },
    { q: 'The average Indian\u2019s daily domestic water need (standard) is about:', o: ['135 litres', '13 litres', '1350 litres', '1 litre'], a: 0, w: 'Norms vs reality gap is wide.', p: 1 },
    { q: 'Assertion (A): Recycled "grey water" can be reused. Reason (R): Treated waste water suits flushing and irrigation.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Circular water economy.', p: 1 },
    { q: 'Glacier retreat threatens Himalayan rivers because:', o: ['Glaciers are their dry-season base flow', 'They never mattered', 'They purify water', 'They increase flow forever'], a: 0, w: 'Climate change water risk.', p: 1 },
    { q: 'Which of the following is NOT a water conservation slogan-practice?', o: ['Rainwater harvesting', 'Kuls', 'Khadins', 'Over-irrigation'], a: 3, w: 'The opposite.' },
    { q: 'Groundwater recharge pits in cities work by:', o: ['Letting runoff soak into aquifers', 'Pumping more', 'Storing on roofs', 'Heating water'], a: 0, w: 'Sponge-city thinking.', p: 1 },
    { q: 'Assertion (A): Big dam benefits are unevenly shared. Reason (R): Power and water flow to cities/industry while displacement hits the rural poor.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The equity critique.' },
    { q: 'The total estimated utilizable water of India is about:', o: ['1,122 billion cubic m', '100 bcm', '10,000 bcm', '4 bcm'], a: 0, w: 'Of ~4,000 bcm precipitation.', p: 1 },
    { q: 'Fill in the blank: The ______ scheme plans interlinking of rivers.', o: ['National River Linking', 'Ganga Action', 'Namami Gange', 'Swachh Bharat'], a: 0, w: 'Debated mega-plan.', p: 1 },
    { q: 'Fill in the blank: India\u2019s water demand by 2050 may nearly ______.', o: ['Double', 'Vanish', 'Halve', 'Stay flat'], a: 0, w: 'Industry + cities grow.', p: 1 },
    { q: 'Which sea would the Narmada flow into, absent the dam debate?', o: ['Arabian Sea', 'Bay of Bengal', 'Caspian', 'Red Sea'], a: 0, w: 'West-flowing Narmada.' },
    { q: 'The Sardar Sarovar primarily irrigates:', o: ['Gujarat + Rajasthan + MP', 'Bengal', 'Kerala', 'Assam'], a: 0, w: 'The tri-state bargain.', p: 1 },
    { q: 'Match: (A) Meghalaya (B) Rajasthan (C) Himachal (D) Bikaner with (1) khadins (2) kuls (3) bamboo drip (4) tankas:', o: ['A-3, B-1, C-2, D-4', 'A-3, B-2, C-1, D-4', 'A-1, B-3, C-2, D-4', 'A-3, B-1, C-4, D-2'], a: 0, w: 'Geo-culture of water.', p: 1 },
    { q: 'Assertion (A): Water pricing could curb waste. Reason (R): What is free is over-used.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Economic water literacy.', p: 1 }
  );

  /* ==================== GEO4 · Agriculture (26 + 74 = 100) ==================== */
  N.geo4.quiz.push(
    { q: 'The share of Indians engaged in agriculture is about:', o: ['Two-thirds of workers', 'One-tenth', 'Half', 'None'], a: 0, w: 'The largest livelihood.', p: 1 },
    { q: 'Agriculture\u2019s GDP share is roughly:', o: ['One-sixth', 'Two-thirds', 'Half', 'All'], a: 0, w: 'The employment-output mismatch.', p: 1 },
    { q: 'Assertion (A): India\u2019s agriculture shows disguised unemployment. Reason (R): Extra workers add little output on family farms.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The core problem.', p: 1 },
    { q: 'Primitive subsistence farming uses:', o: ['Hoe, dao, digging stick', 'Combine harvesters', 'Drones', 'Tractors'], a: 0, w: 'On small patches cleared by fire.' },
    { q: '"Bewar" and "Dahiya" are names of:', o: ['Slash-and-burn cultivation', 'Tools', 'Crops', 'Festivals'], a: 0, w: 'Madhya Pradesh variants of jhum.', p: 1 },
    { q: '"Kumari" jhum is practised in:', o: ['Kerala', 'Punjab', 'Bengal', 'Assam'], a: 0, w: 'NCERT\u2019s example.', p: 1 },
    { q: 'Intensive subsistence farming dominates:', o: ['Densely populated rice areas of the east/south', 'Deserts', 'Himalayan peaks', 'Cities'], a: 0, w: 'High labour, tiny plots.' },
    { q: 'Plantation farming is:', o: ['Single-crop estates run as factories-in-fields', 'Family subsistence', 'Jhum', 'Grazing'], a: 0, w: 'Tea, coffee, rubber — capital intensive.', p: 1 },
    { q: 'Assertion (A): Plantations need good transport links. Reason (R): Perishable or bulk produce must reach processing fast.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Tea leaf can\u2019t wait.' },
    { q: 'Kharif crops are sown:', o: ['June-July, with the monsoon', 'October', 'March', 'December'], a: 0, w: 'Harvested Sept-Oct.', p: 1 },
    { q: 'Rabi crops are harvested around:', o: ['March-April', 'June', 'September', 'December'], a: 0, w: 'Sown Oct-Nov.', p: 1 },
    { q: 'Which of the following is a rabi crop?', o: ['Mustard', 'Rice', 'Cotton', 'Jute'], a: 0, w: 'Winter oilseed.', p: 1 },
    { q: 'Which of the following is a kharif crop?', o: ['Jowar', 'Wheat', 'Gram', 'Mustard'], a: 0, w: 'Great millet of the rains.' },
    { q: 'Zaid crops include:', o: ['Watermelon and cucumber', 'Wheat', 'Rice', 'Jute'], a: 0, w: 'The summer gap filler.', p: 1 },
    { q: 'India is the largest producer in the world of:', o: ['Pulses and jute', 'Wheat', 'Maize', 'Barley'], a: 0, w: 'Also second in rice, wheat, sugarcane.', p: 1 },
    { q: 'Rice needs:', o: ['100+ cm rain or irrigation, high temp', 'Frost', 'Low moisture', 'Sandy desert'], a: 0, w: '~25°C+ and standing water.' },
    { q: 'Leading rice state:', o: ['West Bengal', 'Rajasthan', 'Haryana', 'Gujarat'], a: 0, w: 'Bengal\u2019s delta paddies.', p: 1 },
    { q: 'Wheat needs:', o: ['Cool growth season and warm ripening', 'Constant rain', 'Heat all through', 'Floods'], a: 0, w: 'The rabi logic.', p: 1 },
    { q: 'Wheat\u2019s leading state:', o: ['UP (then Punjab)', 'Kerala', 'Assam', 'Tamil Nadu'], a: 0, w: 'UP largest area, Punjab highest yield.', p: 1 },
    { q: 'Bajra grows best in:', o: ['Rajasthan\u2019s sandy soils', 'Waterlogged basins', 'Hill slopes', 'Deltas'], a: 0, w: 'Hardy dry millet.', p: 1 },
    { q: 'Ragi is richest in:', o: ['Iron and calcium', 'Fat', 'Sugar', 'None'], a: 0, w: 'Karnataka\u2019s poor man\u2019s millet.', p: 1 },
    { q: 'Pulses restore soil fertility by:', o: ['Fixing nitrogen', 'Using more fertiliser', 'Draining water', 'Nothing'], a: 0, w: 'Legume root nodules.', p: 1 },
    { q: 'Sugarcane needs:', o: ['75-150 cm rain, deep rich soil, year\u2019s growth', 'Frost', 'Sandy desert', 'No sun'], a: 0, w: 'UP + Maharashtra lead.', p: 1 },
    { q: 'Oilseeds grown in India include:', o: ['Groundnut, mustard, coconut, castor', 'Only sunflower', 'Only olive', 'None'], a: 0, w: 'India among top oilseed producers.', p: 1 },
    { q: 'Groundnut\u2019s leading state:', o: ['Gujarat (then Rajasthan, TN)', 'Kashmir', 'Himachal', 'Sikkim'], a: 0, w: 'Kharif oilseed king.', p: 1 },
    { q: 'Tea grows best:', o: ['On well-drained fertile slopes, 150-300 cm rain, shade', 'In swamps', 'Deserts', 'Glaciers'], a: 0, w: 'Assam + Darjeeling.', p: 1 },
    { q: 'Coffee\u2019s initial variety in India was:', o: ['Arabica (from Yemen via Baba Budan)', 'Robusta first', 'Liberica', 'Decaf'], a: 0, w: 'Seven beans on a hill shrine.', p: 1 },
    { q: 'Coffee\u2019s Indian heartland:', o: ['Karnataka (Chikmagalur/Coorg)', 'Punjab', 'Bengal delta', 'Rajasthan'], a: 0, w: 'Plus Kerala and TN Nilgiris.', p: 1 },
    { q: 'Cotton requires:', o: ['210 frost-free days and black soil', 'Snow', 'Deep shade', 'Sea water'], a: 0, w: 'Maharashtra, Gujarat, MP.', p: 1 },
    { q: 'Cotton is called:', o: ['White gold', 'Black diamond', 'Golden fibre', 'Green gold'], a: 0, w: 'The Deccan\u2019s cash king.' },
    { q: 'Jute is called:', o: ['Golden fibre', 'White gold', 'Black gold', 'Red gold'], a: 0, w: 'Bengal\u2019s bundle crop.', p: 1 },
    { q: 'Jute is retted in:', o: ['Water ponds', 'Ovens', 'Sand', 'Oil'], a: 0, w: 'Fibres separate in water.', p: 1 },
    { q: 'Jute\u2019s competitor is:', o: ['Synthetic fibre', 'Cotton', 'Tea', 'Rice'], a: 0, w: 'Plastics stole the sack market.', p: 1 },
    { q: 'Rubber grows in:', o: ['Hot humid equatorial Kerala-Karnataka', 'Rajasthan', 'Ladakh', 'Punjab'], a: 0, w: 'Plantation crop of the south-west.' },
    { q: 'Assertion (A): Green Revolution widened regional gaps. Reason (R): HYV packages needed reliable irrigation that drylands lacked.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Punjab vs Vidarbha.', p: 1 },
    { q: 'White Revolution concerned:', o: ['Milk', 'Wheat', 'Rice', 'Eggs'], a: 0, w: 'Operation Flood.', p: 1 },
    { q: 'Yellow Revolution concerned:', o: ['Oilseeds', 'Jute', 'Sunflowers only', 'Maize'], a: 0, w: 'Mustard/sunflower push.', p: 1 },
    { q: 'Blue Revolution concerns:', o: ['Fish/water produce', 'Sky', 'Indigo', 'Frogs'], a: 0, w: 'Aquaculture.', p: 1 },
    { q: 'MSP guarantees farmers:', o: ['A floor procurement price', 'Free seeds', 'Free power', 'Loans'], a: 0, w: 'Announced pre-sowing for major crops.', p: 1 },
    { q: 'Procurement at MSP feeds:', o: ['Buffer stocks and the PDS', 'Exports only', 'Industry only', 'Nothing'], a: 0, w: 'Food security chain.', p: 1 },
    { q: 'Kisan Credit Card gives:', o: ['Short-term crop credit', 'Insurance', 'Pensions', 'Seeds'], a: 0, w: 'Affordable working capital.', p: 1 },
    { q: 'Crop insurance protects against:', o: ['Yield loss from drought/flood/pest', 'Market gossip', 'Fuel prices', 'Land disputes'], a: 0, w: 'PMFBY today.', p: 1 },
    { q: 'Subsidised fertilisers aim to:', o: ['Keep input costs low', 'Poison soil', 'Reward industry', 'Raise prices'], a: 0, w: 'But overuse degrades soil.' },
    { q: 'Grameen-style credit for Indian farmers is inspired by:', o: ['Bangladesh\u2019s SHG model', 'US banks', 'IMF', 'None'], a: 0, w: 'Micro-credit movement.', p: 1 },
    { q: 'The institutional reforms include:', o: ['Consolidation of holdings and cooperative farming', 'Fragmenting land', 'Banning credit', 'Abolishing markets'], a: 0, w: 'Fixing the structural.', p: 1 },
    { q: 'Fill in the blank: ______ of holdings merges tiny plots into viable farms.', o: ['Consolidation', 'Fragmentation', 'Subdivision', 'Leasing'], a: 0, w: 'The anti-fragmentation fix.' },
    { q: 'Bhoodan-Gramdan movement was led by:', o: ['Vinoba Bhave', 'Nehru', 'Patel', 'Tilak'], a: 0, w: 'Land-gift voluntarism.', p: 1 },
    { q: 'Zamindari abolition happened under:', o: ['Land reforms post-1947', 'British acts', 'Mughal rule', '2010 laws'], a: 0, w: 'First reform wave.', p: 1 },
    { q: 'Ceiling laws aimed to:', o: ['Cap land holdings and redistribute surplus', 'Raise ceilings', 'End farming', 'Tax farmers'], a: 0, w: 'Equity in land.', p: 1 },
    { q: 'Fill in the blank: The cropping season from Oct-Nov to Mar-Apr is ______.', o: ['Rabi', 'Kharif', 'Zaid', 'Jhum'], a: 0, w: 'Winter crops.' },
    { q: 'Fill in the blank: The ______ Revolution was anchored on HYV wheat.', o: ['Green', 'White', 'Blue', 'Grey'], a: 0, w: 'Borlaug\u2019s seeds.' },
    { q: 'Fill in the blank: ______ is the leading state in tea.', o: ['Assam', 'Punjab', 'Gujarat', 'Bihar'], a: 0, w: 'Brahmaputra gardens.' },
    { q: 'Fill in the blank: India\u2019s most important fibre crop is ______.', o: ['Cotton', 'Silk', 'Wool', 'Nylon'], a: 0, w: 'And jute second.' },
    { q: 'Fill in the blank: Kerala leads in ______ cultivation.', o: ['Rubber', 'Wheat', 'Bajra', 'Mustard'], a: 0, w: 'Latex land.' },
    { q: 'Match: (A) Jowar (B) Bajra (C) Ragi (D) Maize with (1) Rajasthan (2) Karnataka (3) Maharashtra (4) a kharif cereal used as fodder:', o: ['A-3, B-1, C-2, D-4', 'A-3, B-2, C-1, D-4', 'A-1, B-3, C-2, D-4', 'A-3, B-1, C-4, D-2'], a: 0, w: 'Millet geography.', p: 1 },
    { q: 'Match: (A) Assam (B) Karnataka (C) WB (D) Gujarat with (1) jute (2) tea (3) groundnut (4) coffee:', o: ['A-2, B-4, C-1, D-3', 'A-2, B-1, C-4, D-3', 'A-4, B-2, C-1, D-3', 'A-2, B-4, C-3, D-1'], a: 0, w: 'Crop-state pairs.', p: 1 },
    { q: 'Match: (A) Green Rev (B) White Rev (C) Yellow Rev (D) Blue Rev with (1) oilseeds (2) fisheries (3) wheat/rice (4) milk:', o: ['A-3, B-4, C-1, D-2', 'A-3, B-1, C-4, D-2', 'A-3, B-4, C-2, D-1', 'A-4, B-3, C-1, D-2'], a: 0, w: 'The revolutions.', p: 1 },
    { q: 'Which of the following statements is/are true? (I) Cropping patterns shape water demand. (II) MSP covers all crops equally. (III) Pulses improve soil.', o: ['I and III', 'All', 'II and III', 'I and II'], a: 0, w: 'MSP is selective — II false.', p: 1 },
    { q: 'Assertion (A): Farmers shift from pulses to wheat where MSP favours wheat. Reason (R): Price signals steer cropping choices.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Incentives are destiny.', p: 1 },
    { q: 'Assertion (A): Globalisation always helps Indian farmers. Reason (R): Export opportunities open while import competition also rises.', o: ['A false, R true', 'Both true, R explains A', 'A true, R false', 'Both false'], a: 0, w: 'It cuts both ways.', p: 1 },
    { q: 'Which is NOT a food crop?', o: ['Rubber', 'Rice', 'Wheat', 'Millets'], a: 0, w: 'Rubber is a plantation industrial crop.' },
    { q: 'Horticulture includes:', o: ['Fruits and vegetables', 'Fish', 'Cattle', 'Silk'], a: 0, w: 'India is top producer of many fruits/veg.', p: 1 },
    { q: 'India ranks first globally in the production of:', o: ['Mango and banana', 'Apple', 'Cherry', 'Olive'], a: 0, w: 'Mango king.', p: 1 },
    { q: 'Sericulture concerns:', o: ['Silk worms', 'Bees', 'Fish', 'Goats'], a: 0, w: 'Karnataka leads.', p: 1 },
    { q: 'Viticulture concerns:', o: ['Grapes', 'Cotton', 'Rice', 'Tea'], a: 0, w: 'Nashik\u2019s vineyards.', p: 1 },
    { q: 'Organic farming avoids:', o: ['Synthetic pesticides and fertilisers', 'All tools', 'Water', 'Sunlight'], a: 0, w: 'Soil health first.', p: 1 },
    { q: 'The "Operation Flood" linked:', o: ['Dairy cooperatives from village to national', 'Dams', 'Fisheries', 'Wool'], a: 0, w: 'Amul\u2019s Anand model scaled.', p: 1 },
    { q: 'Anand (Gujarat) is famous for:', o: ['Dairy cooperatives', 'Steel', 'Coal', 'Silk'], a: 0, w: 'Tribhuvandas-Patel-Kurien legacy.', p: 1 },
    { q: 'Fill in the blank: The ______ season bridges rabi harvest and kharif sowing.', o: ['Zaid', 'Rabi', 'Jhum', 'Bewar'], a: 0, w: 'Summer crops.' },
    { q: 'Fill in the blank: ______ is sown with the onset of monsoon.', o: ['Kharif', 'Rabi', 'Zaid', 'None'], a: 0, w: 'Rice, cotton, jute.' },
    { q: 'The largest jute producing state is:', o: ['West Bengal', 'Odisha', 'Bihar', 'Assam'], a: 0, w: 'The delta belt.', p: 1 },
    { q: 'Which cropping intensity booster allows two-three crops a year?', o: ['Irrigation', 'Fallowing', 'Jhum', 'Rainfed risk'], a: 0, w: 'Water on demand.' }
  );

  /* ==================== GEO5 · Minerals & Energy (27 + 73 = 100) ==================== */
  N.geo5.quiz.push(
    { q: 'Which rock type hosts most metallic minerals in India?', o: ['Igneous and metamorphic (peninsular)', 'Alluvial', 'Loess', 'Coral'], a: 0, w: 'The ancient Deccan core.', p: 1 },
    { q: 'Minerals in veins and lodes occur in:', o: ['Cracks of igneous rocks', 'River beds', 'Dunes', 'Glaciers'], a: 0, w: 'Tin, copper, zinc from magma.', p: 1 },
    { q: 'Coal and iron in beds/layers form in:', o: ['Sedimentary rocks', 'Volcanoes', 'Granite cracks', 'Caves'], a: 0, w: 'Strata of ancient basins.', p: 1 },
    { q: 'Bauxite forms from:', o: ['Deep leaching of silica-rich surface rocks', 'River silt', 'Volcanic ash', 'Coral'], a: 0, w: 'Residual aluminium concentrate.' },
    { q: 'Placer deposits are found in:', o: ['Valley sands and beach sands', 'Mountain tops', 'Sky', 'Lakes only'], a: 0, w: 'Gold (Kolar), monazite (Kerala).', p: 1 },
    { q: 'Which mineral comes from ocean water?', o: ['Common salt and magnesium', 'Gold', 'Diamond', 'Coal'], a: 0, w: 'Evaporated brine.', p: 1 },
    { q: 'Ferrous minerals include:', o: ['Iron ore and manganese', 'Copper and bauxite', 'Mica and limestone', 'Salt'], a: 0, w: 'Iron-based.', p: 1 },
    { q: 'Non-ferrous minerals include:', o: ['Copper, lead, zinc, bauxite', 'Iron', 'Manganese', 'Coal'], a: 0, w: 'No iron content.', p: 1 },
    { q: 'Which is a non-metallic mineral?', o: ['Mica', 'Hematite', 'Magnetite', 'Bauxite'], a: 0, w: 'The electronics insulator.' },
    { q: 'Assertion (A): Minerals are unevenly distributed. Reason (R): They form in specific geological environments.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Geology is destiny.', p: 1 },
    { q: 'Magnetite\u2019s iron content is about:', o: ['70%', '50%', '30%', '90%'], a: 0, w: 'The finest ore.', p: 1 },
    { q: 'Hematite\u2019s iron content is about:', o: ['50-60%', '70%', '20%', '80%'], a: 0, w: 'Most mined variety.' },
    { q: 'Odisha-Jharkhand belt\u2019s famous mines include:', o: ['Badampahar and Noamundi', 'Bailadila', 'Kudremukh', 'Ratnagiri'], a: 0, w: 'Singhbhum + Mayurbhanj.', p: 1 },
    { q: 'Bailadila\u2019s high-grade mines are in:', o: ['Chhattisgarh (Dantewada)', 'Karnataka', 'Goa', 'Odisha'], a: 0, w: 'Exported via Vizag.', p: 1 },
    { q: 'Ballari-Chitradurga belt lies in:', o: ['Karnataka', 'Jharkhand', 'MP', 'UP'], a: 0, w: 'Kudremukh too.', p: 1 },
    { q: 'Maharashtra-Goa belt centres on:', o: ['Ratnagiri', 'Nagpur', 'Pune', 'Sholapur'], a: 0, w: 'Ratnagiri\u2019s coastal reds.' },
    { q: 'Kudremukh is a ______ mine.', o: ['Iron', 'Coal', 'Gold', 'Mica'], a: 0, w: 'The horse-face mountain.', p: 1 },
    { q: 'Copper\u2019s Khetri mines lie in:', o: ['Rajasthan', 'Bihar', 'Kerala', 'Sikkim'], a: 0, w: 'Also Singhbhum, Balaghat.', p: 1 },
    { q: 'Copper is mainly used for:', o: ['Electrical wiring (conductivity)', 'Fuel', 'Fertiliser', 'Cement'], a: 0, w: 'Malleable, ductile, conductive.', p: 1 },
    { q: 'Bauxite\u2019s Odisha belt lies in:', o: ['Kalahandi-Koraput (Panchpatmali)', 'Bhubaneswar city', 'Chilika', 'Puri coast'], a: 0, w: 'Also Amarkantak plateau.', p: 1 },
    { q: 'Mica\u2019s indispensable property:', o: ['Excellent electrical insulation in thin sheets', 'Conductivity', 'Radioactivity', 'Flammability'], a: 0, w: 'Electronics need it.' },
    { q: 'Mica\u2019s key Indian belt:', o: ['Koderma (Jharkhand) and Nellore (AP)', 'Kerala', 'Kashmir', 'Punjab'], a: 0, w: 'Also Ajmer (Rajasthan).', p: 1 },
    { q: 'Limestone\u2019s key use:', o: ['Cement and iron smelting flux', 'Food', 'Fuel', 'Wiring'], a: 0, w: 'The construction mineral.', p: 1 },
    { q: 'Gondwana coal age is about:', o: ['250 million years', '10,000 years', '5 million years', '1 million years'], a: 0, w: 'Permian swamps.', p: 1 },
    { q: 'Tertiary coal age is about:', o: ['15-60 million years', '250 million', '5000 years', '1 billion'], a: 0, w: 'Younger, found in NE and J&K.', p: 1 },
    { q: 'Gondwana coal share of India\u2019s reserves:', o: ['98%', '50%', '10%', '30%'], a: 0, w: 'Damar valley, Jharia, Raniganj.', p: 1 },
    { q: 'Jharia is famous for:', o: ['Best coking coal and century-old fires', 'Gold', 'Mica', 'Bauxite'], a: 0, w: 'The burning fields.', p: 1 },
    { q: 'Bokaro and Jharia lie in:', o: ['Jharkhand', 'Odisha', 'MP', 'UP'], a: 0, w: 'The Damodar valley coalfield.' },
    { q: 'Talcher coalfield lies in:', o: ['Odisha', 'Bengal', 'Bihar', 'Assam'], a: 0, w: 'Mahanadi basin.', p: 1 },
    { q: 'Korba coalfield lies in:', o: ['Chhattisgarh', 'Kerala', 'Goa', 'Punjab'], a: 0, w: 'Hasdeo valley.' },
    { q: 'Singrauli coalfield spans:', o: ['MP-UP', 'Kerala-TN', 'Bengal-Bihar', 'None'], a: 0, w: 'The northern powerhouse.', p: 1 },
    { q: 'Neyveli is known for:', o: ['Lignite', 'Gold', 'Mica', 'Bauxite'], a: 0, w: 'Tamil Nadu\u2019s brown coal.', p: 1 },
    { q: 'Petroleum forms in:', o: ['Anticlines of sedimentary rock between porous and impermeable layers', 'Volcanoes', 'Granite', 'Rivers'], a: 0, w: 'Trapped oil dome.', p: 1 },
    { q: 'Mumbai High lies about:', o: ['Offshore in the Arabian Sea', 'In Mumbai suburbs', 'The Bay of Bengal', 'Goa'], a: 0, w: 'India\u2019s biggest field.', p: 1 },
    { q: 'Digboi\u2019s first refinery town status dates to:', o: ['1901', '1947', '1975', '1990'], a: 0, w: 'Oil struck 1866; refinery 1901.', p: 1 },
    { q: 'Naharkatiya is in:', o: ['Assam', 'Gujarat', 'Maharashtra', 'AP'], a: 0, w: 'Brahmaputra valley oil.', p: 1 },
    { q: 'Ankleshwar oilfield lies in:', o: ['Gujarat', 'Assam', 'Rajasthan', 'MP'], a: 0, w: 'Cambay basin.' },
    { q: 'Natural gas\u2019s advantage:', o: ['Cleaner burning than coal/oil', 'Dirtier', 'Costlier always', 'Non-flammable'], a: 0, w: 'Low-carbon fossil.', p: 1 },
    { q: 'The HBJ pipeline carries:', o: ['Gas from Hazira to Jagdishpur', 'Crude to ports', 'Water', 'Slurry'], a: 0, w: 'Feeding fertiliser/power plants.', p: 1 },
    { q: 'Krishna-Godavari basin is rich in:', o: ['Natural gas', 'Coal', 'Mica', 'Gold'], a: 0, w: 'KG-D6 deepwater.', p: 1 },
    { q: 'Thermal power\u2019s fuel share:', o: ['Coal ~68%', 'Gas', 'Oil', 'Wood'], a: 0, w: 'India\u2019s electricity backbone.', p: 1 },
    { q: 'Nuclear energy uses:', o: ['Uranium and thorium', 'Coal', 'Wind', 'Water only'], a: 0, w: 'Fission fuel.' },
    { q: 'Thorium\u2019s great reserve in India:', o: ['Monazite sands of Kerala', 'Punjab wheat', 'Bengal jute', 'Kashmir saffron'], a: 0, w: '3-stage programme hope.', p: 1 },
    { q: 'Jaduguda mines:', o: ['Uranium (Jharkhand)', 'Coal', 'Iron', 'Gold'], a: 0, w: 'Also AP\u2019s Tummalapalle.', p: 1 },
    { q: 'India\u2019s first nuclear plant:', o: ['Tarapur', 'Kalpakkam', 'Narora', 'Kaiga'], a: 0, w: '1969, Maharashtra.', p: 1 },
    { q: 'Which pairing is wrong?', o: ['Kakrapar — Odisha', 'Rawatbhata — Rajasthan', 'Kalpakkam — TN', 'Kaiga — Karnataka'], a: 0, w: 'Kakrapar is in Gujarat.', p: 1 },
    { q: 'Wind\u2019s giant farms lie at:', o: ['Muppandal (TN) and Jaisalmer', 'Mumbai', 'Ladakh', 'Kolkata'], a: 0, w: 'Coastal/desert winds.', p: 1 },
    { q: 'Solar\u2019s biggest park:', o: ['Bhadla (Rajasthan)', 'Kerala', 'Bengal', 'Assam'], a: 0, w: 'Among the world\u2019s largest.', p: 1 },
    { q: 'Biogas plants use:', o: ['Cow dung and organic waste', 'Coal', 'Petrol', 'Sand'], a: 0, w: 'Gobar gas for kitchens.' },
    { q: 'Tidal energy potential sites:', o: ['Gulf of Kachchh and Cambay', 'Delhi', 'Bhopal', 'Jaipur'], a: 0, w: 'Also Sundarbans.', p: 1 },
    { q: 'Geothermal sites include:', o: ['Manikaran and Puga valley', 'Mumbai', 'Chennai plains', 'Kolkata'], a: 0, w: 'Hot springs of HP/Ladakh.', p: 1 },
    { q: 'Assertion (A): Conservation is essential. Reason (R): Minerals are non-renewable.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Finite = careful.', p: 1 },
    { q: 'Recycling metals saves:', o: ['Both ore and energy', 'Nothing', 'Only money', 'Only time'], a: 0, w: 'Scrap is ore twice-used.', p: 1 },
    { q: 'Improved technology helps:', o: ['Use low-grade ores economically', 'Nothing', 'Waste more', 'Import only'], a: 0, w: 'Beneficiation upgrades ore.', p: 1 },
    { q: 'Exporting raw ore unprocessed is:', o: ['Value-losing', 'Value-adding', 'Illegal', 'Impossible'], a: 0, w: 'Process at home first.', p: 1 },
    { q: 'Fill in the blank: The finest iron ore is ______.', o: ['Magnetite', 'Limonite', 'Siderite', 'Haematite'], a: 0, w: '72% iron.' },
    { q: 'Fill in the blank: Bauxite is the ore of ______.', o: ['Aluminium', 'Copper', 'Iron', 'Zinc'], a: 0, w: 'Alumina source.' },
    { q: 'Fill in the blank: Khetri is famous for ______.', o: ['Copper', 'Gold', 'Mica', 'Lignite'], a: 0, w: 'Rajasthan\u2019s belt.' },
    { q: 'Fill in the blank: The Koderma belt produces ______.', o: ['Mica', 'Iron', 'Coal', 'Oil'], a: 0, w: 'Jharkhand.' },
    { q: 'Fill in the blank: Digboi is in the state of ______.', o: ['Assam', 'Goa', 'Kerala', 'UP'], a: 0, w: 'First oil town.' },
    { q: 'Fill in the blank: The ______ pipeline feeds fertiliser plants with gas.', o: ['HBJ', 'TAPI', 'IP', 'Nabucco'], a: 0, w: 'Hazira-Vijaipur-Jagdishpur.' },
    { q: 'Fill in the blank: Tarapur atomic station lies in ______.', o: ['Maharashtra', 'Gujarat', 'Kerala', 'Odisha'], a: 0, w: 'Near Mumbai.' },
    { q: 'Fill in the blank: ______ sands of Kerala contain thorium.', o: ['Monazite', 'Silica', 'Garnet', 'Ilmenite'], a: 0, w: 'Beach nuclear fuel.' },
    { q: 'Match: (A) Jharia (B) Bailadila (C) Khetri (D) Digboi with (1) iron (2) coal (3) oil (4) copper:', o: ['A-2, B-1, C-4, D-3', 'A-2, B-4, C-1, D-3', 'A-1, B-2, C-4, D-3', 'A-2, B-1, C-3, D-4'], a: 0, w: 'The map-work minerals.', p: 1 },
    { q: 'Match: (A) Tarapur (B) Rawatbhata (C) Kalpakkam (D) Kakrapar with (1) Rajasthan (2) Maharashtra (3) Gujarat (4) TN:', o: ['A-2, B-1, C-4, D-3', 'A-2, B-4, C-1, D-3', 'A-1, B-2, C-4, D-3', 'A-2, B-1, C-3, D-4'], a: 0, w: 'Nuclear map.', p: 1 },
    { q: 'Match: (A) Wind (B) Solar (C) Biogas (D) Tidal with (1) Bhadla (2) gobar gas (3) Muppandal (4) Gulf of Kachchh:', o: ['A-3, B-1, C-2, D-4', 'A-3, B-2, C-1, D-4', 'A-1, B-3, C-2, D-4', 'A-3, B-1, C-4, D-2'], a: 0, w: 'Non-conventional map.', p: 1 },
    { q: 'Which of the following statements is/are true? (I) Coal is India\u2019s main power fuel. (II) Nuclear share is small. (III) Renewables are growing.', o: ['All', 'I only', 'I and II', 'III only'], a: 0, w: 'All three hold.', p: 1 },
    { q: 'Assertion (A): Solar is ideal for remote villages. Reason (R): It is modular and needs no grid fuel.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Distributed energy.', p: 1 },
    { q: 'Which fuel replaces kerosene in villages via solar?', o: ['Lanterns and home lights', 'Tractors', 'Mills', 'Pumps only'], a: 0, w: 'Clean light for study.' },
    { q: 'Iron ore exported from India goes mainly through:', o: ['Vizag and Paradip/Marmagao ports', 'Delhi airport', 'Roads to Nepal', 'None'], a: 0, w: 'Ore-bulk ports.', p: 1 },
    { q: 'Which steel plant is not on the coal-iron belt but near a port?', o: ['Vizag (RINL)', 'Bhilai', 'Bokaro', 'Durgapur'], a: 0, w: 'Imported-ore coastal logic.', p: 1 }
  );

  /* ---- top-ups to exactly 100 ---- */
  N.geo1.quiz.push(
    { q: 'Which soil is most widespread in India?', o: ['Alluvial', 'Black', 'Laterite', 'Peaty'], a: 0, w: '~40% of area.', p: 1 },
    { q: 'Assertion (A): Resource planning is essential for India. Reason (R): India has enormous diversity in resource availability across regions.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'Balanced planning matches need with availability.', p: 1 }
  );
  N.geo2.quiz.push(
    { q: 'The "Project Elephant" was launched to protect:', o: ['Elephant corridors and habitats', 'Rhinos', 'Tigers', 'Birds'], a: 0, w: '1992 flagship for pachyderms.', p: 1 },
    { q: 'Which is a bird sanctuary (Rajasthan) famous for cranes?', o: ['Keoladeo (Bharatpur)', 'Kaziranga', 'Gir', 'Simlipal'], a: 0, w: 'UNESCO heritage site.', p: 1 }
  );
  N.geo3.quiz.push(
    { q: 'India’s national water policy priority order puts this use first:', o: ['Drinking water', 'Industry', 'Irrigation', 'Recreation'], a: 0, w: 'Survival before economics.', p: 1 },
    { q: 'Assertion (A): Urban water demand is exploding. Reason (R): Cities grow faster than their water infrastructure.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The 2030 supply gap fear.', p: 1 },
    { q: 'DVC’s multipurpose list includes navigation on:', o: ['The Hooghly', 'The Narmada', 'The Kaveri', 'The Krishna'], a: 0, w: 'Damodar-Hooghly system.', p: 1 },
    { q: '"Hydro-conflict" between states is best resolved by:', o: ['Tribunals and negotiated sharing', 'War', 'Silence', 'Ignoring'], a: 0, w: 'Constitutional machinery exists.', p: 1 }
  );
  N.geo4.quiz.push(
    { q: 'Assertion (A): Millets are climate-smart crops. Reason (R): They withstand poor rainfall and poor soils.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The "nutri-cereals" comeback.', p: 1 },
    { q: 'The MSP is announced by the government:', o: ['Before sowing season', 'After harvest', 'Yearly only for cotton', 'Never'], a: 0, w: 'Pre-sowing signals guide planting.', p: 1 }
  );
  N.geo5.quiz.push(
    { q: 'Which is India’s oldest operating oilfield?', o: ['Digboi', 'Mumbai High', 'KG-D6', 'Barmer'], a: 0, w: 'Since 1901.', p: 1 },
    { q: 'Assertion (A): Wind and solar are intermittent. Reason (R): Storage and grid balancing are essential for renewables.', o: ['Both true, R explains A', 'Both true, R does not explain A', 'A true, R false', 'A false, R true'], a: 0, w: 'The integration challenge.', p: 1 }
  );
})();

